### ISSUE TITLE
Gerald loses power during a cut

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1003]
Over the duration of a (reasonably long) cut, Gerald's power fades from good enough to cut all the way through to barely noticeable.

It doesn't seem to be alignment of the mirrors or the bed, as the cut I've just seen it on had some concentric circles (about 400-500mm in diameter) and one of the earlier cuts had cut through fine, whereas another about 10-20mm larger in diameter around the first wasn't cutting.

**Comment by MatthewCroughan** [comment]
Observed this when I was cutting a large 400+MM circle with Hugh Miller who makes furniture and occasionally hires me to assist him with the laser cutting. Resulted in a half hour rescue mission manually editing nodes in the software. 

I don't believe it can have anything to do with laser alignment, since the rescue was successful, we got it to cut exactly where it stopped with editing and a redownload, if it were the mirrors then physics wouldn't allow that to be a solution. 

That leaves a few options in my mind:
- Dodgy Power supply
- Corrupted files in transfer over wire
- Corrupted data in RAM

**Comment by amcewen** [comment]
Diane had had trouble with it on Tuesday, and I took the air assist off to see if it improved matters.  They said that it did cut better, but yesterday Suzy was running it and having similar problems with the air assist off still, so agreed that it probably isn't alignment.

**Comment by MatthewCroughan** [comment]
@amcewen How soon do you think we could get that going?

**Comment by magman2112** [comment]
I did a few checks on Gerald yesterday before Maker night. I found that one of the mirrors was loose on the y-axis (it moved when I tried to clean it with a cotton swab) the mirror was also badly scratched. 

I found and fitted a better quality mirror in the laser spares cupboard, making sure that it was fitted tightly in the mount. I then did a realignment with the new mirror and was then able to cut 3mm ply on 70 power and 24mm speed over most of the bed. I also was able to cut 8mm ply at 6mm speed. I re-fitted the air assist as well, though I had to hunt for the parts, as they were in different places in the room. In future, these parts should be placed in the laser spares cupboard, rather than left lying around (if they need to be moved again).

I will hopefully be in DoES over the weekend, so I will see if Gerald has been behaving before closing this issue.
