### ISSUE TITLE
Replacing the cooling fluid for Gerald and Sophia.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1012]
When Gerald and Sophia were re-installed after the move to The Tapestry building, I believe that normal tap water was used. Since then, i don’t Believe either cooler has been topped off, but this should be done soon (and may also address some of the issues with Gerald when he has been running all day).

I have found an interesting article on the web regarding laser coolants

https://lasergods.com/laser-water-coolants-additives/

So I was going to suggest that we replace the coolants for both Gerald and Sophia using the methods suggested in this article, whilst also topping up the coolant levels at the same time.

Does anyone know what the coolant capacities are for the two chillers, so that we can order the right quantity of distilled water?

**Comment by magman2112** [comment]
Including a link to the laser maintenance team to open up the discussion @DoESLiverpool/laser-maintenance

**Comment by magman2112** [comment]
I have found quite a few relatively local suppliers of distilled water on eBay, whereas web based suppliers seem to quote a lot for carriage.

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F121070029632

**Comment by amcewen** [comment]
Issue #106 shows we've got CW3000 and CW5200 chillers.  [This manual for the CW3000](http://www.rabbitlaserusa.com/Manuals/Chiller_CW3000_Manual.pdf) says its capacity is 9L, and [this manual for the CW5200](http://images10.newegg.com/UploadFilesForNewegg/itemintelligence/Callaway%20Golf/CW_5000_hiendro1445108848123.pdf) shows a 6L capacity.

I don't know if they do distilled water, but we used to get deionised water (which I suspect is what HPC told us to use) from Mersey Batteries on Jordan St in the Baltic Triangle (see #78 for details)

**Comment by magman2112** [comment]
The article I linked to suggested that deionised water isn’t as good as distilled water, hence my suggestion. We also need something to kill any algi that may accumulate in the water, as the water is a little brown in Gerald at the moment for example.

**Comment by johnmckerrell** [comment]
We used to use a place in the Baltic to get *deionised* water (for batteries). I believe Patrick was of the opinion we didn't actually need it but I forget what that was based on.

**Comment by KarlDunkerley** [comment]
Halfords do cheap distilled water.


Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com

--------------------------------------------
On Fri, 21/12/18, Mike Gorman <notifications@github.com> wrote:

 Subject: Re: [DoESLiverpool/somebody-should] Replacing the cooling fluid for Gerald and Sophia. (#1012)
 To: "DoESLiverpool/somebody-should" <somebody-should@noreply.github.com>
 Cc: "KarlDunkerley" <karldunkerley@yahoo.com>, "Team mention" <team_mention@noreply.github.com>
 Date: Friday, 21 December, 2018, 16:14
 
 The article I linked to suggested
 that deionised water isn’t as good as distilled water,
 hence my suggestion. We also need something to kill any algi
 that may accumulate in the water, as the water is a little
 brown in Gerald at the moment for example.
 
 —
 You are receiving this because you are on a team that was
 mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by KarlDunkerley** [comment]
Halfords Battery Top-Up Water 5L



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Halfords Battery Top-Up Water 5L

Halfords Battery Top-Up Water is de-ionised for use in lead-acid batterie & many other applications
 |

 |

 |




Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Friday, 21 December 2018, 16:18:39 GMT, John McKerrell <notifications@github.com> wrote:  
 
 We used to use a place in the Baltic to get *deionised* water (for batteries). I believe Patrick was of the opinion we didn't actually need it but I forget what that was based on.

**Comment by Sean-anotherone** [comment]
Reverse osmosis water from a tropical fish shop is cheaper, plus I have a conductivity meter I can bring in to check it with if required.

**Comment by magman2112** [comment]
As part of the general laser move, both chillers were removed, emptied, flushed and refilled. Normal tap water was also used. This will be monitored to see if there is any algae growth, but closing this issue for now.
