### ISSUE TITLE
Emergency light above east fire escape not working.

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1035]
The emergency light above the external fire escape on the east side of the main room is not working.

As there is very little lighting in this area anyway, this is quite critical.

**Comment by johnmckerrell** [comment]
Turns out that the light switch in the soundproof room also has a separate light switch for the emergency light, the bit that looks like a fuse. Probably when the switch was replaced with a dimmer the switch got turned off. If we make sure it's on this should stay working!

This sort of thing, I'm not aware of us having a "key" for it but imagine a screwdriver might do the trick:

https://www.screwfix.com/p/lap-2-way-16ax-key-switch-with-emergency-lighting-test-text-white/58453
