### ISSUE TITLE
Laser printer is getting low on toner, both B&W and colour

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#104]
From previous discussions I think we came to the conclusion that generic was fine, no need to buy HP. Assigning to Adrian as he'll know what we bought previously.

**Comment by amcewen** [comment]
We've still got spare magenta/cyan/yellow toner - it's in the stationery cupboard in the Fridge.  

We ordered from http://www.cartridgeshop.co.uk/s/search?view=list&w=q6000&submit=Go last time (the Q600[0/1/2/3] code give you [black/colours...]).

I've ordered a double-pack of compatible (rather than original HP) black, as that was on offer and will give us one to go in store for when we need it.  Will close this ticket when it arrives.

**Comment by osfameron** [comment]
I've replaced the magenta/cyan/yellow from the stationery cupboard toners.
I have NOT yet replaced bw (as control panel claims to have some left) but have put cartridges into stationery cupboard.

@DoESsean: I'm leaving old cartridges on your desk as you were looking into recycling them?
@amcewen: as you have an account handy, want to order replacements? Q6001A, Q6002A, Q6003A

**Comment by osfameron** [comment]
Have done a test-print.  Amused to find the printer complained about a "Non-HP Cyan" (but lets you accept the inferior product.)

Printout (on Sean's desk) looks "ok", possibly missing some yellow, not sure if that will improve on future prints.
