### ISSUE TITLE
Add some instructions for exporting laser-compatible dxf file from Adobe Illustrator

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1064]
As we tend to use Inkscape, it can sometimes be difficult to help people who use Illustrator.
It would be good to have a set of instructions for creating a laser-compatible dxf file from Illustrator. I found this useful yesterday afternoon: https://www.youtube.com/watch?v=5fPsk-SQtlQ. It would also be good to include steps to convert images to paths.

Maybe @zarino would like to do this? (did provide some useful tips a while ago).

**Comment by zarino** [comment]
My workflow is usually:

1. Select everything on the artboard with `cmd-A`
1. Set the Stroke to None, in the tool palette
1. With everything still selected, do "Type > Create Outlines" (or `shift-cmd-O`) – you could just skip this if you don‘t actually have text in your file
1. "File > Export As… > DXF"
1. Hit "OK" with whatever the default settings are.

That’s it. I’ve never bothered to try out the various "AutoCAD Version" options. The chap in that video set his to 2004/2005/2006, I’ve only ever left mine on the default R14/LT98/LT97.

I’m suspicious as to why the chap in the video didn’t need to remove the strokes from his elements. In my experience, exporting with a stroke will result in a file that contains three parallel lines when read into our laser software (the two "edges" of the stroke, plus the centre line). Maybe that’s a weird quirk specific to our software. Or maybe it’s because I’m exporting in the older file format, and he’s using the newer one. Who knows. But just doing `cmd-A`, setting border to None, then exporting takes about 5 seconds, so I’ve never bothered experimenting further ;-)

**Comment by jackie1050** [comment]
Thanks Zarino - I'll see if I can get Jet to check that works for her, then I'll update the Wiki.

On 24 Feb 2019 19:50, Zarino Zappia <notifications@github.com> wrote:

My workflow is usually:

  1.  Select everything on the artboard with cmd-A
  2.  Set the Stroke to None, in the tool palette
  3.  With everything still selected, do "Type > Create Outlines" (or shift-cmd-O) – you could just skip this if you don‘t actually have text in your file
  4.  "File > Export As… > DXF"
  5.  Hit "OK" with whatever the default settings are.

That’s it. I’ve never bothered to try out the various "AutoCAD Version" options. The chap in that video set his to 2004/2005/2006, I’ve only ever left mine on the default R14/LT98/LT97.

I’m suspicious as to why the chap in the video didn’t need to remove the strokes from his elements. In my experience, exporting with a stroke will result in a file that contains three parallel lines when read into our laser software (the two "edges" of the stroke, plus the centre line). Maybe that’s a weird quirk specific to our software. Or maybe it’s because I’m exporting in the older file format, and he’s using the newer one. Who knows. But just doing cmd-A, setting border to None, then exporting takes about 5 seconds, so I’ve never bothered experimenting further ;-)

**Comment by DoESsean** [comment]
It doesn't look like the above was put into the Wiki.

Did it work? If so, I'll edit the Wiki to reflect it.

**Comment by zarino** [comment]
Documentation here: https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutterIllustrator
