### ISSUE TITLE
Test support for OctoPrint / OctoPi with Ultimaker

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1065]
I've (finally) been playing with OctoPrint on my Creality CR-10S and I really like it.

OpenSource, nice features, seems pretty standard (e.g. Slic3r supports it natively).

Loads of plugins, such as MQtt support to publish printer events.

I recall talking to somebody or other, perhaps @amcewen about this but can't remember if there are blockers.

I quite fancy testing out OctoPi support for an Ultimaker to support

- PiCam, timelapse videos of prints
- Costings
- MQtt reporting of print states
- Remote uploads / print control
- MakeSpace workshop usage metrics 

Thoughts / Advice ? Thx x

**Comment by ajlennon** [comment]
It was surprisingly easy to set up OctoPrint on Prints Adam.

- Raspberry Pi 3
- Download of OctoPi
- Ran through the wizard
- Connected a USB cable to the Ultimaker USB port

Then I sliced a 3DBenchy through Sli3R and uploaded/started printing direct from Slic3R.

During the print the Ultimaker shows "Printing from USB" then when the print has finished reverts to it's normal interface so the existing SD Card / local control is unaffected.

With OctoPi we can do all sorts of things

- Information on sizes / costs of print
- Webcam monitoring of prints in real time
- Capture of webcam movies of builds
- MQTT publication of messages relating to start/stop/movement/bed etc.
- Realtime G-Code display
- "Watched folder" to print dropped files
- Plugin architecture for extensibility

Seems really nice

![image](https://user-images.githubusercontent.com/1537834/53413436-e4b53e80-39c3-11e9-8a32-054a3446dc04.png)

![image](https://user-images.githubusercontent.com/1537834/53413434-e121b780-39c3-11e9-9bcb-146b028e9e2d.png)

![image](https://user-images.githubusercontent.com/1537834/53413449-e848c580-39c3-11e9-828d-2bc8a684c738.png)
 
![image](https://user-images.githubusercontent.com/1537834/53413455-ebdc4c80-39c3-11e9-9bd0-22a33288f9e9.png)

**Comment by ajlennon** [comment]
@MatthewCroughan @goatchurchprime et al 

You can find the RPi as `octopi-adam.local` running its web server on the usual port 80

**Comment by Pezmc** [comment]
Glad to see you got it set up, some tips from my use at home:

- Others advise against using the inbuilt slicer, it's quite out of date
- Some plugins I think would be of value:
  - [CostEstimation](https://github.com/malnvenshorn/OctoPrint-CostEstimation), could be of use to DoES for charging people for prints?
 - [Exclude Region](https://github.com/bradcfisher/OctoPrint-ExcludeRegionPlugin), draw a shape around an area of your print to stop printing it, great for recovering from a partial print failure!
 - [HeaterTimeout](https://github.com/google/OctoPrint-HeaterTimeout) automatically turn off the heatbed and extruder header after an idle timeout (save power and "safety")
 - [Preheating](https://github.com/marian42/octoprint-preheat) A QOL improvement for one-click preheating of the printer
 - [PrintHistory](https://github.com/imrahil/OctoPrint-PrintHistory) logging of all prints
 - [PSU Control](https://github.com/kantlivelong/OctoPrint-PSUControl) automatically turn off the high voltage rail (effectively turn off the printer) after inactivity

**Comment by ajlennon** [comment]
Those are brilliant thanks @Pezmc !

I did run into some trouble with the Ultimaker over the weekend. Getting CRC errors or something. Will have to investigate...

**Comment by ajlennon** [comment]
The more I look at OctoPrint / OctoPi the more I like it. 

I have those plugins on there thanks @Pezmc and particularly like the filament management stuff.

I have the webcam streamer streaming up to YouTube too. 

Lovely stuff

![image](https://user-images.githubusercontent.com/1537834/53768106-bf4a9800-3ecf-11e9-9caa-042aa2dc0e6f.png)

**Comment by MatthewCroughan** [comment]
Will get on with this after updating their firmware some day this week.

**Comment by ajlennon** [comment]
Firmware? What firmware?

**Comment by MatthewCroughan** [comment]
@ajlennon I was referencing the firmware on the Ultimaker 2, Jackie had mentioned it being necessary, however it's less necessary than I thought. But the firmware update was there, and it was easy enough to install via Cura.

I've set up a raspberry pi zero via Balena to print, however I have a big problem starting prints, they seem malformed by comparison to doing it with just the SD card and Cura. This is because there is something different between the way Cura is slicing for octoprint, and the way it is sliced for the Ultimaker raw.

**Comment by jackie1050** [comment]
If I said "necessary", I meant in terms of taking advantage of any new features or incremental improvements.
________________________________

**Comment by MatthewCroughan** [comment]
This issue is still Live, I'm working on it by forking balena-octoprint to support Alpine. 

https://github.com/balena-io-playground/balena-octoprint

**Comment by MatthewCroughan** [comment]
Right, I've made this
https://github.com/matthewcroughan/balena-octoprint-alpine

So we need to get on making #933 happen. @DoESLiverpool/directors 

We need to make that reasonably secure, like the youtube account with a 3 word mnemonic at least, so that access is granted at the will of the directors. Permissions on Balena are granular like they are on Github, since effectively that's what it is doing behind the scenes, git.

We should eventually host our own OpenBalena instance to control these devices without any semblance of reliance on an external service, but because of the nice web interface Balena.io has, it's probably a good idea to use them for small scale experimentation as we are now. 

Here is the example configuration I have set up. We have two devices, the Ultimakers. Access to push updates to these devices would be given to people in a group, those people become the effective maintainers of those devices. 

![image](https://user-images.githubusercontent.com/26458780/62003040-2d565c80-b108-11e9-8271-3888c7b728a5.png)

**Comment by ajlennon** [comment]
Good work. What happens if you add a plugin?

**Comment by MatthewCroughan** [comment]
@ajlennon What plugin in particular? All of the standard plugins are installed, do you have a particular one in mind?

**Comment by MatthewCroughan** [comment]
@ajlennon 
![image](https://user-images.githubusercontent.com/26458780/62005451-576d4600-b12b-11e9-9fb2-15b1d751b47b.png)

Seems to work just fine.

**Comment by ajlennon** [comment]
Quite a view - but OctoLapse is the most important

**Comment by ajlennon** [comment]
@MatthewCroughan see @Pezmc comment on plugins for a starting point.

**Comment by MatthewCroughan** [comment]
I'm going to close this, since I have tested support. My conclusion is that it's not a good idea, because the way UltiGCode and the printer's firmware interacts with octoprint is less than satisfactory. It could interrupt someone's print, and the output is not the same as executing the gcode from an SD via the menus and I can't figure out why. Instead I've installed Octoprint on the two Ender 3s we have now on some Orange Pi Zeros.

#1252
