### ISSUE TITLE
Clear the recess (alcove)

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1083]
Nobody knows what we need and what can be dumped so collecting some discussion so far:

* Dark large desk tops need to be cut down as sacrificial beds for the CNC and moved to the CNC room
* The two desks that were most recently in Dinky should be kept to go against the wall in the recess.
* All other desks here can go.
* White boards here should go on walls, somewhere.

**Comment by amcewen** [comment]
Some of the geometric lights are in there, a few need fixing and then installing in the events room.  There has been talk of installing some of the remaining ones in the stairwell too.

**Comment by amcewen** [comment]
The vac former is covered in issue #168 (and is stalled on me, or someone, buying a new element for it)

**Comment by jackie1050** [comment]
We're waiting for @epsaul to decide whether we should keep the knitting machines (I'd like to get an electronic one that can be made to work with a PC).

**Comment by jackie1050** [comment]
We need to keep the whiteboard (which needs to be put on a wall somewhere), and the the screen (this could be placed flat on the racking).

**Comment by amcewen** [comment]
The L-shaped tops that we used to have in the workshop at Gostins need chopping up to use as sacrificial bed.
The two desks marked with "Keep" should be kept, the legs are in the green crate.
The other desks should be disposed of.

**Comment by magman2112** [comment]
John Cassidy has expressed an interest in the worktops, but can't move them for over a week. @johnmckerrell has checked with Jason and we can store these outside for a short while, till John Cassidy can come in with some transport to move the worktops. 

John plans to use these worktops for his chicken coop.

I plan to be in DoES this Saturday, so will move the worktops, as well as cutting down the other worktops for sacrificial beds as required.

**Comment by magman2112** [comment]
All of the remaining worktops have been moved down to the ground floor, under the fire escape, ready for John to collect them. The two Ikea worktops have been cut down to make shelves for the alcove and between the North side windows.

One of the whiteboards has now been installed on the wall in the Laser room, the other is currently against the wall in Room 29, though I suspect this may need to be used for the Robot Wars for Maker Fest.

The only thing I think is currently outstanding for this issue is that I plan to cut the worktop on the CNC room side of the alcove to 600mm, to give a bit more working space in the alcove. We should then be able to close this issue.

**Comment by DoESsean** [comment]
Final sticking point broken down into its own issue, so...

CLOSED!
