### ISSUE TITLE
Support work experience placement

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1106]
We've been asked by Sale Sharks to take on one or more people for work experience placements.

We need to find out from them:
 * [ ] How many people? (I suspect "as many as possible")
 * [ ] For how long and how many days or hours/week?
 * [ ] What experience they'll have, what type of tasks are they looking for?

And we need to:
 * [ ] Arrange computer(s)
 * [ ] Decide what they can do (possibly by adding a label to GitHub issues)

**Comment by goatchurchprime** [comment]
Is it too late to expose them to DoES, like we should have been doing, so they are more able to work out among themselves about what tasks we need doing and what they can do?  That's one of the important skills of "work" -- that of working out what work there is that could and should be done, according to what you're good at.  

For example, can we give one of them a laser induction so they could organize and do some laser cutting for themselves for some of their projects that they get up to?  Then if one of them turns out to find it interesting, there's a lot of jobs cutting signs and stencils around the place.  Or making boxes and dividers to organize the tools and nuts and bolts.  It would be nice for one to decide to list all the books in the library on the wiki, rather than to be told to do it.  Can that be specified in the job description?

**Comment by johnmckerrell** [comment]
* Get in touch with companies in DoES, on mailing list and directly, they can communicate with Jon Travena directly
* Ready to start as soon as possible.
* Up to 5 people
* Flexible on how many days per week, from now until July they need to do 100 hours.
* Mostly looking to get into hospitality, don't have much experience, even of using computers much.
* DIY type tasks @magman2112 can lead on.
* Ben at Find Out Digital might be interested, @johnmckerrell will check

**Comment by johnmckerrell** [comment]
@goatchurchprime absolutely, the only limitation really is how much time "we" have to spend training and looking after them. For me I have virtually zero spare time but I had wondered about @magman2112 showing them the laser, if you're also willing to do the same or other stuff that will be a great help.

**Comment by johnmckerrell** [comment]
FYI I've sent this issue to Sale Sharks so they can see the discussion and see the general issues list too.

**Comment by ajlennon** [comment]
I'll spend some time with one of them.

I also told them I'll give them a tour around to introduce them to the space

**Comment by MatthewCroughan** [comment]
If someone can teach them how to use the laser cutter effectively, they could be getting on with the requests that we get from people on the google group to laser cut items for them, he might even get genuine payment for that.

**Comment by ajlennon** [comment]
or she

**Comment by DoESsean** [comment]
@ajlennon  gave them a tour earlier on in the week, so I guess we're now waiting to find out whether any of them think that we'd be able to be of any use.

**Comment by ajlennon** [comment]
I did indeed. At the end the chap in charge did mention the work experience. I told him I felt he probably needed to catch up with @johnmckerrell when he got back :)

**Comment by ajlennon** [comment]
Oh and he has said a few times if DoES needs any kind of maintenance work doing these guys could do it

**Comment by DoESsean** [comment]
There hasn't been any further movement on this in the last few weeks has there?

@johnmckerrell is it worth us asking, or are we waiting for Sharks to come to us?
