### ISSUE TITLE
Liverpool MakeFest - June 29 2019 - DoES Liverpool stand

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1124]
This is to list of exhibits and things we need to get ready for Liverpool Makefest, which is on 29 June 2019 this year.
I have spoken to @ka81, who says we can have 4 trestle tables.

**Comment by jackie1050** [comment]
List of exhibits (please add details of anything you want to display here) - 

- @Sean-anotherone - Arcade machine
- @jackie1050, @zarino, @goatchurchprime (and others) - Wing costume, Defence dress
- @magman2112 (and others) - Knitic
- John Cassidy - IoT-related

**Comment by jackie1050** [comment]
List of display-related stuff to take with us:

- black tablecloths
- display triangles (need cable ties), or replacement
- printed descriptions for exhibits
- stands for descriptions
- vertical display unit
- business cards and flyers
- television to show promotional videos

**Comment by anotherrrealm** [comment]
Hi it's Sasha. Planning to take my Cabinet of Curiosities to MakeFest.
![IMG_3452](https://user-images.githubusercontent.com/51460495/59061619-c94bb080-889b-11e9-8ae2-2525c1256af9.jpg)
Will need some sort of stand to prop it up

**Comment by jackie1050** [comment]
Thanks Sasha - it's an amazing piece - we'll get back to you when you can bring it in for Makefest

On 6 Jun 2019 20:44, anotherrrealm <notifications@github.com> wrote:

Hi it's Sasha. Planning to take my Cabinet of Curiosities to MakeFest.
[IMG_3452]<https://user-images.githubusercontent.com/51460495/59061619-c94bb080-889b-11e9-8ae2-2525c1256af9.jpg>
Will need some sort of stand to prop it up

**Comment by jackie1050** [comment]
More stuff being displayed on the stand in addition to above:
Jeremy and Luke - fake levitated pearls, levitator - both need mains electricity
Julian - Telepresence robot - needs mains electricity if used for 6 hours or more
Mike - Synths: TaTSH, Jasper: need mains electricity, vocoder
Paul H: retro computer

**Comment by amcewen** [comment]
I'll have some [LED cufflinks](https://mcqn.com/lfc), a Museum in a Box, and an Ackers Bell.  The bell and the Museum in a Box will need power, and the bell will need WiFi.

**Comment by anotherrrealm** [comment]
@magman2112 depth of cabinet is 5.4cm

![IMG_4094](https://user-images.githubusercontent.com/51460495/59600473-285dc080-90f9-11e9-8183-fbce8e2b69b1.JPG)
![IMG_4095](https://user-images.githubusercontent.com/51460495/59600474-28f65700-90f9-11e9-8708-d4ff15b426d7.JPG)
![IMG_4096](https://user-images.githubusercontent.com/51460495/59600476-28f65700-90f9-11e9-8e4c-4ceaa9ad3cef.JPG)
![IMG_4097](https://user-images.githubusercontent.com/51460495/59600477-28f65700-90f9-11e9-8330-e34205116b07.JPG)

**Comment by anotherrrealm** [comment]
Please don't judge the terrible gluing, it was a rush job! No one will see the back anyway

**Comment by anotherrrealm** [comment]
**text for Makefest display card**


CABINET OF CURIOSITIES

Laser cut MDF, print and promarker pens


My curiosities include many everyday things from my life special to me, from my bike, my d20 d&d dice, my studio mug, favourite teapot, my weird brain, lemons, but also represent my love of otherness, occult, sci-fi, horror, fantasy etc that seep into my being. The wardrobe to Narnia, lampost, and Mr.Tumnus’s house are something I’ve obsessed with since a very early age. Lastly why not include my fused together catdog, and of course, my kids in a jar.

Made by Sasha Spyrou

**Comment by zarino** [comment]
The fabulous [Julijana Zappia](https://www.facebook.com/julijana.zappia) will be bringing a "steampunk"-styled fascinator, based on the one she built at our [Fabulous Fascinators workshop](https://github.com/DoESLiverpool/somebody-should/issues/1125).

The lights and Arduino Nano _can_ run off a 9V battery, but probably not all day. I’d suggest we plug the Nano into mains power, with a micro-USB phone charger cable. So that’ll mean, all she requires is:

* A micro-USB power cable and plug (typical phone charger)
* A mannequin head to display the fascinator on
* A display card – I’ll ask her for text this week

**Comment by jackie1050** [comment]
I've put the new table cards and stands in the drawer with the triangles (thanks @zarino and @Sean-anotherone for producing these).
We need to arrange for the following items we've borrowed to be returned:
- 3 mannequin heads to Cathy Reilly at LJMU (would be good if we could get another to use permanently with "Bath time jewels"
- Defence Dress to Little Inventors
- Dress Stand to Mary Lamb
-

**Comment by jackie1050** [comment]
Defence dress needs to returned by 5 September, with its new power supply, any other components, and amended instructions.
jill@littleinventors.org 
16 The Crescent 
West Rainton
Houghton-le-Spring
Tyne & Wear 
DH4 6SB
I've copied in @magman2112 as he's currently making the new power supply

**Comment by zarino** [comment]
The 3 mannequin heads have been returned to Cathy at LJMU.

I’ve opened new tickets for the Defence Dress items:

* #1205 Finish the Defence Dress power supply, and return it to Little Inventors
* #1206 Return Defence Dress mannequin stand to Fabrication

So I’m going to close this ticket.
