### ISSUE TITLE
Trial Sonoff wall switches & PIR sensors

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1130]
I'd like to trial putting in some Sonoff Wall Switches

With these in place we could automate lights on/off on a schedule and perhaps link them to motion detection to reduce energy usage.

![image](https://user-images.githubusercontent.com/1537834/57574695-a44b5580-7435-11e9-9ddc-dda3db455bbe.png)

What are the thoughts for / against ?

**Comment by ajlennon** [comment]
I also have some PIR sensors that given the break-in that happened last night we might want to install?

**Comment by DoESsean** [comment]
If it's not going to negatively affect the user experience in the space or cost us money, then have at it.

**Comment by ajlennon** [comment]
Hurray!

**Comment by amcewen** [comment]
The first part of @DoESsean's sentence is the key one to me.  What's the user need it's trying to solve?  

(Personally, I also think light switches should look like light switches, so that people know to use them, rather than wall blanking plates...)

We might also need to get Mick to do any work to the electrics - I'm not sure what our lease specifies.

**Comment by johnmckerrell** [comment]
There does seem to be a habit of leaving the light on in the alcove and the laser room though so a way of solving this would be good.

**Comment by DoESsean** [comment]
I don't _think_ this ever happened. Should we close it?

**Comment by ajlennon** [comment]
yeah I guess so
