### ISSUE TITLE
Horizontal grey banding on prints from the B&W LaserJet Pro M402dn

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1164]
The network-attached B&W laser printer started printing poorly over the weekend:

![IMG_8453](https://user-images.githubusercontent.com/739624/60422578-36750c00-9be4-11e9-8e2b-1ee1d9f04734.jpg)

![IMG_8454](https://user-images.githubusercontent.com/739624/60422590-3c6aed00-9be4-11e9-976d-2a50a75e2f0f.jpg)

I tried printing the printer’s in-built Cleaning Page, twice, and it made no difference.

The printer reports that its black toner cartridge is about 45% full.

Things we could try next, sourced from a quick browse of the web:

* "Ensure that the toner collection unit isn’t full."
* "Shake the toner."
* "Pull out the toner and look at the drums. You can have a waste toner collector gummed up."
* "If cartridges are low or very low, for better print quality replace the cartridge."

**Comment by chris-does** [comment]
This printer is currently offline with the toner cartridge that was in it having been permanently removed due to issues with how it was releasing toner seemingly causing banding.

A new, high capacity, replacement cartridge has been ordered as follows:

[Compatible HP 26X Black High Capacity Toner Cartridge](https://www.cartridgeshop.co.uk/Toner/HP/HP-26X-CF226X-Compatible-High-Capacity-Black-Toner-Cartridge-16577.html)

It should arrive on either 18th or 19th November 2019.

In theory, this cartridge ought only to need to be inserted and the printer will then be ready to commence - non-banded - printing. 
However, based on the insides of the printer (and the removed toner cartridge), I plan on completing a more thorough clean of the inside of the printer before installing the cartridge.
I hope to be able to complete the more thorough clean of the inside of the printer on either 18th or 19th November.

- [ ] Clean inside of B&W HP LaserJet Pro M402dn

**Comment by chris-does** [comment]
The new toner arrived - thank you for taking delivery of it @DoESsean.

The B&W HP LaserJet Pro M402dn has now been cleaned inside.

The new toner cartridge has been installed.

Following some initial test prints, the B&W HP LaserJet Pro M402dn now appears to printing normally again.

The following demo page was the last test I printed:

![Demo Page printout after cleaning inside of printer and installing new toner. by chris-does](https://i.imgur.com/MDPZOTp.jpg)

This newly installed toner cartridge should provide c9000 prints.

Going forward I believe there is a balance to be struck with regards to the cost of the replacement toner cartridges:
- Official HP toner is approximately £180. I think it is unnecessary to purchase official toner given the extremely high price. Though there is some anecdotal evidence of using an official toner once in a while increasing the life of the printer, personally I believe this to be more applicable to inkjet printers and ink cartridges.
- Non-official / certified compatible toner from “printer supply specialists” is approximately £80. This is the type of toner purchased and installed to close this #1164 issue. There are a reasonable number of reports that this “class” of toner performs equivalently to Official HP toner and lasts as long.
- Non-official / compatible low-cost toner sourced from various marketplaces is approximately £30. This is the type of toner that was previously installed in the printer. There are several reports that this type of toner does not perform / last as well as the other two options above. However, if it performs adequately, and lasts half as long as the toner from the “printer supply specialists”, given it costs less than half as much then perhaps it is still acceptable to use. . .

I will close this issue on the basis the actual fault has been remedied. 

Though I plan to do some follow up work on the cost benefit analysis.





<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
