### ISSUE TITLE
Set DNS for robochallenge.doesliverpool.com to point to the same host as robotwars.doesliverpool.com

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1187]
@Sean-anotherone asked for a new hostname for the robotwars forum, in prep for its next iteration.

**Comment by amcewen** [comment]
New DNS records created, presumably @MatthewCroughan might need to tweak bits of the forum machine to recognise its new name.

Once you've confirmed it's propagated and working, we can close this issue...

**Comment by MatthewCroughan** [comment]
I did this last night but forgot to update the issue, the docker container I had for this now indeed points towards robochallenge.doesliverpool.com. Now I just need to:

- [ ] Update the assets on the forum
- [ ] Use docker-compose instead so that it's more maintainable, and its source can be put on the Github here.

**Comment by MatthewCroughan** [comment]
Will get on this in the next 24 hours.

**Comment by MatthewCroughan** [comment]
10 days is apparently 24 hours for me, my time is heavily dilated. I'll fix this up tomorrow, as I've been busy and productive doing things around DoES and have caught the productivity bug.

**Comment by MatthewCroughan** [comment]
I've updated references to robotwars on the forum, I'm going to spend a bit of time now trying to get this deployable via docker-compose in the [Robochallenge Repo ](https://github.com/DoESLiverpool/robochallenge/tree/master/logos)

If this proves difficult I'll simply back up the forum and then call it a day for now since it would take too much time.

**Comment by MatthewCroughan** [comment]
I can't quite succeed at using Docker-Compose yet because of issues with using the bitnami image, however the title of this issue is complete, so I'll close it and spin up another issue relating to the docker-compose stuff.

https://github.com/bitnami/bitnami-docker-discourse/issues/106
