### ISSUE TITLE
Vinyl cutter PC isn't online

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1192]
The PC for the vinyl cutters and sublimation printer doesn't seem to have any network connection.

It did a couple of weeks back, as I used Dropbox on it then.  Has someone stolen a WiFi dongle from it or something?

**Comment by MatthewCroughan** [comment]
The reason for this mainly is because we can't use just any wifi dongle on it. An unactivated windows 7 will refuse driver downloads from the Windows update servers, meaning it only works whenever we happen to plug in the specific dongle that the drivers already exist for, which is just luck. 

We seem to have two of those long wifi dongles that clearly say "54MBPS" In italic, they often get swapped between the Vinyl Cutter PC and Sophia's PC, since they both are not connected via ethernet **and** both have unactivated Win7 which prevents them from using any random dongle.

**Comment by amcewen** [comment]
And the issue for us to solve that is listed where @MatthewCroughan?  Oh, here, where I've raised it...  We're allowed to make things better, rather than just shuffle WiFi dongles around, but it's hard to know that needs doing if nobody reports it...

There is an Ethernet port on the back of the PC - any reason why there isn't a network cable going to one of the network ports that @magman2112 and @Thingomy spent *lots* of time installing for such purposes?

**Comment by kayharvey** [comment]
The Ethernet socket with cat 5e cable currently plugged into it both worked fine when tested last night on Jackie's laptop with Ubuntu for ten minutes.  However when it is plugged into the vinyl cutter PC, the network status is instantly stuck in a 5-second loop between "Identifying... (No network access)" and "No connection is available".

**Comment by MatthewCroughan** [comment]
I don't know what could be causing that, I think we're best off reinstalling the majority of the software at DoES that relies on Windows in a reproducible way, using Win7/Win10 LTSC (Long Term Support) to eventually satisfy #1127

**Comment by johnmckerrell** [comment]
Just had a look and tried switching to the cable that was plugged into Bubblino and that seemed to work so hopefully it was just a bad cable (or, less likely, but could be the network port).

@amcewen tells me that it did work with the previous cable for a while but then stopped working again so it could just be a temporary fix and still a dodgy network "card".

**Comment by johnmckerrell** [comment]
Wasn’t online this morning so I’ve put the WiFi dongle back in. I guess that does put it online so this can remain closed
