### ISSUE TITLE
Obtain official "Transport New" font for vinyl cutter PC

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1212]
The Raoul Transport Britannique font that we have been using isn't really suitable for vinyl cutting as it contains some extra lines inside the bounding lines of the characters. By default vinyl (and laser) cutters will cut these.

Adrian bought a personal copy of New Transport and used it for the door signage, but Arial has been used for some less prominent signs (e.g. on workshop desks). 

We could buy an official version of New Transport for around £15. @amcewen to provide details.

**Comment by chris-does** [comment]
@jackie1050 @amcewen 

I wholeheartedly support, and am happy to contribute to the cots of, ensuring DoES has the appropriate licenses for any typeface usage.

The indicated licensing cost of circa £15 seems very low to me (admittedly it's a while since my graphic design days though!).

I'll gladly be advised that due to DoES operating as a CIC (or some other mitigating factor), that DoES is able to benefit from favourable licensing terms that result in the substantially reduced estimated licensing cost.

I know I am the newbie here, and I don't doubt DoES has collectively addressed similar licensing scenarios in the past both appropriately and successfully.

I just thought I ought to at least mention this potential discrepancy to mitigate the risk of DoES paying (whatever amount) in good faith, only to discover down the road that there are significant back-payment of licensing costs to cover.

Yours hoping that I am being over-cautious and paranoid . . .

**Comment by johnmckerrell** [comment]
I don't see how to buy it for £15, my attempts to buy all variants for printing by many people end up costing in the many thousands? (at https://www.a2-type.co.uk/new-transport )

**Comment by MatthewCroughan** [comment]
In the spirit of open source, I'm just suggesting that if we ever decide to remove this burden in the future, we should use https://fonts.google.com/specimen/Open+Sans. There's lots of other options on google fonts too. In my brutal honesty, and I think many others would agree, there's little visible difference between New-Transport and Arial, so much so that it's used interchangeably.

**Comment by amcewen** [comment]
It's Transport New rather than New Transport because, as @johnmckerrell noted, New Transport is super expensive.  (I couldn't remember exactly which end the New went on when I was telling @jackie1050 about it).

@MatthewCroughan, in an attempt to help you understand how the fonts do not "have little visible difference", are we allowed to argue on any of your "we should put Linux on X" issues that "there's little visible difference between Windows and Linux and so we should use Windows"? ;-)  One of my first thoughts on seeing the "Leave this desk clear" vinyls on the workshop desks (after "ace!  People making the space better") was "hmm, that doesn't look like the right font :-("

@chris-does, AFAICT the £15 for [Transport New](https://www.k-type.com/fonts/transport-new/) is legitimate, and they do have an "Enterprise" option for £180, if we don't want to worry about any usage of it for DoES purposes... I think a single license on the Vinyl PC is good enough to start :-)

I've bought one copy and installed it on the Vinyl PC, updated the [style guide](https://github.com/DoESLiverpool/somebody-should/wiki/Style-Guide-(signs,-logo,-etc.)) and put it somewhere really safe.  @johnmckerrell spotted that the commercial license lets us install it on up to 5 machines that DoES owns, so we could add it to a few other machines.

**Comment by johnmckerrell** [comment]
Indeed, for the record I have since spotted that the license for Transport New rather than New Transport is much cheaper but should cover our needs. There are restrictions and we shouldn’t just install it wherever we want but that shouldn’t be necessary anyway.

**Comment by MatthewCroughan** [comment]
@amcewen When we reinstall the machines, does that count as a "new machine" in the same way as a lot of these licenses do? Where are the font files so we can re provision it?

**Comment by MatthewCroughan** [comment]
Also, I think operating systems and fonts are apples to oranges, we can agree to disagree though.

**Comment by amcewen** [comment]
@MatthewCroughan I haven't checked, but I'd think that transferring the license would be okay (so if the old copy has been deleted).  The files are somewhere really safe(tm), so you'll have to get the copy from an organiser when you need it.

And glad that my OS comparison struck the right nerve ;-)  You were very strident in your opinion that fonts aren't important, and I was pointing out that while *you* might not care about fonts, that's not true of everyone.  

If you want not to have to care about fonts, then stick to using Transport (or one of the derivatives listed in the [style guide](https://github.com/DoESLiverpool/somebody-should/wiki/Style-Guide-(signs,-logo,-etc.)) round here and you won't have any problems :-D

**Comment by MatthewCroughan** [comment]
I'll be sure not to mention my opinion on these things in future in that case if they're not valuable as I suspected. Not playing a victim, just don't know what else you're suggesting. I think you've focused on the wrong thing, there's an entire paragraph suggesting alternatives. I'm not understanding how you've equated that to **"You don't care about fonts."**

**Comment by chris-does** [comment]
> It's Transport New rather than New Transport because, as @johnmckerrell noted, New Transport is super expensive. (I couldn't remember exactly which end the New went on when I was telling @jackie1050 about it).

@amcewen thank you for this clarification. Indeed, the prices @johnmckerrell encountered for [_New_  **Transport**](https://www.a2-type.co.uk/new-transport), rather than [**Transport** _New_](https://www.k-type.com/fonts/transport-new/), are more inline with my previous experience of licensing similarly identifiable commercial fonts.

I am really glad that my concerns were not applicable in this instance :-)
 
> @chris-does, AFAICT the £15 for [Transport New](https://www.k-type.com/fonts/transport-new/) is legitimate, and they do have an "Enterprise" option for £180, if we don't want to worry about any usage of it for DoES purposes... I think a single license on the Vinyl PC is good enough to start :-)

@amcewen As [K-Type](https://www.k-type.com/about/) self-identify (and are corroborated by some third party font providers) as the creator/designer of [**Transport** _New_](https://www.k-type.com/fonts/transport-new/), I agree with you that they are in a legitimate position to license their [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font.

I have reviewed the [K-Type Licensing Agreement](https://www.k-type.com/licences/) and I also agree with you that an initial "Commercial Licence (Normal Licence)" ('allowing installation on up to 5 workstations and output devices, and unlimited page views with @font-face usage") installed on the Vinyl PC is a good place to start. :-)

@amcewen @MatthewCroughan regarding the status of a license pertaining to an existing device which has been counted as 1 of the '5 workstations and output devices': the wording of the [K-Type Licensing Agreement](https://www.k-type.com/licences/) is constructed such that, so long as a counted device is no longer able to make use of the font, a replacement / alternative / new device would be able to (re)use that license and be counted as 1 of the '5 workstations and output devices' without increasing the total in-use count.
In the event that the "device" does not change physically e.g. the change is due to an O/S reinstall or VM re-provision etc. again, so long as the original means of access (e.g. prior O/S installation or VM etc.) is no longer able to make use of the font, a replacement / alternative / new / reinstalled O/S or revised VM would be able to (re)use that license and be counted as 1 of the '5 workstation and output devices' without increasing the total in-use count.

Thus so long as DoES never requires more than 5 "active" workstation and output devices, then the quantity of such devices afforded by the "Commercial Licence (Normal Licence)" would be sufficient.

However, the license would not support the operating practice of repeatedly installing and uninstalling the font on multiple devices (exceeding 5 in total) for different purposes or for use by different people, whilst "technically" ensuring that at any one instant the "active" install base never exceeds '5 workstations and output devices'.
This practice would be considered "license manipulation" and therefore be a breach of the terms & conditions - I do not mean to imply DoES or any of its members would propose or partake of this practice, but thought I should include it and state its invalidity for the avoidance of doubt.


With that said, and I am happy to accept I may be biased by my past, I believe that obtaining an "Enterprise Licence (Extended Licence)" permitting considerably expanded use cases, in particular:
- "incorporated within software products such as apps, games, ebooks or computer programs intended for resale, redistribution or promotional purposes"; and
- "fonts to be stored on an unlimited number of workstations and output devices belonging to you";

would be of significant benefit to DoES.

@DoESLiverpool/directors I would be more than happy to contribute 50% of the necessary funds to acquire this "Enterprise Licence (Extended Licence)" as I am passionate (feel freed to read "pedantic" / "obsessive") about the importance of typography :-)

P.S.

_I absolutely do not wish to _even by accident_ teach anyone to suck eggs, so if anyone reading this is familiar with the limitation of liabilities in Ts&Cs, and in particular how they relate to three (or more) party conflict, please feel free to skip the rest of this note and enjoy the rest of your day unhindered by my further ramblings ;-)_

I should probably add, that I have also reviewed the [K-Type Terms & Conditions](https://www.k-type.com/terms-conditions/). I do not wish to sound negative or be alarmist, when I state that there are several clauses in this document - significantly those regarding liability - that, at best, would require litigation to resolve, in a licensee's favour, conflicts with the [K-Type Licensing Agreement](https://www.k-type.com/licences/) regarding font usage.
Specifically, in this particular instance, these conflicts arise primarily due to [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) being what is referred to in the design profession as a "redrawn" font:

A "redrawn" font is one which is based on an existing font, and that incorporates changes to the original font sufficient that the "redrawn" font is distinct to, and not considered a copy of, the original font and instead acknowledges its heritage whilst identifying its differences.

In principle this practice is well established and accepted within the design profession.

The proverbial "fly in the ointment" is that there is not a truly objective legal definition as to what constitutes "sufficient changes". As a result, if the designer of the original font asserts that there are _not_ "sufficient changes" between the original font and the "redrawn" font, the burden of proof rests with the creator of the "redrawn" font.

There are several actions that are often taken in the design profession, either in isolation or combination, to mitigate the risk of any such claim being made. These are listed below in order of decreasing frequency of usage, and increasing level of risk mitigation:

1. Attribution - the designer of the "redrawn" font will explicitly and, notably, in advance of any claim made against them or a licensee, reference the original font;
2. Specification - the designer of the "redrawn" font will explicitly and, notably, in advance of any claim made against them or a licensee, describe / show in detail the differences between the original font design and the "redrawn" font design that constitute "sufficient changes";
3. Limitation - the designer of the "redrawn" font will explicitly, and, notably, in advance of any claim made against them or a licensee, include in either (or both) their license agreement for the "redrawn" font or (and) their overall terms and conditions that they (the designer of the "redrawn" font) will not be liable for _any_ claims brought against them or a licensee of their "redrawn" font; and, lastly, 
4. Indemnification - the designer of the "redrawn" font will seek explicit and, notably, in advance of any claim made against them or a licensee, a guaranteed confirmation from the designer of the original font that "redrawn" font contains "sufficient changes" according to the original font designer and will therefore be exempt from any legal claim to the contrary. This particular step may or may not result in the creation of specific licensing terms between the designer of the original font and the designer of the "redrawn" font regarding how the "redrawn" font may or may not be used; this license may or may not require a monetary sum or sums to be paid to the designer of the original font by the designer of the "redrawn" font according to defined criteria.

It is fair to say that the pursuit of legal claims against "redrawn" fonts is most commonly encountered when a "redrawn" font pertaining to the typeface of a recognisable brand / organisation / entity is used in a manner to benefit the licensee of the "redrawn" font by - perceived rather than actual and authorised - association or affiliation with the recognisable brand / organisation / entity.
In such cases, whilst the designer of the "redrawn" font is often pursued as well, the emphasis (and usually the significant proportion of any determined damages) is typically placed on the licensee of the "redrawn" front.

In summary:

- The [K-Type Licensing Agreement](https://www.k-type.com/licences/) contains suitable and sufficient clauses to legitimately license the [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font as created by [K-Type](https://www.k-type.com/about/).

- The [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font definition includes both 1. Attribution and 2. Specification from the list above.

These two aspects are positive from the perspective of DoES as a licensee of the [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font.

- The [K-Type Terms & Conditions](https://www.k-type.com/terms-conditions/) contains limitation of liability per 3. Limitation in the list above. However, this is notably implemented such that the limitation of liability applies only to [K-Type](https://www.k-type.com/about/) and not to the licensee.

- It is not known whether [K-Type](https://www.k-type.com/about/) have implemented 4. Indemnification from the list above, and by extension the terms of any such indemnification are not known.

These two aspects are not positive from the perspective of DoES as a licensee of the [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font.

When combined these four aspects mean a licensee who legitimately licenses the [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font from [K-Type](https://www.k-type.com/about/) in accordance with the [K-Type Licensing Agreement](https://www.k-type.com/licences/) is protected by a claim from the designer of the "redrawn" font (in so far as the licensee complies with the [K-Type Licensing Agreement](https://www.k-type.com/licences/)), but the licensee is, in fact, not protected from a claim by the original designer of the font, that the "redrawn" font being used does not contain "sufficient changes".

In conclusion, despite the conflict that exists between the [K-Type Licensing Agreement](https://www.k-type.com/licences/) and the [K-Type Terms & Conditions](https://www.k-type.com/terms-conditions/), due to the nature of DoES (its operating practices, offered products and services, and the manner in which DoES currently uses the [**Transport** _New_](https://www.k-type.com/fonts/transport-new/) font) I believe the risk of such a claim being brought against DoES is minimal.
