### ISSUE TITLE
Plastic melting on the heat press leaves residue behind

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1225]
The heat press has deposited some of its plastic on shirts that someone was trying to press today.

![image](https://user-images.githubusercontent.com/26458780/63193794-43e83780-c066-11e9-8f96-a130d8f3c413.png)

**Comment by jackie1050** [comment]
Wondering if this is due to melted PLA, although that last happened 12 days before this incident - more likely than that plastic has come off the heat press itself.
I looked at the heated surface and couldn't see any plastic residue, but there was a slight blue colour when I rubbed it with kitchen roll dipped in solvent.
In any case, whether melting plastic or printing t-shirts, it's a good idea to use baking paper to stop plastic or sublimation ink getting on the heat press surfaces and to protect whatever you've put in the press.
