### ISSUE TITLE
Gerald's laser housing has been knocked up, causing bed leveling problems.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1228]
The laser housing is higher than usual, meaning that it's not possible to level the bed using the bed leveling/clearance tool. This has not caused any real issue for me personally. But one person who has booked the laser had to raise their materials up to meet the beam by using some of the scrap plywood. I'm unsure if they actually needed to, or whether they just did so to be safe, since the clearance tool makes you believe it's not in focus. I had no problems engraving on or cutting 3mm and 4mm material.

I think this likely to have happened when someone lifted the bed up for cleaning.

**Comment by magman2112** [comment]
The lens module and air assist can be raised and lowered using a butterfly screw on the laser block. I suspect that the lens had been pushed up accidentally, but someone has already lowered the lens down to its usual position, so I will close this issue.

Also, remember to include @DoESLiverpool/laser-maintenance in any laser issues so that it gets flagged to the Laser Maintenance team.
