### ISSUE TITLE
A3 HP OfficeJet 7510 inket printer won’t print

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1240]
Displays error message on startup:

> There is a problem with the printer or ink system. Turn printer off, then on. If problem persists, contact HP.

For the last few days, the printer has been complaining that it’s too low on colour ink to print in colour, so I’d printed a few things in just Black & White instead (using the option presented at print time on the touchscreen).

This morning, after seeing @DoESsean tidy up the printer cartridges in the supply cupboard, I figured I’d swap out the empty cartridges.

After installing new Cyan and Magenta “CMYBabee” compatible cartridges (933XL), the printer seemed to get stuck in a software loop, complaining that the cartridges needed to be replaced. Tried turning the printer off, but after 10 minutes of the "Shutting down" animation, I figured something was properly messed up, so pulled the plug. On restarting, the printer showed the “There is a problem” error, above, and won’t let you do anything else.

I‘ve obviously tried turning it off and on, and while the printer does shut down and start up nice a quickly, it doesn’t get rid of the error.

Here’s HP’s page on the error, and suggested fixes:

* https://support.hp.com/gb-en/document/c03096304

Here’s a third party resource:

* https://www.bchtechnologies.com/blog/solved-ink-system-failure-there-is-a-problem-with-the-printer-or-ink-system-turn-printer-off-then-on-if-problem-persists-contact-hp

If we want to replace the set of ink cartridges, we’ll need to buy a new set. We only have 2 Black cartridges, and 1 Yellow cartridge in the cupboard.

**Comment by DoESsean** [comment]
I've ordered a colour pack (no black) of [these](https://www.amazon.co.uk/Smart-Ink-932XL-933XL-932/dp/B073S8TV96/ref=sr_1_6?crid=2BAGONC8G7947&keywords=933xl+ink+cartridges&qid=1569932095&s=gateway&sprefix=933%2Caps%2C144&sr=8-6) - figured that, since we already have black, it made sense to save a few quid while we checked if these would work.

I've no idea why the ones we have have suddenly decided not to, as we've never had a problem before and have got them a few times, but there you go.

These should be delivered tomorrow.

**Comment by DoESsean** [comment]
The new inks arrived, have been installed, and the printer is now working again.
