### ISSUE TITLE
Configure the DHCP server to hand out unchanging IP addresses to specific MAC addresses

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1279]
There's been a lot of discussion recently around m-DNS, ZeroConf, Bonhour or whatever we want to call it. Whatever the underlying issues they seem to be ongoing.

As a fall-back (e.g. for the Creality Printers) we've been printing the IP address alongside the m-DNS domain name.

Unfortunately these IP addresses keep changing.

There should be a feature in the DHCP server I would think that allows us to create a list of DHCP assigned IP addresses which don't change, and are handed out to specific devices based on the MAC address they report when obtaining an IP address via DHCP.

Assuming we don't already do this and I haven't missed it, can we maintain a list of such devices and their assigned IPs somewhere on the Wiki?

**Comment by skos-ninja** [comment]
Yes we can issue static IP's on request.

We also maintain a list that is managed by @DoESLiverpool/networking who can see this list however it is kept private right now as it doesn't seem appropriate to publically list devices with their IP's on the internet

**Comment by johnmckerrell** [comment]
Yes, this is very much a thing we do, and have done on request for MQTT.local, for example. Just let me know what devices you want making static and I can do that.

**Comment by ajlennon** [comment]
Great thanks. OK so as a starter for ten

MQtt broker - mqtt.local - b8:27:eb:9e:c3:d9 - 10.0.30.130
Creality CR-10S printer - octopi.local - b8:27:eb:4b:84:25 - 10.0.39.51
Matt's Ender 3 - matt-octoprint.local - b8:27:eb:7b:a1:2a - 10.0.38.149
Alex's Ender 3 - ender3-octoprint.local - b8:27:eb:a2:f6:28 - 10.0.38.32

**Comment by ajlennon** [comment]
Just realised. This is public! Shall forward the list directly :-D

**Comment by amcewen** [comment]
It'd be nice if the Pi at mqtt.local was actually set to use its allocated IP address too :-)  It's been sat on 10.0.30.194 for a while now...

**Comment by MatthewCroughan** [comment]
@ajlennon The issue from #1210 regarding mDNS I think is still that the Ubiquiti feature that essentially caches the last DNS result from a given piece of hardware.

The reason I think this is because even if two devices are running mDNS, they will not discover eachother **if** their .localdomain (dhcp hostname discovery) has been preferred by this ubiquiti feature. 

So, it's a race condition, wherein regular DNS is sometimes being preferred, making things subservient to the router's domain (.localdomain or otherwise) or the device's configuration in /etc/hosts.

**Comment by MatthewCroughan** [comment]
So if I have two Pi's running avahi-daemon, it will be up in the air whether their hostname resolves .localdomain or .local because this feature is preferring .localdomain some of the time. I don't know if this is simply when the router is discovering it, or how the feature works, but this is something I've observed.

**Comment by johnmckerrell** [comment]
These have now been configured, I'm afraid I've changed the IP addresses for the 3D printers but they should be easier to remember/transcribe now.

**Comment by johnmckerrell** [comment]
(I haven't touched the 3D printers themselves though so I believe they're still operating on their old IP addresses for now)

**Comment by ajlennon** [comment]
@MatthewCroughan given these IP addresses won't change again would it be possible for you to update those lovely little stickers you did? If you do make the change could you make the text bigger for #grumpyoldengineers ?
