### ISSUE TITLE
Need new batteries for the safety-nerd approved door opener

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1287]
The door-opener on the door to the main room needs new batteries.

**Comment by amcewen** [comment]
I bought some brand-new Duracell C cells from the small Tesco on Monument Place, and have installed them now.

**Comment by johnmckerrell** [comment]
I noticed the opener in our nursery was making a similar beeping noise and asked them how often they replace the batteries and they said the noise was actually due to a problem, that they generally don't have to change the batteries very often. She did say something about only changing the batteries at midday but I imagine that's related to the automatic settings they have set up, which we don't. I was told that one of them had used the same batteries for years with no problem.
