### ISSUE TITLE
Design and print A5 flyers for the Inclusive Economy event next Friday

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1289]
Next Friday I'm speaking at Inclusive Economy's [People Power Forum - Empowering the Grassroots](https://www.eventbrite.co.uk/e/people-power-forum-empowering-the-grassroots-tickets-72258997607).

Chatting to Patrick (who's organising it) earlier, he said that we can include a flyer in the attendee welcome pack.  So we should design an A5 flyer for it, get ~75 printed, and then get them to him before the event.

(Raising this as its own issue, rather than tagging it into #1097, as it's more targetted.

**Comment by chris-does** [comment]
>Next Friday I'm speaking at Inclusive Economy's [People Power Forum - Empowering the Grassroots](https://www.eventbrite.co.uk/e/people-power-forum-empowering-the-grassroots-tickets-72258997607). ...

@amcewen @DoESsean 

If you have something ready to go, great :-)

If not, I am happy to have a go at producing something tonight / before the end of tomorrow for your review.

May I seek a point of clarification:

On the basis we are printing it ourselves (or at the very least, having it printed by a local printer for us), can I assume that both sides of the A5 flyer can contain content? 
Rather than, for example, if we were just submitting A5 artwork for print / inclusion in an “Event Printed (or managed)” brochure / Welcome Pack.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DoESsean** [comment]
@chris-does that would be fantastic, thank you. While we're very good at many things, producing marketing material isn't one of them!

I would assume double sided would be right.

**Comment by chris-does** [comment]
I have started working on this.

I am a little behind where I wanted to be at this moment in time, but I hope to have a little more time to work on it tonight and will definitely have some time again on Wednesday afternoon which should hopefully still leave time for proofing, amendments and printing.

**Comment by chris-does** [comment]
@DoESsean @amcewen (and of course anyone else who would be willing to provide feedback for me to incorporate).

I have now produced the first draft for this #1289 A5 Flyer.

Attached here as two separate zipped PDFs are the proposed front [A5-Page001.zip](https://github.com/DoESLiverpool/somebody-should/files/3765013/A5-Page001.zip) and back [A5-Page002.zip](https://github.com/DoESLiverpool/somebody-should/files/3765015/A5-Page002.zip) layouts. 
If it would be beneficial, I can provide the original [Scribus](https://www.scribus.net/) file used to create them (I will absolutely make the final version available in this format and be sure to add it to [Branding-Kit](https://github.com/DoESLiverpool/branding-kit) repository).

In the meantime, I would welcome any feedback and/or change requests etc.

I will be able to work on this during Thursday, though with the event taking place on Friday morning, there will need to be a cut off at some point so that the final version can be printed in time.

With this in mind, I hope to be in DoES during the daytime on Thursday which will hopefully speed the proofing and amendment iteration process up (though by all means please leave any comments here, and I will start to action them as soon as I am able - regardless of location).

P.S. If this has completely missed the mark - please be brutally honest . . . I may yet be able to salvage something usable in time! :-)

**Comment by DoESsean** [comment]
Right, I think I'm falling on the side of copy being good, but I'd make some minor changes.

Side 1:

'DoES Liverpool is a co-working office and Makerspace in Liverpool's Fabric District, used and run by an enthusiastic and diverse community, from charity workers to Internet of Things experts. Whether you're a home office worker looking for a change of scene, or a hobbyist inventor that needs a little push, you'll find a home at DoES.'

Paragraph 3, I'd change the colon to a hyphen: '(...)meeting areas to support you - from our informal(...)'

Side 2:

Our Makerspace gives you low cost access... 
We provide a home for startups, established businesses and tinkerers, and all in a friendly environment that will give you the tools to do your best work.

Paragraph 2, I'd drop the Ultimaker from the 3D printer bit, as we have lots of other types too, and also lose vacuum former, as it's basically never working.

Final para, I'd drop the colon again and replace it with a full stop.



Happy to hear any push back on that, from @chris-does or anyone else. If there isn't any, we can make those changes and I'll try and get these out to a printer this afternoon.

**Comment by chris-does** [comment]
@DoESsean I too was a little concerned about the amount of text :-) 
I wanted to try and write a little bit about everything that DoES is, while staying below the 250 word (1 minute read time for an “average reader”) threshold, but I just stepped over at 251 :-( 

With that said, my thinking was that if I wrote about that quantity of text - assuming all the capabilities of DoES are covered - then whatever is less relevant for a specific event can be expunged to create a more visually impactful call to action (albeit with less information) or replaced with more targeted messaging accordingly e.g. a paragraph (and image or two) that address a recent project at DoES which relates to the theme/topic at the event/venue from which the associated flyer will be distributed.

I know that DoES has selected the Transport New font as its official typography per #2012, and so have used it here.
However, I did also want to ask if DoES has a colour wheel or brand palette (black and white are definitely included based on what I have seen around DoES and online), but is _yellow_ also an agreed colour (there seems to be some usage of this, but it’s not as pervasive)?
If not, I would be happy to work up some options - though I think more discussion on this is likely for #1097 and more general brand / marketing type chat :-)



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zarino** [comment]
@chris-does yeah we don‘t have any official brand colours other than black and white. Maybe one day we’ll sort out some proper brand guidelines, but today is not that day.

The flyers look ok to me. Thanks for your contribution!! In future I’d probably say don’t use the bold version of Transport for all the text, but I know choices are limited when it comes to the typeface/weights available. Also the vertically stretched logo is offending me slightly, but I doubt anybody who’s not a designer would notice or care.

**Comment by DoESsean** [comment]
Ok, I've just spoken to a printer who can do us a small run this afternoon that I can pick up about 4pm, if we get them the artwork over by about 2.

@chris-does would you be able to get that to me asap, and I'll send it over and get a price? Thanks!

**Comment by chris-does** [comment]
@zarino I’m glad you mentioned the “stretched” logo, I was slightly confused by the asset files I could find: the .eps file which I used for the logo in the top left has the ratio as depicted, and yet concurrently the .png file I used for the logo inside the QR code has the ratio as depicted there . . .

If you can let me know which one is correct, I will (gladly as it annoys my eyes too!) make sure they match :-)

Also, believe it or not - that isn’t the **bold** version of the font (that’s an even heavier typesetting!). With that said, in the version I’m working on to include the revised wording from @DoESsean, I have switched to the lightest weight for the font, so please do let me know if it’s OK to stick with that.

@DoESsean Working on your typographic edits now and should be able to send over within the next half hour for final proofing...

Thank you both for your feedback - it’s much appreciated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chris-does** [comment]
@DoESsean please find the two updated files here:
[A5v2-Page001.zip](https://github.com/DoESLiverpool/somebody-should/files/3767432/A5v2-Page001.zip)
[A5v2-Page002.zip](https://github.com/DoESLiverpool/somebody-should/files/3767434/A5v2-Page002.zip)
I think I have captured all the changes.
The one thing I have not yet amended is the logo as I do not know which ratio is correct (per above), alas I need to attend a meeting at 13:30 and so wanted to make sure I had incorporated as much of the feedback as I could in time for the 14:00 print deadline.
If I am available again before the ink has to hit paper - and if the correct DoES logo ratio can be confirmed - I will be only too happy to remedy that and make a further update.

Either way, I'll be heading to DoES as soon as my meeting is finished.

**Comment by zarino** [comment]
https://github.com/DoESLiverpool/somewhere-safe/blob/master/logos/DoESLiverpool.svg is the "official" vector copy of the logo. In a nutshell, the black square should be square.

**Comment by DoESsean** [comment]
@johnmckerrell has (in no way smugly) found a place that can do us a load of these relatively cheaply. There's not the time pressure either, so we can change the logo to the correct one when @chris-does arrives.

**Comment by amcewen** [comment]
Thanks for this @chris-does, and @DoESsean / @johnmckerrell  for sorting out the printing.  Apologies for just dropping this issue here and then disappearing - have been laid up all week with the lurgy that's going round :-(

I'll be calling into DoES later on to get the pop-up banner, so will be able to collect the flyers then too.

Longer-term (i.e. after today :-) we should update the .eps so we don't have the "which logo?" problem in the future (ta @zarino for giving the answer that I'd have given).  And @chris-does, I'm having the same "is yellow used enough to be a brand colour?" pondering while I pull together my slides for tomorrow.  Maybe we can get together with @zarino at a later date to think about that?

**Comment by chris-does** [comment]
Thanks @zarino for the definitive logo link, I have updated both the top left logo and the logo in the QR Code to reference this now (along with my own records too, for any future use :-) )

As always, a little nip and tuck here meant a little bit of re-sizing / aligning there to ensure appropriate image and spacing ratios are maintained - which I think they now have been.

@DoESsean On this basis, may I propose the following as the final version (pending any "final final" last-minute corrections required ;-) )

[A5v3-Page001.zip](https://github.com/DoESLiverpool/somebody-should/files/3768204/A5v3-Page001.zip)
[A5v3-Page002.zip](https://github.com/DoESLiverpool/somebody-should/files/3768205/A5v3-Page002.zip)

@amcewen Sorry to hear that you haven't been too well this week, hopefully, you will be feeling well (enough at least) for tomorrow. I would be only too happy to have the colour wheel / brand palette conversation with yourself and @zarino at some point in the future.

**Comment by chris-does** [comment]
@johnmckerrell thanks for catching that the logo in the QR Code still doesn't look quite right. I have double checked and despite updating to the correct source image, it appears that the QR Code generator is ignoring/overwriting some of the white space around the logo (perhaps to satisfy their own requirements/standards for separation between logos and the surrounding QR Code), and rather than scaling uniformly (albeit making the logo smaller) so it fully fits within their "designated area", the image is being transformed.

In any case, as we discussed, I have just manually placed a copy of the DoES logo (with correct ratio) inside the QR Code inside of the [Scribus](https://www.scribus.net/) document and based on the QR Code still working on both your and my QR Code Readers, I think we are safe to publish.

@DoESsean Therefore, as almost inevitably predicted, please find the "final final" versions below ;-)

[A5v4-Page001.zip](https://github.com/DoESLiverpool/somebody-should/files/3768314/A5v4-Page001.zip)
[A5v4-Page002.zip](https://github.com/DoESLiverpool/somebody-should/files/3768318/A5v4-Page002.zip)

**Comment by DoESsean** [comment]
Excellent stuff Chris, thanks.

I've sent this over now, it will be available for collection this evening.
Someone will have to pick them up, and preferably someone with a DoES Bank
card, as it's pay on collection. If that ends up having to be me, that's
fine, although it will depend on what time.

**Comment by amcewen** [comment]
I don't mind collecting it, but someone will have to tell me where that is from... :-D

**Comment by DoESsean** [comment]
It's Copy Stop UK, 14 Water Street.

**Comment by amcewen** [comment]
(and in general, it'd be good to know who "[a printer](https://github.com/DoESLiverpool/somebody-should/issues/1289#issuecomment-545870260)" is too @DoESsean, so we can continue to embed knowledge of useful suppliers into issues like this to save us having to hunt round again in future... :-)

**Comment by DoESsean** [comment]
Good point!

**Comment by chris-does** [comment]
The flyers have now been printed and hand delivered by [Copy Stop Printing Services](http://www.copy-stop.co.uk).

500 were delivered at a cost of £50 (no VAT) and @jackie1050 paid for them with DoES Cash (I believe the transaction has been entered where it needs to be and the receipt put in the appropriate place).

@jackie1050 has collected about 1/3 of the flyers to take with her in the morning to the event where @amcewen is speaking.

The remainder are on @DoESsean desk.

I have set the tracking for the QR Code to start from tomorrow, so we can see how effective it is. . .

I’ll leave this issue open until all relevant people have confirmed receipt of the flyers and then I think we can close it :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amcewen** [comment]
We have flyers!  Big thanks to @chris-does, @DoESsean and @jackie1050 for the wrangling to get this all sorted.

I've put the [latest version somewhere-safe](https://github.com/DoESLiverpool/somewhere-safe/tree/master/Promo/Posters/A5%20General%20Flyer).
