### ISSUE TITLE
We need to buy a new reel of lead free solder

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1313]
The large reel of lead free solder has run out - there is a small amount of other solder on the soldering station.but won't last long

**Comment by jackie1050** [comment]
![IMG_20191109_123631](https://user-images.githubusercontent.com/12802256/68533002-37e5dc00-031c-11ea-8773-152a5a289dcc.jpg)

**Comment by DoESsean** [comment]
The only one that is exactly the same as the picture that I can find in the UK is [this one from Rapid Online](https://www.rapidonline.com/weller-t0051387599-wsw-sc-m1-99-3-0-7-solder-wire-0-8mm-500g-85-6566) but it looks like it would take weeks to arrive, so I assume it's no good.

If anyone knows whether any other solder would be fine, let me know and I'll order it - I'm seeing a fair bit of WSW SAC M1 (rather than SC M1) which might be some kind of new thing? I have literally zero clue.

**Comment by amcewen** [comment]
I think the key features are 0.8mm diameter and lead-free.  Farnell, RS or CPC will likely have something suitable - I'll have a look later if no-one beats me to it.

**Comment by amcewen** [comment]
I've ordered a [500g reel of Duratool 0.7mm lead-free](https://cpc.farnell.com/duratool/d01686/solder-sn99-3-cu0-7-0-7mm-500g/dp/SD01540?st=solder) from CPC.

**Comment by amcewen** [comment]
Solder has arrived, and is installed on the spool holder on the electronics workbench.
