### ISSUE TITLE
The B&W laser printer isn't printing from the network

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1318]
The black and white laser printer (the white one next to Matt's desk) doesn't seem to be printing from the network.

Abdullah has printed fine from it directly, but both @ajlennon and I have tried from the network in recent days without any joy.

**Comment by zarino** [comment]
Not sure whether it’s obvious, but the JaserJet M402dn doesn’t have wireless capability. So it needs to be plugged in via Ethernet.

I came to use it this morning, only to find it wasn’t plugged into the ethernet network. (Which makes me wonder – was it plugged in when @ajlennon and @amcewen tried to print to it in the last few days?)

Anyway, I "borrowed" the red ethernet cable from the (big black) LaserJet Pro 200 Color, popped it into the back of the M402dn instead, and the print sent fine from my Mac – although it still produces pale grey banding on the output, likely because it’s low on toner? A new toner cartirdge would cost about £80 inc VAT.

I’ve moved the red ethernet cable _back_ to the Pro 200 Color now, but I guess really we should have both of them wired into the network at the same time. Is the reason we’ve _not_ done this so far because:

1. There aren’t enough ethernet ports nearby?
2. Connecting a second device would require some configuration at the router to open up another line, and nobody’s been able to do it?
3. Someone’s just stolen the ethernet cable for a different device nearby and not replaced it?
4. Or… something else?

**Comment by zarino** [comment]
PS I have updated the [OfficePrinters wiki page](https://github.com/DoESLiverpool/somebody-should/wiki/OfficePrinters) to include both laser printers now, and also make clearer which printers work wirelessly or not.

**Comment by chris-does** [comment]
I intend to remedy this, permanently, when I clean the printer ahead of installing the new toner cartridge ordered per #1164.

**Comment by chris-does** [comment]
#1164 Has been closed successfully.

Unfortunately I did not have my networking supplies with me and so I was not able to finish working on this #1318 issue.

However, I still plan to close the issue and will aim to do so on or before 28th November.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DuncReid** [comment]
I'm not in till next week but if it's a network cable you need, there may be some in the box under my desk - help yourself!

**Comment by amcewen** [comment]
I've just printed off on it successfully over the network, so I think this can be closed.
