### ISSUE TITLE
Need more sublimation paper

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1333]
When Sasha was going to do some sublimation printing earlier it turned out the printer was out of paper.  We could only find t-shirts in the "sublimation printer supplies" drawer, so I think we need to get some more paper...

**Comment by johnmckerrell** [comment]
There’s paper on Sean’s desk

--

**Comment by DoESsean** [comment]
We've had issues with the sublimation printer not pulling its weight in
terms of covering costs. Honestly, as it's difficult to track what is being
used, we're not totally sure whether that's down to it being priced
incorrectly, or to people printing and not paying.

Although I'm loathe to think it would be the latter, John and I had decided
that, until we can figure out a way to track it (which is going to be
awkward as all the inks are now running dry at different times, meaning I
can't just count the paper left when we change the cartridges), it made
sense for the paper to be kept separate to the machine so that we knew what
was being used. As I say, I'm not happy about it, as it kind of goes
against how the place works for everything else, but, given just how much
those inks cost, we can't really afford to be getting nothing back for them.

On top of that, there are a few (unopened) boxes of paper in my drawers -
there wasn't room for them in the supplies drawers when they arrived, so
they were put there for the time being, and quietly forgotten about.

**Comment by RussCoty** [comment]
DoES (pun intended) this call for the construction of an elaborate automated weighing paper dispenser and page print tracking script? 

Clearly something that would be OTT but could be “very DoES”.

**Comment by DoESsean** [comment]
Yes. Yes it does.

**Comment by jackie1050** [comment]
Just wondering how we know it isn't covering it's costs? 
Also, do we have a solution for maker night / out of hours when people might want to use the sublimation printer.
