### ISSUE TITLE
Experiment laser cutting circuits from mirrored acrylic

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1374]
The fact that the mirror layer is conductive and made from metal is interesting. Jackie and I posit that it might be possible to make conductive circuits similar to how one might make them on a cnc router but with a laser instead. 

Any thoughts? @goatchurchprime @amcewen

**Comment by RiverMersey** [comment]
Could the laser be damaged by the beam being reflected back into it's own lens?

**Comment by MatthewCroughan** [comment]
@RiverMersey Not at all, we do this all the time and it is produced in order to be laser cuttable by hobarts. The metal layer is incredibly thin and at no point is directly exposed to the laser, the acrylic layer is what is directly exposed.

**Comment by RiverMersey** [comment]
A quick google search suggests that acrylic mirrors can be relatively easily cut whereas glass mirrors are more problematic. Seems that the type of laser diode used also makes a big difference.

As I've not actually used the DoES lasers, I'm not fully aware of their specs. On the assumption that it is possible to have the reverse of the mirror laser-etched, then i think it would be possible to make circuit boards from the mirror. Another consideration, would the components be mounted on the reflective or non-reflective surface of the mirror? Would this make any difference in accessing/forming solder-points for the components?

Does this have to be done with a laser? How does an acrylic mirror react to the usual PCB chemical etching process?

Depending on the conductivity and thickness of the mirror layer, the tracks of the circuit would likely need to be many-times wider than those of an equivalent copper PCB - otherwise the mirror's tracks will burn-out as if they are fuses.

For now, the best reference I've found on using a laser on reflective surfaces is semi-advertorial at: 

https://www.daysteel.co.uk/news/cutting-reflective-metals-overcoming-issues-laser-cutting

**Comment by seanspotatobusiness** [comment]
Soldering without melting the acrylic would be an issue. The melting point
of acrylic is 160 C. You can get low melting temperature solders but
they're more expensive than conventional ones.

**Comment by RiverMersey** [comment]
Could the soldering be done in a solder bath?



On Wed, Jan 22, 2020 at 12:50 AM +0000, "seanspotatobusiness" <notifications@github.com> wrote:










Soldering without melting the acrylic would be an issue. The melting point


of acrylic is 160 C. You can get low melting temperature solders but


they're more expensive than conventional ones.

**Comment by RussCoty** [comment]
I’ve had some success recently with a new method that involves cutting the outlines into acrylic at a low power and fast speed to cut a groove 0.5 mm deep.

Then copper tape can be stuck on top, and the grooves followed with a scalpel. 

On a side note I wouldn’t be supposed if we like directly cut copper tape on a substrate. Effect on the laser tube would need to be tested.

Happy to try on my diode laser.

**Comment by Sean-anotherone** [comment]
Or, remanufacture the clasp nuts (or ball screws or whatever they are) on the proxxon machine and just exclusion-rout pcbs directly on that?  I understand that it works fine, but there is currently several mm of backlash in the axes, so useless for pcb.

I agree that the machines would cut the tracks into mirror acrylic easily - the problem would be getting the power balanced to cut the paint and copper without going all the way through.
But it would melt when soldered.

**Comment by arthurrowland** [comment]
Closed due to inactivity - if anyone feels a second wind on these experiments please reopen and forgive me for aggressive issue-pruning.
