### ISSUE TITLE
CCC conference in Hamburg 10 - 13 April 2020

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1403]
@MatthewCroughan suggested this CCC conference in Hamburg, having missed out on the one in Leipzig at new year:  https://presale.eh20.easterhegg.eu/eh20-orga/eh20/  It looks a bit too German.

**Comment by amcewen** [comment]
Dunno, I usually end up watching more of the talks from CCC than I do from other conferences; @goatchurchprime I think you might enjoy https://media.ccc.de/v/36c3-11241-from_managerial_feudalism_to_the_revolt_of_the_caring_classes for example.

**Comment by chris-does** [comment]
Unfortunately, this event has been cancelled due to restrictions put in place by the Hamburg Health Authority:

[Source Details](https://eh20.easterhegg.eu/)

Translation:
**No EasterHegg 2020 in Hamburg**
 
We are very sorry to announce that EasterHegg 2020 cannot take place in Hamburg. 

On Wednesday, the Hamburg health authority announced that it would shortly issue a general enforcement. This prohibits large events from 1,000 participants until April 30, 2020. 

In addition to this announcement, the recommendations of the Robert Koch Institute are sufficient to stop pursuing EasterHegg 2020 in Hamburg. The implementation of these recommendations would have presented us with an almost unsolvable problem. 

In the next few days we will also communicate further information, especially about the reimbursement of tickets and pre-order merch. 

By refraining from individual inquiries about rejection and reimbursement, you help us to deal with the tasks currently before us better and faster. We will keep you up to date with news. 

Thanks for your understanding! 

Sad greetings from Hamburg

the EasterHegg 2020 team 

**Note on DB tickets** 
Please do not cancel the tickets yourself. Send an e-mail to fahrkartenservice@bahn.de with the subject “Corona” and describe the case with ticket / order number and confirmation of the cancellation of the event due to Corona.
