### ISSUE TITLE
Sophia isn't cutting

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#141]
Sophia's laser seems to be malfunctioning, the machine works fine but the laser isn't coming on.

Magnet sensor has been checked, flow sensor has not and neither have the electrical contacts to the laser tube.

**Comment by amcewen** [comment]
@johnmckerrell has run some more checks - "I had a look this morning, the flow is fine and there's no obvious problems with the contacts, they're covered up and I didn't want to remove any tape but there was no charring and no obvious disconnections. Now that it's warmed up I just checked if it was firing, when you press the Laser button the  light shows up in the tube but just for a brief moment and then goes out. I haven't actually tried running it yet (didn't seem to be a program loaded and I have my call shortly)."

I tried running a quick test cut with no marks made on the material.  Checking the mirrors with masking tape, they get marked when you fire the laser, but no matter how long you hold down the "laser" button you only get a brief mark that doesn't cut all the way through the masking tape.  I've cleaned the mirrors and lens, but that didn't improve matters.

Looking at the tube, I spotted a divot in the inner tube.  The old tube doesn't appear to have that, so that seems the most likely culprit so far.  Some photos of it at https://www.flickr.com/photos/amcewen/sets/72157651803767388

**Comment by DefProc** [comment]
Fixed. The tube wasn't at fault, somehow during use, the 4th mirror (which points the laser downwards) had been rotated in it's mount — it's threaded, and clamps onto the moving gantry plate — so the laser was striking the surround instead of the mirror. This has now been realigned and the gantry wheels tightened too. 

The short pulse duration when running the laser is intentional (onboard menu, `Laser Setting` -> `Duration: 40ms`, `Power: 40%`) to use a short pulse on the masking tape covers when aligning the mirrors, and remains so the `Laser` button gives a small mark when pressed.

**Comment by amcewen** [comment]
For future ref, I'd checked with Just Add Sharks and the tube should look like that (obviously, given that it's still functioning fine :-)
