### ISSUE TITLE
Shutter doorbot isn't reading cards

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1417]
Luckily I was in early today, as the shutter doorbot wasn't recognising cards.  I got in by `ssh`ing into the doorbot and running the open door script.

`logcards` is still running on it, and seems okay.  I'll poke at it some more today.

**Comment by JackiePease** [comment]
I actually tried to use the card reader on leaving last night.l It didn't work, but at the time I put it down to not leaving it long enough between attempts.On 8 Apr 2020 08:40, Adrian McEwen <notifications@github.com> wrote:
Luckily I was in early today, as the shutter doorbot wasn't recognising cards.  I got in by sshing into the doorbot and running the open door script.
logcards is still running on it, and seems okay.  I'll poke at it some more today.

**Comment by Knottyashcreative** [comment]
Thank you for looking into it as tried to access this morning but the fob activated the sensor lights but the shutters never activated.

**Comment by amcewen** [comment]
A reboot didn't fix things, but investigating the fob reader it had come loose and it was too far back in the box to read things.  I've re-located it and it seems to be working fine - will try it again when I leave tonight and keep an eye on it

**Comment by MatthewCroughan** [comment]
Looks like a cable has come loose as can be seen in this image. I can recrimp and fix this before I leave at 9AM today.

**Comment by MatthewCroughan** [comment]
![image](https://user-images.githubusercontent.com/26458780/79037001-7cc0b800-7bc5-11ea-9b2f-fd7884400482.png)

**Comment by amcewen** [comment]
It was still working fine when I was there earlier - tried quite a few times without any problems.  I've taken @Sean-anotherone's suggestion though and popped a cut-down washing up sponge in the box behind the PCB, to help hold it in place against the front of the box.  Hopefully that'll also stop the wiring from moving at all.

It was still working okay when I boxed it all back up and did a few tests.

**Comment by MatthewCroughan** [comment]
Sorry! I didn't get around to filling out the details of what happened after I woke Adrian up at 4AM to get into DoES.

I wouldn't call this closed quite yet. I sent details to you in Signal @amcewen 

This is the state the wire was in.

![image](https://user-images.githubusercontent.com/26458780/79066319-ff717200-7cae-11ea-8aea-5d38319ab8c3.png)

I then used a pair of pliers to manually crimp a new dupont into place.

![image](https://user-images.githubusercontent.com/26458780/79066314-f2ed1980-7cae-11ea-94ab-aa498bcf6d16.png)

The real problem is highlighted in the [video I've taken here.](https://files.catbox.moe/1zvubj.mp4)

Succinctly, the dupont header is too loose and the thick wire behind is too thick. Attempting to shove the sensor into its enclosure causes massive strain directly onto the dupont header. So much so that it actually rips some of the wires out of their plastic dupont header.

**Comment by Sean-anotherone** [comment]
I think Matt has the right idea, but I'd propose just stripping Bach the last section of cable and cooling the conductors, to allow for future mods or trimming.  Also might be sensible to solder the connections if this has been a recurrent issue.

Sent from Yahoo Mail on Android 
 
  On Sun, 12 Apr 2020 at 11:19, MatthewCroughan<notifications@github.com> wrote:   


Sorry! I didn't get around to filling out the details of what happened after I woke Adrian up at 4AM to get into DoES.

I wouldn't call this closed quite yet. I sent details to you in Signal @amcewen

This is the state the wire was in.



I then used a pair of pliers to manually crimp a new dupont into place.



The real problem is highlighted in the video I've taken here.

Succinctly, the dupont header is too loose and the thick wire behind is too thick. Attempting to shove the sensor into its enclosure causes massive strain directly onto the dupont header. So much so that it actually rips some of the wires out of their plastic dupont header.

**Comment by MatthewCroughan** [comment]
@Sean-anotherone There is no risk of cutting the cable too short, as it's very very springy. My attempt to pull it back from the other side was unsuccessful since it just springs back. We can however pull it as far as we want through towards the street, it seems there's a lot of cable to play with.

I think soldering is potentially wise. The only reason this has caused an issue is the amount of pressure inside the enclosure from the tautness of the wire.

So, we have two issues:

 1. The wire is too taut, causing strain on all connections
 2. The sensor sometimes dis-adheres from the front of the enclosure, where there is two double sided sticky pads. This causes it to be too far away from tags when presented

The second issue is the *initial* reason this issue presented. I think that's probably due to the Summer temperature change.

**Comment by amcewen** [comment]
@kayharvey re-terminated all the dupont headers on this (relatively) recently.
