### ISSUE TITLE
There's no hot water in the kitchen

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1425]
The water heater in the kitchen isn't working.

The power light isn't on.  I checked the circuit-breaker and that seems fine.  Didn't have chance to investigate any further.

**Comment by johnmckerrell** [comment]
Only asking because you didn't say it, but is there a switch next to the heater and is it definitely on?

**Comment by amcewen** [comment]
I can't see a switch next to the heater.  I know there used to be one in Gostins, but the wiring seems to disappear into the wall now.

**Comment by amcewen** [comment]
There is a switch in the server cupboard, but that didn't make any difference.  I popped the case off it and checked that it's getting 250V to the unit, but the power light isn't on.  I guess the next step is to see if Mick can come look at it...

**Comment by JackiePease** [comment]
Mick is coming in on Fridaay morning (I'll be there as I'm doing a laser induction then)

**Comment by amcewen** [comment]
If it turns out we need to replace the water heater, we should probably get a slightly more powerful one, as the current one only just gets the water hot enough to pass the legionella(?) test, so it'd be good too have a bit more headroom.

**Comment by JackiePease** [comment]
Mick has looked at both water heaters:
- kitchen: he thinks the thermostat has gone, and that it probably isn't worth trying to fix. He's going to get a quote for a replacement heater
- toilets: he thinks that the heater isn't up to the job that's being asked of it. He's going to get a quote for a replacement heater

**Comment by johnmckerrell** [comment]
Is there an issue about(/with) the toilets heater? I know this was the second option that Jason put in. If it’s not up to the job it would need to be him that replaced it (or paid for it) but he’d want to be sure there was a problem I imagine.

**Comment by amcewen** [comment]
The toilets water heater has a heated reservoir of water, which does run out if you run the hot water for long enough, but I think it's all working fine and doesn't need replacing.

For the replacement kitchen one, it's maybe useful to get one with a reservoir too - the old one doesn't have that.  As a datapoint, Aeternum has an [Ariston Europrisma 15ltr 3KW unit](https://www.screwfix.com/p/ariston-undersink-water-heater-3kw-15ltr/2371g), which is almost too hot at times.

**Comment by johnmckerrell** [comment]
I think the bathroom one can actually be (almost) too hot as well. For the record I've now contacted a plumber (rather than electrician) and he's going to get us a price across.

**Comment by amcewen** [comment]
Could we ask the plumber about the sink in the less-accessible toilet too? #1521

**Comment by johnmckerrell** [comment]
> For a Triton 3KW over sink water heater, you are looking at £220 supplied and fitted.

I've now gone back to mention we'd need something that can be plumbed in and serve two sinks. The unit he mentions is similar price to the one Adrian mentioned so hopefully it won't cost too much more to fit (I suppose it does have 2 connections vs 1). I've also mentioned we might want some drainage work doing as covered in #1522

**Comment by johnmckerrell** [comment]
Doesn't look like I linked to the heater that we have in the toilets: https://www.screwfix.com/p/redring-ms6-undersink-stored-water-heater-1-5kw-6ltr/5314p?_requestid=178277

That one seems cheaper than Adrian's, which is an Ariston which isn't the best brand? (I don't know for sure really and have no idea about Redring but the one in the toilets has lasted for 3 years now)

@Sean-anotherone I've seen your email to Jackie, yes 9.5kW is probably an issue, I think the water heater might be on its own circuit but the circuits aren't well labelled so it's hard to be sure. 

Actually I just had a try to find the one we've currently got that has broken and it looks like it's quite high wattage (I don't have the model number so this is just a guess): https://www.toolstation.com/stiebel-eltron-instantaneous-water-heater/p97614

As a person with solar panels my general preference is for lower wattage anyway, oh and also the existing one didn't get hot enough and we know that the Redring one does so that's another plus point for it.

**Comment by magman2112** [comment]
A new water heater has now been installed in the kitchen. 

See issue #1522 for further details.
