### ISSUE TITLE
Sophia's laser wouldn't turn off and it stopped moving

### ISSUE THREAD

**Issue by fjfish** [DoESLiverpool/somebody-should#143]
Reset and the big red button didn't help.

For now I have taken the key and put it on Pat's desk, with the charred piece it was in the middle of as "evidence". Apparently been acting up today too.

**Comment by DefProc** [comment]
@fjfish am I right in thinking that the chain of events was:

 * the cutter was running a job, 
 * the head stopped moving while the laser was firing, 
 * the laser continued to fire, 
 * the workpiece caught fire as a result, 
 * cutting the electrical power to the cutter didn't affect the flames that were on the work piece, 
 * someone opened the lid and blew out the fire, 
 * when the cutter power was restored it still didn't work as expected in some way.

**Comment by fjfish** [comment]
Not quite - workpiece did catch fire but big red button and pause didn't stop laser firing. Or that's what they said anyway.

**Comment by DefProc** [comment]
I've re-run the laser with the job that caused the problems, and it didn't stop at the same point. The laser quite happily ran the whole 10 minute cut all the way to the end. 

It's quite possible that the laser freezing is an intermittent problem, so we'll keep an eye on this and see if it turns up at any other time. 

I've checked the emergency stop button (the big red one) and it definitely cuts power to the entire machine when pressed. (It won't do anything about fires that have already started though!)

**Comment by DefProc** [comment]
I've added specific reporting instructions for laser cutter problems to the DoES wiki: http://wiki.doesliverpool.com/LaserCutter

## Reporting Problems

Should you have a problem when using the laser cutter and the technician, or another suitable organiser is not available to look at the machine at the time, you should report what's happened, and the state of the cutter on the DoES Liverpool [https://github.com/DoESLiverpool/somebody-should/issues Issues List]. (requires a github account)

You should:

 1. Make a quick summary of the problem in the title,
 1. Provide details of the chain of events that caused the problem (detailed enough that someone can recreate the same conditions again),
 1. Mark the issue with the label of the cutter, i.e. '''Sophia the Smaller Laser Cutter''' or '''Gerald the Gigantic Laser Cutter''',
 1. If the cutter in question is not suitable for anyone to use, mark the issue with the label '''Broken''', otherwise mark it '''Bug''',
 1. If the problem has been caused by a particular cut file, save it to the '''Error''' folder on the respective cutter's computer and give the name in the issue.
