### ISSUE TITLE
Get Creality printers going with PETG

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1461]
Spun out from #1460 

We have a lot of 1.75mm PETG which can't be used with the Ultimakers. We've got a Creality CR-10S and a Creality Ender 3 so it makes sense to try to work out if reliable printing with PETG is possible, and if so document that process for the community.

**Comment by Sean-anotherone** [comment]
I genuinely don't know what the issue is?  My printer has been busted for a while but was used almost exclusively with PETG and ABS before I killed it.   ( the new bearing housing on Felicity is ABS and I printed on the first attempt)

My homebrew hybrid (mostly an Alfawise u30 but with a BL and a creality control board)  has been working again (thanks @MatthewCroughan ) for almost a week now and I've successfully printed both PLA and PETG just by taking the default settings in cura and adding about 5°C to the extruder temp to allow for old damp fillament.

I would say the recipe for success is :

1. make sure the printer frame is tight and stiff and the eccentrics are properly adjusted - the axes should be smooth to move but with zero free play whatsoever.  It can help to physically unplug the stepper cables when testing as you need to run the axis from end to end to do this effectively..
2. level the bed manually, heat the bed to full temp first
3. level the bed manually again
4. level the bed manually one more time ( seriously, go around three times, or more)
5. run your bl touch to generate a new mesh for the bed as it still isn't level enough     ( < new step  now mine works ! ) and check and reset the Z offset if necessary
6. print some simple things with gaps in them and use these to optimise the retract speed and retract distance to give nice edges with no whiskering
7. slice your model and select a reasonable speed - 30 to 50 mm/sec works.  It's better to succeed with the print once quite slowly than fail three times at 80mm/sec.
8. add a bit to the extruder temp unless the filament is brand new and toasty dry, if has been in a steamy place add up to 10 or 15ºC to the normal temp.  base the start point on the temperature printed on the reel, not the handbook for the printer.  filament varies
9. clean the bed glass scrupulously with a scratchy pad and dish soap (in the sink!), followed by windolene or similar, then wipe with solvent, and then apply a small amount of whatever you use to ensure good adhesion - a bit of watered-down pva works best for me and costs pennies for a jam jar full.  make sure there is nothing underneath when reinstalling it, then check the bed level  and Z offset (only for bltouch) again.
10. assuming your filament is clean and dust free, extrude a small pile onto the bed to flush the nozzle and ensure the extruder drive has a clean bite
11. run the job, noting the need to not rush it as per (7) above.  If it messes up either change your sticky strategy or print slower.

**Comment by ajlennon** [comment]
I have spent a long long time trying to do this and found it to be really hard. I think part of the problem is the hot end doesn't really go hot enough. Am closing this for now
