### ISSUE TITLE
Gerald not cutting well

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1463]
Gerald seems to not be cutting well - I couldn't cut through a piece of MDF, although there have been some regular users in, and they haven't mentioned any problems.
I spoke to @magman2112 and he suggested refocusing the mirror on the left side. This seemed to help slightly but power is still poor.
I have tried several bed heights as that was one suggestion, but this made surprisingly little difference.

**Comment by Sean-anotherone** [comment]
I'm not aware of the alignment being checked since I fitted the new tube - although I did service all the mirror mounts (i.e. grease them a bit and adjust them all very carefully).
The tube itself will have accrued a good number of hours cutting 20k+ visor bands, but as it is at 50% or so it should last a good while.
The damaged lens @magman2112  reported previously is certainly a contender, also the sled bearings were pretty ropey, and them allowing the head assembly go go out of alignment would badly impact the power.  A good way to tell is to try and cut something that takes a few minutes (even if unsuccessful) and then feel the temp of the air assist/beam outlet - if it's warm, the beam is probably off axis.

I think the best I could manage is probably Thursday eve, will come in sooner if I can but the day job is becoming more demanding at present.

Sean

**Comment by JackiePease** [comment]
Adding the broken label as people haven't been able to cut anything except thin card.

**Comment by jltomo** [comment]
I had real issues on Sunday which I attributed to me not being able to get the focal height right after a quick chat with @JackiePease about the new tube. In case it’s helpful: I had to go over my lines 5 times to get a cut through 3mm acrylic and even then only about 60% of the design cut through, tried changing bed height etc. but didn’t seem to help!

**Comment by Sean-anotherone** [comment]
Fixed it - kinda.  
Alignment redone all the way back to the tube, Cuts well across the whole bed but not so well at the back edge - but as the mirrors and lens are looking pretty ropey I think that's as good as it will get for now.
