### ISSUE TITLE
Install a PoE socket on the roof outside the event room

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1488]
I’m working with @goatchurchprime on a project to add IoT instrumentation to one of the hives Andrea (B4biodiversity) has on the roof.

I’d like to connect to the instrumentation with a PoE cable linked back into the PoE switch in DoES if possible. 

The advice from @magman2112 is that there’s already a hole in the wall we could go through so it would be a matter of routing cat 6 cable to the outside of the event space wall and affixing a weatherproof box. 

This could potentially support other outdoor projects in the future. 

I’d like to approach Jason (Landlord) but obvs first need to understand if this is something the DoES directors and community feel is a good idea.

**Comment by ajlennon** [comment]
@magman2112 could you recommend an outdoor box on Amazon?

**Comment by johnmckerrell** [comment]
Should be possible, I guess we'll probably just plug into an existing socket in the events room perhaps rather than trying to wire something back to the patch panel? I'll check what ports we have spare tomorrow.

**Comment by ajlennon** [comment]
Brillo. Thanks!

**Comment by johnmckerrell** [comment]
Ok I've plugged in one of the sockets by the safe in the events room and labelled it PoE.

**Comment by magman2112** [comment]
I’ve been looking into this a bit and here’s a few thoughts.

First, as @ajlennon asked, I have been looking at some external boxes. Here I have been focusing on IP66 or IP67 boxes, with glands, as these are actually waterproof. One I thought was a good start is this one.

https://www.amazon.co.uk/Waterproof-Kohree-Connection-Electrical-Distribution/dp/B07Q9QNLLC/ref=pd_ybh_a_10?_encoding=UTF8&psc=1&refRID=PZV6Q474HJNAXFSD3VN3

Although it Is a 3-way box, being 3-way makes it a little larger, hence giving us a little more space to work.

Next is the cable. I suggested to Alex the he get waterproof external grade CAT 6 cable. I will qualify this a little more and suggest that this should also preferably be copper cable, not CCA - or Copper Covered Aluminium. CCA cable is cheaper, but is more prone to corrosion, especially at the connections. If we can find it, we should also watch the cable gauge and wire diameter. Some of the external cable is specified as AWG 23, this is good for lower resistance overall, but it is awkward to find connectors to fit this higher gauge, so AWG 24 or higher would be preferable. We also need to figure out how much cable is needed overall, it is better to get too much rather than too little. Here’s a couple of suggestions from Amazon:

https://www.amazon.co.uk/Smedz-CAT6-Outdoor-Network-Ethernet/dp/B0765FF3HC/ref=sr_1_3?dchild=1&keywords=cat6+outdoor+cable+copper&qid=1599671441&s=computers&sr=1-3

https://www.amazon.co.uk/kenable-External-SHIELDED-Outdoor-Ethernet/dp/B01HVTV83K/ref=sr_1_23?dchild=1&keywords=cat6%2Boutdoor%2Bcable%2Bcopper&qid=1599671441&s=computers&sr=1-23&th=1

I’ve not used either of these cables before, but they look reasonable.

Next, the cable needs to be installed without connectors fitted, both for fitting through the existing hole in the wall, as well as the glands in the external box, it simply isn’t practical to install the cable with fitted connectors. The most practical connectors for this application are crimp plugs for the external end, plus we can make a patch cable from the junction box to the Pi computer. Again, a couple of suggestions, though unfortunately they don’t appear to do small quantities of these at reasonable prices:

https://www.amazon.co.uk/gp/product/B07H3K2YNG/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1

https://www.amazon.co.uk/VCE-50-Pack-Connector-Ethernet-Plug-50u-50-Pack-End-Pass-Through/dp/B07MM3FQ3F/ref=pd_ybh_a_9?_encoding=UTF8&psc=1&refRID=EVS8SDCHECSZ791DTHJ9

I think we have a couple of spare wall socket terminations and back boxes in the network closet, so we can build a termination in the event room next to the existing LAN socket, then use a short patch cable. So that end shouldn’t be an issue.

Once we have an OK to do this, I can help to get this installed once the bits have arrived, 

Over to you folks for thoughts and comments.

**Comment by ajlennon** [comment]
Hiya @magman2112 - before I went away I got this in which should be at my desk. I'd forgotten to check for copper :( Will this be OK?

https://www.amazon.co.uk/gp/product/B00EOTHDWQ/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1

Also what of the above do you suggest I get in?

**Comment by ajlennon** [comment]
So things are moving along slowly. I have tested the 50m external cabling here with the PoE socket in the events room and a PoE hat for a Raspberry Pi 4 and that all works OK.

So have spoken with @magman2112 and am going to buy in the boxes etc. he's recommended above and then we'll try to get together when it's not raining and cable it up.

**Comment by ajlennon** [comment]
Have bought these connectors @magman2112 

https://www.amazon.co.uk/VCE-50-Pack-Connector-Ethernet-Plug-50u-50-Pack-End-Pass-Through/dp/B07MM3FQ3F/ref=pd_ybh_a_9?_encoding=UTF8&psc=1&refRID=EVS8SDCHECSZ791DTHJ9

And this box (arrives Friday)

https://www.amazon.co.uk/Waterproof-Kohree-Connection-Electrical-Distribution/dp/B07Q9QNLLC/ref=pd_ybh_a_10?_encoding=UTF8&psc=1&refRID=PZV6Q474HJNAXFSD3VN3

**Comment by ajlennon** [comment]
Hi @johnmckerrell. @magman2112 and I have the Bee-hive connected up now over PoE!

The only problem is I seem to be getting very slow throughput, too slow for A/V to YouTube. This might be problems with the wiring I guess but I was wondering if it might be possible for somebody to have a look at PoE settings?

With my laptop on the DoES WiFi I get

```
ajlennon@ROG-Strix-G712LW:~$ curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
Retrieving speedtest.net configuration...
Testing from Baltic Broadband Limited (185.135.107.82)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by IDAQ Ltd (Sheffield) [114.42 km]: 25.234 ms
Testing download speed................................................................................
Download: 202.28 Mbit/s
Testing upload speed......................................................................................................
Upload: 150.54 Mbit/s
```

But with the PoE sockets in the event room I get

```
bash-5.0# curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
Retrieving speedtest.net configuration...
Testing from Baltic Broadband Limited (185.135.107.82)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by IDAQ Ltd (Sheffield) [114.42 km]: 95.887 ms
Testing download speed................................................................................
Download: 0.23 Mbit/s
Testing upload speed......................................................................................................
Upload: 0.64 Mbit/s
```

Thanks !!!

**Comment by skos-ninja** [comment]
@ajlennon if you can tell me what port it's connected to I will check it for you

**Comment by johnmckerrell** [comment]
If you can give the MAC address of the device it's connecting from or the IP address you're getting that will be helpful. Can you try the test from other connected ports in the space it see what you get there?

**Comment by ajlennon** [comment]
Thanks John. I can’t spot the MAC atm but it’s on 10.0.35.212. Entering the events room it’s the socket on the right hand side nearest the safe. The phone is in its own socket, 2nd from left looking at the wall. The external cabling is in the socket to the right of that. I’ve tried swapping them over to see if it makes a difference.

Chatting to Mike it may still be a cable crimping thing but would be really helpful it we could discount any other potential issues.

**Comment by skos-ninja** [comment]
@ajlennon without the MAC we can't be certain but that IP is currently connected via the WiFi and not the wired connection

**Comment by ajlennon** [comment]
Brilliant thanks! So it looks like I’ve managed to get power to it but not comms @magman2112 . That makes sense. Awesome. Thanks @skos-ninja @johnmckerrell 

![5D3E0CC3-901D-4940-8E05-6E7A60A82524](https://user-images.githubusercontent.com/1537834/101201894-5376ff80-3660-11eb-8cc9-748b87ce4cee.png)

![0E9F5EBC-85D5-4ABD-AF55-9C94718D7C3C](https://user-images.githubusercontent.com/1537834/101201915-5bcf3a80-3660-11eb-9754-ebf27fbbf0da.png)

**Comment by skos-ninja** [comment]
@ajlennon I can see two devices that are plugged not getting configured with IP's. One in port 11 and one in port 12 on the switch. Both are using POE so I can't identify which is yours

**Comment by ajlennon** [comment]
Ooooh! Maybe I did get the crimping right then! So the output is as follows. I guess it's the eth0 that isn't getting an IP?

```
eth0      Link encap:Ethernet  HWaddr DC:A6:32:49:56:68  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr DC:A6:32:49:56:69  
          inet addr:10.0.35.212  Bcast:10.255.255.255  Mask:255.0.0.0
          inet6 addr: fe80::a919:91fb:23a6:ed7b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6714890 errors:0 dropped:5 overruns:0 frame:0
          TX packets:11855946 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:376110887 (358.6 MiB)  TX bytes:17578485466 (16.3 GiB)
```

**Comment by ajlennon** [comment]
Weird it is getting no packets at all though?

**Comment by johnmckerrell** [comment]
Can you confirm what you've actually done and at which point in the setup you're testing as I'm really unclear on all this. My assumption was that you were fitting a new socket in the events room which would connect up to a socket or something by the hives. You would then use an standard cable to connect these two sockets.

The existing socket should work fine (Can't say for absolutely certain that I tested it for data but I thought I had), so it should be something downstream of that. In fact all cable runs should be testable with Mike's cable tester (although I'll admit it gave me a positive result when I patched a plug on but my router didn't like it).

**Comment by ajlennon** [comment]
> Can you confirm what you've actually done and at which point in the setup you're testing as I'm really unclear on all this.

So we've connected a cable into the spare of the two labelled PoE sockets beside the safe in the events room.

This cable is poked through the existing hole in the wall and run over to the two hives on the roof.

The original problem was that the pins weren't fully crimped down so the unit in the hive wasn't getting power. I recrimped this but I can only guess I've done something wrong. 

Mike's in tomorrow and I am going to head in and (weather permitting) try to recrimp again and test with his test box...

**Comment by johnmckerrell** [comment]
Have to leave now but I'm getting inconclusive results. I've had good results on the left-most 3 ports, but then the phone is currently not connecting and the right PoE has now disconnected and won't reconnect, just leaving the below although it's a bit out of date now....



When I got there the left PoE socket was plugged into the phone with the purple cable, the phone was on but said Network Unavailable. It looks like this was due to the purple cable, I've replaced with a long white cable.
 
I've tested the sockets by plugging into my computer:

 * Leftmost - worked - 700 Mbits/sec - Plugged into DELL switch
 * PoE - worked - 740 Mbits/sec - Switch port 12
 * PoE - worked - 925 Kbits/sec - Switch port 11 (I thought from looking at it this would be plugged into 14 but apparently not)
    * Although.. I then struggled to get it to connect part-way through my test, couldn't be certain if it's a bad cable again (I didn't have a known good one handy) 
 * Rightmost - Appeared to be inactive

I've also left `iperf` running on `10.0.17.10` as I find that very handy for testing connection speeds, note that not all Pis can go beyond 100Mbits/sec.

**Comment by ajlennon** [comment]
OK so had another look and there were a couple of issues

- the crimp tool we were using wasn't really designed for the connectors and I don't think it was making good contacts
- we got in a new tool which came with new connectors and I recrimped both ends which looked very good
- we still had a problem which turned out to be the RJ45-RJ45 socket in the external connector we were using

![image](https://user-images.githubusercontent.com/1537834/101654429-70347e00-3a38-11eb-8446-b40e88248ce5.png)

With this done and replaced I can now use @magman2112 's RJ45 test box to show all connections are good out to the hive.

However I am still not getting an "online" status on Balena.

- I tried swapping over sockets
- I tried using my own PoE injector

@johnmckerrell has also confirmed that neither MAC address from the box is being picked up.

So I'm thinking now in all my faffing around I might have done something to corrupt the box or worse so will try to arrange with #B4Biodiversity to take it back out of the hive to check.

**Comment by ajlennon** [comment]
Interestingly the board has come online, connecting through the DoESLiverpool AP.

So it's working but not connecting over wired ethernet for some reason.

**Comment by ajlennon** [comment]
Doing some googling there may be a potential issue with wired ethernet on the RPiv4

https://shantanugoel.com/2020/01/19/raspberry-pi-4b-ethernet-lan-disconnect/

**Comment by ajlennon** [comment]
`ethtool` shows a link is connected (!) But it's not working,

```
Settings for eth0:
        Supported ports: [ ]
        Supported link modes:   Not reported
        Supported pause frame use: No
        Supports auto-negotiation: No
        Supported FEC modes: Not reported
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Advertised FEC modes: Not reported
        Speed: 10000Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: off
        MDI-X: Unknown
        Link detected: yes
```

**Comment by johnmckerrell** [comment]
Interesting. I've got a few Pi4s using ethernet fine (and fast) so I wonder if it's related to the PoE hat.

**Comment by ajlennon** [comment]
People seem to be reporting odd incompatibilities. Some Pi4's work fine, some don't

https://www.raspberrypi.org/forums/viewtopic.php?t=249112

**Comment by ajlennon** [comment]
Cracked it!

I was pondering and have replaced the PoE connection into the PoE wall socket with my own PoE injector and connected it to the non-PoE adaptor on the left hand side by the safe. One other problem I think I've been having is that the right hand side socket of the four doesn't seem to do comms.

With this change the bee hive monitoring is working. Hurray! Thanks for your help everybody. Will close this

**Comment by johnmckerrell** [comment]
* Rightmost - Appeared to be inactive

;-) I should perhaps have been more committed but I'm sure this one isn't patched in.

**Comment by magman2112** [comment]
I was just wondering if there is a configuration item on the Ubiquiti switch for the different types of PoE. It appears from the wiring issues we had that we need a type A PoE configuration (Pairs 1/2 and 3/6) for the hive connection to work. There is also a type B connection that uses the alternate pairs. It may be that both are enabled, but the fact that Alex had to use a PoE injector shows that something isn’t quite right.

**Comment by ajlennon** [comment]
fwiw I wired it like this from the new crimping tool

![image](https://user-images.githubusercontent.com/1537834/101783938-c665f780-3af2-11eb-87e1-4718dfcc20cd.png)

**Comment by johnmckerrell** [comment]
I'm not aware of configuring anything relating to PoE on sockets in the unifi interface. I thought B was standard for data and A was more for audio. Got a few webcams and VOIP phones working with it as it is.

(and can't get onto the interface at this moment)
