### ISSUE TITLE
Put together knitting machine donated by Mike from Game Over

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1493]
We have been donated a knitting machine by Mike from downstairs in Game Over. At the moment it is sitting on one of the social distancing desks in the main space but obviously can't stay there long term. 
We are told that it is in good working condition and appears to be complete with many parts that allow it to produce tubular and two sided knitting for example. It is not electronic but has punch cards (which can be laser cut) and an electric motor.. 
It would be good to assemble iand evaluate whether it is a useful addition to the space. It might also help us work out which of the other knitting machine parts we can use to give similar features to Ariadne (the knitting machine with the Arduino shield) and which can be disposed of.

**Comment by MatthewCroughan** [comment]
This might be a bit far fetched. But I think we should store these machines on a shelf that can be reorganised from top to bottom depending on the machine you want to use. The bottom shelf would be the same level as a desk and could be used much like a desk. Then if you wanted to use the knitting machine on top, you could take that machine down with the help of another member and swap it with the bottom machine. Since we're limited with space, I think this is a good compromise between accessibility and space, since we have as much vertical space as needed in the space. 

(We would have to create this desk-shelf combo)

**Comment by JackiePease** [comment]
I did put this together, now raised #1575 to look at actually get it running
