### ISSUE TITLE
Bicycle pump -letting out air

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1494]
Good morning , 

The bicycle pump would not hold pressure because there was air escaping. The air gauge is also not working. I could attempt to take this apart but not sure if this is okay or someone else would like run with this?

**Comment by JackiePease** [comment]
On 8 Sep 2020 07:51, Knottyashcreative <notifications@github.com> wrote:
Good morning ,
The bicycle pump would not hold pressure because there was air escaping. The air gauge is also not working. I could attempt to take this apart but not sure if this is okay or someone else would like run with this?

**Comment by Knottyashcreative** [comment]
The problem is partly resolved i.e. the pump will work but (no air escape) but the gauge is not working.  I needed some form of miniature o-ring or plumbers paste.  I will attempt it again when I gain access to either of those items.  The pump now works but the pressure gauge will not identify the pressure - resolution is ongoing.

**Comment by amcewen** [comment]
We've got a new pump now!
