### ISSUE TITLE
Jitter when cutting on Gerald

### ISSUE THREAD

**Issue by craigmagee** [DoESLiverpool/somebody-should#1510]
Experienced jitter as the cutting head moved on Gerald, causing wavy lines and partial cut through. Mirror is moving out of alignment and cutting off laser to lens. 

This was using the left side of the bed, as the head was moving from the bottom left of the design to to the upper right.

Issue went away using a more central portion of the bed.

**Comment by magman2112** [comment]
I was in DoES this morning and completed an alignment on Gerald, so he is cutting much better at the moment.

I did notice some roughness in the travel on the x-axis though, which may be a sign of failing bearings. I will investigate this further on Thursday evening with @Sean-anotherone hopefully.

**Comment by Sean-anotherone** [comment]
I'm certainly planning to come in on Thursday, but unless the bearings are grease-packable I'm not sure what could be done other than to replace them - the rods might be OK and new slides may be cheaper and quicker to get than whole new assemblies. 
A checked the alignment on Gerald last week and it was pretty much spot-on then, so something is clearly failing fast.  Would need to check the measurements but these were the best I found : 2X SBR20 L200-1500mm Linear Rail Slide Guide Rod + 4X SBR20UU Bearing Block | eBay#

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
2X SBR20 L200-1500mm Linear Rail Slide Guide Rod + 4X SBR20UU Bearing Bl...

Model :SBR20. Linear bearing is a low-cost production of linear motion system for unlimited travel in conjunctio...
 |

 |

 |





Did you look at the cable tray on Tony? - only the HV PSU and control to hook up now, then it's ready for plumbing etc.

Sean


    On Tuesday, 27 October 2020, 21:40:14 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 


I was in DoES this morning and completed an alignment on Gerald, so he is cutting much better at the moment.

I did notice some roughness in the travel on the x-axis though, which may be a sign of failing bearings. I will investigate this further on Thursday evening with @Sean-anotherone hopefully.

**Comment by magman2112** [comment]
I suspect it may be the bearings at the stepper motor end of the horizontal rail, or perhaps even the stepper motor itself.

We will likely have to measure the bearings to identify replacements anyway. We can also measure things like drive belts to source replacements for these at the same time

**Comment by magman2112** [comment]
After quite a bit of work on Thursday night, @Sean-anotherone and I found that one of the bearings is in poor condition at the stepper motor end of the horizontal axis, as suspected.

We re-assembled Gerald after cleaning and lubricating the existing bearings, so Gerald is operational, while waiting for the replacement bearings to arrive. Although Gerald is working, it is not perfect, so people should be aware of its current limitations.

The bearings have been identified as followsm

Beam, Motor end
Upper bearing - Type 6800Z - 10x19x5mm
Lower bearing - Type 6801Z - 12x21x5mm

It is the lower bearing that has failed, but we may as well replace both while we have the machine apart.

We also identified the bearings for the side belt drives, as some of these are close to failing. These are Type 688Z - 8x16x5.

I did find most of these bearings on Amazon at relatively low prices, but one had an earliest delivery of 16th November. As an alternative, I decided that it would be better to obtain high quality SKF bearings from a UK based supplier for the key bearings, which will deliver them in days rather than weeks. They are more expensive but the originals have lasted many years so it is not worth penny pinching for a key component.

Total costs for all of the bearings is £35.95 including VAT and postage.

Another issue that @Sean-anotherone identified is that the drive shaft has badly worn where the bearing has failed. Sean is going to see if he can make an equivalent replacement part to make the optimum repair for this issue, as this is a critical component for the accurate operation of Gerald.

I will raise an order for the bearings today.

**Comment by Sean-anotherone** [comment]
I found a suitable piece of 12mm steel bar amongst my offcuts - it's a bit softer than I'd like for a bearing shaft, but it will still be a big improvement over the worn out one.  I have all the dimensions and will get started on making the part as soon as I can.
Sean


    On Friday, 30 October 2020, 12:48:04 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 


After quite a bit of work on Thursday night, @Sean-anotherone and I found that one of the bearings is in poor condition at the stepper motor end of the horizontal axis, as suspected.

We re-assembled Gerald after cleaning and lubricating the existing bearings, so Gerald is operational, while waiting for the replacement bearings to arrive. Although Gerald is working, it is not perfect, so people should be aware of its current limitations.

The bearings have been identified as followsm

Beam, Motor end
Upper bearing - Type 6800Z - 10x19x5mm
Lower bearing - Type 6801Z - 12x21x5mm

It is the lower bearing that has failed, but we may as well replace both while we have the machine apart.

We also identified the bearings for the side belt drives, as some of these are close to failing. These are Type 688Z - 8x16x5.

I did find most of these bearings on Amazon at relatively low prices, but one had an earliest delivery of 16th November. As an alternative, I decided that it would be better to obtain high quality SKF bearings from a UK based supplier for the key bearings, which will deliver them in days rather than weeks. They are more expensive but the originals have lasted many years so it is not worth penny pinching for a key component.

Total costs for all of the bearings is £35.95 including VAT and postage.

Another issue that @Sean-anotherone identified is that the drive shaft has badly worn where the bearing has failed. Sean is going to see if he can make an equivalent replacement part to make the optimum repair for this issue, as this is a critical component for the accurate operation of Gerald.

I will raise an order for the bearings today.

**Comment by magman2112** [comment]
The new bearings arrived about a week ago, but I haven't been in to DoES recently to drop them off. 

Once @Sean-anotherone has had the time to make the new bearing shaft (if he hasn't done so already), we can look to book a slot to complete this repair.

**Comment by Sean-anotherone** [comment]
Hi Mike,
shaft done, there are actually two of them in an envelope on the back of the spares cupboard door - my lathe isn't much good at bearing fits, so one is measured a little over, one a little under (about 0.02mm).  One will certainly fit, might need a bit of sandpapering in the drill press.
I've also been progressing Tony, but nothing yesterday as a new tube for Sophia was more pressing - I note that all the mirror mounts in Sophia are rubbish and need either rebuilding with springs or replacing.
I'm available all weekend and Monday if you're up for it?
Sean


    On Friday, 20 November 2020, 19:01:28 GMT, Mike Gorman <notifications@github.com> wrote:  
 
 


The new bearings arrived about a week ago, but I haven't been in to DoES recently to drop them off.

Once @Sean-anotherone has had the time to make the new bearing shaft (if he hasn't done so already), we can look to book a slot to complete this repair.

**Comment by magman2112** [comment]
@Sean-anotherone and I fitted the new bearings today, as well as a new drive shaft that Sean had made. X-axis motion is now back to a good level and motion is a lot smoother.

As part of the upgrade, the laser was re-aligned and the air-assist repaired, so Gerald is cutting well again.
