### ISSUE TITLE
Work out what to do with "spare" visor money

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1548]
We raised £22,918 and made and donated over 25,000 visors! We've actually ended up with a surplus of £4494.06 that we really need to do something with. I believe we initially stated that we would donate any surplus to NHS charities. I raised it on the mailing list and we've had some non NHS charity related suggestions which are great, but we have to be careful to do what we said we would. We should work out any costs relating to the project that we may have missed or could consider appropriate (like further repairs to the lasers) and then work out what charity the money should go to. We should aim to do this before the anniversary of lockdown!

Assigning to @DoESsean to do some initial investigation/research and make suggestions.

**Comment by johnmckerrell** [comment]
We could consider a poll around this, but again I'd point out that we never said we'd do a poll. If we are going to let people make a collective decision the people making that decision need to be gofundme supporters so we'd need to contact them, might be a bit late to do that but I guess at least if we only get 5% response we have at least tried to ask them.

**Comment by ajlennon** [comment]
fwiw for me I fully support 

- covering any costs incurred by DoES for the PPE effort (including making good any wear and tear on machinery) before calculating a surplus
- the DoES leadership team (directors) making a decision on where any surplus goes in line with any commitments they feel relevant e.g. giving to NHS charities

**Comment by DoESsean** [comment]
Ok, I've gone back through the bank accounts to last May, when the money came in and production ramped up.

As far as I can see, there are three transactions which are for laser parts/repairs that may not have been taken into account:

7/8 - £30 to Smoke & Mirrors
12/11 - £360 to HPC
6/8 - £141.90 to Pangolini (PayPal payment)

I agree with @ajlennon about making good any wear and tear. However, since the machines would have been in use without the project, although to a lesser degree, I'd suggest maybe getting @magman2112 and/or @Sean-anotherone to work out what needs doing to get the lasers back into full working order, and maybe saying that a percentage of that would be reasonable to claim from the funds raised. 50% maybe?

I'm assuming that DoES is going to accept the hit with regards to energy costs rather than trying to reclaim any of those.

Has everyone that wanted to be paid/recover expenses received those monies? Might be worth checking that too.

Beyond that, I think we just find an NHS charity (or an NHS adjacent charity - I'm not a huge fan of the fact that the NHS needs charity in the first place as it covers the funding gap which shouldn't be there, but that's by the by) and donate the excess. I don't think there's much need for the money to be with us for longer than necessary.

**Comment by johnmckerrell** [comment]
@DoESsean I've forwarded a spreadsheet of income/outgoings. I thought that the existing laser costs had been covered but I could be wrong, it would only be any further work that's required. It also shows the money going to the people/staff who made the visors. You could check what the energy costs were from the financial reports but I don't recall them being so much higher that it's worth worrying about.

Yes NHS charities is just such a ridiculous idea (like 21st century food banks) but they do exist. The Royal have one, Alder Hey and Clatterbridge too (though apparently they already get a lot more than the Royal). Others could be worth considering.

**Comment by ajlennon** [comment]
>maybe saying that a percentage of that would be reasonable to claim from the funds raised. 50% maybe?

I'll happily agree with whever is decided but I would only comment that I agree with @Sean-anotherone that the PPE effort totally blitzed the laser cutters compared to "normal" use. I wouldn't find it at all unreasonable for that 50% to be much higher towards 100%

**Comment by ajlennon** [comment]
>Yes NHS charities is just such a ridiculous idea 

I was kind of surprised to find out that the NHS have these digital innovation centres. They seem pretty cool. Are there any "NHS innovation charities" perhaps involved in covid/PPE DoES could support?

**Comment by johnmckerrell** [comment]
Agree, laser costs that can safely be attributed to the project can be 100% covered (as some have already).

**Comment by DoESsean** [comment]
Yeah, none of the costs that I've outlined above are included on that spreadsheet, so that's £531.90.

I would suggest that the stuff that was blitzed were replaced - the payments mentioned include a new tube and mirrors - which is why I'd lean towards an overhaul being covered *some* of the way rather than *all* of the way.

To be perfectly honest, I'd personally lean towards us using less than we could rather than more, just to be on the safe side. But then I have an outstanding moral character :)

**Comment by johnmckerrell** [comment]
Hoping @JackiePease and or @amcewen can confirm. I have a feeling that some if not all of the costs assigned to them are actually relating to them paying for things. If they're showing on the DoES bank account maybe not but it could just be a mistake in the accounting (i.e. the person doing the accounting didn't realise that Jackie or Adrian were paying for things with a DoES card).

**Comment by Madscouser** [comment]
Firstly, the NHS Charities often provide extras that aren't medical, for example, Clatterbridge Cancer Charity paid 50% of the wifi costs when we upgraded a few years ago. Which meant we were able to provide much better wifi for patients than we would have been able to afford otherwise. So I do understand why they exist, they don't pay for standard medical stuff. 

Secondly, considering CCC have just opened a brand new cancer hospital in Liverpool, esp to support the city and it's just round the corner from DoES then I'd say it would be a good choice. I'm happy to put you in touch with the team.

**Comment by magman2112** [comment]
One small item that was definitely consumed by the visor project, the filters for the extractor system. Both of these are now broken beyond repair and should be replaced. We are back to using no filter and the blower getting clogged up again.

**Comment by Tactile-electronics** [comment]
we discussed the remaining visor money at yesterdays directors meeting - we came up with a suggestion that we set aside 25% to further laser works and then give the rest to an NHS related charity, e.g.  https://healthcareworkersfoundation.org/ and or to individual hospital’s charities (the Royal, The Walton Centre, Liverpool Heart and Chest).

**Comment by Sean-anotherone** [comment]
To keep some aside for further laser works is a great idea - Gerald in particularly was hit really hard and still isn't right, needing more bearings replaced, belts, pulleys and a full overhaul of the drives as a bare minimum.
For the balance, I would propose keeping it close - I recall that the local support for the campaign was the largest part of it, so I think the most appropriate beneficiaries would be the local hospitals. 
Sean-Anotherone




    On Wednesday, 22 September 2021, 21:01:31 BST, Tactile-electronics ***@***.***> wrote:  
 
 


we discussed the remaining visor money at yesterdays directors meeting - we came up with a suggestion that we set aside 25% to further laser works and then give the rest to an NHS related charity, e.g. https://healthcareworkersfoundation.org/ and or to individual hospital’s charities (the Royal, The Walton Centre, Liverpool Heart and Chest).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amcewen** [comment]
Sounds like a plan.  The three hospitals you mentioned @Tactile-electronics are the ones which were the most helpful when we were developing the visors so it'd be good to support them

**Comment by Tactile-electronics** [comment]
As there have been no objections we will go ahead with this and allocate 25% of the remaining funds to further laser works and then give the rest to local individual hospital’s charities (the Royal, The Walton Centre, Liverpool Heart and Chest) as suggested.

**Comment by johnmckerrell** [comment]
Sorry @Tactile-electronics but I'm going to re-open this as the money hasn't gone out yet :-)

@doessean can you make payments of £1,123.52 to the Royal, The Walton Centre and Liverpool Heart and Chest (whichever their "main" charities are, but feel free to ask if you're not sure).

**Comment by DoESsean** [comment]
I've done the Royal, and Walton Centre, but have apparently hit my sending limit when trying to do the third donation. Unless someone gets to it in the meantime, I'll do it next week.

**Comment by DoESsean** [comment]
Liverpool Heart and Chest done too now. So I think I can close this issue :)

**Comment by ajlennon** [comment]
Great work sir!
