### ISSUE TITLE
New Laser Tony - Try cutting with different Windows Laptop

### ISSUE THREAD

**Issue by BrettNewnes** [DoESLiverpool/somebody-should#1549]
I don't have much experience with these things so forgive me if this is irrelevant..

I have downloaded Lightburn to my own laptop - Mac OS - and some of the problems cropping up seem to have been eliminated. Namely engraving seems to work better and the problem when the laser starts but then freezes in one place.

Speaking to Jackie, it was mentioned it may be a good idea if somebody could download light burn onto their own laptop (using 30 day free trial) and test to see if the problem could be with the laptop we are currently using?

Thanks

**Comment by magman2112** [comment]
Just a quick note to let you know that we installed new firmware on Tony this evening which requires a small change in configuration in Lightburn. The new firmware supports clustering which is about 4 times faster than the earlier version of Smothieware in engraving.

In Lightburn Go to Edit → Device Settings and enable the toggle for “Smoothie Clustering”, to enable the software to work correctly with the current firmware.

**Comment by magman2112** [comment]
Going to close this issue now, as there is a new USFF desktop PC and monitor installed on Tony, so this should not be an issue going forwards. This PC has an i5 processor and 8G of memory, so this should be more than sufficient for running Lightburn.

Also, we intend to install a USB socket on the front of Tony, so that people can plug in their own laptops if they prefer.
