### ISSUE TITLE
Doorbots not working on exterior door

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#1567]
The entry pads to the building are playing up.

On Tuesday, my fob would only open the door with one of the pads. This morning, Jackie's would open it with the other, and mine won't do either. Everything is fine at the door to DoES itself.

If taken the fronts off and had a look but, quite frankly, I haven't the faintest clue. I think I looked like I did though, so that's the main thing.

Jackie is going to have a look at lunchtime and see if she can figure anything out.

**Comment by amcewen** [comment]
On Tuesday (when I was adding new tags) `doorbot5` wasn't responding on the network, but both were working with my fob, so I'd expect @DoESsean's new fob to only work on one door.

As another datapoint, the inner pad (that didn't work for @JackiePease or @DoESsean) worked for me when I got here this morning.

**Comment by JackiePease** [comment]
Redeployed config to doorbots, but getting 'No route to host' from doorbot5

**Comment by DoESsean** [comment]
I managed to get in by using the doorbot inside the shutter after having to
go to Home Bargains. Maybe an intermittent thing?

**Comment by johnmckerrellav** [comment]
I may be able to come in shortly and bring my telescopic ladder to power cycle them. (Not actually sure it's long enough but I guess I'll find out)

**Comment by amcewen** [comment]
`doorbot5` seems to have found the network again - I've just deployed the latest config to it, so maybe this was just a glitch and we can keep an eye on things?

**Comment by johnmckerrell** [comment]
I did this. Both readers working before and after but I think the inner one might just be a bit far from the front. Someone needs to push the latest config out again. 

--

**Comment by johnmckerrellav** [comment]
Think we can probably close this? If the inner reader is still being a bit flakey I wonder about just putting some kitchen roll or foam behind the RFID reader inside the box to push it to the front.

**Comment by zarino** [comment]
Adding another datapoint to this – When I arrived at the Kempston Street entrance this morning:

- the shutter was up
- the inner rfid reader wouldn’t respond to my fob
- the _outer_ rfid reader _did_ respond to my fob

@JackiePease said she’d heard/read that you should try "reseating" the board… or the connectors… but neither of us were sure what that really meant.

- I popped the front off the black box by pulling it
- I noticed there were some unterminated wires dangling free inside the box (some wrapped in tape) but I figured that was intentional
- I inspected the wires inside, checking for a break or exposed copper or whatever, but everything seemed fine
- I pushed the dupont connector strip more firmly onto the pins on the back of the circuit board, but it didn’t move anywhere – it was already firmly in place
- I tried to scan my fob again (without closing the box), and it did nothing
- I _unplugged_ the dupont connector, then plugged it back in again
- I tried to scan my fob again (without closing the box), and the door opened
- I closed the box
- I scanned my fob a third time, and the door opened

I later came to this ticket, and found there had been discussion of the circuit board (the reader) being too far from the front face of the box. I’m not sure this was the case – it felt fairly secure against the front face, to me (although, I wasn’t specifically checking for this) and I would have thought, when I first attempted to scan with the box open, the board would have been resting pretty close to the front, because at that point it was lying horizontally, being pulled down by gravity, on top of the opened-up front of the box.

It seems that "turning it off and back on again" worked in this case, which would lead me to believe it’s something about restarting the connection with the doorbot? A software issue, most likely?
