### ISSUE TITLE
Reconnect an ethernet cable to Sophia's computer

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#157]
There doesn't seem to be a cable around from the switch under Gerald.

**Comment by ReddbridgeMark** [comment]
What is it you need an ethernet cable for? If it's just for momentary use in order to re-activate Windows, there is a miniature tp-link wifi dongle in one the USB ports at the back of my black desktop computer on my desk. The drivers for it are already on the sophia's computer, so if you want to borrow it go ahead.

(If it's for day to day use, then why not just buy http://www.maplin.co.uk/p/tp-link-tl-wn725n-single-band-n150-nano-usb-network-adapter-n20nf or cheaper & save the cabling)

**Comment by DefProc** [comment]
@johnmckerrell found it had just dropped down the back!
