### ISSUE TITLE
Gerald software not working

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1582]
Brian was unable to use Gerald yesterday due to software issues. He came in again this morning to report this.
It appears that there are multiple issues with the software on Gerald's PC.
- the shortcut points to a file called lasercut50.exe in c:\lasercut50\. This doesn't seem to exist anywhere on the C:\ drive
- other programs e.g. Corel Draw, Inkscape are also not working
- side-by-side configuration error when attempting to run Chrome (although Internet Explorer does work)

**Comment by amcewen** [comment]
https://github.com/DoESLiverpool/somebody-should/issues/356 covers when @ajlennon set up the machines originally, and once you find the [page where he documented the Windows PC setup](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems) on the new location oft he wiki, the Gitlab repo that points to still seems to have copies of things.

**Comment by ajlennon** [comment]
Yay me!

**Comment by magman2112** [comment]
I have managed to get Lasercut to work again. I found an old hard disk from when Sophia’s PC was upgraded to an SSD which had the missing files on it.

I found that the .exe file and 4 other dll’s had been deleted, there appears to be no logical reason why these particular files have been deleted.

I tried to re-install Corel Draw X4 as well, but I suspect some additional files outside of the Program Files folder will need to be copied as well, to get this to work.

I think we should be looking at perhaps installing some anti virus software on these shared PC’s as well - possibly Avast Free, as the number of different memory keys that get used with these PC’s do tend to make it more of a risk of potential virus infection.

**Comment by Knottyashcreative** [comment]
I have installed the latest version of Inkscape 1.1 and Chrome.  I would suggest enabling system restore function (free option within Windows), however this can take up space on the computer and run with miminal footprint.  I believe Alex installed Coral 4 and wonder if you have the file or can sign post me to where it is i.e. so I could install (appreciate any guidance).  Regards.

**Comment by MatthewCroughan** [comment]
It is my understanding that system restore only restores system files, it does not modify user installed programs like Chrome, Inkscape or Coral Draw for example. Or at least it is incomplete and this is a misunderstanding of how system restore should be used.

The system restore function would not prevent this situation from occurring again. 

It can in fact make the situation much worse, depending on how long the system has been accumulating [state](https://en.wikipedia.org/wiki/State_(computer_science)):

See this for some evidence of that. https://en.wikipedia.org/wiki/System_Restore#Limitations_and_complications

> System Restore takes a "snapshot" of the some **system files** and the **Windows registry**

Source: https://support.microsoft.com/en-us/topic/what-is-system-restore-a9d1b33f-1df9-e0f2-8aa3-d904cd940ee4


This situation occurs because users can modify the machine, and so over the course of a year people modify it slightly; eventually it ceases to work because users have modified the system and created a situation makes programs stop working, for one reason or another. 

The only thing that will prevent this scenario from occurring is to make it such that users of the machine are not able to install programs, modify the system, etc.

**Comment by Knottyashcreative** [comment]
I have just restarted the computer as noticed Corel 4 sometimes crashed and this fixed the issue.  I have tried it again just now and this appears to have resolved the issue. 

Corel is working for now, I'm not sure what is the reasoning behind this.

I also wonder what preventative/system restore options are available to make our PC's more resilliant (if system restore is not viable as Matty said) ....possible create a System Images every 6 months.  I offer this as a discussion point.

What is the long term solution? reinstall Corel

**Comment by MatthewCroughan** [comment]
If the software doesn't need to change, there's no reason to recreate the image every 6 months for example. 

The issue comes when we want to add new software, if we were to follow my idea. Because then, someone would have to of the job of recreating the image. This is a typical problem in system administration and has no obvious solution.

# The modern solution 

Windows has this feature called "auto unattended setup" which allows you to create a Windows image with code.
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/automate-windows-setup 

There is a tool called Nix which I'm quite fond of that would allow us to make `gerald.nix` and then `nix-build gerald.nix`. The result would be our windows 10 system image that we want, with laser cut installed, coreldraw, etc. There's a library called [wfvm](https://git.m-labs.hk/M-Labs/wfvm) that makes this possible.

This is my preferred solution, though I don't plan on working too hard on it. This doesn't stop anybody else from working on setting up an `autounattend.xml` solution in another way though. It just depends on how much time someone is willing to put into this.

In the short term, just hacking it by creating golden images every 6 months seems reasonable. But over time this will become a drag. If the systems ran Linux this would all be trivial, but this is not possible for Gerald, whereas it is for other systems that use Lightburn.

**Comment by ajlennon** [comment]
> But over time this will become a drag.

We've managed for 4 years so far...

**Comment by MatthewCroughan** [comment]
> We've managed for 4 years so far...

Yeah, and the fact that this issue is guaranteed to occur at a certain frequency is the 'drag' I am talking about.

The method used so far is perfectly usable and fine. I'm just proposing that there's a different and better way.

**Comment by ajlennon** [comment]
>The method used so far is perfectly usable and fine. I'm just proposing that there's a different and better way.

No you are proposing a different way. Not a better way. Your way is over complicated and unmaintainable which are critical factors here.

**Comment by MatthewCroughan** [comment]
> > The method used so far is perfectly usable and fine. I'm just proposing that there's a different and better way.
> 
> No you are proposing a different way. Not a better way. Your way is over complicated and unmaintainable which are critical factors here.

I disagree that it is complicated and unmaintainable. And I do believe it to be better than manually creating the disk image, yes. I would appreciate if you would not try to cause an emotional argument and just discuss instead.

Creating a disk image by hand, wherein steps are missed at each point is unmaintainable, it is also complicated. Running `nix build` on a file that produces the same output every time by comparison is uncomplicated and maintainable. :smile:

**Comment by ajlennon** [comment]
>I disagree that it is complicated and unmaintainable. And I do believe it to be better than manually creating the disk image, yes. I would appreciate if you would not try to cause an emotional argument and just discuss instead.

Then do it and maintain it or let me get on with actually DOING THE WORK without commenting on why I should be DOING THE WORK in some other way you prefer.

**Comment by MatthewCroughan** [comment]
> > I disagree that it is complicated and unmaintainable. And I do believe it to be better than manually creating the disk image, yes. I would appreciate if you would not try to cause an emotional argument and just discuss instead.
> 
> Then do it and maintain it or let me get on with actually DOING THE WORK without commenting on why I should be DOING THE WORK in some other way you prefer.

If possible, I'm requesting that you give me a chance before criticizing in the manner that you just have. You're just yelling at me, you're not discussing.

1. I'm not stopping you from doing anything.
2. I'm not telling you to do anything differently

Did you read the following:  "The method used so far is perfectly usable and fine."

**Comment by amcewen** [comment]
@Knottyashcreative Thanks for digging into this along with @magman2112 and @JackiePease.  We've still got the Corel installer (along with the other installers), but they're not publicly available.  One of the organisers should be able to get it for you, and I'll stick it on a USB stick next time I'm in, if it's not been sorted by then.

@MatthewCroughan, as @ajlennon points out, the system he implemented and documented has been running fine for years, and now&mdash;when there's been a problem&mdash;we have the documentation and files we need to fix things.  There's some cost to it in people's time, but we've seen there are a bunch of people *other* than @ajlennon who've been able to step in and do that work.

We can contrast that with #1208.  I realise that's using a different build system than the one you're proposing now, but it's only lasted 16 months, and now that it's failed I don't know how we're supposed to fix it as there's no documentation (that I can see, having re-read that issue, and read through the wiki page for the cutter) of how it was set up beyond mention of Balena and a `Dockerfile` pasted in at some point during getting it running.

[And in response to the comments that have come in while I've been writing this comment]

Glad to hear @MatthewCroughan that you agree that "The method used so far is perfectly usable and fine.".

**Comment by MatthewCroughan** [comment]
Indeed, there's nothing wrong with the way we're doing it now. I just think there's a better way.


> We can contrast that with #1208. I realise that's using a different build system than the one you're proposing now, but it's only lasted 16 months, and now that it's failed I don't know how we're supposed to fix it as there's no documentation (that I can see, having re-read that issue, and read through the wiki page for the cutter) of how it was set up beyond mention of Balena and a Dockerfile pasted in at some point during getting it running.

It is correct that the Vinylcutter's current state has not been documented. I will make it my goal today to describe how it has been done today and close #1208

**Comment by ajlennon** [comment]
There are also a host of other issues with the Crealities I have had to sink huge amounts of time into.

Not least that the Ender 3 is unusable for the average person with the interface wheel disabled...

The Ender 3 hasn't worked since you broke the extruder and replaced it with a different extruder then headed off.

These are *not* improvements and I have absolutely no interest in hearing about "clever" strategies that just make life hard. Dig in and do work to make things continue working in a way other people can maintain rather than making life hard for everybody else.

**Comment by MatthewCroughan** [comment]
It's not quite right to compare 3d printer parts to software.

> The Ender 3D hasn't worked since you broke the extruder and replaced it with a different extruder then headed off.

The extruder is the bit that oozes out the filament. I've never replaced an extruder on any printer. Are you thinking of something else? I've tried to get in touch about this but you haven't yet replied on Discord for example. Though you have been sick.

If you do want to have a moan, please contact me instead of moaning about it here, I'm happy to help.

And for what it's worth, I documented every single detail of my process for what I think you're complaining about, wherein I got permission to perform each operation explicitly from you. So I don't think you're being fair at all. In fact, I think you're being rude.
https://github.com/DoESLiverpool/somebody-should/issues/1396
https://github.com/DoESLiverpool/somebody-should/issues/1394

**Comment by ajlennon** [comment]
>The extruder is the bit that oozes out the filament. I've never replaced an extruder on any printer. Are you thinking of something else? I've tried to get in touch about this but you haven't yet replied on Discord for example. Though you have been sick.

You broke and replaced the extruder I thought? You told me you fitted the metal replacement for it? Did I misunderstand you?

I don't want to have to moan about anything. I just want this stuff to work without "improvements" I then have to fix.

**Comment by MatthewCroughan** [comment]
> You broke and replaced the extruder I thought?

Extruder is right. My bad. The hotend is what I was thinking of.

The extruder on **my own** printer broke. I then informed you about this design flaw in the creality extruders. You bought one for me to fit, preemptively, since it was assumed your one would eventually break. I then fit it for you. It was on your Ender 3.

I even still have the old parts in baggies on my desk.

**Comment by ajlennon** [comment]
>Extruder is right. My bad. The hotend is what I was thinking of.

Live and learn - remember to remind me **never** to take advice from you on "improvements" as it invariably makes life much harder than it should be. I don't have time to waste "maintaining" things that shouldn't need maintaining. None of us do. Maintainership is onerous and we need **SIMPLE** & **DOCUMENTED** strategies that can enable **anybody** with time and a will to step in and help.

**Comment by MatthewCroughan** [comment]
Is it possible you could bring down the heat of the conversation and be more constructive and not use loaded and emotive language to insult me?

:smile_cat:

**Comment by amcewen** [comment]
It would be good if you could *both* do that.  You're allowed to take your own advice too @MatthewCroughan, and take it offline.  Or leave it a while before replying.

**Comment by ajlennon** [comment]
Blocked and ended.

**Comment by MatthewCroughan** [comment]
https://www.youtube.com/watch?v=GE94BJg3U1Q

**Comment by MatthewCroughan** [comment]
https://www.youtube.com/watch?v=GE94BJg3U1Q

![image](https://user-images.githubusercontent.com/26458780/123555127-b5719080-d77b-11eb-8a36-bb937a0da49f.png)

**Comment by nixinator** [comment]
arguing about the reliability of windows,  is rather like arguing about the pros and cons of nuclear armageddon.

bill gates, you have a lot to answer for , creating an OS so bad, that it makes my friends fall out, because windows is designed to be unmanageable, incomprehensible, unmaintainable and with constant change, of both UI and system... unlearnable. That's how they like it, so you are completely reliant on others, not yourself. Is that a message maker spaces should be promoting?

We actively ban windows here, unless there is absolutely no way we can get something running without it. It's trouble, causes trouble, and just when you think you have everything running, it's a virus comes along a destroys the whole thing. It's also completely unfixable, wipe and reinstall , another 8 hours of my life i cannot get back.. while bill gates buys up farmland globally ..???????

I used to run Corel draw for a company making magazines, at the time, corel was awesome, but it crashed a lot, corrupting anyfiles it had open at the time. once it just deleted it open dll's and exe's, too, sounds like it up to it's old tricks again. 

I once was called to large factory, they had an industrial robot arm that did important things, someone had install free AOL isp cdrom on to it.... the robot arm just kept spinning around, nearly injuring the operator.!!! that was running windows 95.

that was over 25 years ago, and this reminds me of that... is that progress.

but don't let bill gates, and that disgrace to humanity steve ballmer let good friends fall out.. if anyone is to blame here....the  real enemy here is microshaft....that shoddy piece of software, not fit for human consumption. 

I've never got system restores to work, it's an afterthought at best.

if does really want to promote open maker spaces, then why is it relying on expensive, close , proprietary software.

This issue is deeper than just 'i can't get windows to work again'.

to make a change, your going to have learn something new, because if you do exactly the same as you did, you will get exactly the same result... do you think windows will get better with version 11, do you think it will be more privacy preserving, do you think it will be cheaper to buy?  

How does one ween does liverpool of proprietary closed source software like windows and corel?

probably not possible , so i'll see this groundhog day discussion, in another 25 years.

the problem you have , everyone has that problems, and guess what there are some very expensive enterprise tools, to do the things your asking. 

good luck and may be the 'open' source be with you, always.

**Comment by RonRicoSuave** [comment]
"How does one ween does liverpool of proprietary closed source software like windows and corel?"

I'm somehow less of a proponent of open source after reading your incoherent screed, so thanks for that.   I just picked this sentence out as the perfect example of what makes most people run in terror from frothing anti-Microsoft ranters.  Modern Windows has its problems and you managed to hit on exactly none of them except your own inability to use it properly, assuming you're even talking about modern Windows.  It's hard to read babbling rants.

**Comment by nixinator** [comment]
LOL.

**Comment by magman2112** [comment]
I am going to close this issue for a number of reasons.

1st, the old laser software was re-installed and was working, cancelling the original reason for this issue.

2nd, The controller on Gerald has died and we currently have an issue, #1642, that has been opened to track this issue. The plan is to replace the controller with the same one as on Tony, so the related software will be changing to Lightburn.

Lastly, all the other issues that were discussed have not really progressed in the last few months. If this still needs to be discussed, it should be opened as it's own issue (with a link back to this issue to give some history if required).
