### ISSUE TITLE
Embroidery machine - clogging

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1587]
The embroidery machine is sewing at various given points and then suddenly refuses to move from a spot and creats a clump of thread that is also tangled beneath.  The thread underneath has to then be cut to resolve this issue.  The machine will then move along happily and work on various areas until it randomly appears to do the same again.

Contexualising the issue;

- The bobbin thread was used, correctly installed and wound propler as per instructors instructions.
- The upper embroidery thread is installed as per the instructions.
- The material/cloth has a supporting interface and is not too thick (with the correct tension on the hoop)
- The file used is compatitable and it happens on various embroidery threads.

Thank you in advance for any ideas that will help resolve this issue.

**Comment by Robotorium** [comment]
When you say "various embroidery threads" can I ask what you've used?

Op ma 28 jun. 2021 10:33 schreef Knottyashcreative ***@***.***

**Comment by Knottyashcreative** [comment]
The ones from the embroidery box (see attached image![Screenshot_20210701-203619_Photos.png](https://user-images.githubusercontent.com/58068720/124180398-07802200-daac-11eb-848f-becd5187119c.png))

**Comment by Robotorium** [comment]
Thanks Terry :) I didn't have time to look today but I'll be in on Monday
and have a nosey then.

At what point(s) in the process is it happening? First layer, subsequent
layers, etc? What stitch length are you using/is it happening in places
where a lot of stitches are crammed into a small area?

It's okay if you don't have the answers, I'll make some test files and have
a nosey.

Op do 1 jul. 2021 20:37 schreef Knottyashcreative ***@***.***

**Comment by Knottyashcreative** [comment]
The stitch length was short and I never set double layered, but the clumpy cloggy issue trended to happen when stitching a small area. The clogging trended to happen a random times and so no specific thinking was identified.


Thanks Snoof

**Comment by KayaScott** [comment]
Hi 

I went to use the embroidery machine yesterday evening.
I encountered a couple of issues – some which may lead to the problems Terry has been having.

1)	The screw for tightening the frame up was threaded in the middle section.  The frame would appear to be tightened up correctly but would slip out 
•	This would mean the fabric and stabiliser would not be under tension and could therefore lead to bunching of the fabric. 
•	This issue has been logged by Jackie and I have added an extra nut inside the frame as a temporary fix, whilst awaiting replacement screw and nuts.

2)	There was a mass of threads under the bobbin winder – this could cause the bobbin to not wind correctly which in turn would lead to poor tension whilst embroidering.
•	The mass took me some time to remove, there were some red threads in the middle of this .  
   
    
![image](https://user-images.githubusercontent.com/62438090/124482690-78238900-dda1-11eb-8a91-d76da619cf1d.png)

 
![image](https://user-images.githubusercontent.com/62438090/124482781-8c678600-dda1-11eb-9567-a67ec07ec393.png)

![image](https://user-images.githubusercontent.com/62438090/124482807-94272a80-dda1-11eb-896f-a883ad78e40b.png)
![image](https://user-images.githubusercontent.com/62438090/124482835-9be6cf00-dda1-11eb-9b3a-91c074818da1.png)

![image](https://user-images.githubusercontent.com/62438090/124483045-d2bce500-dda1-11eb-88aa-81c0f0fb746d.png)
![image](https://user-images.githubusercontent.com/62438090/124483077-db152000-dda1-11eb-86b6-92d676fe6fea.png)

  
It is important that only the white and black bobbin threads on the larger blue cones should be used. 
Do not try to mask tension issues by hiding with same coloured threads.  Follow the procedures for checking your tension in either the manual or online.

Manual - https://download.brother.com/welcome/doch100205/888g80_g82_om02en.pdf
Troubleshooting and FAQ https://support.brother.com/g/b/faqtop.aspx?c=gb&lang=en&prod=hf_inov800eeuk

3)	Upper tension problems could be caused because the thread is very fine and can unwind too quickly.  
Make sure the correct size spool cap is used and one suggested solution is to put a spool net over the thread 

After cleaning the bobbin winding spindle, inserting a freshly wound bobbin and fixing the frame tension I successfully embroidered a simple design with a 1.5mm running stitch pattern and some monogramming.  The designs came out clear and without tension issues

![image](https://user-images.githubusercontent.com/62438090/124483194-f5e79480-dda1-11eb-9910-ac82624cf0ce.png)
![image](https://user-images.githubusercontent.com/62438090/124483246-0435b080-dda2-11eb-97e2-6477eb3fb2e4.png)

**Comment by Robotorium** [comment]
Brilliant, thank you! Looking great!

I've been in today and Terry was using Fred. I started noticing the fabric
dragging across the frame, took a brief 10-second video to show Terry, and
paused the machine to go get him. Once he got into the event room, he
realised the needle had fallen completely out and was now bent. The
assembly where the needle should have been inserted and fastened was
extremely loose.

While the things KayaScott said are extremely true and important and please
listen to them, I'm also wondering if the added vibration is causing some
problems? At Sandbox, Fred was on a very sturdy desk on some carpet, and
made a lot less rattly noise, which I mentioned to Terry. We're wondering
if maybe the added vibration is causing some of the problems, so we're
going to try wedging carpet under various things. I have a spare hank of it
at my house that's for the skip if not used, so we'll sort out getting it
here and give that a go.

Another option is maybe the density of the stitches. Terry is using Hatch
(?) and I'm not sure how it organises everything but I know that the denser
the stitches are, the more likely you'll get a clog. So if the carpet
doesn't solve the problem with this specific file, then we'll look into
that/I'll bully Terry until he uses Ink/Stitch.

Op ma 5 jul. 2021 om 15:06 schreef KayaScott ***@***.***>:

**Comment by JackiePease** [comment]
I've just embroidered a simple star pattern created in InkStitch fill stitch, plus some inbuilt lettering. Looks ok on both sides to me - @Knottyashcreative perhaps you could try recreating a small part of your design using different software?
![IMG_20210705_184423](https://user-images.githubusercontent.com/12802256/124505712-03ad1200-ddc2-11eb-8045-8c9df3ee6f4d.jpg)
![IMG_20210705_184405](https://user-images.githubusercontent.com/12802256/124505718-0871c600-ddc2-11eb-88e7-719a4c066e91.jpg)

**Comment by Knottyashcreative** [comment]
I agree it something I'm looking into.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by JackiePease** [comment]
We don't seem to have had any further issues - can reopen if we do
