### ISSUE TITLE
Sheila laser cutter momentarily losing or reducing laser power

### ISSUE THREAD

**Issue by AndyH0** [DoESLiverpool/somebody-should#1591]
When using Sheila on Thursday 15th July afternoon, she momentarily lost laser power and no laser tube current. Otherwise motion control all normal. I tried turning her on and off and still no cutting laser power at all. Then just started cutting again while working an outline. Later in the session, the power randomly dropped and it did a sort of etch which should have been a clean cut. Then went back to normal. She was working OK at the end of my session.

Context:
- Using low/medium powers 15-25W.
- Water bath was 27 degrees which I thought was quite warm given I was cutting small and few parts at modest powers.

Is there anything I should do or check next time I use it?

**Comment by magman2112** [comment]
I meant to check the water level in the chiller for Shiela on Sunday and got distracted as usual.
I am in DoES tomorrow though, so will check this.

We also had temperature alarms on Gerald on Sunday, likely due to the high ambient temperatures. We use chillers for all of our laser coolers, so these are unlikely to chill much below ambient temperatures, so for the present we just need to give the chillers a chance to cool down to some degree, or the laser cutting may be affected. 

Unless we invest in more expensive refrigerant based chillers, this is unlikely to be eliminated as an issue, so we just have to be aware of the ambient temperature limitations and try to work around these limitations.

**Comment by AndyH0** [comment]
That's useful to know, and I will be a bit more relaxed the next time it happens! Also I will keep an eye on the temperature to see if any failure is correlated to the bath waring up. Am I right in assuming that the laser has some fail safe that when the cooling water is too warm it refuses to fire?  I have booked it for Thursday afternoon so will report back how that goes.

**Comment by Robotorium** [comment]
Sheila did this today a little bit, too. I didn't realise it was due to the
heat (I was able to finish my work).

Op di 20 jul. 2021 21:50 schreef AndyH0 ***@***.***>:

**Comment by amcewen** [comment]
The lasers operate best at around 19-20&deg;C, and the power output does drop off as temperature rises.

The chiller unit on Gerald can actively cool, so it should be able to cope with the hotter days.  The one on Sheila/Sophia can only chill down to room temperature, which obviously isn't as good in current temperatures.  There is air-con in the room, so having that on will no doubt help a bit, but worth keeping an eye on.

**Comment by Robotorium** [comment]
Would that lead to a gradual decrease or an immediate cutoff?

I put the a/c on as soon as I got in, and when I opened the window for the
hose I immediately closed both blinds nearest the wall because she was
roasting (and I thrive best in mushroomy conditions).

She cut really well (immediately post-Mikening grade), the only issues I
had when she was cutting were down to the wood in small bits and were
ironed out with snapping and some sanding. The only times she didn't cut
were complete cuts (I'm not sure how to state this properly, she didn't
ever lose power mid-cut, just sometimes wouldn't start).

Because the room was at a decent temperature, it didn't occur to me that it
could be heat-related (retroactively silly) and instead I opened the lid
and ran my fingers along the sensors before closing again (on autopilot),
which fixed it every time (I want to say it happened maybe 3 times, I did
31 cuts).

Is there risk associated with running the cutters when it's too hot?

Op di 20 jul. 2021 23:46 schreef Adrian McEwen ***@***.***>:

**Comment by amcewen** [comment]
Generally it would gradually lose power as it heats up, rather than being a sudden not-working.

I didn't think there's anything in the chiller to have it cut out, but maybe I'm wrong.  Or maybe we're still seeing the issue from #1563?

**Comment by Robotorium** [comment]
I think it might be impossible to tell for sure until the heat dies down,
then?

Op wo 21 jul. 2021 10:18 schreef Adrian McEwen ***@***.***>:

**Comment by AndyH0** [comment]
I used Sheila yesterday and got to the bottom of the problem. And indeed the same issue from #1563 I think. It's the magnetic interlock. It stopped cutting a few times. Press on the lid above the magnet (not particularly hard) and starts cutting and stays cutting. Mike has some stronger magnets which should fix this so we can close the issue. Bath was warm, 31-33 degrees (Mike had refilled it), but Sheila cutting fine.

**Comment by amcewen** [comment]
Good sleuthing @AndyH0!

**Comment by AndyH0** [comment]
Hi Mike @magman2112, Sheila still cutting fine yesterday but still need to press on the lid a bit to squish the magnet closer to the sensor. Can you fit one of your stronger magnets and we can close this issue. Thanks, Andy.

**Comment by magman2112** [comment]
The magnet has been replaced on Sheila and the laser test worked straight away.

I will leave this issue open for now, to see if this clears the fault on longer cuts which I don’t have time to do at the moment.

**Comment by Robotorium** [comment]
Thanks Mike!

Op zo 1 aug. 2021 18:27 schreef Mike Gorman ***@***.***>:

**Comment by magman2112** [comment]
Closing this issue now as Sheila has been working well for over a week now.
