### ISSUE TITLE
Recycled 3D printer filament‏ extruder

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#161]
(as suggested by Adrian via GoogleGroups)
I'll have a look at the instructions  http://www.thingiverse.com/thing:30642 and see what's needed...

**Comment by aubergine10** [comment]
Open source plastic recycling project that might be of interest - would be epic if we could build this kit: https://preciousplastic.com/en/

**Comment by goatchurchprime** [comment]
I saw an attempt at 3D printer plastic recycling at @makespacemadrid.  They had a shredder but were having problems with the electric motor.  I'm wondering if a big handle from a mangle could be practical (and a lot more cool because you can leave stuff in the hopper for anyone to grind up in their coffee break)
  https://twitter.com/goatchurch/status/969893854580281344

The grinding up of the plastic parts into small pieces is necessary before you can melt it.  It also reduces its space and makes the scrap more portable.  

They said that regenerating filament works for PLA, but ABS is much less good because it undergoes some change when it melts and you never get back to the original characteristics.  

There are home built grinding machines, like this one:
    http://www.instructables.com/id/50-Plastic-Shredder-Grinder-Recycler/

The perfect unit is this one:
    http://www.sinoshredder.com/shredders/small-sized-plastic-granulator/

The fact that there's nowhere to take our scrap, but there are 3D printers all over the place, could be an opportunity if we see a plan that makes it practical.  Best option is to wait until another hackspace more advanced in this field does it and copy/learn from them.

**Comment by DoESsean** [comment]
Arthur Rowland from PlasticTactics recycles plastic, and we're talking with him about doing so with ours. Given that a member of the community does this, it seems silly to step on any toes and try and set up in competition. 

Closed!
