### ISSUE TITLE
Buy new 0.4 nozzles for the Ultimakers

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1614]
While looking into #1611, it was noted that both Ultimakers could do with replacement nozzles. 3DGBIRE site is down for maintenance at the moment - will take a look tomorrow

**Comment by amcewen** [comment]
@JackiePease and I compared some of the nozzle options and went with two of these [coated brass nozzles](https://www.3djake.uk/micro-swiss/coated-nozzle-for-the-ultimaker-2) as they weren't much more expensive than plain brass and we can see if they're any better.

**Comment by amcewen** [comment]
These have arrived, and are currently on @DoESsean's desk (not really the best place for them, but that's where they are for now)

**Comment by AndyH0** [comment]
Felicity was virtually out of filament Friday evening but I failed to get the reloading with PETG teal filament to work. I made the end nice and pointy but no joy. I think the nozzles blocked. I didn't want to mess further and break something. Posting this here because it seems relevant to nozzle replacement.

**Comment by huffeec** [comment]
The Ultimakers could both use new nozzles. Does anyone know where I can find these ones?

**Comment by JackiePease** [comment]
@AndyH0 did you replace the nozzles?

**Comment by AndyH0** [comment]
No I haven't replaced the nozzles. See Issue #1649. I had a lot of problems which seemed like nozzle blockage (poor or no flow) but in the end I concluded the nozzle was fine and that the problem is that the filament can melt behind the nozzle and because of the curve in the filament slip to one side. My advice is that if no flow from nozzle, remove filament and reload straight away. Don't try to feed filament otherwise the swelling can get worse and then dismantling is required! Also when loading make sure the filament is cut at an angle which compensates for the direction of its bend and straighten the end of the filament. By reloading as soon as flow was poor, straightening and trimming the filament carefully, flow was restored and getting nice prints. A new nozzle might help lubricate the filament into the nozzle if the old one has crud at the filament entry.

**Comment by JackiePease** [comment]
Thanks @AndyH0 - some good ideas there.
I've ordered 2 new nozzles from 3DJake anyway, as we can't find the others at the moment.

**Comment by JackiePease** [comment]
Replacement nozzles have arrived. I've temporarily taped then to the inside of the 3d printer cupboard.
