### ISSUE TITLE
The doorbot 2 gpio pins should be better secured

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#162]
The single GPIO pin (on [pin 25](http://www.raspberrypi-spy.co.uk/2012/06/simple-guide-to-the-rpi-gpio-header-and-pins/)) came out today. It wasn't clear where it should go back in again, and is likely to happen again in the future because it's a single pin, and the pi is mounted on the doorframe, subject to the vibration of the door closes. 

Ideally, this should be more secure, to prevent this happening in the future.

**Comment by amcewen** [comment]
It had fallen out again on Friday.  

I'm most of the way through a PCB design for it - current work-in-progress at https://github.com/DoESLiverpool/doorbot-setup/tree/master/hardware - as part of https://github.com/DoESLiverpool/doorbot-setup/issues/6

I've got a few parts on order to let me complete the PCB design, then we'll need to make three of them - which might be a good test for @goatchurchprime and the Architype mill (or an exercise for someone who wants to try milling PCBs on the Proxxon) (or failing both those, I can mill them sometime :-D)

**Comment by goatchurchprime** [comment]
I've just made a board that seems to pass the quality control test waiting to be soldered together.  

If this works I'll cut the second one.

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by johnmckerrell** [comment]
Was this fixed when @amcewen provisioned a new board?

**Comment by amcewen** [comment]
I don't think so, because I didn't modify the relay side of things.  The custom PCB would solve this, but I figured we'd hold off until after we move to see if we're still using the same door entry system.  If we aren't, then this can be closed then; if we are then I'll order some PCBs :-)

**Comment by amcewen** [comment]
We've got new PCBs now, and I've ordered the remaining parts we'd need - https://github.com/DoESLiverpool/doorbot-setup/issues/6#issuecomment-327133019 - so once they arrive we can solder one up and try it out.

**Comment by amcewen** [comment]
PCB soldered up (thanks @helicalbytes!), but doesn't seem to be working just yet.  Haven't tracked down what's causing that yet.

**Comment by amcewen** [comment]
Turns out the problem was with the solder joint on the 5V feed from the Molex connector.  Because the pin holes aren't quite big enough we had to file down the pins a bit to get them to fit.  I think the 5V pin was too snug a fit and didn't let any solder through to make a good connection on the top side of the PCB.

I've fixed that now and the PCB seems okay *apart from the sound card*.

The sound card isn't used by doorbots 1 and 3, so we could solder those up regardless.  Given https://github.com/DoESLiverpool/doorbot-setup/issues/22 though, we'll need to get some stackable headers for them so the PCB doesn't foul the taller components.

We should tape the top of the USB/Ethernet connectors too to insulate them, because with the stackable headers there's enough play in the PCB mounting that the 12V on the underside of the solenoid connector can short against them if you're not careful.

**Comment by amcewen** [comment]
Doorbot2 failed again today - the GPIO pin came loose and (it turned out eventually) the 3V3 connection wire had come loose on the RFID reader itself (i.e. not at the Pi end).

I couldn't spot any problem with the sound card, but similarly didn't get it to work.  While unsoldering it to switch an another (to see if it was the soundcard itself at fault) I managed to destroy a few pads on the connector for it on the PCB :-(

So, the new PCB is now installed and working on doorbot2, but without any sound.  I'm going to close this issue (as the GPIO pins are better secured :-D) and spawn a new one to cover remaining "deploy the new PCBs" tasks.
