### ISSUE TITLE
Sheila has excessive leakage current

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1641]
Sheila has failed her PAT test on excessive (1.74mA where it should be below 0.9mA) leakage current.

**Comment by amcewen** [comment]
With the mains filter removed the leakage drops to 0.88mA (which is still a fail)
With the mains filter and the high voltage power supply disconnected we get 0.42mA (which is a pass)
With the mains filter and the 24+5V DC power supply disconnected we get 0.50mA (which is also a pass)

We need a new filter: It's marked as an FT127-10.  10A 110/250VAC

**Comment by magman2112** [comment]
I have found an equivalent filter at CPC and Farnell, a Corcom 10EMC1.

the Farnell device is this one 

https://uk.farnell.com/corcom-te-connectivity/10emc1/filter-10a-1-phase/dp/9586474

The CPC device is this one, though they are out of stock at the moment

https://cpc.farnell.com/corcom-te-connectivity/10emc1/filter-10a-1-phase/dp/FT01464?st=mains%20filter%2010a

There is also an equivalent device, a Corcom  6EMC1 filter which should be suitable for Sophia’s other filter. 

https://uk.farnell.com/corcom-te-connectivity/6emc1/filter-6a-1-phase/dp/9586466?ost=6emc1

Also, Gerald has another similar filter 10EMC1,  so I would suggest buying 3 of these devices and 1 6EMC1 for Sophia at the same time.

**Comment by JackiePease** [comment]
I've ordered 3 x 10EMC1 and 1 x 6EMC1 from Farnell. Total cost £83.59. They should arrive tomorrow.

**Comment by JackiePease** [comment]
The filters have arrived - I've left them on @DoESsean desk

**Comment by magman2112** [comment]
A new mains filter has now been installed in Shiela. It is now ready for a PAT retest.

**Comment by amcewen** [comment]
I've re-tested it and with the new filter the leakage current is 1.25mA, which is still too high :disappointed: 

We tried swapping out the laser power supply for the brand new one that's just arrived for Gerald, and the leakage current then was actually higher at 1.36mA.

I think we need to do a bit more reading up to work out our next steps.

**Comment by paulgeering** [comment]
We may be able to define a process for devices where we know there is legitimate mains filtering going on.
So long as we understand why leakage is there, how much, and whether that is safe.

Paul

**Comment by amcewen** [comment]
That seems a sensible approach @paulgeering.  What do we need to do to understand the leakage better?

@pkharvey found some useful resources online (and has one of the electricians' guidebooks too, which has some info about it) which he's (hint, hint ;-) going to post here sometime.

I've dropped Dominic at Smoke and Mirrors an email, too, to see if it's something he's come across.

**Comment by amcewen** [comment]
Heard back from Dominic, and it seems it's fairly common for laser-cutters to fail their PAT test, with the high voltage power supply tending (as we've seen) tending to have high leakage current even when new.

**Comment by pkharvey** [comment]
Useful resources for PAT testing (in the hope they're useful) as follows...

I heard the PAT tester does an I<sub>LEAK</sub> test for Class II devices though many don't even have even an earth pin.  In these cases, the tester still tests for I<sub>LEAK</sub> to "earth" by measuring for current (presumably from L/N) through an exposed metal part of the Class II device by connecting the test probe, which would indicate a failure with its double insulation.  The leakage test on Class II equipment is referred to as a Touch Current Test.  I liked the detail given in [this description](https://www.pat-testing-training.net/articles/leakage-current.php) though it's also described [here](https://www.pat-testing-expert.com/support/leakage-tests) and [here](https://www.pat-testing-course.com/blog/faqs/earth-leakage-testing/).  It's also in §10.7 (p-p 73-74) in the official [code of practice](https://electrical.theiet.org/wiring-matters/years/2020/81-july-2020/the-all-new-5th-edition-of-the-iet-code-of-practice-for-in-service-inspection-and-testing-of-electrical-equipment/) (come see at Aeternum or I can bring/lend).  Still, if a Class II appliance fails on I<sub>LEAK</sub>, it should be failed ([ref](https://www.parker-bell.co.uk/class-ii-appliance-fails-pat-test/)).

Is Sheila's power supply Class II?

As far as the code book goes on filters, §6.3 (p 52) has info on the Class II FE (functional earth as opposed to safety earth) classification, for products that fulfill the requirements for Class II fault protection but for functional reasons (eg. EMI filter), require an Earth connection.  The figure in the code book depicts the filter capacitors to earth, text describing "...filter capacitors or other coupling between the protective conductor on the input and the extra-low voltage output connection" but nothing on the leakage side of things.  That's the closest matching info I could find in the code book but you're welcome to try find something I might have missed.  Older equipment that would now be Class II FE might be marked as "ITE".  The new inclusions to the 5th edition (including Class II FE) are summarized [here](https://www.pat-testing-training.net/articles/iet-code-of-practice-5th-edition.php).  [This page](https://patta.co.uk/class-2-functional-earth/) describes Class II FE well enough for PAT testing.

The [Testing Plastic Encased Class I Equipment](https://www.pat-testing-training.net/articles/class1-earth-testing.php) page is nice that it details tests for this type of Class I equipment, commonly monitors and TVs, and introduces the need for introducing Class II FE.

The document [PSU Isolation and Identity PDF](https://en.globtek.com/pdf/technical-article-pdf/PSU%20Isolation%20and%20Identity.pdf) has diagrams of some devices having other possible different configurations not described in the code of conduct and PAT testing websites.

This nice [IEE article on PAT testing leaky equipment](https://electrical.theiet.org/media/1697/pat-testing-of-equipment-having-high-protective-conductive-leakage-current.pdf) though bit old, using Variable Speed Drives as example (does Sheila have one?), says that EMC filters often fail PAT due to excessive I<sub>LEAK</sub> although it is a normal characteristic of the equipment.  It's worth reading for the full explanation, but to summarize, it emphasizes that **maintenance** of equipment is what counts to comply with the law (not inspection and testing alone), then goes on to explain the reasoning of the competent person doing the test in this case:

> However, equipment employing a VSD will, in most cases, have a leakage current greater then 3.5mA due to the filters at the input and hence will be unsuccessful when performing this test. Although this does not show the equipment to be unsafe if this test is performed, the value of current should be recorded since an increased current in any future tests can be due to deterioration of components within the equipment.
> The engineer performing the tests will then have to decide if the equipment is still safe for service and will make his judgement based on whether the protective conductor current increased from the previously recorded value or from the manufacturer’s advised maximum current. The engineer must then verify that such equipment with a protective conductor current designed to exceed 3.5mA complies with the requirements shown in table 4.  Further precautions need to be taken for equipment with a protective conductor current exceeding 10mA, see Section 607 of BS 7671.

Finally, might be useful to know from this particular filter manufacturer's [installation and maintenance guide](https://www.mpe.co.uk/wp-content/uploads/2013/02/TEMPEST-PLUGGABLE-FILTERS-INSTALLATION-AND-MAINTENANCE-GUIDE.pdf) how they recommend to deal with the issue for their Class I filters:

> Portable Appliance Testing (PAT)
> MPE filters may be subjected to PAT testing however due to the nature of EMI filter elements some tests will report a false fail and cannot be used as a valid assessment of the product’s functionality or safety. This filter range is classified under IEC 61140 as Class I having a protective earthed metal case. Below are the tests that will give a valid result in a functional unit:
> • Earth Resistance Test – less than 0.2Ω.
> • Earth Loop Test – 100mA (screen test), 10A (routine test) or 25A (bond test).
> • Earth Leakage – 5mA limit as per Class I. Insulation resistance will produce a false fail due to the discharge resistors within the filter.
> • Extension Lead Polarity Check – polarity should be maintained to all outputs from the input plug.

Hope any of that is useful.

**Comment by amcewen** [comment]
That's really helpful @pkharvey, thanks!

In particular, https://www.pat-testing-training.net/articles/iet-code-of-practice-5th-edition.php which goes into the leakage limits in more detail.  From that, even in the 4th edition the 0.75mA limit for leakage current is only for "handheld and portable", whereas there was a 3.5mA limit for "Class I IT, Movable, Stationary & Fixed".  I think the laser-cutters would come under that latter category.  In the 5th edition all of the limits have been increased to 5mA.

So from my reading of that, we're a way below the 4th edition limit even for Sophia's 2.36mA leakage (see #1643) and below the 5th edition limit of 5mA for all devices.

**Comment by RussCoty** [comment]
It seems reasonable to use the new 5mA limit as of the 5th edition guidelines.

**Comment by amcewen** [comment]
So, I was PAT testing a power supply so figured I'd re-test Sheila.  The leakage current is 1.23mA, so easily passes the (newly understood) limits.

So I'm going to close this.  However, Sheila isn't powering up at present, so is still inoperable.  I've spun that out as #1656
