### ISSUE TITLE
Move Sheila into the laser room for the time being

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1696]
We've had some complaints about the fumes coming from Sheila as it just vents out of the window in the events room. Now that there are no longer any pandemic restrictions we can move it into the laser room. This will likely be temporary as we're looking at getting a filtration system so that we can move it back into the events room.

It should be possible to reunite the plan drawers by the alcove, possibly putting Sophia on top. Sheila can then go into the corner of the laser room and be hooked into the existing fume extraction system.

/cc @DoESLiverpool/laser-maintenance

**Comment by johnmckerrell** [comment]
After some sterling effort by various people called Chris and also some people not called Chris (@chris-does @huffeec @zarino and @goatchurchprime ) Sophia and the plan drawers have now been moved out and into the alcove. We didn't move Sheila yet as we wouldn't have been able to hook it up to the ventilation system yet.

**Comment by huffeec** [comment]
I think confusingly one of the Chrises isn't called Chris on Github. He's @helicalbytes

**Comment by magman2112** [comment]
@Sean-anotherone and I managed to fit an extra piece to the adaptor @johnmckerrell brought in so that Sheila’s extractor hose would fit. This allowed us to relocate Sheila into the laser room.

Everything initially appeared to be OK until we tried powering up the chiller for Sheila. This now alarms all the time, but I can’t see what is causing the alarm. The fluid level is OK and the chiller was not disconnected during the move, so the alarm is a little puzzling. 

It was very late when we completed this move, so I was too tired to do anything more tonight and I doubt that I can get back into DoES on Friday, so I would appreciate it if someone can check this in the morning to see if this is still an issue.

**Comment by magman2112** [comment]
I was able to look at this on Saturday and found that the pipes from the chiller to to laser along with the flow switch in the laser were blocked with some organic growth. This was stopping the flow of coolant and causing the flow switch in the chiller to alarm.

All of the affected items were cleaned and re-assembled and the flow was back to normal. I also added algicide to the coolant water when I re-filled the chiller, this should prevent this kind of blockage in the future.

I then tested the laser and extraction now works very well and the laser is cutting well also.
