### ISSUE TITLE
Apply waterproof varnish to the bookcase and tables from Urban Workbench 

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1708]
These are unfinished and will absorb water and buckle.
Somebody should apply a layer of waterproof varnish e.g polyurethane, preferably with an unobtrusive matte finish

**Comment by JackiePease** [comment]
Nalini has identified the following items:

Here's the link for the varnish:
https://www.screwfix.com/p/ronseal-interior-varnish-satin-clear-750ml/551ht

https://www.screwfix.com/p/no-nonsense-quick-dry-varnish-satin-clear-750ml/30824

https://www.screwfix.com/p/ronseal-interior-varnish-matt-clear-750ml/859ht

Here's the link for the foam roller sleeves that we need that don't leave brush marks and are small enough to do the legs and details of the table:

https://www.screwfix.com/p/no-nonsense-4-gloss-roller-sleeves-multipurpose-4-x-5-pack/2637v

We will also need a dust sheet or a drop sheet to protect the carpet and also sand paper.

Thank you

Nalini

**Comment by JackiePease** [comment]
@magman2112 is going to bring in dust sheet on Wednesday and investigate varnish we have used previously (Johnson's) - varnish needs to be matt or satin, and clear.

**Comment by magman2112** [comment]
The varnish we have used before is Osmo Polyx Satin:-

https://www.duluxdecoratorcentre.co.uk/woodcare/osmo-polyx-hard-wax-oil-satin-clear?returnurl=%2fsearch%3fq%3dosmo%26count%3d18

This is obviously more expensive than the Screwfix alternative, (was this Screwfix varnish what we used for the floors in DoES though?), but you can go and look at the desks downstairs if you ask Paul nicely, these desks were painted well over a year ago.

if you do decide to go the Osmo route, I can pick some up on my way into DoES if needed. Hopefully this will be on Wednesday morning, depending on what the issue is with my car.

**Comment by magman2112** [comment]
Sorry for the delays in bringing in the dust sheet, but car problems and now what appears to be a dose of flu (thankfully not COVID, I just tested myself), have got in the way.

I’m going to get on the lemsip’s and see if I can break the back of this flu dose. If I can, I plan to visit my brother tomorrow in the Royal hospital, so can hopefully drop things off then, otherwise it will be for the Repair Cafè on Sunday.

**Comment by JackiePease** [comment]
@magman2112 has brought in the dust sheet and trestles, which are by the bookcase.
I asked Urban Workbench what finish they recommended. They suggested Holzöl Worktop oil, applied with rags, lightly sanding the surface first and between layers (they provided sandpaper).
I ordered the oil and it is with the sandpaper, on the bookcase.
Nalini and Nikki are going to apply the oil in the next couple of weeks.

**Comment by JackiePease** [comment]
Nalini and @NikkiHiggins have applied one layer of oil to the tables.

**Comment by JackiePease** [comment]
Closing this, as the tables and chairs have been passed on, and the bookcase shouldn't be at too much risk from water damage. We might need to reopen the issue if we decide to use the bookcase for plants in the future.
