### ISSUE TITLE
New office desks

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1755]
Where @Sean-anotherone works is getting rid of some desks, and we figured it would be good to replace the banks of desks in Room 29 so they all match.

The desks are like this:

![image](https://user-images.githubusercontent.com/108468/212291226-1c01ec8e-e396-419e-adc3-422b2aa53e55.png)

There are also some chairs too, so we'll be able to replace some of the assorted in-various-states-of-malfunctioning wheelie chairs :grinning: 

We'll need to arrange collecting them - not sure exactly when, but in the next few weeks IIRC - and then arrange assembling them, etc.

They've got more than we'll need, but we have to take all or none, so there'll be some spare (and the old desks we're replacing) if anyone wants a new desk for themselves (in exchange for a bit of manual labour :wink:)

**Comment by Sean-anotherone** [comment]
I did not have a measure to hand, but by estimating using a sheet of A4 paper (297mm) these are 2M by 74cm, and are about 75cm high.
They don't seem to need any bolts to assemble them as there are twist-locks that attach the legs to the base.

A good many have now been removed from the building, but final permission for them to be donated is still awaited.  The good news is that they are stored in the basement rather than being thrown into a skip, so still looking good.

The less good news is that while I can arrange pretty-cheap transport to the front door, it will be an all-hands-on-deck call to get them upstairs, and they're not light.  I'd suggest it will be one desktop between two for each trip, then a pair of legs or a cross-rail singly, i.e. for 20+ desks there will be about 80 trips up/down the stairs :(

**Comment by Sean-anotherone** [comment]
Another update.....

The joys !  The last person who is in the loop to give final approval, the representative of the building owner, has gone on leave for 3 weeks, the final go-ahead now cannot be granted before mid February.

**Comment by johnmckerrell** [comment]
I heard a rumour this was unlikely to go ahead now, is that true?

**Comment by JackiePease** [comment]
Seems this was stopped by red tape
