### ISSUE TITLE
Extraction in the laser-cutter room

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1764]
It seems there's a problem with the extraction in the laser-cutter room.  I did a small cut on Friday and the extraction didn't seem great - the room seems full of smoke right now (the windows have been opened now)

I think there was some talk a few weeks back about some problem with it outside the building?  Is that the case?  Was that fixed?  I can't see anything on here about it.

Is it just that the extractor fan needs its regular vacuuming-out?

/cc @DoESLiverpool/laser-maintenance

**Comment by JackiePease** [comment]
@magman2112 did clean the extraction pipe a few weeks ago using the cable puller (the day after January maker day?). It didn't completely resolve the problem and it does seem to be getting worse again. We probably would need access to the roof to investigate further - I'm not sure if @magman2112 has arranged anything already.
Vacuuming-out the extractor fan might improve things a bit.

**Comment by Tactile-electronics** [comment]
I used Tony yesterday to cut some ply  and the smoke was coming out of side of the cutter.  I swapped to use Gerald instead and had no further issues.  So it seems that the issue is with Tony or that section of the extraction.

**Comment by FatihDeveci** [comment]
As a regular laser user, I can confirm that Tony's fume extraction is extremely inefficient. The fact that a single extractor is connected to 3 lasers already creates a fume extraction performance degradation in all lasers. However, Tony's fume extraction performance has been much lower than the others from the beginning. Fume leaks from the left side of the machine during cutting and waiting 2 minutes after cutting does not solve the problem.

In my opinion, there is a need for a more powerful extractor or more than one extractor. Because the fume extraction system has been very insufficient since the very beginning. The smoke in the laser room creates an unhealthy situation for all workspace users, not just those in the laser room.

**Comment by magman2112** [comment]
I have contacted the landlord to enquire about access to the Fashion Hub roof. There are builders working in there at present, so they can give access during working hours, so I plan to come in to DoES one work week next week with a folding ladder, to see if I can resolve this issue.

**Comment by JackiePease** [comment]
@magman2112 has access to the roof for Tuesday morning. The extraction was so bad today that I couldn't finish my laser cutting. I've emailed the people who have booked on Monday and Tuesday am to cancel.

**Comment by magman2112** [comment]
I have now got access to the roof and the vent cap was virtually fully blocked. 

![IMG_0831](https://user-images.githubusercontent.com/37077154/234268596-a474f3ec-f1c5-4a4d-9495-d372b3be44e2.jpeg)

I brought the vent cap back in to DoES and gave it a good clean.

![IMG_0832](https://user-images.githubusercontent.com/37077154/234269286-24523cb7-966e-4bf7-beb7-1993a16d43b3.jpeg)


To reduce the risk of this from happening again, I decided to remove some metal between the holes to make bigger gaps whilst still keeping a good degree of structural strength.

![IMG_0833](https://user-images.githubusercontent.com/37077154/234270529-a8ae0383-dc4d-4b6e-9cd1-a7be2684f520.jpeg)

With some help from Andy Green, I re-installed the cap, also removing some of the debris inside the vent pipe. Subsequent test laser cuts showed no further issues with the extraction system.
