### ISSUE TITLE
Prints Adam (3D printer) Needs new piece (bowden tube white clip thingy) As I broke it, sorry.

### ISSUE THREAD

**Issue by Mmss12345** [DoESLiverpool/somebody-should#1798]
Hi, I apologise as I broke a piece that holds the tube to the print head area. Also it looks like part of the piece has fallen inside, and would need removing before new prints I assume.

I am really sorry for the inconvenience and I am willing to pay the cost of it etc. Also please let me know if there is anything i could do at all, as it was my fault. 

Please contact me to let me know what to do next. Thanks.

14/04/2023

<img width="557" alt="image" src="https://user-images.githubusercontent.com/130775816/232083979-f0465c17-5ecd-4996-8cc5-726de4588490.png">

<img width="556" alt="image" src="https://user-images.githubusercontent.com/130775816/232084391-a75537c1-2733-4397-a6c9-bd94732e6b3b.png">

Below in the two images you can see the white piece stuck:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/130775816/232084739-da1c1314-2ac1-49b8-bf5f-6a67ab1ee9ce.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/130775816/232086070-0d03a12d-e636-4e10-ad7e-c7e6b13d9065.png">

**Comment by huffeec** [comment]
Replacement collets are available on eBay for a couple of pounds [Collet for um2](https://www.ebay.co.uk/itm/225231929170) I've ordered one.

Until it is delivered we could swap out the collet from Felicity, it's not getting used at the moment because the nozzle isn't in great condition. I'm happy to look at this at the hack the space day on Sunday. 

While we are maintaining these machines there is also a case for upgrading the hot end on Felicity with an [Olson block](https://uk.rs-online.com/web/p/3d-printer-parts/1101981) so it'd have replaceable nozzles.

Alternatively, and much more expensively, we could look at the upgrade kit to convert one of the 2 series machines to a 2+ and use the collet and olsen block we have in the other machine.
[Extrusion upgrade kit](https://marketplace.createeducation.com/product/extrusion-upgrade-kit/)

**Comment by RussCoty** [comment]
This collet has been causing issues for a long time, particularly with new users who seem to get jams regularly.

**Comment by JackiePease** [comment]
The Olsen block would be good - we know it works and makes things easier long term.

I'd love a geared feeder too but the upgrade is quite expensive and we might be better off finding out all the features people like (speed, multimaterial, etc.) and aiming to get a new generation printer. Maybe a pledge drive?

**Comment by amcewen** [comment]
Thanks for reporting it @Mmss12345, I've sent you an invite to join the @DoESLiverpool organisation too, so you can add labels, and fix other issues, etc. :grin: 

Thanks for ordering the replacement @huffeec.

Do the geared feeders make a the prints lots better then?  Has anyone got experience with a 2+ to say/show how much better the prints are?

**Comment by huffeec** [comment]
I've replaced the plastic piece with the one from Felicity. This machine is working again.

The 3d printed parts of the head are not in great condition, so if we decided to go with the Olson block approach we will need to reprint them.

**Comment by huffeec** [comment]
Closing as fixed 
Opened #1813 for the discussion on ongoing upgrades and #1814 for short term maintenance
