### ISSUE TITLE
Tony out of square

### ISSUE THREAD

**Issue by RussCoty** [DoESLiverpool/somebody-should#1801]
Tony was out of square again on sat night. Quite significantly. 

I left a note but have been delayed in getting the issue posted.

**Comment by Sean-anotherone** [comment]
I fixed in on Sunday, was cutting within 0.5mm on a 250mm square.  

This is normally caused when someone tries to manually move the beam while the machine is energised - the servos ramp up the power to hold position and the bar that keeps the upper and lower z bents in synch slips at the front end.

**Comment by amcewen** [comment]
Presumably this can be closed then, if it's fixed?
