### ISSUE TITLE
Restrict ability to edit wiki to organisation members only.

### ISSUE THREAD

**Issue by 5CR1P7-K177Y** [DoESLiverpool/somebody-should#1818]
Attended Maker Night on Thursday the 4th, and had a go at using the CR-6 Marcus. Came across an issue where prints with filenames exceeding a certain character length didn't show up, I was encouraged by one of the members to document this on the relevant wiki page.

Being completely new and unaware of the formal process in place, I edited the page directly and without first raising the issue; I was successful.

The change I made can be found on line 78.

**Comment by 5CR1P7-K177Y** [comment]
Currently ***cannot*** add labels to this issue, as I don't have triage access to this repository.

**Comment by RussCoty** [comment]
Nice to meet you yesterday. Dice looked great. 

I'm not sure who is best to deal with this issue.

The Marcus thing is interesting I wonder if that is a FAT issue or a MAX_PATH thing.

**Comment by 5CR1P7-K177Y** [comment]
Thanks! It was great meeting people, very welcoming.

With a quick look, I found a [forum post](https://community.ultimaker.com/topic/28272-cr-x-gcode-files-not-displaying-on-printer-fix/?do=findComment&comment=275649) that confirms this is actually an issue with certain printers.

According to [github documentation](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis), the default option for editing permissions is usually set to collaborators only.

**Comment by johnmckerrell** [comment]
Given that we've identified it as a problem that you have to sign up for GitHub to add issues I think it's probably ok if non-members can edit the wiki, makes it easier for people to help us (as you did, thanks!) I've often thought it would be good to get notifications of edits though so that you could keep an eye on things and it turns out that you can follow an RSS feed for edits: https://github.com/DoESLiverpool/somebody-should/wiki.atom

I've added you as a member of the organisation now so you should be able to add labels to this issue now although I'd suggest it could actually be closed if we're happy with people editing things so long as we can monitor the updates.

**Comment by johnmckerrell** [comment]
I'm going to close this issue now, I've had the atom feed in my RSS reader for a while and have seen edits come through. One complaint I would have is that it shows you the entire page that was edited rather than just the changes so you'd need to read the whole page to know if someone had done some subtle manipulation, but it should at least make me/us aware of outright vandalism quite quickly and with git it's easy enough to reverse that.
