### ISSUE TITLE
CR-6 Max not extruding

### ISSUE THREAD

**Issue by dxlp** [DoESLiverpool/somebody-should#1840]
On Thursday, 13/07/23, I swapped the filament to white PLA. It seems to extrude fine at 240°C but can't print PLA at 210°C. The only thing I think it could be is the hotend thermistor misreporting the temperature.

**Comment by JackiePease** [comment]
@Sean-anotherone did this:
"Stripped and cleared out the extruder, large chunk of pancaked material was inside.  Replaced nozzle and reseated the heatbreak tube against it firmly.  Reassembled, ran the auto-levelling and set a benchy printing, which at 20% was still going strong and printing very well

I suspect this was caused by a combination of factors:
1. The heatbreak had unscrewed a little from the nozzle, so there was a gap for a pancake to form, and
2. the switch from PETG to PLA had left some garbage in the heatblock and nozzle, which allowed the PLA to pile-up and pancake

Suggestion - only print with PLA unless you are confident to repeat the above procedure!"
