### ISSUE TITLE
Move into our temporary space

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1849]
We have arranged access to the ground level space in the yard of the Tapestry Building that we can use as a mini-makerspace while the lift is out of action (in issue #1833). This issue is to be used for planning the move.

Main access to the space would be from Constance Street. There is a large shutter which needs to be raised for wheelchair access but there's also a smaller shutter that can be used if you can manage a step. It will also be possible to use the fire escape to access it from DoES although we need to be aware of a problem with the render on the wall above the fire escape.

The space was previously Melodic Distractions's bar & cafe. For now the actual bar area won't be available to us but there's enough space within the "conservatory" to be useful. We have to keep anything that could be a fire risk, e.g. laser cutters or 3D printers, around 2m away from the fire escape. To do this we'll put them in a corner next to the bar area.

There will be keys within DoES that can be used to open the doors and the shutters. We'll need to work out how these are managed but as it's attached to DoES hopefully it will be easier.

We need to decide what we're taking, a list follows, this can be discussed in comments then updated here once decisions are made, checked boxes mean they've been moved:
 * [x] Fridge (the spare white one that is currently by the front door)
 * [x] Small laser cutter
 * [x] Laser cutter filter
 * [x] Some desks (tbd which)
 * [ ] A printer (if we have one spare)
 * [x] Some chairs (maybe best if stackable)
 * [ ] Heat source (e.g. oil filled radiators)
 * [ ] Cupboard to store paper, some laser materials etc.
 * [x] 3D printer?
 * [ ] Sewing machine / overlocker? (Could just be moved down when needed)
 * [x] Kettle
 * ...

Subtasks:
 - [ ] Create a plan of the space
 - [ ] Decide what we're taking
 - [ ] Decide how we arrange access
 - [x] Confirm insurance requirements
 - [x] Sign agreement
 - [x] Move in

**Comment by johnmckerrell** [comment]
I've just updated this to reflect a new plan which involves using the space that was previously occupied by Melodic Distraction, who have sadly gone out of business. See the main description but for those following on email I've updated it with the following:

We have arranged access to the ground level space in the yard of the Tapestry Building that we can use as a mini-makerspace while the lift is out of action (in issue #1833). This issue is to be used for planning the move.

Main access to the space would be from Constance Street. There is a large shutter which needs to be raised for wheelchair access but there's also a smaller shutter that can be used if you can manage a step. It will also be possible to use the fire escape to access it from DoES although we need to be aware of a problem with the render on the wall above the fire escape.

The space was previously Melodic Distractions's bar & cafe. For now the actual bar area won't be available to us but there's enough space within the "conservatory" to be useful. We have to keep anything that could be a fire risk, e.g. laser cutters or 3D printers, around 2m away from the fire escape. To do this we'll put them in a corner next to the bar area.

There will be keys within DoES that can be used to open the doors and the shutters. We'll need to work out how these are managed but as it's attached to DoES hopefully it will be easier.

**Comment by JackiePease** [comment]
Having spoken to @huffeec today, who felt that this wasn't a useful space for @Robotorium as what she wanted was to interact with other users rather than needing access to specific equipment, I realised this could do with an update. 

So far the space has mainly been used by laser cutter and 3D printer users who wouldn't have had issues with getting to the main space. They seem to be generally happy with the space, as it gives them more room to work, and to not mind having to go round the outside of the building to let themselves in (although I have a set of keys, I haven't always got in early enough to open the shutter before work).

As far as I know, @Robotorium has used the space on one maker night and on a Saturday afternoon and nobody else with accessibility needs has used it as yet (@cheapjack did mention bringing some people from Winsford, before the lift was broken).

It is possible that the lift will be fixed relatively soon but things that might help if people think they are worth it are:

- Moving more equipment down, so people use the space more
- Checking that we can use the oil-filled radiator safely (#1876) or buying/borrowing other efficient heaters
- Moving the handle mechanism from the door behind the laser cutter to the door leading to the fire escape (Joe suggested this might be possible)
- Publicising the fact that we have a temporary space

**Comment by Robotorium** [comment]
This is a very odd thread.

I'm fine with things as they are, it's probably best not to ask Chris silly
questions when he's at work, and in future please ask me about myself,
thank you.

Op di 31 okt. 2023 18:17 schreef Jackie Pease ***@***.***>:

**Comment by huffeec** [comment]
The lift is fixed and we no longer have this space so closing.

**Comment by JackiePease** [comment]
We just need to move a couple of things out - maybe we can do that at today's Maker Night

**Comment by johnmckerrell** [comment]
This space has re-opened as a bar so I'm pretty sure we won't have anything there any more!
