### ISSUE TITLE
Doorbot2 (entrance to main room) not working consistently

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1866]
Doorbot2 (entrance to main room) is slow and/or requiring multiple taps before releasing the door lock.

I have tried rebooting it and reseating the board, but this hasn't made any difference.

**Comment by johnmckerrell** [comment]
This seems to have been a reoccurrence of this issue: https://github.com/DoESLiverpool/logcards/issues/15

I've tweaked the yaml file and restarted the doorbot and it seems to be working now. I've also updated the IP address so that it is now the correct IP address after the Pi was changed recently. I haven't fixed the underlying problem.

Also worth noting that it did seem that it would work if you just held the fob for long enough, so we can try that in the future if it reoccurs.
