### ISSUE TITLE
The website could look much nicer

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#19]
We'd like to update the website, so it does a better job of telling new visitors what we are, and also looks much nicer.

(When we're doing a refresh anyway, it might be a good point to move it onto some hosting that DoES owns - as outlined in issue #18).

- [ ] List what content we have already that needs to move to the new site
- [x] List the "customer journeys" we expect it to satisfy - e.g. new arrival wanting to maybe hot-desk; new arrival wanting to 3D print; existing user needing to book laser-cutter; community member looking to see what events are on;...
- [ ] Draw up a list of similar websites to use as inspiration

From that then prepping a list of features/pages/etc. that we need (the requirements), which can be used by the developer and designer to create the site.

**Comment by amcewen** [comment]
Should issue #91 go in the requirements list for the website?

It doesn't *have* to live at status.doesliverpool.com, but should be at an easy to remember URL, and could be on the main site somewhere.  However, status.doesliverpool.com would let it sit on different hosting and allow notification of whether http://doesliverpool.com was up or not, in the future... :-s

**Comment by zarino** [comment]
@amcewen – Looks to me like #91 is a separate ticket. This one is already overly broad, I wouldn't want to add yet more considerations into it. The status page can be thought about completely separately, no?

**Comment by amcewen** [comment]
@DoESsean to audit our existing site(s) to build a list of pages, etc.  Then we can have a meeting to work out what we still need, and we'll (I expect) generate a list of additional requirements too (at least to get us moving on it)

**Comment by jamieisboss** [comment]
@amcewen Nothing happened on this for a long time so I did a bunch of it one day and took photos, I'll finish it soon and then you can not like it and iterate or whatever until you do but you might as well assign this one to me for the time being

**Comment by madjake45** [comment]
Turns out, I can't assign you for some reason

**Comment by amcewen** [comment]
I think it's because @jamieisboss isn't a member of the @DoESLiverpool organisation - yet.  I've just sent him an invite, so assuming he accepts then we'll be able to assign it to him :-)

**Comment by jamieisboss** [comment]
Hi

**Comment by jamieisboss** [comment]
Ok, so i have a half done wordpress site somewhere but as decided in #273, it's unneeded overhead, so will use the design, rip out the WP bits and change with a view to being auto-regen html pages.

@amcewen did you take a look at those photos yet? Any that you specifically don't want used? Also i think you said you were getting some back from that photo thing  while ago, did you? if so can you pls give me access somehow, removing any you don't want used from the share, and if there's loads, and people like some in particular, you pick 5 now then we can set up some more fair system for people to vote if anyone wants to have a say. 

Half the time you end up needing text where the detail is and stuff so it's usually better to get a version going so people can see the restricting factors, then iterate with input that's already been refined by the person inputting IM(nv)HO 

I'm going to find that cloud thread to see if the answers o my questions are there before i ask tthem

**Comment by amcewen** [comment]
Have sent the ones the LEP took over to you, and forwarded the email about the ones you took to the rest of the organisers (they look pretty good to me, and we can always complain about ones you pick and suggest alternatives once they're on a website ;-)

**Comment by jamieisboss** [comment]
Ok cool, I'll  go for it then and once there's something sans-wordpress, (i can't remember what i got up to, it's probably be better to start fresh anyway, there's new stuff since I started it.) 

I'll pop a staging server somewhere for a few rounds of picking at it before it goes live.  

I dont know if there's any copy people about who would want to get involved with the creation of a few alluring passages or who'd be alright with goin  o'er what i write. My copy is usually pretty good for a muggle but of all the things that I'm good at, copy is somewhere in he middle, so if anything was going to benefit to benefit from a professional touch, words is it.

**Comment by ReddbridgeMark** [comment]
Happy to help out with a copy-edit. Bang down what you want to say, and, subject to any additional guidance as to what you want, I can shape it/make suggestions for it.

**Comment by jamieisboss** [comment]
@ReddbridgeMark Awesome, will let you know when there's something for you to look at.

@amcewen A broader marketing type question. (And maybe a bit
 more difficult to answer unless the organisers have already discussed it, because really it should be consistent throughout all the outward facing communication) is there a voice that you guys have in mind for DoES. [I found a decent article explaining so i dont try](https://uxmag.com/articles/tone-and-voice-showing-your-users-that-you-care) and we're on the same page with the definintion. 

Personally I've always thought the secret acronym and the Days since last explosion sign (accurate as it is) and other little touches make the place feel personal and able to be funny in an introspective way. (and for this bit, I'd also met a few of you before DoES was born, so I cant use myself as an example anyway) That's all real world stuff though so ideally, we want to mirror the real word feeling as much as possible in/on anything  that is meant to be attracting people to DoES. Doing so should minimise wasted time and maximise conversions, or to not sound like a Salesperson, people feeling what they expected to feel on their first visit means they'll probably join or they wouldn't have bothered coming.

**Comment by madjake45** [comment]
The only issue I see with moving away from wordpress is that we will either have to import all the old blog posts or keep an old version of the site

**Comment by jamieisboss** [comment]
Thats not an issue, im guessing the weekenotes thing generates a blog post then, you can export them all from the backened as json anyway, or use the new API to pull them across. No neeed to worry about that stuff, I'll have the new site running in a staging environment before we switch so any/everyone can check it's all alright, and I'll keep the old one running with the name changed for a few weeks after the switchover ideally so a rollback will be a DNS change and 2 wordpress database fields (if we put you on cloudflare, that stops th 48hour dns propogation thing so would be useful here, should be discussed but ive started a [new repo for the website](https://github.com/DoESLiverpool/Public-Website) as of 30 mins ago so these things can be seperated out into their own issues list)

**Comment by madjake45** [comment]
I will also need an api that I can ping so that the status system can ddetect if it is offline

**Comment by jamieisboss** [comment]
it'll be a static html site fro the user perspective so just getting a couple of pages return 200 would be ok id have thought; unless you say otherwise in which case let me know what you need. From the other side some extra tests would fire after any generators run as part of the generation process? Would that be cool?

**Comment by madjake45** [comment]
If it's going to be a static site wouldn't something on [github pages using jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) be a smart idea then?

**Comment by jamieisboss** [comment]
It would, but I don't know if the concept can be implemented in jekyll alone, I don't know it particularly well, though I've not heard anything negative about it so I assume it's pretty good   I'll explain what I've been thinking in a sec,  plus,  in usual transparency,  wordpress would have been easy,  but if we weren't doing that,  which I still agree with for speed (and adding that Google AMP),  I wanted to do some stuff in systems that I've wanted to work on for a while so I can get one under my belt for the future,  until a couple of days ago I thinking to use aws, (s3, lambda, cloudfront, etc)  But after all the new firebase features were announced,  that seems like an equally important technology which supports the breif,  so I don't really want to do it that way given my current knowledge ,  but I'd like to have some more knowledge and that could well pull me into full agreement,  I'll have a look at the Jekyll docs,  but I'd like to also  open this back up a bit and check I'm still going in the right direction,  and that no one else is wanting in on the site design and build,  because I probably would have just started ploughing through it sometime soon,  as it seemed quite settled, I thought I might be rocking the boat with the idea outlined below,  but maybe I'm not,  or I'm not enough @amcewen 

Where I'm coming from:  The breif was that this new site was meant to be a separation of concern.  Moving away from focusing on existing members, as ~~better solutions like~~ everyone was using  github anyway.  

The  plan then was to use the freed up  'purpose space'  on the  main  site to market DoES  in a more approachable way * which allows for a more welcoming onboarding,  after giving them time and answers,  and whatever else the data would show demand for,  guiding visitors to the information or whatever content they were looking for,  then continuing to shape the site to match the successful inbound search terms and social media referrals to ensure that the site was providing the right information, encouragement and feeling to move from the website to a maker day/night  or a cake  hotdesk day.  Originally the idea was to stay with wordpress,  but it seemed to be unnecessary bloat when most of the content is pulled,  embedded or autogenerated to use wordpress where we'd be undoing it's core functions anyway,  hence the whovian-static idea,  serving static  content that was regenerated in response to a range of different events (or the appearance of Karen Gillen) 

_*(as the feeling of needing to already belong was repeated in the feedback I got about the existing site when I asked some people a while back (scientific I know) ,  it's also the feedback I hear most about the space after people visit, usually something like " everyone seems lovely and it was fun,  but... [I don't feel like I  know enough] | [I don't know know what I'd do after the thing I'm thinking about now] | [Everyone seems to know about this stuff, how would I learn? ] ". 

Perhaps a look at how onboarding members could counter some of these things would be beneficial? I have only seen a heavily biased sample and have no idea how many visitors convert so Im only commenting on the off chance that it's a good idea, because I don't actually have a clue and I'm aware of that.  )_

Anyhoo,  To that end, I was thinking  for the site to change regularly ,  but for those changes to  be almost  entirely data driven (from referral,  search term,  advert {I know but it works with ssl and you only need a bit to get a ratio then you can jib it off }   plus reported local search volume for key terms and feedback,  Maybe also twitter if there's anything useful there  }  not necessarily taking into account anything other than machine guided effectiveness and some proof reading'.  Potentially even automated split tests with victory conditions cycling  nightly or faster to adapt to changing trends

For all that,  I really wanted to use aws and lambda,  service workers,  geolocation,  visitor identification and any other cool things that could alter the site to mould it to the user, eventually leading them to the community here (or perhaps away to somewhere more appropriate if they aren't looking for a DoES right now)  when they have had their 7ish  comfort interactions with the website, which I think I've now made sound like a  like a machine learning powered personal seduction engine (which as a marketer,  sounds just about perfect. As a human,  mildly terrifying, but if it becomes self aware,  I think it'll just travel through time seducing it's way through history until it eventually creates  itself 😉  )  So this idea has been bubbling for some time,  but no one asked until now so I hadn't wanted to commit to this until I was more sure it was achievable  in the time I have coming up to do it in. 

Firebase is a bit 'spanner in the works' after I/O  because of the integration with analytics/adwords and the expanded free tier,  plus the whole realtime concept could facilitate a very dynamic type of static site but I haven't played with that since the IO changes so I was going to try and do that before someone said this,  but I apparently haven't checked github for a few days and you've beaten me to it 

However,  I need to start planning things soon,  so either I've just convinced you,  or you've mentally been countering my points,  and I'm about  learn that jekyll or something else completely that you know about that's a better fit is pretty freakin sweet. 

Second however  it's been said so many times now about different systems; I need to know if it's going to be policy of some sort that no 3rd party soley manages a service that something of DoES ' lives on as it will  be a design constraint if that's the case,  probably not a problem one,  but one to be taken into account when planning.  

From my perspective, the website was something that no-one particularly wanted to manage or jumped on whenever this process  started,  so I tried to come up with  a concept that did a similar thing for advertising as the site does for content now,  but github seems to be much better at getting people interested,  which is cool,  but should I change my underlying assumptions and the concept built on them, dialling back the automation aspects,  or are people concerned about certain specifics which I should account for? Or something else?

**Comment by zarino** [comment]
@jamieisboss – Eeek, starting to sound quite complex. Maybe before you jump into a big project like this, we should make sure we're solving the right problems? It would be a shame for you to build something nobody uses!

My suggestion would be for someone to talk to the DoES organisers, members, and visitors, find out what they like and don't like about the current site, and use that information to draw up some quick personas / user needs documents. Then you've got something concrete to base your improvements on, and you can make sure you don't spend time implementing features nobody needs.

You might be surprised to find that most people's requirements can actually be met by just a super simple site with some well crafted copy and a clear layout. Or the research might point at something more complex, in which case, great, at least you've now got some clear user needs to base it on.

Anyway, if you think some user stories like this might be useful, but none of the DoES regulars want to conduct them, I can do them for you. Just let me know. It'd probably take a week or two.

**Comment by jamieisboss** [comment]
>Anyway, if you think some user stories like this might be useful, but none of the DoES regulars want to conduct them, I can do them for you. Just let me know. It'd probably take a week or two.

@zarino That would be awesome thank you, i was a bit tired writing my last response and jumped in a bit heavy and at the wrong end, worry not; Simple, clear and good copy (and good images!) are the starting point from which here might not be a reason to go anywhere. The Rest is just me wanting to make something clever, but that comes last, sometimes never at all. :innocent: 

> My suggestion would be for someone to talk to the DoES organisers, members, and visitors, find out what they like and don't like about the current site, and use that information to draw up some quick personas / user needs documents. Then you've got something concrete to base your improvements on, and you can make sure you don't spend time implementing features nobody needs.

This i did but there's a lack of consistency in that everyone wants different stuff, or not to change anything, or less stuff, or doesn't care. Though that was a while ago, with the github quicksand, it will almost definitely be worth re-vistitng this now the site isn't the only option for a lot of things. 

Next then:

- [ ] Gather Simple Feedback about existing site from known users

(but they aren't the target any more so also:)

- [ ] Gather feedback through the existing site from a sample of visitors who aren't members, 

- maybe a simple dismissable panel with a few questions, 

- and some heatmap stuff with analytics analysis to check that they know what they do and manage what they try

**Comment by amcewen** [comment]
@zarino: If you could do some user stories that would be fantastic.

@jamieisboss: that sounds like either (a) an attempt to use every web service from AWS all at once or (b) a completely different startup all of its own.  Or probably both of those things :-D  We'll have a better idea once we've got some user stories, but my gut feel is that @zarino's right and a simple clear site will probably meet our requirements.

And if the user stories are written down somewhere (maybe that's what we missed when - as you say - you asked around about what was wanted) that will effectively form a spec for what's wanted (and is easier for people to argue with/suggest additions to)

**Comment by goatchurchprime** [comment]
Nothing left on wordpress site except the weeknotes, some deep-links from the menubar into the wiki

**Comment by DefProc** [comment]
Probably worth keeping this open, as the website is still running on a basic theme. So the original issue is still valid.

**Comment by zarino** [comment]
The new main nav—especially with that “Services” menu—is so much better! Well done everyone involved!

**Comment by DefProc** [comment]
I think the biggest improvement we could make in the short term would be to have a better overview of the services that DoES offers. As there is currently a menu item, but no page, a services page with some kind of table breakdown listing services, cost and benefits would be easier for a new viewer to see what we offer them, and what it costs. 

e.g. things like: 

 * Maker Night (free)
 * Maker Day (free)
 * evening events (normally free to attend)
 * Friends of DoES £9
 * Friends with benefits £15
 * Hotdesking £10/£5
 * Monthly Workshop access £50
 * Monthly desk rate £150

**Comment by goatchurchprime** [comment]
Done that:  https://github.com/DoESLiverpool/wiki/wiki/Membership-and-access#rates

**Comment by goatchurchprime** [comment]
Perhaps we could close this and replace it with a slightly more closable ticket -- ie one that can be satisfied.

Now that all the changeable content is moved to the github wiki (where folks can efficiently self-manage their accounts and therefore do stuff), the wordpress page is only holding deep-links to the github wiki and the weeknotes.  

Do we want to specifically improve the decoration and banners on the wordpress page with a photo or something?  Do we want to fiddle with the layout and decoration on particular core pages on the github wiki?  Either of these (or both) would define a ticket that's a bit more soluble and has a greater likelihood of getting closed.

**Comment by DefProc** [comment]
@goatchurchprime I've reverted some of the wiki links for the website, specifically dropping the [Membership and Access](https://github.com/DoESLiverpool/wiki/wiki/Membership-and-access) link because it's a page that does *everything-in-a-giant-page*, and separating out: 

 * Services — with a pricing table 
 * re-adding the laser calendars #459 
 * re-adding the google group link
 * removing "start here"
 * having **Location** as a root item
 * consolidating the other links under **Services**, **Events** and **Community** so there are just 4 top level headings.

**Comment by amcewen** [comment]
Organisers' meeting notes: There's an ongoing group looking at this and covered in the last meeting minutes.

**Comment by DoESsean** [comment]
Helen has agreed to help with the website. @amcewen or @johnmckerrell , can you please put her in touch with Will (as she's not sure who he is) and see if they can coordinate together?

**Comment by DefProc** [comment]
Update on this: 

We've got a working group on this consisting of: 

 * Helen, with experience on copy and marketing,
 * Will with backend and frontend website development experience, 
 * Sean who "gets stuff done around here" ,
 * Me, coz I did the last wordpress deployment, and can access all the hosting stuff.

The expected work will split into two parts: 

 1) revise the current website to make DoES offering more prominent, and explain where DoES is currently/will be located for prospective users. 
 2) A larger redesign to better present DoES through the website. 

We're creating a spec for the outcome at the moment, so are currently collecting input on features, recomendations and warnings, either below, or on the whiteboard in the main room. This is based there being two main user types for the website: 

 * People who haven't been in (or have only been a few times) to DoES who want to find out what DoES is, how it can help them and how they can get involved, 
 * More frequent DoES members who use the website as the starting point to get to DoES's more in depth resources.

**Comment by goatchurchprime** [comment]
Where is this document?  (Maybe on the wiki?) 

I've put some notes on the whiteboard, mostly about a really good "how to find us" printable page, and inlining feeds of events, twitter, issues, personal github commits and equipment status on the front page.  

Also, @paulfurley has tech for syndicating other events into the main feed.  
    https://github.com/DoESLiverpool/somebody-should/issues/573

Oh, and we should use Bret's plugin that dumps your websurfing history into a daily stream of links.  Use this feature whenever looking up technical stuff or searching for electronic sensors you're thinking of buying (or writing drivers for) to more easily get to know when someone is sizing up for an order.  

I'd like to be able to publish my RS shopping cart before I pay so other people can add stuff to it.

**Comment by DoESsean** [comment]
@willcrobinson and @Helen-8, any idea when you guys will be available to get together again?

I don't know if there has been any movement on the discussion we had last time - and we should probably include any notes that were made in this issue so that people can see where we're up to - but it might be worth seeing if we can fit something in before Christmas if you have chance, although I do appreciate that this is a busy time for everyone so that might not be possible.

**Comment by ajlennon** [comment]
Website looks lovely to me. Can we close this?

**Comment by zarino** [comment]
Yes! If there _are_ outstanding issues with the website, it’s much better to raise them as new tickets, than keep this old one open.
