### ISSUE TITLE
Sublimation printer needs ink

### ISSUE THREAD

**Issue by Robotorium** [DoESLiverpool/somebody-should#1925]
Please can we buy more ink for the sublimation printer? Ta <3

**Comment by DoESsean** [comment]
I've ordered these now from MDP - due in in a couple of days.

**Comment by Robotorium** [comment]
Thanks Seán!

Op do 18 jul. 2024 16:25 schreef Seán Gleeson ***@***.***>:

**Comment by DoESsean** [comment]
WE have a slight issue.

DPD (grrrrrr) have said they've delivered to our neighbour at Abbas, 71-73 (I assume Kempston Street, but it doesn't say that). This apparently happened at 8:56 on Friday.

However, there is no business called Abbas on the street (it could be the name of a person?), and 71 and 73 are separate entities (71 is the cafe, 73 the reception for the flats). There is no delivery photo.

I've been to 73, and they don't have a parcel for us. 71 isn't open, and I've never seen it open at that time. I'm about to call DPD.

**Comment by DoESsean** [comment]
DPD were about as useful as you'd expect (chocolate fireguard, etc). They've said that it's been delivered, _they_ can see the delivery image (it shows a parcel in a doorway. There's a person wearing jeans), and that, as it's been such a long time since delivery (two whole working days! Which, of course, wouldn't have mattered if they'd DELIVERED TO THE CORRECT BUILDING) there's nothing much they can do, and I'll have to get the seller to instigate an investigation.

So I've emailed MPD, apologised for us being forced to do admin for a much larger company that apparently can't do the one job it has, and asked them to do so. I'm feeling quite snippy.

**Comment by Robotorium** [comment]
More than reasonable :( thanks for chasing, Seán... Fingers crossed someone
at DPD is of medium competence.

Op di 23 jul. 2024 10:46 schreef Seán Gleeson ***@***.***>:

**Comment by DoESsean** [comment]
I have them! They're on my desk.

**Comment by Robotorium** [comment]
Thanks Seán!
