### ISSUE TITLE
Doorbell for the main space isn't working 

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1936]

**Comment by huffeec** [comment]
I think the battery is the same as the shuttter fobs from downstairs. If it is there are replacements in the basket of batteries.

**Comment by zarino** [comment]
Ah, a dying battery would explain the intermittent behaviour in https://github.com/DoESLiverpool/somebody-should/issues/1932 :+1:

**Comment by JackiePease** [comment]
@magman2112 found the batteries mentioned by @huffeec and has replaced the one in the door bell. However it's still only working intermittently. We should order a new one.

**Comment by JackiePease** [comment]
The bell seems to be consistently working at the moment. Will leave this open for the time being though.

**Comment by JackiePease** [comment]
There haven't been any further problems

**Comment by DoESsean** [comment]
Since this doorbell being out of action is an ongoing and regular problem, coupled with the fact that someone has unplugged the receiver and put it, erm, somewhere, we've ordered a new bell. It's due to arrive tomorrow.

https://www.amazon.co.uk/gp/product/B09GK4ZDXP/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by JackiePease** [comment]
I've installed the new bell, and it is working. I've just used the sticker to attach the new button. It seems to be secure, but if anyone would like to use screws as well, they're still on @DoESsean desk at the moment.
