### ISSUE TITLE
The gardening group box is aiming to escape

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#208]
The grape hyacinth (at least that's what it says on the label in the pot) in the gardening group box on the racking is making a bid for freedom.  It doesn't look particularly healthy, but is doing its best to grow :-)

**Comment by aubergine10** [comment]
This issue looks stale - can it be closed? If no follow-up comments by 1st May I will close this ticket.

**Comment by DoESsean** [comment]
Please don't delete this - it's a long term issue that we need to be
reminded of every now and again. If it's deleted, the likelihood is that it
will get forgotten completely.

**Comment by aubergine10** [comment]
I'm not convinced a pot plant merits a long-term github ticket, especially considering a) there have been no updates to this ticket since Oct 2015 and b) no solution has been proposed to the hyacinth predicament.

Maybe we could refactor this ticket to implement a long-term solution, for example: _Use a microcontroller and some sensors to monitor soil moisture and leaf RGB and have it tweet the plant status should things take a turn for the worse (eg. too much yellow or brown in the leaves, soil too wet or dry)?_ -- at least then there is a tangiable goal and clear exit to the ticket.

(I have an RGB sensor I can donate if anyone wants to work on this mini project?)

**Comment by DefProc** [comment]
And it's probably just worth checking if this plant from 2 years ago is still trying to get out of its box. If not (knowing how good DoES it's at watering plants) then it can be closed.
