### ISSUE TITLE
We should turn off comments on the blog

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#222]
Every now and then we get questions about the space - workshop facilities, booking desks, etc. - left as comments on some of the pages around the website.  They tend not to get noticed or dealt with very promptly (even by our standards :-)

I think we should turn off comments everywhere on the blog, to encourage people to email hello@... instead (and maybe check that it's easy to find the contact info too?)

**Comment by DefProc** [comment]
Agreed. I turned off comments on my blog too for similar reasons, and no one's left any complaints that they can't post since!

**Comment by DefProc** [comment]
Turned off

**Comment by jamieisboss** [comment]
I think commenting is good when done properly, presented in a usable way, secured and de-spammed and integrated with something like Slack so any comments are very visible and easily actionable. I'll think on some options (including leaving them off)  and put them in #19  to discuss

From experience commenting on pages is a recipe for everything you described but commenting on blog posts (or other types of content) can a good way to start a conversation or let people communicate to  group if they've attended a free event or similar.

The issue is usually in understanding the person's intent (i.e. do they really want to comment on the content or are they trying to find a way to ask a question or enquire) there are some cool new ways of managing this so i'll collate what i think is relevant

**Comment by DefProc** [comment]
I did find one page that had a load of comments on them, and have now turned that off, so we should be comments free. If we do move to discourse ( #306 ) then a discourse post is automatically created by wordpress through the wp-discourse plugin (already installed and tested) so we then would allow comments in the normal community forum.
