### ISSUE TITLE
Can we buy a better <insert kit list here>?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#247]
From the Organisers meeting - http://wiki.doesliverpool.com/DoESMeetingMinutes20151029

General discussion about how to decide what new kit to buy - with an initial suggestion of a better soldering iron.

Can we encourage more pledge drives, with DoES explicitly listing how much "match funding" it would provide?

Action: @DoESsean to kick off discussion about it on the google group, pointing people at the existing pledges page (on the new wiki)

**Comment by jamieisboss** [comment]
I mentioned this to @DoESsean near the end of one of the larger pledge drives last year but it was way too late to consider and I don't imagine it's been brought up since.  

Has running a campaign on a crowdfunding platform, been considered for raising extra money, the pledge rewards could be workshop memberships/ hotdesk days/permanent  desks etc. It would be easier to lump a lot of what would have been pledges into one larger upGradeDoES campaign but even the small reach that local campaigns usually have could be working as a marketing tool to attract new members as well as raising money for doing the ES

**Comment by amcewen** [comment]
Raising the money isn't the important bit, it's working out what we need to buy that's difficult.  

We did run a campaign (though not on a crowdfunding platform) for the laser upgrades, and I definitely think we'd do a kickstarter or indiegogo or similar campaign when we expand.  

As ever it's the "what's the money for?" question that's the stumbling block, not "how do we get the money?"

**Comment by jamieisboss** [comment]
Well thinking on this plus a bit of brain stewing and talking to Sean led to #248 so maybe that would be a starting point.

**Comment by johnmckerrell** [comment]
Notes from meeting 20160614 - @DoESsean to update and close this ticket.

**Comment by DoESsean** [comment]
The things listed in the Group thread are:

8x4 CNC Router;
Reflow Oven;
Pick and Place Machine;
Vacuum Chamber;
Lathe (CNC Lathe if such a thing exists)
