### ISSUE TITLE
Make pull up signs for exhibits

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#254]
It's just getting to the MakerFaire/MakeFest planning season (as some applications are currently open), so to have enough time to actually get something made and delivered before the first event (Aprilish). Should we have pull-up signs promoting DoES made to take to these kind of events (or to use in the background of hosted events)?

**Comment by amcewen** [comment]
What's better?  A pull-up board or a banner (maybe that we can easily attach to a tablecloth to put across the front of a stand?  Or both?  What are the design specs - sizes, etc. for them, so we can get someone to design them?

**Comment by euanwithersby** [comment]
I've done pull-up designs before and am happy to pitch in with this. Banners can be awkward, ok if you know what size of table you're going to have and are often below people's eyeline. Banners are great for a bit of finishing on a display table but key info should be on a pull up in my experience. Not sure on suppliers, I used to use PrintDesigns in Stafford but only because I could pick it up easily back in the day.

**Comment by amcewen** [comment]
This is what I like about the @DoESLiverpool community.  You can start chatting about something and someone comes along with some _actual_ experience :-D  I suppose the business cards would be a starting point for working out what the "key info" is...

**Comment by euanwithersby** [comment]
I knew the years of trailing display stands around shows wuld pay off at some point ;-) There's a whole range of options for display stuff. Although we don't need to use them specifically, PrintDesigns website is an interesting place to start for options - it often comes down to cost.

**Comment by DoESsean** [comment]
![doesliverpool-promobusinesscard](https://cloud.githubusercontent.com/assets/9075760/22106645/a6eae166-de41-11e6-9c10-09171d373667.png)

Current business card blurb

**Comment by euanwithersby** [comment]
Thanks Seán. I've had a look at local prices, either they don't publish or they're £75 - £125 from local companies or £39 +vat upwards online including PrintDesigns. There are new types of stands, tubular frame and fabric covers seem to be the new thing but are more expensive. Is there a set layout for the display? It would be useful to know how this would be used.

**Comment by DefProc** [comment]
We've normally had a single table with things on, adjacent to a 3m square gazebo that has made-invaders in. Sometimes with a blank backboard that Tosca runs on. 

Even when we haven't had made-invaders, the standard pitches and maker faires / make fests is 2 tables in a line with no back wall.

**Comment by shrkey** [comment]
Don't know if of interest, but we used these (below) for our narrow Bob pull up banner (primarily because we left it to the last minute and needed something quick) - it turned out very good.

http://www.ebay.co.uk/sch/knightprintltd/m.html?_nkw=&_armrs=1&_ipg=&_from=

**Comment by euanwithersby** [comment]
That's a good price! I'll look into it.

**Comment by DefProc** [comment]
I've had one from [standbanner.co.uk](https://www.standbanner.co.uk/banner-stands/pull-up-banner-display) — actually the 24hr version, delivered to the location I was travelling to!

**Comment by euanwithersby** [comment]
Some brief mockups attached. The first two demonstrate the issue of what happens when the information is spread down the banner - people just don't look at the bottom bit and you have to leave a bit that stays within the mechanism in my experience.
The third and fourth ones follow the principle of key info at the top and the rest towards the bottom. Variable data (i.e. prices and key contact info) should be on a flyer or card to take away.
As regards the pics, I have a reasonable camera and flash and know something about illuminating a room for photos, but if anyone is a keen photographer, so much the better. They will need to be posed and set up, I've often found that trying to reuse one is quite time consuming in adjusting it (unless it's of a unique event, of course).
[skapa-does-pullup-mockups.pdf](https://github.com/DoESLiverpool/somebody-should/files/717251/skapa-does-pullup-mockups.pdf)

**Comment by DefProc** [comment]
@Red-Violet is too lazy to log in under her own account: 

> Hello, had a look at the mock ups and really like the black background and white logo version. Can you make the logo much bigger so it fills the top and then have the info underneath? Keep it quite simple really. The business cards I did last time had "Work. Meet. Make". which came from what your working from and there is always the tag line "Do Epic Stuff" which could look cool in large letters with the logo underneath it with the online info. Maybe we don't need to put the address on it and so many website details, maybe just go with doesliverpool.com because you will get all that info from that link anyway so it doesn't need lots of repeating. The black background looks great very sleek and I would like to definitely keep that as a theme and focus on making the logo more prominent. :+1:

**Comment by euanwithersby** [comment]
Thanks for the feedback @Red-Violet, the black has the additional benefit of not getting grubby when being put up and down in less than clean conditions. I like the simplification of the wording and I've done some more mockups (attached). The only issue with enlarging the logo to fill the width is that it pretty much wipes everything else out as people take in the top half - two thirds (if they even see the banner at all!) particularly if it's behind a table. I've added three mockups at the end highlighting the three services as it may be useful to be able to shift the focus of the banner if you're at a particular event without losing the sense of the unique triad of services that DoES offers. All constructive feedback is welcomed!
[skapa-does-pullup-mockups-v2.pdf](https://github.com/DoESLiverpool/somebody-should/files/718987/skapa-does-pullup-mockups-v2.pdf)

**Comment by euanwithersby** [comment]
I've also left the twitter handle in as people may want to follow before committing themselves!

**Comment by Red-Violet** [comment]
Hello @euanwithersby I really like the version without the images on. We don't have any really great marketing images that can be used at that size. I have done a very quick idea, its not in the right font or size. I think maybe if we have the website across the top, the the large logo and the "WORK MEET MAKE" without the full stops. Its only to identify who we are rather than an advert and the business card has the extra information on anyway. Less is more I think.
[Workmeet make.pdf](https://github.com/DoESLiverpool/somebody-should/files/719607/Workmeet.make.pdf)

**Comment by euanwithersby** [comment]
I was only really using the image as a placeholder, I would take specific ones if need be. I agree that they would be more effective on a larger display and, after reading the style guide (at last), I've made some adjustments. The full image can't be used as unfortunately it pushes everything else down into the "unseen zone" but I think the half size is a good compromise. I've centre aligned things which I was reluctant to do before taking design cues from existing cards but, if there's been other stuff produced, no problemo! I've tried putting the URL at the top, but it unbalances the layout overall.  The colour is an approximation of the wall in Dinky, seems to be quite noticeable. I'm going for a single banner with the three services on initially, larger displays can be looked at once we've at least got something on the go.
[skapa-does-pullup-mockups-v3.pdf](https://github.com/DoESLiverpool/somebody-should/files/719976/skapa-does-pullup-mockups-v3.pdf)

**Comment by Red-Violet** [comment]
I have put some ideas together, very basic, along the line of my previous suggestion. I made them at approximately the size they would so I could see how much space there is. I have had a play with some coloured backgrounds and some different sizes of logos and wording just to give you a clear idea of what I mean (its always easier to draw it than use words :smile_cat:,). I hope that they might give you some other inspiration to try some other compositions or do something very different.

Its best to stick to one font, its usually the golden rule unless it is the main feature of the work. Have fun playing some more.

**Comment by johnmckerrell** [comment]
I've now ordered a banner using artwork supplied by @euanwithersby , pending proof checking it should be here early next week. Ordered from Knight Print mentioned above (eBay link)

**Comment by johnmckerrell** [comment]
Banner has arrived and looks great!

**Comment by amcewen** [comment]
Where is it stored?  Is that noted somewhere in the wiki so anyone going to an event knows where to find it (and where to return it to afterwards!)? :-)

**Comment by johnmckerrell** [comment]
Documented here: https://github.com/DoESLiverpool/wiki/wiki/Pull-up-banner

**Comment by stevesparrow** [comment]
Thanks Euan, Good job.

**Comment by euanwithersby** [comment]
Glad it's come out well, happy to help.
