### ISSUE TITLE
Violet - move error

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#263]
When starting to print, moves to one corner and displays move error

Probably related - makes grinding noise when moving as part of Initialize sequence

**Comment by amcewen** [comment]
This was caused by the spring tensioner on the y-axis belt drive not being positioned correctly - so when the printer tried to move to the far end of the y-axis (away from the homing microswitch) the tensioner would hit one of the pulleys and stop the belt moving.

Fixed it by moving the platform carriage (it was easier to move than the spring tensioner) along a few teeth on the belt so that it was in the right place.
