### ISSUE TITLE
Sophia is slipping/skipping on the x axis

### ISSUE THREAD

**Issue by JimNixon** [DoESLiverpool/somebody-should#269]
Tried to do some cutting on Sophia this morning and the x axis is slipping so the laser carriage isn't moving far enough across during cuts. Seems to happen at the same time when doing the same job multiple times. Tried a few different dxf files and they all seem to have issues.

**Comment by DefProc** [comment]
This is an ongoing problem where the motors over-torque and stall during a fast traverse between cuts. It typically happens between quick line-engraving actions, but I have seen it happen between small cuts. Unfortunately, because the cutter motors run open-loop, if the number of step pulses sent to the motor don't match the number actually taken, the rest of the job gets shifted out of position. 

This effect is very consistent; running the same job almost always shows the same skipping in the same place. Some ways to stop it happening in a problem job are to: 

 * try rotating the job by 90 degrees, so the traverse happens in the other axis, 
 * try moving the item after the traverse further away (if applicable), 
 * try setting the item after the traverse to another unused colour, and have it happen after the end of the problem layer, instead of when it has a problem. 

But there's currently no single fix-for-all-cases. 

We have tried some things to stop this from happening: 

 * cleaning the rails
 * reducing the traverse speeds
 * increasing the current limits on the motor drivers

without being able to cure it. The skipping has been observed on occasion on Gerald, but is much likely to occur.
