### ISSUE TITLE
Top head part of Ultimaker 2 Extended needs replacing

### ISSUE THREAD

**Issue by JimNixon** [DoESLiverpool/somebody-should#276]
One of the parts of the hotend carriage has snapped in 2 places, making it unusable at the moment. For now I've stuck a "Do not use" sign on it.

Later this week I'll 3D print the replacement part on my Ultimaker and rebuild it.
-

**Comment by JimNixon** [comment]
Reprinted the replacement part and installed it. Should be easy to spot as it's in green.

**Comment by DefProc** [comment]
The part basically works, but it's missing the internal chamfer that makes the tube grip work properly. As a result, the bowden tube retracts by around 5mm when in use, and this means it's possible for the filament to miss the center of the hot end and jam. 

I have a model that includes the chamfer, so I'll try printing a replacement.

**Comment by DefProc** [comment]
The new top part is ready for an exploratory print: [1320-B2P-B_1-5mm.stl](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/3Dprints/ultimaker_parts/1320-B2P-B_1-5mm.stl)

I've added a 1.5mm offset of the internal chamfer, to see if that will cause the spring clip to force the white tube grip to engage. 1.5mm is approximately the amount of offset that the current tube grip has before it engages, but this is difficult to measure accurately. 

If it needs adjusting, the Onshape model (linked above), as a single variable that controls this and changes it from the original shape.

**Comment by amcewen** [comment]
I've printed off one of that STL, in orange.  It's next to the printer ready to be fitted.

**Comment by DefProc** [comment]
As the print out has gone missing before anyone got round to fitting it, I've since realised that if we could print a thicker clip, that would also do the same job. 

I've created an onshape model that should be the same dimensions as the original, just 1.5mm thicker: https://cad.onshape.com/documents/bd683829cfe20271cd3726e8/w/77b575d3781fb02d30a13f3e/e/5bf5a5ea978881293c95cf07 (and one the same size as the original)

It's a work in progress, but if it prints successfully, we should place the correctly sized stl in somewhere-safe. It would also mean that the current clip could be moved to the UM2 #406

**Comment by DefProc** [comment]
Printed and fitted. 1.5mm extra is a little snug, but it fits. Also closes #406
