### ISSUE TITLE
Gerald has misplaced a screw

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#287]
Gerald was having problems with the y-axis today - moving towards the front of the bed was fine, but moving back would often stall.

We eventually traced it down to one of the shims on the right-hand side of the carriage on the right-hand rail.  They're each held in with two screws, but that one had lost one of its screws and the other was loose.  That meant the shim would hang down and foul on the bolts holding the rails to the frame.

We managed to tighten the remaining screw, but couldn't get the other one back in successfully (there's ~1mm of clearance beyond the length of the screw to get it in, and hardly any space to then turn it once you get it into the hole).  So as a temporary fix we used a blob of threadlock to help hold it in place.

We have the "missing" screw, it's in a white tub labelled "Gerald's important screw" and in the locked cupboard in the main room.  I suspect we might need to do more dismantling of the carriage/rails to get at it and replace it properly.

**Comment by amcewen** [comment]
@cheapjack had this problem again today.  I've tightened the one remaining screw back up, which seems to have sorted it for now, but we should schedule in a proper dismantling and fixing it when we move.

**Comment by amcewen** [comment]
Re-tightened the screw today.

**Comment by amcewen** [comment]
And re-tightened it again just now :-/

**Comment by DefProc** [comment]
There is some Loctite in the workshop if it would help (solvents cupboard)

**Comment by DefProc** [comment]
Happened again (source cause of #517 ). Added loctite the the joining surfaces, and jammed the screw side with a small piece of laser offcut to try and reduce vibration at the screw.

**Comment by johnmckerrell** [comment]
Can this be close now?

**Comment by amcewen** [comment]
I think we've lost the screw now - at least, it's no longer in the "Gerald's important screw" tub :-(

Had worked loose enough to cause problems again today.  Currently waiting to see if some more loctite helps fix it again.

Marking as broken for now.

**Comment by amcewen** [comment]
The loctite didn't work.  @johnmckerrell and I wondered about just removing it for now, but couldn't get any purchase on the remaining screw (I think because it's now nicely greasy because the bearings look like they got regreased on Sunday).  We've tried some more loctite, and if that doesn't work then maybe we should clean up the grease and try unscrewing it again.

I've blocked Gerald out in the calendar so no-one else can book him before Friday to give us a bit of time to look at it.  It is booked for Friday, so if we aren't going to get it fixed before then we'll need to let them know.

**Comment by johnmckerrell** [comment]
Some more loctite didn't work.

**Comment by amcewen** [comment]
Suzy stuck some tape over it to hold it up and that seems to have done the trick.  For now at least, a better fix would be good.  I'm going to remove the `broken` label from here, although it's still applied on #909 as Gerald isn't very usable at the moment.

**Comment by magman2112** [comment]
I was able to get into DoES on Tuesday night to work on Gerald. I ended up taking the complete bearing rail out on the left of the machine to get access to the screws on the bearing block. This was surprisingly easy, despite there being 14 Allen screws holding the rail in, but only 4 screws holding the carriage to the bearing block.

The metal clip is part of the mechanism for holding in the bottom bearing race. Luckily, it was only an M3 6mm countersunk screw, which I had a spare for in my parts collection. This and the original screw were installed, along with some thread lock.

I also took the opportunity to clean and lubricate the rail whilst it was out. Refitting was ok and I ran Gerald up and tested the full extent of front to back movement then tightened down rail. A test run with a very large rectangle had smooth movement with no snagging so I would say that this issue is now closed.
