### ISSUE TITLE
Gerald's bed is visibly off-kilter

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#288]
There's a centimetre (or more?) of difference in height from the left edge of the bed to the right edge, so larger cuts don't have a hope of succeeding unless you shim the bed lots...

**Comment by DefProc** [comment]
While the bed height was set, it has slipped since then. The most likely cause is that the long belt down at the bottom of the bed, is worn and needs replacing.

**Comment by huffeec** [comment]
Had another look today, the back belt is making an intermittent clunking sound.
The belt is labeled "Fulong Ningobo 1170 MXL 15 J05" Width 15mm
I've measured it as 3m but a second opinion wouldn't harm as I don't think we can join a longer one like we did with Sophia. (There is a bit of play on the motor to tighten it but not much.)

I wondered if the z axis leveling instructions from this (similar model) page 22 would work.
http://www.engravingsys.com/support/legacy/VL200%20VL300%20Service%20Manual.zip
But until the belt is replaced it probably won't fix it for long.
So I've put some new shims in to level it for now.

**Comment by huffeec** [comment]
Gerald's bed is still slipping further out of level, there is about 30mm difference in height on the x axis. I needed to add more shims on Monday to level the bed (window side), they are now as thick as the depth of the frame holding the bed. 
I spoke to the person using it today and they said it was cutting fine so it's definitely not broken. But probably getting to the point where shims aren't really a fix anymore.

**Comment by stevesparrow** [comment]
So, Do we need to buy something?  Chris or Patrick, do you have a link?

**Comment by huffeec** [comment]
A few of us had a look tonight at Maker night. By temporarily disengaging the belts we managed to get the bed back level without shims. It's not a fix, the belt will keep slipping and it will gradually run off again.

We measured the belt again and we do need a 3m belt (detail above) and replacing and refitting this might fix it more permanently. I've not found a site selling single belts of this size anywhere.

We did notice there are a couple of belt tensioners missing though. There is one in place for the belt nearest the window. The other two belts run along places with mounting points for tensioners but they are missing. It's the belt at the back slipping that is causing the problem and it could be a tension problem rather than a belt problem. So sourcing a couple of the tensioner parts might be a better fix.

**Comment by huffeec** [comment]
Used Gerald again today and the bed is already visibly off level again. I've added 3mm of shims to the window end to level it. Otherwise it's cutting very well but if it keeps slipping at 3mm/fortnight it will become a problem again soon.

**Comment by DoESsean** [comment]
This needs fixing - it seems like it's going to constantly need readjusting until that point.

I've tried googling the information listed above, and the first result returned for Fulong Ningbo 1170 MXL 15 J05 is this thread, so not very useful. If anyone can figure out how and where we get the required belt, I'll order one.

**Comment by helicalbytes** [comment]
Rob and @jackie1050  have been working on this. The bed wasn't level so the main belt to the motor was tensioned. Rob noticed there are 2 belts. There was a metal ring on the right hand side that had to be removed because the belt was riding up on it, and then jumping (stuck onto Gerald at the moment).
![wp_20170304_13_30_29_pro](https://cloud.githubusercontent.com/assets/17219493/23579628/00319f7a-00e9-11e7-8186-2598e50c031e.jpg).

**Comment by DoESsean** [comment]
As far as I understand it, we're still having some serious issues with Gerald's bed. 

Does anyone have any idea about what parts we might need to buy or how exactly we can make this better in the long term rather than just making constant short term fixes?

**Comment by huffeec** [comment]
It just needs a new belt tensioner on the back belt, there are mounting holes for one.
I've not had any luck finding a replacement part, maybe it's something we could make? There is one on the window side belt we could copy. I'll try to get some photos at maker night to show what I mean.

That's not to say it would be a bad thing to replace the belt (above) but on it's own I think we'll keep having the same issues.

**Comment by johnmckerrell** [comment]
Worth pinging the photo to Just Add Sharks to see if they have any suggestions?

**Comment by huffeec** [comment]
The belt tensioner on the side belt.
![gerald](https://cloud.githubusercontent.com/assets/4748179/25501396/8a9bae6e-2b8a-11e7-8029-15a39513e6bb.jpg)
The back belt looking floppy with mounting points for a tensioner.
![gerald2](https://cloud.githubusercontent.com/assets/4748179/25501458/b9c3f912-2b8a-11e7-9512-40d49ad1528e.jpg)

I'll see if Just Add Sharks have anything suitable.

**Comment by huffeec** [comment]
Just Add Sharks don't stock anything like this, and didn't have any suggestions where we could try.

**Comment by DefProc** [comment]
When I looked in the bottom of the cutter, it looks like the motor mount is in slots, so the position of the motor provides the tension for the back belt. The main problem I had is that in needs two people, one below with a spanner on the nuts, and one with access to the top for the bolt heads. 

I don't remember ever seeing tensioners on the other belts tho.

**Comment by DefProc** [comment]
OK, I made a little progress on specifying the belt. `MXL` refers to the [belt tooth profile and pitch](http://www.cnfulo.com/products.html?ptid=1), and 15 says it's 15mm wide — which matches with the measurement!

Type | Pitch (mm) | Tooth height (mm) | Belt thickness (mm) | Angle β°
-------|-----------------|-------------------------|-----------------------------|-------------
MXL	| 2.032 | 0.51 | 1.14  |40

I did find the original manufacturer ([Fulong Ningbo](http://www.cnfulo.com/products.html?ptid=1)) and the [product page](http://www.cnfulo.com/productsd.html?pid=2) for this belt. 

Type | Pitch Length (mm) | Sleeve Width (mm) | No. Teeth
-------|--------------------------|---------------------------|--------------
1170MXL | 2972.82 | 450 | 1463

It looks like long, continuous MXL belts might be hard to find above 1m, so we might have to splice the a specific length of belt to make one the right size. 

[This video](https://www.youtube.com/watch?v=YDNXlYpdpM8) seems to show the typical way of joining flat toothed belts with pins, and looks like we *might* be able to do it in house. Otherwise, we should find the spec of the other two belts if we're going to order replacements from the manufacturer.

**Comment by DefProc** [comment]
I've found an aliexpress supplier with belts from the same manufacturer, just waiting to here if they can supply this one.

**Comment by aubergine10** [comment]
Is [this belt](https://www.aliexpress.com/store/product/free-shipping-mxl-rubber-timing-belt-1170mxl-6-1463-teeth-pitch-2-032width-6mm-length-2972/1304277_2046447898.html) the same thing? $78.65

**Comment by huffeec** [comment]
I'd be happy to hold a spanner if it helped, could come in early for Maker night.
I did get the impression when @jackie1050 and Rob looked at this there wasn't enough travel in the motor mounts. Maybe with a new belt as well it might fix it? 
It can't have had a tensioner before but there is definitely a place to mount one, and it would make adjustment easier. I've just no idea where to get one.

**Comment by DefProc** [comment]
@aubergine10 almost, it's only 10mm wide, and we need 15. I've contacted the seller to see if they will do wider ones.

**Comment by huffeec** [comment]
Will be fixed by #518 but this is becoming an issue again. 
Approx 20mm difference in height across the x axis.  I've packed it again for now.

**Comment by DefProc** [comment]
On the basis that done is better than perfect, I've ordered two of the 10mm 1170MXL belts that @aubergine10 suggested [alixepress link](https://www.aliexpress.com/item/1PC-MXL-Black-Rubber-Timing-Belt-640-764-810-848-870-910-1000-1140-1170-1212/32807703701.html). They'll be two weeks for delivery.

**Comment by DefProc** [comment]
We received 2× 15mm belts that are now ready for fitting. They are in the laser spares cupboard.

**Comment by DoESsean** [comment]
Did these belts get fitted? Is the bed all better now?

**Comment by amcewen** [comment]
Access to the top and bottom of Gerald is much easier at the moment, as he's sat on his side waiting to get moved into the new Wood Workshop.  It would be good to fit the belt before he's reassembled and harder to work on...

**Comment by amcewen** [comment]
I found the belt earlier, and it's now in this box along with the wood drawers in the metal workshop, awaiting moving into the wood workshop when the varnish is dry #732.

![](https://c1.staticflickr.com/1/790/41184381541_6fdb9414e8_b.jpg)

**Comment by amcewen** [comment]
@johncain39, @dazz-ling, this can be closed now, right?  Can one of you write a brief comment explaining what fixed it (the belt didn't get replaced in the end, is that correct?) and then close it please.

**Comment by dazz-ling** [comment]
![20180405_175252](https://user-images.githubusercontent.com/26006843/38482360-c9b9bb5c-3bc6-11e8-825a-04607433f885.jpg)

The issue seemed to be a just a mechanical one. Had to chance to have a good look at bed when it being moved to the new premises.  There are two bolts just under each corner of the bed that needed tightening ( they now have double nuts on them so hopefully won't slip )

**Comment by amcewen** [comment]
Thanks @dazz-ling!  You should have an invitation to join the @DoESLiverpool organisation on github somewhere (in the notifications, linked from the top of the page maybe?), which if you accept it will let you close issues as well as comment on them.

**Comment by johncain39** [comment]
Just to add to what @dazz-ling has already mentioned. The drive motor was also not secured properly which would have affected the belt tension. 2 if the securing bolts were badly worn and not able to retighten the nuts. These have now been replaced and double nutted too to prevent future slippage.
