### ISSUE TITLE
Review laser-cutter procedures following fire in Gerald

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#293]
Breaking out the new action from issue #290 rather than morph that action into something it's not :-)

@DoESsean can we add an agenda item for the next organiser's meeting to review the laser cutter fire procedures, to look at if:

* the current fire blankets are still suitable,
* or another extinguisher should be used in the future,
* or if revised information during the laser induction is sufficient.

Revise the laser information wiki pages to specifically note the problems of:

* cutting multiple sheets at once,
* not cutting lines more than once where possible.

**Comment by jamieisboss** [comment]
As much as people should follow the rules and stay vigilant, there will eventually be a mistake made, and there's definitely something that could be done to automate some safety, @amcewen do you have any experience of how making the air inside the cutting chamber hypoxic would affect the cutting?  

I know it stops combustion, so there would be no smoke, but the laser should still be shooting a beam hot enough to do something to the wood/acrylic/material. and i think i've seen something about this as an alternative to the replacements for halon gas because the air is still breathable, just not good enough for fire.

Adding nitrogen to the chamber to lower the oxygen content below a certain level (14% i think but I'm no expert) would achieve this, and would mean there physically couldn't be a fire. (unless this system failed)

The gas would only have to be added just before the start of the cut, then the level monitored and topped up to maintain the hypoxic environment, it could be made a compulsory part of the process (I read up on the laser cutter software, it seems too basic to control a process like this, but it wouldn't be difficult (in the scale of the impact a fully fledged fire when people are in the workshop could have) to get a system in place so the top door has to be closed, and an oxygen sensor has to give a reading below that level before a relay will engage and let the machine turn on.

As it's only nitrogen, a little leakage wouldn't be an issue, and (I'll see if i can find actual laws to back this up) as you're not using very much, on the same scale as someone welding, i think it could be vented outside without worry once the cut has finished. It might actually be cleaner than what gets vented now. Gerald and Sophia could be fed from a single bottle.  

As a backup, a smoke and fire detector could follow the laser head and automatically kill the power and turn on a very strong vent fan to remove all the hot air and carbon-heavy smoke from the chamber, which would have a similar effect, but would be quite a bit more likely to damage something.

I'm kind of free flowing with ideas, hopefully some of it is useful at your meeting, There are plenty of more obvious solutions but most of them mean the workshop would have to be evacuated if there was a fire so i tried to find something that wasn't that as a counterpoint, I definitely prefer the idea of a system that doesn't rely on people, and so wont work unless things are right to one that does rely on human oversight.

[This site](http://www.boconline.co.uk/en/products-and-supply/industrial-gases/inert-gases/nitrogen-oxygen-free/nitrogen.html) says nitrogen introduced hypoxic air is used when laser cutting stainless steel as an assist gas ( which i think means so you can use a higher powered laser and not set the air on fire) so thats a suggeston it'd work here. Though a lot of the cutters i just looked at shoot air at the laser to make it burn better so maybe it's not viable as an every time solution, That company BOC, have an office in the City centre, they sell all kinds of gasses and have a rep named on the site who might come and give some advice

Hope there's something useful in there. 

Jamie

**Comment by DefProc** [comment]
This was more so we could have brief discussion during the organisers meeting on whether the fire blanket was still suitable (as a review process, since one had been used) or if we should replace it with a CO2, or dry powder extinguisher, etc.

Thank you for your input @jamieisboss; but as the measured risk of fire remains low (two non-trivial fires in 4½ years), both of which were sorted straight away, and resulted in minimum damage to the machines (a single item damaged by the fire in both cases — both easily replaced): inert gas assist, or air-tight sealing the cutting environment and then flooding with an inert gas do seem like excessive (and also, potentially dangerous) steps.

**Comment by jamieisboss** [comment]
Fair enough, and with that low an incident rate i can see why you wouldn't   want to invest in  complex system. But for the sake of completeness as i was reading for a while, Co2 extinguishers have  the issue that they rapidly cool the air in the chamber, often destroying some or all of the optics and anything else that doesn't like to go from hot to cold, Including the laser tube. Powder extinguishers leave the machine messy, and this can be very difficult to remove to get the cutter working again.

**Comment by johnmckerrell** [comment]
Notes from meeting 20160614 - get a CO2 extinguisher (#298), we should always have 2 fire extinguishing devices.
