### ISSUE TITLE
Investigate discourse

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#306]

**Comment by DefProc** [comment]
got one online (on a 7 day free trial before being billed $20 a month) at http://doesliverpool.discoursehosting.net

**Comment by DefProc** [comment]
It's working, bar the incoming emails (which I've hit a bit of a wall with) I think the internet just needs to catch up with the new gmail account I created!

It's interesting that if the incoming mail stuff does work, we may be able to retire supportbee, as discourse should be able to do the "message a group of people when incoming emails arrive"

**Comment by DefProc** [comment]
Right, [incoming email](https://meta.discourse.org/t/setup-incoming-emails-e-mail/42026) and outgoing email seem to work OK

**Comment by DefProc** [comment]
We're just about to go over the 7 day threshold, and have to pay the first month's hosting for this trial. 

As we're only up to 8 users, I'd recommend letting this one run, to at least see if there's more traction with this. So unless anybody objects I'll let this trial continue for a few more weeks.

**Comment by amcewen** [comment]
What are we aiming to achieve with moving to Discourse?  How do we decide if we're going to move to it?  How are we going to manage the people side of moving across (if we decide to move)?  (Telling people it's happening, the timescale for expressing opinions one way or t'other, etc.)

**Comment by DefProc** [comment]
It should allow us to replace support bee (which is just going up in
price), allow for group emails a la #244, and replace the Google group with
a nicer to use mailing list with easier public access.

I'd suggest if the organisers agree that the demo's suitable, and there's
no good objections from the community, that would be enough to move across.

Other hackspace migrations notified in their original group, migrated the
discussions and then switched at a set date, setting the original group
read only from that point.

Migration of the discussion threads should create user accounts with the
same email addresses, which can then be claimed in Discourse. These can
still be used via email without any new login.

On 4 Oct 2016 19:15, "Adrian McEwen" <notifications@github.com> wrote:

What are we aiming to achieve with moving to Discourse? How do we decide if
we're going to move to it? How are we going to manage the people side of
moving across (if we decide to move)? (Telling people it's happening, the
timescale for expressing opinions one way or t'other, etc.)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/306#issuecomment-251468663>,
or mute the thread

**Comment by cheapjack** [comment]
Comments between [Ross & Patrick on Discourse](http://doesliverpool.discoursehosting.net/t/why-does-discourse-look-good/41)

**Comment by amcewen** [comment]
I can understand the arguments for replacing SupportBee (although would that mean everyone's email count would increase as you wouldn't have SupportBee's "person X replied first, so I'll just email them" feature?  There are pros and cons to that :-D) and also for the group emails.

In what ways is it nicer to use than the Google Group?  

It sounds like you're proposing that existing Google Group uses will have to actively do something to receive emails?  Are we happy with all the users of the GG we'd lose as a result?

I'd be happier if there were more people arguing that we should make the move, or providing more arguments for what we'd gain.  It feels like a technological fix for a social problem (not enough discussion within the community) to me at the moment.

**Comment by DefProc** [comment]
Although with Supportbee, I can't see if something's been replied to (although I thought it used to do that) without going to the web interface (which I don't do). And as one of the reasons to use Supportbee was so we could see other people's replies, so they didn't go out of the group email, this seems like a mark against Supportbee. 

The signup specifically is easier, google groups requires a google account, and discourse will allow 3rd party logins (github is already enabled). The forum+ features means it has threaded *and* chronological ordering (without changing the view). The web interface acts like live chat, so incoming new posts will appear live in other users, so we get a friendlier web interface, plus the mailing list. And it allows breakout threads that stay linked to the original conversation (a la github issue cross references). 

Other hackspaces (eg. Hackman) chose to default to the "mailing list mode" so post are automatically emailed out, rather than the current default for google groups where we currently list instructions on what to do to activate that. Using mailing list mode would encourage this result, but it's a judgement call if we'd want to change this behaviour. 

I don't see it as just a "technological solution to a social problem" (we won't get discussion if there isn't any to have ), it specifically saves us money over supportbee, provides us with a solution to #244, follows the recommendation of #18.

**Comment by DefProc** [comment]
I have a more customisable install running now on [disourse.doesliverpool.com](http://discourse.doesliverpool.com) (once the DNS propogates to include [188.166.158.202](http://188.166.158.202)) that has the google group posts imported, plus the user accounts and discussions from `doesliverpool.discoursehosting.net`. It's currently on a Digital Ocean droplet that I'm paying for. 

There are a few things left to check: 

 - [ ] check the google group posts are reasonably complete
 - [ ]  generate the letsencrypt ssl certificate (once the DNS propogates)
 - [ ] Outgoing email via mailgun (once the DNS txt records propogate)
 - [ ] Incoming email via gmail (to `doesdiscourse@gmail.com`)
 - [ ] Incoming email (to aliases of a new `community@doesliverpool.com` account)
 - [ ] Groups and email replies (eg. `lasercutter@doesliverpool.com`)
 - [ ] cancel the current discoursehosting.com account (before 25th Nov)

And assuming everything's hunky dory:

 - [ ] move the VPS (or resintall Discourse and transfer the content) to somewhere DoES controls
 - [ ] point community.doesliverpool.com at the discourse install

**Comment by johnmckerrell** [comment]
Cons of Google Groups
 * Sign-up is complicated
 * Some people don't like that Google own it
 * Not self hosted or "owned"

Cost of switching to Discourse
 * Migrating accounts across - don't want to force people to get emails, or not get emails, if they don't want to.
 * New email address for posting - have to inform people

**Comment by DefProc** [comment]
Added a forum link onto the website (listed as testing)

**Comment by willcrobinson** [comment]
Link appears to be cut off for me. Checked in Chrome, Safari and Firefox and all showing the link as "doesliverpool.dis"

**Comment by DefProc** [comment]
doh, fixed

**Comment by aubergine10** [comment]
Moved from #383:

> Any chance we can change its background-colour - make it green (like github comment button: #28a745) or something? It's practically invisible when just glancing at the screen.

**Comment by aubergine10** [comment]
Is it possible to edit the header bar on discourse?

* DoES logo
* Links to website, wiki, issue tracker?

**Comment by DefProc** [comment]
As this has been waiting on a decision by grouping it in with the website improvements ( #19 & #548 ) but appears to have been unlinked from the blog, has seen little engagement, and is still costing us money each month (pending a decision on it's future) I recommended at the most recent organiser's meeting that we save a backup of the current site, shutter it, and not be paying for it until the website overview gets picked up again. 

While I still think that discourse offers us a lot of benefits over sticking with the google groups, there's no need for us to keep paying for it while we're waiting on a decision.

**Comment by DoESsean** [comment]
Seems sensible to me.

**Comment by DefProc** [comment]
I've applied to have the forum closed.
