### ISSUE TITLE
Update the wiki entry for the vinyl cutter

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#388]
Need to update the [cutter guide on the wiki](https://github.com/DoESLiverpool/wiki/wiki/RolandVinylCutter) since we've managed to set it up with Inkscape though have to weirdly flip the artwork to get it to cut ok.

**Comment by stevesparrow** [comment]
I've written up the new bit, and edited the instructions to make them into more of a setup by step user guide.  Ideally someone could pick up the guide and just cut, which as someone who is at DoES most of the time know, and knows how to use it, is excellent.)

I've copied the old text below for safekeeping / reference.

Ros - Do you want to have a look / edit and check it's clear and correct?

_______________________________________

# RolandVinylCutter Instructions Instructions for Vinyl Cutter

**Ensure your design is formatted correctly as below, think about the sections of your design and how you will apply it. Text below 30mm high just does not work with this cutter well; can become a nightmare! Also some fonts are easier to cut than others!**

## Making it work

### Inserting the vinyl

Turn the machine on at the switch on the left.  Push lever on back right down to release the rollers.  Position the vinyl under the rollers and slide them sideways to the widest extent of the bed but always under one the white rectangles.  (If you don't the cutter will give an error.)  Pull the lever up to push down the rollers.  Click the "Enter" to button to so it scans the width of the vinyl.  It will be a number like 140mm or 400mm.  Copy this down.  (It is approximately the width between the rollers as the cutter is unable to pull and cut outside the region where the material is held down.)

> Vinyl not scanning? On a bright day the sun can cause an error when scanning so you may have to stand on the left of the cutter to prevent sunlight being cast on the head's sensor. Turn the cutter off and repeat the process above.

### Setting up the software

The vinyl cutter is controlled by a small silver "Advent" laptop to the right of the machine.  Log on with the user "OFFCUT".  Open the program called "2D design".  Go into File -> Print setup -> Properties and enter the width number of the vinyl that you copied down in the paragraph above.  Set the length of the vinyl you intend to cut as well.  (Do overestimate this because if your parts go off the top of the page the software will truncate them and the results will be useless.)  The white page rectangle in the software represents the working area.  

### Cutting your shapes
Import your designs from WMF (windows metafile) files.  Inkscape is able to save these, but you must not have filled areas.  (In Inkscape select the part and change the stroke type to have a colour, and cancel the fill type.)  If you don't it will cut round your shapes twice and ruin them.  

Position your shape at the bottom of the white page rectangle and it will come out at the bottom of the page.  (If you put your shapes at the top of the area then the cutter will feed through lots of blank vinyl before it makes the shape and it will be difficult to use that blank area again.)

Feel free to rotate, scale, reflect your shapes before you are ready.  Then go File -> Print (not plot) and it will do the shape you have selected.  

## Notes: A nicer laser cut roller feed would help; one for the todo list.

 * When it completes the cut it often outputs the message "Wrong Numbers" but it just means its ran out of data and its completed the cut.
 * If you find the cuts are not quite right you may need to replace the blades; ask Ross to help or mail him at hello@doesliverpool.com
 * Give yourself some clear workspace.
 * Remove and cut the completed vinyl. Use a FRESH blade on a scalpel and carefully unpick the negative of the design but take EXTRA CARE you dont lift up the part you want by mistake; it will stick to the negative parts (the parts you dont want) and be irretrievable! Do a section at a time and use the scalpel to lightly cut the vinyl but NOT the backing.
 * Take the low tack transparent roll of application tape and roll evenly onto the prepared vinyl and its backing: there is a knack to this; use a cardboard roll
 * When applying to your surface make sure its clean then CAREFULLY peel off the vinyl from its backing using the transparent low tack application tape & ensure you dont lose any items. Use your finger or a plastic squeedgy (near the machine) to make sure it adheres to the application tape.
 * Lightly place on surface; don't fully commit until you sure its in the right spot then press vinyl to surface through tape FIRMLY
 * Finally gently remove the application tape
 * Done!

## Tips and Vinyl Stock
 * I use [MDP supplies](http://www.mdpsupplies.co.uk/categories/sign-vinyl-supplies.asp) on the wirral who do quick delivery but you can pickup from their shop also. You need to buy the 610mm width tape of the length you require. 
 * Try not to use text characters of less than 20mm high; the plotter can jam text thats cut too small or most likely cut the vinyl but end up fouling up when it comes to application stage. Also you will find some fine cyrillic/italic text can foul up also, you have to experiment!
 * Nottinghack have the smaller version of our cutter, and are using it with an HP JetDirect 300 network print server.  They've also found the manual for it, which can be downloaded from their wiki https://wiki.nottinghack.org.uk/wiki/Signmaker

**Comment by cheapjack** [comment]
All looks good to me @stevesparrow Ill give you the pleasure of closing this one 👍

**Comment by stevesparrow** [comment]
Thanks Ross,

I'm not sire I have permission to close?

**Comment by cheapjack** [comment]
Oh yes, as I opened it. Thanks for writing it up 👍
