### ISSUE TITLE
Put some shelves up above the 3D printer bench

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#392]
Extending #391, we should put some workshop shelving up there. It'll allow the display space, and filament storage, but also give space for some of the increasing amount of soldering equipment (hot air, board preheater, solder oven, vacuum tweezers) that should be accessible, but not normally taking up worksurface space, and don't fit nicely into the soldering cuboard.

And we can put the Makerbot Cupcake on display (status: working when we last used it) there too. 

Are there any good sources for sturdy, wall mounted, workshop shelving?

**Comment by stevesparrow** [comment]
Closed as moving.  Be worth bringing this into our new space plan

**Comment by amcewen** [comment]
If it's worth bringing into the new space plan (or at least considering for it) then we should leave it open, not hide it away where it'll get forgotten.  We can always close it once the new space is fitted out if it turns out not to make sense then.

I've added the Move label so it'll show up when we're filtering by that too.

**Comment by DoESsean** [comment]
We have spool hangers and all sorts, thanks to @goatchurchprime.

Boom, closed.
