### ISSUE TITLE
Replace electronics in UP3 printers 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#397]
Both UP3D printers are out of action and won't connect to USB.  
    https://github.com/DoESLiverpool/somebody-should/issues/256
    https://github.com/DoESLiverpool/somebody-should/issues/274

There's nothing we can do about this closed source hardware.  But Brian at the Cambridge Makespace has had success replacing it with a Melzi board:
    http://wiki.makespace.org/Equipment/3D_Printer/Up#Firmware
    http://reprap.org/wiki/Melzi

He says the main problem is getting the thermistor temperature curve calibrated.  

These seem to be available on ebay a lot:
    http://www.ebay.co.uk/itm/Melzi-v2-2-0-Mother-board-controller-3D-Printer-3-D-2016-Reprap-Prusa-i3-5s-6s-/172409562502?hash=item2824692586:g:ZBMAAOSw5cNYKtRq

We should order one of these soon and get on with fitting it into Rose.  Nothing to lose there.  

(If it works, maybe try out a BB/machinekit one on Violet)

**Comment by amcewen** [comment]
Getting a Melzi board sounds like a good idea.  @DoESsean can you order one for us please?

**Comment by amcewen** [comment]
I've ordered a Melzi board, should be here for Monday.

**Comment by DoESsean** [comment]
This got refunded. We're checking to see if it was reordered.

**Comment by DoESsean** [comment]
The board was reordered, but has yet to be delivered. Adrian had received a message in December saying that they were currently out of stock, and the seller had a 15-30 day lead time.

I've messaged him today asking for an update on the status of the item. As the eBay account is linked to organisers@, anyone who has access to that inbox should feel free to update this issue when a reply is received.

**Comment by DefProc** [comment]
As we seem to be having an issue still with getting a melzie board, I have just come across an advert that there's now an up CPU upgrade replacement for the plus 2 (and others). I've had a quick look, though only found Australian retailers atm. Would this be worth persuing as an alternative?

**Comment by amcewen** [comment]
Got a link for that @DefProc?  Does that replace the entire board of the Up (i.e. there's some undefined problem between the USB connector and the CPU, so is this likely to fix it :-)?  Presumably it also keeps us tied to the Up proprietary software?

IMO moving to the Melzi (or to another of the RepRap electronics options) moves us to a more maintainable solution, and gives us more control over filament types, etc. (I've got a reel of recycled PET that was sent in the wrong diameter, which we could run through the Up if we had more temp, etc. options, for example...)

**Comment by amcewen** [comment]
There was an [article about deficiencies in the Melzi board design](https://blog.adafruit.com/2017/03/23/the-melzi-problem-or-why-did-my-wanhao-i3-duplicator-catch-on-fire/) recently, so I wonder if it's worth getting a [Smoothieboard](http://www.reprap.me/mks-sbase-v1-3-smoothieware-control-board.html) instead?  That's ARM-based rather than AVR, but otherwise will be pretty much the same as switching that in.  The Smoothieboard also has on-board Ethernet and a simple web server, which would let us kick off prints over the network too.

**Comment by amcewen** [comment]
The Smoothieboard seems to be out of stock everywhere (they're working on a replacement board, but don't seem to be making particularly quick progress on it).  So, I've just ordered a [Duet WiFi](https://www.duet3d.com/DuetWifi) as that seemed the best combination of available and capable from the list on the RepRap wiki.

**Comment by amcewen** [comment]
The Duet WiFi board has arrived.  I've put it with Rose.  Volunteers to work out how to wire it up to one of the printers?

**Comment by goatchurchprime** [comment]
Up printer has been handed to wesley who has done one of his own

**Comment by DocTrucker** [comment]
Hello. Yes, I've got the printer and board and plan to have a look at it over the weekend to see what is going to be involved. For work I've run the Duet 0.6 board with an Ormerod 2 from RepRapPro (who've ceased trading) and am currently in the process of upgrading that to Core X-Y based D-Bot.

I've found a user manuals online for the original system. It looks like there may be a calibration cable that I left at DoES Liverpool, but there is plenty I will be able to do before needing that, and I'm not sure if the sensor will be compatible with the Duet without looking.

**Comment by DocTrucker** [comment]
Update.

I've stripped the old control board out, identified the wiring and converted most of the plugs to the ones supplied with the DuetWifi board. There were two spare connectors on the extruder head breakout board so I have taken the liberty of assuming a microswitch to detect running out of filament, and a controllable part fan may be of interest.

I've emailed goatchurchprime about a daughter board that is needed for the DuetWifi to run the PT100 thermistors that are used on the extruder hot-end and the bed.

For testing I am running an old ATX PSU. This is a lower voltage than the 19V PSU that came with it, but allows the DuetWifi to cut the 12V supply to the heaters and steppers if it detects a fault in either of the heating circuits. I'm not 100% sure at the moment what was being driven at the full voltage as some components are clearly limited to 12v (eg extruder fan) while others are rated at 24V (both cartridge heaters). As the internal wiring is on the conservative side I'd rather test on 12V then discuss the implications of moving away from the ATX PSU and running at higher voltages once everything is set up.

Currently the board is loose and not screwed onto the base. I won't cut into the framework of the printer until things are tested and the final voltages picked. I think it is likely that running at 24V will be preferred, but there are safety implications (entirely resolvable, but would require more parts) to discuss.

**Comment by amcewen** [comment]
@DocTrucker Thanks for the update.  Sounds like you're making decent progress with it.  I've just ordered one of the [PT100 daughter boards](https://www.duet3d.com/DuetAddons/PT100_DaughterBoard) for you.

**Comment by DocTrucker** [comment]
All of the basic functions of the printer have now been tested. The heated platform is underpowered when running @12VDC from the ATX supply. For bench testing I will wire up the original 19V PSU to the Duet supply but keep the 12V supply from the ATX powering the fan (it is modulated on the low side of the circuit). The mains supply to the 19V PSU will need to be isolated by a relay in order for the DuetWifi to be able to safely shut off the heater in the event of a detected failure in order to reduce the fire risk of an uncontrolled heater. The simplest method to achieve this is to fire the relay from one of the 5V lines that come live after the computer ATX power supply has been enabled by the DuetWifi.

Currently the stepper motors are jumping steps from time to time so I need to spend an evening tuning the drives before progressing to any live polymer builds.

I have yet to replicate the nozzle height detection, and the automatic bed levelling.

**Comment by DocTrucker** [comment]
I'll add some photos soon and will arrange the collection of the machine with Jackie.

Here are some of my observations:
* Stepper motors are high resistance. They appear to be intended for constant voltage stepper drivers rather than the constant current. Things seem to be running well as set in the configuration file, but they did stall when I tried to increase the current. They don't appear to be causing much of an issue.
* Both the heater cartridges are sized for 24VDC, but driven at 19VDC. I would not be comfortable about using 24VDC (ignoring fan voltage issue) as in my opinion the cabling in the system is only just capable of taking the current draw.
* As wired the system uses an old computer PSU of mine. The PS_ON signal is used from the duet to turn the PSU on. The control board draws it's supply from the 5VDC standby line.
* Try to avoid powering down the system with the elevator high. The sudden drop in the elevator feeds a voltage back into the control card. There is a risk this could cause damage.
* The fans are 12VDC models, not 19VDC, and so are supplied by a different line from the PSU. On the original board there was a drop down regulator providing the 12VDC for the fans. They only come on after the PS_ON signal is sent. It is not ideal that the hot end could be enabled without the fans running. I advise you use a 12V line from the PSU to drive a mechanical relay to cut the power to the 19VDC power supply.
* The nozzle height detection is enabled, but I found it a faff. I'd recommend using the macro to probe the bed with the micros switch then move the nozzle to the centre of the bed and move it down slowly onto a piece of paper. Once the required offset is identified then use the G10 command to set the tool offset to suit.
* The microswitch is normally open. This is not ideal as the system will not return a fault if you try to run the bed probe with no switch attached. The nozzle will just be forced into the bed and the stepper motor will stall.
* Check the operation of the bed probe microsswitch before use. A light should come on on the board when it is triggered and go off when released. The jack plugs I bought from Maplin don't seem a great fit. I'd advise replacing these with a new external jack socket and pass the leads through the grommet.
* The fans I've added aren't that powerful, and the manifolds are far from ideal. I don't think the system really needs them. As far as I'm aware the board will warn you if it gets too hot.
* It's a wifi board. I've found connection was okay without needing to butcher the front of the machine body. However, I have aligned the wifi aerial, micro sd slot, and usb plug to the front. Perhaps cut yourself a hole and print a cover for easy access. The existing holes in the system are useful for checking the system is behaving as you'd expect.
* I did modify the switch to ease the wiring of the nozzle height probe. This would not really be necessary in the future if you plan to just us a piece of paper to gauge nozzle height. You may however find that comparing the nozzle height results and paper gauge method allows you to make sense of them both. Again, the nozzle height switch is normally open which is not ideal.
* I used some of the screws holding the spring clasps to scre the removable build surface down. In retrospect this was most likely only needed as the material processing parameters are not tuned properly yet.

More posts to follow over the next few nights.

**Comment by DocTrucker** [comment]
This is a good starting point: https://duet3d.dozuki.com/Wiki/Step_by_step_guide

For those not aware the Duet systems do not rely on recompiling in order to change values like accelerations, and motor currents. In fact as far as I'm aware you are free to change any of these by injecting gcodes mid print if you choose to do so using the web interface to send the commands. The web interface is powerful and is used to monitor prints, set up the machine, upload builds, change configuration files, and even upload and install new versions of firmware. A good starting point in understanding the configuration and macros (a file of g code commands that can be triggered from the web interface) g code files is the Duet Gcode reference at: https://duet3d.dozuki.com/Wiki/Gcode

I've mentioned it in passing but the configuration file is where the bulk set up of the machine takes place. I've commented the bits I've added, but it is best that you refer to the GCode reference as well to understand the config file. To be honest the bulk of the leg work was completed by this site: https://configurator.reprapfirmware.org/

Using a USB host program and macros (eg pronterface) to change the wifi network is covered in this document: https://duet3d.dozuki.com/Wiki/Installing_and_Updating_Firmware in the Upgrading to DuetWifi Firmware 1.19 section.

I would strongly advise following a material set process to find the best parameters for a new material. ABS is indeed a sod to work with as I found out the hard way with this machine and my work machine. At a minimum I would look over the nozzle temp, bed temp and e steps section of the following for reference: http://reprap.org/wiki/Triffid_Hunter%27s_Calibration_Guide

Currently the stop inputs for the main extruder and the unused second extruder are repurposed to take the input from the bed level switch and nozzle height detection. I will discuss the start up process for the machine and the macros that use these switches another night...

**Comment by jackie1050** [comment]
Has there been any progress on this?

The last information I have is that @DocTrucker brought in the printer and discussed  with @goatchurchprime and @magman2112 who said they intended to work on it - is that still the case? I would be happy to look at some of the issues.

**Comment by DocTrucker** [comment]
Morning!

My time has freed up considerably now as it's moved from pending to actual redundancy! I've got some work going on at home at the moment but should be able to come over for a day to progress the machine and see how you guys are progressing over there!

I'll sort a time via email to sort the best day to visit.

**Comment by jackie1050** [comment]
@goatchurchprime emailed to say he's going to France on Thursday. @doctrucker replied that he'll delay until @goatchurchprime return.

**Comment by goatchurchprime** [comment]
We should put the instructions up here https://github.com/DoESLiverpool/wiki/wiki/UpCycled

**Comment by DoESsean** [comment]
Where are we with this? As far as I'm aware, one of the UPS has been cannibalised for the other, but I don't know what's actually going on.

**Comment by DocTrucker** [comment]
The machine is in a tested state but needs someone to work on the PSU side
of things to make it safe, and it needs a location to remain in or too much
time is wasted on calibration.

**Comment by amcewen** [comment]
Both the UP3D printers have been superseded by other ones for 3D-printing, and @goatchurchprime has found a better use for the Duet controller, so I think we should close this (and find other uses for the parts elsewhere!)
