### ISSUE TITLE
Apply for Maker Faire UK this year

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#417]
https://www.surveymonkey.co.uk/r/MakerFaireUK17

Before 5pm 23rd January 2017

**Comment by shrkey** [comment]
Sorry for delay, been a bit undecided about whether to apply for a small stand or squeeze in with DoES.

Was thinking of taking the small(ish) autonomous Kayak and stand (2 trestles), a prototype Raspberry Pi powered ROV and possibly a narrow banner. If you think it'd fit with the rest of the stuff you're taking?

**Comment by shrkey** [comment]
On second thoughts - it might take up a bit too much space from your stuff. Might chuck in our own application.

**Comment by DefProc** [comment]
Last time we took a 9 seater minibus with 6 people and the nerf range in. The kayak might be a squeeze, but if transport's similar, then we should be able to the others. 

Previously we've been in the atrium, backed up against the auditorium dome, so I'd expect the space in that location to be fine.

**Comment by DoESsean** [comment]
If we want to take a minibus again, I'll need to know ASAP so that I can
start looking into prices and so on.

**Comment by DefProc** [comment]
We should probably wait till I've actually applied though…

**Comment by shrkey** [comment]
Going to have a chat tonight - I think we're going to split up and one or two of us will head over to Newcastle (and one or two to Pi Wars), so can take a car and transport the Kayak and bits ok in that (and anything else you can't fit in a minibus?) - if you think there'll be space for them in the venue on the DoES stand then that might be the best approach - rather than us having a half empty stand (or being stuck in the dark next to robot wars again!!! )?

This is the Julius site if you need links for listing - https://hackaday.io/project/12484-the-julius-project

The ROV is a bit secret at the moment - so nothing online as of yet.

**Comment by DefProc** [comment]
Cool, I'll add them to the application.

**Comment by jackie1050** [comment]
We'd like to bring Tosca - will need space for the stand and possibly a drawing surface

**Comment by DefProc** [comment]
I'm going to also put in for:

 * Made Invaders
 * Bubblino
 * DoES Tower

Are there any other things that need power?

**Comment by DefProc** [comment]
Submitted. 

I'll close this until we hear if we're successful. At which point, we can open a new issue for organisation.

**Comment by amcewen** [comment]
Ah, just too late, but I'll add an Ackers Bell and a Museum in a Box to the things that need power...
