### ISSUE TITLE
Communal SD card reader/writer

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#425]
It is almost (but not quite) possible to do work in the workshop without your own laptop, by using the laser cutter computers.  

But we need a general SD card writer and reader to save code for the 3D printers.  It could sit in the box of spare memory sticks.

**Comment by DoESsean** [comment]
If you can find one that will be suitable, let me know and I can order it
for you.

**Comment by goatchurchprime** [comment]
this one looks slim  http://www.argos.co.uk/product/2689278

But I'd favour something more clunky like this one that's going to stick around:  http://www.argos.co.uk/product/2874760?rec=webRespPDP:2689278:alt:CWVTPUBOOT:2874760

... especially as if can read old fashioned compact flash cards that is still in use in industrial robots.

**Comment by johnmckerrell** [comment]
I was thinking we should make sure it’s USB3 if we’re buying something new, but then is that backwards compatible? I’m not sure.

**Comment by ajlennon** [comment]
I'd have to check the PCs but presumably we can mount a reader in one of the drive bays? If we got a couple of cheap ones and mounted them they'd presumably be less likely to wander off?

e.g. 

http://www.ebay.com/itm/iMicro-All-in-1-3-5-3-5-inch-USB-Internal-Card-Reader-for-PC-T-Flash-SM-SD-MMCI-/231316560854?hash=item35db8a9bd6:g:DlkAAOSwDFNWFL6I

Cheers

**Comment by ajlennon** [comment]
Or look at that... wow!

http://www.ebay.co.uk/itm/5-25-Front-Panel-Media-Dashboard-Internal-e-SATA-Dual-USB-3-0-2-0-Card-Reader-/182032427374?hash=item2a61fa696e:g:k1EAAOSwxg5Xx5pF

**Comment by johnmckerrell** [comment]
Haha, mad. The USB ports would certainly be useful, again if it can be USB3 for the SD reader that might be handy, quicker for loading raspbian images. Can’t quite tell what interface it uses for the SD cards on that thing.

John

**Comment by ajlennon** [comment]
@johnmckerrell yes my guess is it's just using the USB2.0 for the SD cards... :-/

**Comment by ajlennon** [comment]
For the price (£3) what about we get a couple of these to fit and then source a floating USB3 dongle?

http://www.ebuyer.com/210671-dynamode-3-5-int-reader-black-usballint1black

I need to buy a few things from eBuyer so I'll happily add a couple of these to my order if you think it'll help?

**Comment by johnmckerrell** [comment]
Yeah that’s fine, just after the pain of using a USB1 device yesterday I wanted to try to avoid it again! I wouldn’t particularly worry about the USB3 if there’s no obvious options available.

**Comment by ajlennon** [comment]
On order :)

**Comment by ajlennon** [comment]
There's a 3.5in card reader/writer mounted into Sophia-PC

I've also installed the rather marvellous [Disk Imager](https://github.com/DynamicDevices/DiskImager) utility (if I do say so myself) which can be used for reading and writing uncompressed and compressed SD card images

There is a non-working card reader currently mounted into Gerald-PC. Rather irritatingly Mr. Dell doesn't appear to have included any standard form-factor internal USB sockets on the motherboard. Will have to have a think about that.

**Comment by ajlennon** [comment]
Re-opening as @amcewen has pointed out that the non-working card reader is still... non-working.

Ideas appreciated!

**Comment by aubergine10** [comment]
[SD <--> USB dongles](https://www.amazon.co.uk/Usb-Adapter-Micro-Card-Supports/dp/B001U7R1CM) are inexpensive - an easy way to make the SD card show up as an external drive on any computer. Downside is that they are easy to lose.

Another alternative is a [WiFi SD Card](https://www.amazon.co.uk/s/ref=nb_sb_ss_i_1_7?url=search-alias%3Dcomputers&field-keywords=wifi+sd+card&sprefix=wifi+sd%2Ccomputers%2C156&crid=27MZOGW4XNGMZ) - you connect to it as a network drive over WiFi. Downside is that some operating systems might struggle to use them.

**Comment by DoESsean** [comment]
@ajlennon did we get any further on this?

**Comment by ajlennon** [comment]
The internal reader can't be connected to the Dell motherboard (as far as I can tell) which is rather annoying. I think we're going to have to go the route @aubergine10 suggests with something of an external USB flavour...

**Comment by DoESsean** [comment]
18 months on, has this problem been solved or ignored? If ignored, are we happy with that state continuing?

**Comment by MatthewCroughan** [comment]
@DoESsean This is something I'm interesting in solving and will get to soon.

**Comment by chris-does** [comment]
### Provided 2 x [SanDisk ImageMate® PRO Multi-Card Reader/Writer](https://www.sandisk.co.uk/home/memory-cards/memory-card-readers/imagemate-pro#overview-section) devices

![SanDisk3](https://user-images.githubusercontent.com/52704101/63218543-fa2a4a80-c154-11e9-8f19-152c4ceb03c3.jpg)
![SanDisk](https://user-images.githubusercontent.com/52704101/63218544-feeefe80-c154-11e9-9006-bc3067fae551.jpg)

@goatchurchprime @ajlennon

After some testing of both [does-sophia-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) and [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) in the [Laser Workshop](https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutting) on Thursday 15th August 2019, I have the following update:

Both [does-sophia-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) and [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) have multi-format card readers installed in them (including slots for: SD Card, Compact Flash, Memory Stick Duo, and MicroSD / TransFlash).

Both card readers, in both PCs appear to be working with the following observations:
When using a SD Card with the readers, the card must be inserted "upside down" ([does-sophia-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) already had a label indicating this and I have now printed and added a similar label to [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview));
Both readers have a USB 2.0 port; however this port on [does-sophia-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) does not seem to be reliable. Following the installation of the appropriate system and USB drivers on [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview), the bank of four USB ports on the right side of the front of [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) seem to be working reliably.
Therefore it is recommended that if one wishes to connect a USB memory stick / drive to either [does-sophia-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) or [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview), that the USB 2.0 port on the multi-card readers is not used, and instead one of the USB ports available directly on the PC is used instead,


@aubergine10 @johnmckerrell 

I have provided 2 x [SanDisk ImageMate® PRO Multi-Card Reader/Writer](https://www.sandisk.co.uk/home/memory-cards/memory-card-readers/imagemate-pro#overview-section) devices. These are external units, with a USB 3.1 interface and support the following memory card formats:
non-UHS, UHS-I, UHS-II SD, SDHC, SDXC, microSDHC, microSDXC, and upto UDMA 7-enabled CompactFlash.

![SanDisk5](https://user-images.githubusercontent.com/52704101/63218552-204fea80-c155-11e9-8ec3-8a5cf90b8103.jpg)

These devices are located in a box labelled "Shared Memory Cards & Memory Card Readers" on the desk next to [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) in the [Laser Workshop](https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutting). As of Thursday 15th August 2019, there were also some USB memory sticks in the box too.

@DoESsean 

There may be a better location for this box of  "Shared Memory Cards & Memory Card Readers" to be located, as they need not be constrained for use with just [does-sophia-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview) and [does-gerald-pc](https://github.com/DoESLiverpool/somebody-should/wiki/PC-Systems#overview); indeed they may be reasonably used (on a transient basis) for the purposes of data transfer with any suitable device DoES owned or not.
If there is a better location, please let me know and I shall move the box accordingly.

@MatthewCroughan 
I am not sure what your plans are in relation to this, I had started to address this issue a few weeks back (and hence before seeing your comment) when I was browsing through the [DoESLiverpool/somebody-should list](https://github.com/DoESLiverpool/somebody-should) shortly after joining DoES to see if there was anything I could do to help.
I hope the above is sufficient to close the issue as it stands; though with an eye to the future,
I had considered something akin to a shared media processing / ingestion box with multiple interfaces for a variety of sources (memory cards, UBS keys, hard drives, optical media . . . etc.) that could screen anything being introduced into the DoES environment for any potential "nasties" (hopefully accidental rather than with mal-intent), before making whatever content had been processed available to any machine on the DoES network (perhaps via the [DoES Shared Storage](https://github.com/DoESLiverpool/somebody-should/wiki/Digital-infrastructure#shared-storage).
In any case, I would welcome the opportunity to get your input on potential future enhancements to this requirement.
