### ISSUE TITLE
rationalize down the doesliverpool github repositories

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#434]
There's too much clutter in the set of DoESLiverpool repositories.

I've pinned up the "wiki/wiki" and "somebody-should/issues" repositories (which should have probably been the same thing repo)

There are lots of repositories with little or nothing in them, eg:
    https://github.com/DoESLiverpool/doesliverpool.com
    https://github.com/DoESLiverpool/cover-requester
    https://github.com/DoESLiverpool/simple_sl030_rfid_reader
    ...

Could we move their contents into the "somewhere-safe" repo and delete them? 
    https://github.com/DoESLiverpool/somewhere-safe

Could we also move the handbook into the DoES wiki as there is a huge overlap?
    https://github.com/DoESLiverpool/Handbook

I think the handbook's main purpose is to have a single document you should read all of before you become a member. This would be a sub-selection of the wiki information.

**Comment by amcewen** [comment]
Pinning some repos is a good plan, as does some tidying up and clearing out old repos that didn't go anywhere.

I don't think we should just fold things into somewhere-safe just because they're small though; by all means small bits and pieces should live in somewhere-safe, but if the repo is self-contained and likely to be deployed as a full package - the simple_sl030_rfid_reader repo is a good example - then I think it should stay as its own repo.  Otherwise any scripts that use it (e.g. when provisioning a doorbot, in this case) will have to clone all of somewhere-safe and then pick out what they want.

Pinning important repos and improving the description and README.md files in all of the repos feels like a better approach.

**Comment by amcewen** [comment]
The handbook is, as you rightly surmise, the "introduction to DoES" guide.  There will be a massive overlap with the wiki, and it'd be good to get to a point where it pulls in chunks of the wiki (so we only have to write things once) and similarly directs people to the wiki.  I think it'd also have some more background info on DoES as a community, and have the subset of info that's most important to a newcomer.  (And likely be created as a PDF we can email to them, or maybe we'd even get some copies printed up - there's been talk of it becoming something akin to the [Hiut Denim yearbook](http://hiutdenim.co.uk/products/year-book-3), with interesting articles interspersed with the need-to-know info.

The handbook stuff is covered (or should be covered) by #118.

**Comment by amcewen** [comment]
I've deleted a couple of repos that didn't get beyond an idea, and added descriptions to most of the rest that didn't already have one.
