### ISSUE TITLE
Fix the damp patch in the corner of the main space

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#454]
Not that there is any actual water there, but it's become discoloured again.

**Comment by DefProc** [comment]
Steve mentioned that he did try using a damp sealer last time, but the discolouration has returned quicker than expected.

**Comment by stevesparrow** [comment]
I used a thick coat of this

http://www.screwfix.com/p/thompsons-one-coat-damp-seal-white-2-5ltr/43531

Followed by two coats of regular paint.

I think the likley reason is that we didn't do a thorough enough job of taking it back to the brick wherever damp.  That growth is tough stuff. 

Doing it again, means much more time stripping it down I think.

**Comment by johnmckerrell** [comment]
Or cover it up with a fake wall a few inches out?

--

**Comment by Red-Violet** [comment]
There is damp coming through and on we days (when Sean and I last looked) there was moisture there.

A scrape off and damp sealant should sort it out it's just time to do it and the office needs be clear because it is very very smelly! Headache inducing smelly and breathing problems. Its ok while it goes on but as it drys its nit nice at all.

I could do with some help with getting it organised and when is best to do it?

Jen

On 10 March 2017 02:34:12 GMT+00:00, John McKerrell <notifications@github.com> wrote:
>Or cover it up with a fake wall a few inches out?
>
>--
>Sent from my mobile phone hence brevity and errors
>
>> On 10 Mar 2017, at 00:18, Steve <notifications@github.com> wrote:
>> 
>> I used a thick coat of this
>> 
>>
>http://www.screwfix.com/p/thompsons-one-coat-damp-seal-white-2-5ltr/43531
>> 
>> Followed by two coats of regular paint.
>> 
>> I think the likley reason is that we didn't do a thorough enough job
>of taking it back to the brick wherever damp. That growth is tough
>stuff.
>> 
>> Doing it again, means much more time stripping it down I think.
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/DoESLiverpool/somebody-should/issues/454#issuecomment-285555966

-- 
Sent from phone; Pls excuse brevity.

**Comment by stevesparrow** [comment]
This is a much better idea, quite possibly as quick, and certainly more
long lasting.
Would a gap of 2-3 inches be enough do you think, if we leave some gaps for
air circulation?

S

On 10 Mar 2017 02:34, "John McKerrell" <notifications@github.com> wrote:

Or cover it up with a fake wall a few inches out?

--
Sent from my mobile phone hence brevity and errors

> On 10 Mar 2017, at 00:18, Steve <notifications@github.com> wrote:
>
> I used a thick coat of this
>
> http://www.screwfix.com/p/thompsons-one-coat-damp-seal-white-2-5ltr/43531
>
> Followed by two coats of regular paint.
>
> I think the likley reason is that we didn't do a thorough enough job of
taking it back to the brick wherever damp. That growth is tough stuff.
>
> Doing it again, means much more time stripping it down I think.

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/454#issuecomment-285555966>,
or mute the thread

**Comment by stevesparrow** [comment]
Closing this as we're leaving.  Open again if you disagree

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
