### ISSUE TITLE
add a pricing table to the website

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#460]
I've had a quick go in the [Services page](https://doesliverpool.com/services/) (from #19 ) with a pricing table plugin. 

Services:

 - [ ] Free Events
 - [ ] Friends
 - [ ] Friends with benefits
 - [x] Hotdesking
 - [x] Monthly Workshop
 - [x] Permanent Desk
 - [x] Registered Business Address

There's still a bit of tidying up and clarification to do.

**Comment by zarino** [comment]
FWIW, this morning I was looking for the pricing page (I could remember having seen it in the past!) but I couldn't find it anywhere in the nav:

![screen shot 2017-03-13 at 09 34 01](https://cloud.githubusercontent.com/assets/739624/23848735/7e849baa-07d0-11e7-98d6-ce422a5273c5.png)

I tried "Workshop", but that just led to a Wiki page. Same for "Co-working".

It took me a while to realise that the top-level "Services" nav item was *itself* a link to the pricing page. I’d assumed that clicking "Services" would just open up the dropdown menu, so I never bothered clicking it.

I wonder whether you could add a "Pricing" option into the dropdown menu, that just links to the pricing page?

![screen shot 2017-03-13 at 09 37 25](https://cloud.githubusercontent.com/assets/739624/23848800/b4659a9e-07d0-11e7-9df9-dbc3cc062e5a.png)

**Comment by johnmckerrell** [comment]
FYI I added a PayPal link for the Friend’s recurring billing to the wiki (and today’s blog post) so that might be useful for the pricing page too.

John

**Comment by DefProc** [comment]
Added the Pricing link. 

@zarino I'd actually like to change the Co-working and Laser Cutting links to point to website pages that summarise them, rather than to a catch-all page on the wiki, but that's probably best in a separate issue.

**Comment by aubergine10** [comment]
@DefProc Do you have text images available? If so let me know and I'll add those pages. There's a bunch of stuff I want to move from wiki to website; links unexpectedly dumping website users in github wiki is bad UX.

**Comment by stevesparrow** [comment]
Hi Guy,

I love your enthusiasm.  I'd like to take a little more unified approach to
the website. We've had a series of changes by different people, which have
all improved things.  I'd like though to do something a little bigger, and
avoid simply changing stuff one way and back again! :)  - in the way we
discussed at the Org. meeting.  Could we hold of on other changes till
we've spoken please?

Would you have time to talk next week?

Thanks
Steve

---

**Comment by aubergine10** [comment]
Yup - afternoons/evenings are easiest for me (trains are PITA in mornings).

**Comment by Red-Violet** [comment]
Hi Guy

I was hoping we where going to be going through the website together is this something that we are still going to do?

On 29 April 2017 21:04:12 BST, Guy Fraser <notifications@github.com> wrote:
>Yup - afternoons/evenings are easiest for me (trains are PITA in
>mornings).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DoESLiverpool/somebody-should/issues/460#issuecomment-298191332

-- 
Sent from phone; Pls excuse brevity.

**Comment by aubergine10** [comment]
Yes, definitely. I was just thinking in the interim it would be worth moving some of the github content on to the website (same information - different place) to avoid sending end-users in to github randomly when they click things on website.

In terms of design, I wasn't going to change anything - we still need that DoES "vision" work to be done, in order to work out what specifically the website needs to deliver.

**Comment by Red-Violet** [comment]
Brilliant. That sounds good it should make the website more friendly for the time being.

When do you want to start the design we need a meeting and some ideas putting together I think?  

On 29 April 2017 21:19:35 BST, Guy Fraser <notifications@github.com> wrote:
>Yes, definitely. I was just thinking in the interim it would be worth
>moving some of the github content on to the website (same information -
>different place) to avoid sending end-users in to github randomly when
>they click things on website.
>
>In terms of design, I wasn't going to change anything - we still need
>that DoES "vision" work to be done, in order to work out what
>specifically the website needs to deliver.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/DoESLiverpool/somebody-should/issues/460#issuecomment-298192150

-- 
Sent from phone; Pls excuse brevity.

**Comment by aubergine10** [comment]
@Red-Violet I'd like to arrange a meeting regarding the website as soon as possible so we can get some clear action points and timescales. See also: #480 

@stevesparrow Are you OK for me to clone some git wiki content (probably about 4 pages) on to the WP site in the interim just so that visitors aren't being dumped randomly in to git wiki? Mainly just something to tide us over while the bigger changes are being discussed.

**Comment by stevesparrow** [comment]
Hi,

It was all moved over in the other direction relatively recently by Julian,
so let's leave stuff where it is for now, while we talk about the whole.
Another week of three won't make a difference at this point.

Let's meet this week if we can.  I'll email off list.  If anyone else wants
to be a full part of the conversation, just asj and I'll include you.

I'll bring an agenda, with opportunities to identify linked issues,
audience, functionality and design - (I'd like to get some expert support
in desigm, rather than replying on a series of skilled amateurs with
different ideas - avoiding the historic design cycle)

Late afternoon is good for me, ideally after work, as I spent most of the
day with clients.  I'll email. :)

Thanks
Steve

On 29 Apr 2017 22:17, "Guy Fraser" <notifications@github.com> wrote:

@Red-Violet <https://github.com/Red-Violet> I'd like to arrange a meeting
regarding the website as soon as possible so we can get some clear action
points and timescales. See also: #480
<https://github.com/DoESLiverpool/somebody-should/issues/480>

@stevesparrow <https://github.com/stevesparrow> Are you OK for me to clone
some git wiki content (probably about 4 pages) on to the WP site in the
interim just so that visitors aren't being dumped randomly in to git wiki?
Mainly just something to tide us over while the bigger changes are being
discussed.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/460#issuecomment-298195175>,
or mute the thread

**Comment by aubergine10** [comment]
Yup, good plan. My email address is guy.fraser1@gmail.com

Another topic that might be worth discussing is whether to stick with WP or not? Having looked through existing content on the site it's mostly blog posts which would be relatively easy to convert to some other format. We could also take markdown from the wiki and render it as HTML (although that poses various limitations on formatting).

Just seen [a post by Alex in the google group](https://groups.google.com/forum/#!topic/does-liverpool/-OR-nbtk09U) - he's requesting ability to blog / microsite on the DoES website and it might be worth adding him to the meeting as well?

**Comment by DoESsean** [comment]
#19 needs to look at this issue.

**Comment by MatthewCroughan** [comment]
This seems to have been left open, considering the pricing table on the website is implemented and satisfactory.
