### ISSUE TITLE
Ultimaker Extended is having problems extruding

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#463]
The Ultimaker Extended isn't extruding properly.

We've tried a cold pull, and it seemed to clear the nozzle but nothing is being pulled through when a print is running.

**Comment by amcewen** [comment]
Did you trim the filament in the bowden tube too?  It's pretty common for the end of it to "mushroom" a bit, and then it doesn't feed cleanly into the nozzle.  If you use the "Move material" option you can move a few cm of filament clear of the tube when it's taken out of the extruder (like you'd do for a cold pull) and snip the end off to solve it.

I had to do that one of the at-least-twice that it's run a print since this was reported, so I'm guessing that was the problem and closing this (feel free to reopen if it's still an issue)
