### ISSUE TITLE
Gerald

### ISSUE THREAD

**Issue by dazz-ling** [DoESLiverpool/somebody-should#471]
There doesn't seem to be any laser power in Gerald. He's moving ok but no cutting or etching power

**Comment by DefProc** [comment]
What does the door sensor look like?

**Comment by amcewen** [comment]
Too low.  Or at least, it was.  We should look at fastening it on a bit better than it is right now, so I'll leave this open until we do that.

**Comment by DefProc** [comment]
Re-hot-glued the original door sensor mount and upgraded the cardboard base structure with more hot glue. 

It would be better to make a proper mount for this (perhaps a 3D printed equivalent of what we have now) that screws on, rather that glues/sticks on, that way the fastening is reclosable if it comes loose. Otherwise we will need to organise a better adhesive mount than just hot-snot. I've tried to make the joint as secure as possible (cleaning the mounting surfaces, overlapping the glue to the top side) but it's likely to last about as long as when it was first attached.
