### ISSUE TITLE
Improve the look of the Main Space

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#48]
In order to get good photos, as John has said in #47, we need to organise and generally spruce up the main room.

There have been murmurings of a Hack the Space day to help with this, which I'm happy to organise if no-one has any objections.

**Comment by amcewen** [comment]
@DoESsean likes the physical social network in Dinky (right now).  He'll buy some thin masking tape, and seed the wall with a list of interests/activities that people then link their card to.

**Comment by Red-Violet** [comment]
# Issues to tackle:

## Lack of storage and to encourage a tidier space

When I come into DoES I do notice the continued piles of people various projects or bit of ongoing work, stock that might be used later or whatever it is. This is currently making the main space very untidy and possible off putting to potential hot deskers (especially designers). I would like to propose some investment in lots of storage in the main space that is available to people with permanent desks. This is to help clear some accumulated stuff that isn't used on a daily basis from around everyone’s desk. I am not proposing a clear desk policy but a clear floor policy at the very least!

If we get storage that is practical but with a fun edge, maybe some coloured shelves or cupboards would also make the room fresh, stylish and cared for.

As DoES focus is often on the idea of a community space I think having plenty of storage can allow for people who use the space all the time have what they need while not over whelming new comers with the idea that if they want a nice space to work they have to make that happen.

## Desks

The desks are all miss matched and some are better quality that others. I believe that as there are now other hot desking spaces opening up, DoES should offer some reasonable quality basics should as a nice desk and a comfortable chair. If the environment for people to work in is comfortable then new users are likely to come back. As it currently looks and feels to me it is something that may be off putting. 

It was mentioned that permanent desk people would get pedestals and @DoESSean suggested to get new desks with draws included. I like this idea and I think it would be good to find a couple of styles of desk that would compliment the space so if it was a buy as you need scenario then you will always buy the same desks so in time the stock improves and looks better. If someone wanted to buy a desk to use and donate it to DoES that would work nicely too however, we would ask for it to be chosen from the list so it benefits the overall style of the space too.

Hot desking is something that needs to be more obvious, I would like to propose that we try to create a hot desking area that is made up of dinky style tables and office chairs so it is easier for people to see where to sit. Some coloured table tops would make it nice and fun with out costing too much.

Chairs and Desks are very important to a work environment so I do think it is something to strongly consider.


## Decoration

I would like to propose a Dinky style re-fit where we decided what is most important and what we want from the space.

Having had a discussion with @DefProc he mentioned the general consensus was that it needs to be marketable.

I am aware that DoES does not want to be a slick design office or a bland office space, it needs to be a practical space that also looks attractive. I think a coat of white paint plus a fun colour (not overwhelming) and nice looking storage would really help to begin with. Later if we can replace desks and chairs than that will improve the space in the long term.

# The Fridge

The Fridge seems to be a space that get used but, probably not a often as it could. 

I would like to use the space much more practically. For example adding low-level storage along the wall behind the door and some taller storage to the side of the white board. 

This room would do well if it had a purpose such as a space set up for video conformance calls (@DefProc has had some ideas). Also it would be nice to add a mini bar in there too, so the spare fridge stocked with water, cans and snacks and it can maybe have the cake in there (@DefProc had an idea of a cake or no cake sign on the door). I would like to paint it and add a coloured wall in there too so it feels part of the main space.

# Room 29. 

Only some suggestions a long the lines of it needs some more storage as there is a lot of stuff around everyone’s desks and maybe a paint so it isn't so dull and grey. But that is all up to the people that work in there. 

I would like to suggest a tidy up day for everyone who has a permanent desk to try and stop the overflowing boxes and stuff spilling out over the floor? 

# Use of Spaces within DoES

DoES tries to encourage community and likes to bring people in and to be very inclusive of everyone who comes and joins in on Maker Days, events, working permanently or temporarily. This is one of the best part of DoES as a business.

I would like to invoke Community Spirit! 

I have noticed on my visits to DoES and when working, that Dinky and the Workshop or the main community spaces and get a lot of use from many different people. I would like to introduce a code of community spirit when hiring or using those spaces. I know that @DefProc is the technician and part of his role it keep the workshop in order and the spaces DoES has looking ok. However, the community that uses the spaces also need to take responsibility.

For example I would like to ask all who use the workshop as part of hiring the space that they are also responsible for clearing away any tools they have used and to put them back in the correct place, clearing away dust they have created, put rubbish in the bins and basically tidy up after themselves. It makes it very hard for the next person to work, so tidying up is for the common good. 

# Dinky

I would like to ask that when people use Dinky for an event that they are to put it back as they found it. For example with 4 red tables in the middle with the black and white chairs around it, any other chairs are put back away and all glasses, beer can etc. are taken away. I believe this is important so it not left to the next person or group who want to use it to clear it before they start.

I intend to put this sort of information out in the spaces so people know what is expected at the end of a hiring sessions or event, *a la* village hall rules.

Also it has been mentioned that there has been damage to the paint through taping things to the wall. If Dinky is to remain a nice hire and marketable space it will need to be looked after. If we can get some presentation boards that would fix any further problem. #139

# Plants

I love the potatoes! The potatoes are such a good idea and I think it will be cool when they are ready and we can all have DoES ground potatoes!! Are they internet connected potatoes??

However, I do have a concern about plants. Plants need to be looked after otherwise they die and I am worried that should the lovely gardener be away for some time that this is the only inevitable situation. Having plants in the space looks nice but, if no one else is tending to them then you just get a room full of dead plants and that is not going to look great. As the person attempting to make DoES an attractive space we need something that is low maintenance and robust so it doesn't matter if you leave for 2 weeks. Also there are lots of plants too which is a lot of work to keep on top of so I would like to ask you not to bring in any more plants for the moment. When we re-design the space properly later then we can include the best place for plants and how many, so it is as easy as possible to manage without you.  Maybe there is a project in days since last watered!

# Child Care

I have been thinking for sometime of how to get back into working in DoES with Sam and I have a few ideas that might work for other mums too.

Having Dinky as a crèche working area. So to provide a play pen, maybe some toys, a high chair, some feed things like a bottle warmer and soft spoons and a changing matt. These I am sure can be donated if we asked I know we have some stuff we could bring in to use. Also offer self crèche working days so Dinky is only used for that on a particular day a week or can be booked on request. By having some child friendly things will just make it easier and encourage mothers to come in as a group so there is help around if you need to use the workshop or whatever. It is just an sketchy idea but possibly something to build on.

**Comment by DefProc** [comment]
All broken out then?
