### ISSUE TITLE
status.doesliverpool.com needs updating

### ISSUE THREAD

**Issue by aubergine10** [DoESLiverpool/somebody-should#490]
Due to label changes in `somebody-should` project ( #487 and #477 ), the http://status.doesliverpool.com/ site is currently not detecting errors logged in the issue tracker.

I've updated the config and [committed](https://github.com/DoESLiverpool/status/commit/60444fdc2433546c7ec9c21cf005d7d24584f68c) the changes, but don't have access to push to the live site.

Could someone with sufficient privs please upload the new config file?

**Comment by DefProc** [comment]
I think we have to poke @skos-ninja for that job…

**Comment by aubergine10** [comment]
Already poked via linked issue DoESLiverpool/status#3

**Comment by skos-ninja** [comment]
Will sort it shortly as I'm currently travelling.

On 3 May 2017 5:29 pm, "Guy Fraser" <notifications@github.com> wrote:

Already poked via linked issue DoESLiverpool/status#3
<https://github.com/DoESLiverpool/status/issues/3>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/490#issuecomment-298963712>,
or mute the thread

**Comment by skos-ninja** [comment]
Has been sorted.
