### ISSUE TITLE
Website doesn't appear to have comments enabled

### ISSUE THREAD

**Issue by aubergine10** [DoESLiverpool/somebody-should#492]
It would be good to allow community to provide feedback on blog posts, etc., on the website (assuming we can overcome spambots - but there's lots of WP plugins to help with that).

A far as I can tell, the issue is possibly related to our use of Discourse? I've not used it myself, but when adding/editing posts on the site a message keeps popping up at top of screen:

> You have not set your Discourse username. Any posts you publish to Discourse will be published under the system default username 'system'. To stop seeing this notice, please visit your profile page and set your Discourse username.

Probably something to discuss at web meeting?

Will likely require a WP admin to resolve, preferably prior to building move.

**Comment by DefProc** [comment]
This was covered in #222 

We didn't ever check and reply to real comments, and almost all of them were spam (approximately 1999 out of every 2000 comments were automated spam)

I'm assuming the discourse warning is because you don't have a discourse username using your email address, so it can only notify new discourse threads as being from the default "system" user. You can sign up for a discourse account at: https://doesliverpool.discoursehosting.net/

See also #306 about Discourse.
