### ISSUE TITLE
Fire Safety Precautions

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#511]
We are currently out of step with required fire safety precautions, not just in the workshop, but across all of DoES' rooms.

We've had a couple of quotes from fire service companies that need looking into and a decision making. So far, we have been told that we need C02 and Water extinguishers in each of the three rooms (main room, workshop and Dinky), plus yearly servicing.

If there are any questions that you think need addressing and clarifying, please let me know and I can factor these in in any future discussions.

**Comment by PeterEinig** [comment]
I left a message for Jackie 1050 re helping me helping you. I have the knowledge you need possibly. Waiting for a reply. Also at peter.einig@btinternet.com

**Comment by johnmckerrell** [comment]
It looks like the other tenants are using Simon Walter from Rhino Safety for:

* Fire Risk assessments
* Legionella testing 
* Asbestos Register (Of which there is none so dont worry)
* Health & safety policies and procedures etc for communal areas

Doesn't look like there's a group discount but I imagine it might be quicker to go with them as they'll be in the building already (just listing a "pro", not making a recommendation)

**Comment by cheapjack** [comment]
This may not be the right place (new issue?) but wondered if we made need advice from a fire officer (local frie brigade can do this for free I believe but not sure) on fire escape procedure for any people with limited mobility given lifts are usually out of action/dangerous in a fire. This could be identifying a refuge (cant seem to find latest plans to check there prob. is one already..) or getting hold of a special chair for carrying (by identified hench members) people down the stairs. what do you reckon @Robotorium ? 
I've tried to find previous issues thinking of this but along the way ive added a Building: Accessibility label so we can search for them quick if thats ok happy to remove if Im not following latest label rationale. Apols if this already covered elsewhere

**Comment by Robotorium** [comment]
I'm sure there is a disabled refuge near the stairs, but I haven't looked
at recent plans. Because the disabled refuge would technically be outside
the actual space, I guess it might not be on the more granular plans? There
is one by the stairs, but it would be good to make sure people are clear on
the procedure for informing firefighters that we're in there, if we are!

2018-03-27 18:08 GMT+01:00 Ross Dalziel @cheapjack <notifications@github.com

**Comment by Robotorium** [comment]
Sorry, I'm in the middle of some work so my brain isn't entirely with us -
not sure why I repeated that it's by the stairs quite so often!

2018-03-27 19:38 GMT+01:00 Snoof Snoofington <snoofers@gmail.com>:

**Comment by johnmckerrell** [comment]
You don't appear to have assigned the Building: Accessibility label to this issue, I notice there's an existing "Accessibility" label too. 

Don't think this is the wrong place to ask though. There's definitely an assigned refuge but don't know of any provision for chair or any other facilities.

**Comment by Robotorium** [comment]
It's just a nook by the stairs, it should in theory be signposted (by the
building, not by DoES) and just needs to be kept clear so that if there's a
fire, any wheelchair users or people who can otherwise not get safely
downstairs without a lift can hang out and wait for firefighters to come
get us.

2018-03-27 21:57 GMT+01:00 John McKerrell <notifications@github.com>:

**Comment by cheapjack** [comment]
Great did remember it being mentioned sorry @Robotorium ! but trawling thru issues could not find it. We can just make a note in our own procedures that this is our plan but this might come under wider plan to evacuate the whole building really which im sure jason & co have in place. Maybe `Building: Accessibilty` not necessary now unless we want issues specifically about the building seperate from general accessibility but ill leave both in for now but delete if you disagree. Also didnt spot existing label sorry...

**Comment by amcewen** [comment]
The fire risk assessment was covered in #1067, so I think this issue is about:

* Ensuring we have the right number and types of fire extinguisher
* Seeing what needs to be done re disabled refuge.  There definitely isn't a sign by the main door (which is where I understand the refuge to be).  Is that all that's needed?  Something like [this refuge sign](https://www.safefiredirect.co.uk/fire-safety-signs/fire-safety-signs/fire-safety-signs/disabled-refuge-signs/luminous-refuge-point-keep-clear-sign-photoluminescent-(luminous)-rigid-pvc-300-x-200mm.aspx) I presume?  I've pinged Jason to check with him about it.

**Comment by johnmckerrell** [comment]
@amcewen did you get anywhere with Jason putting a sign up?

@DoESsean can you ping Rhino and 1 other company (one of the ones we've previously used, actually the people we used to re-fill our CO2 ones could be good) asking about prices to assess our fire extinguisher provision? I don't believe we need them to do a fire risk assessment and other things, just tell us how many fire extinguishers we need and provide them.

Might be we can just buy a load ourselves although I believe you have to "provision" them so just getting off Amazon may not be enough.

**Comment by amcewen** [comment]
Jason is going to put a sign up (if it's not up already - he showed it to me the other day, so it's in progress if not already done.  Will keep an eye out next time I'm up in the office)

**Comment by johnmckerrell** [comment]
The sign is in place.

**Comment by JackiePease** [comment]
Does anyone know if the fire extinguisher provision assessment was completed / know who our preferred supplier is at the moment?
We need to get a CO2 extinguisher for Sheila and to check whether the others need refilling

**Comment by johnmckerrell** [comment]
No I don't think it was.

John

**Comment by DoESsean** [comment]
As of today, we're officially compliant with everything, so I'm closing this.
