### ISSUE TITLE
Gerald producing slightliy distorted output

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#517]
Large circular pieces cut for the Knitic were slightly ovoid in shape and had to be filed down (approx. 3mm difference across 375mm diameter). 
Patrick suggested this could be a laser focus problem. 

Also when cutting out cardboard rectangles, a few were out by a few millimetres in one corner.

**Comment by jackie1050** [comment]
John Cain asked if we could possibly set aside some time for maintenance on Gerald, particularly looking into the alignment issues (likely that stepper motor wear is the issue - if they have potentiometers, we may be able to adjust the voltage to align them)

**Comment by DefProc** [comment]
There's currently a question on if the x-axis has become misaligned, which could account for the distortion, some skipping today (if it increases the guide rail friction), and why I had to run a mirror alignment at the end of last week. 

I'm less convinced by the motor wear being an issue, but if other belts are reaching the end of their service life, belt wear *might* have allowed one side to skip a tooth.

**Comment by DefProc** [comment]
Right, this is fixed, and Gerald is running normally again.

Cause: The right hand belt had slipped when the loose bearing cover jammed against one of the right y-axis linear bearing mounting bolt heads. A worn belt, loose mounting screws for the x-axis end-plates (both ends) allowed the belt to skip teeth and move out of square, instead of just stopping the axis.

Symptoms: 

 * cutting circles produced ovals at around 45 degrees to either axis,
 * occasional "stoppages" on movements up in the y-axis at several places (but not always),
 * stops caused a slight jump backwards, instead of just a pause (as from motor overtorque freezing)

Fix: 

 * jammed the bearing cover that is missing a screw and applied loctite to the join to try and stop it hanging down, 
 * realigned the x-axis (loosened one side of one shaft joiner at the back to allow free movement then tighten when in-place) 
 * tighten the 4 countersunk machine screws that attach the horizontal plate at each end of the x-axis to the bearing to prevent free play.
