### ISSUE TITLE
One of the internal fans in Sophia isn't operating

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#525]
There are two fans to push air through into the controller area of Sophia.  One of them isn't operating at the moment, so we need to work out why and replace/fix.

**Comment by DefProc** [comment]
The furthest one has only been running while the door is closed for a little while now, and some smoke came out the other day, so it's likely dead. 

If so, it'll need replacing like the other one #90 — 100mm/4" diameter, 240V

 - [ ] buy a new fan
 - [ ] replace the fan

**Comment by stevesparrow** [comment]
Is this something that is likely to damage the laser if it's not done soon?

Can we identify a part for Sean to order.?

Thanks
Steve

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DefProc** [comment]
It's unlikely to damage anything in the short term, the fan ensures airflow goes from the controller area into the laser cutting area, rather than the other way round. There is a second fan that is doing the job at the moment, and the original fitment had two fans in opposition (for some unfathomable reason). 

It is worth fitting a replacement as soon as is practicable though. Something like this [Sunon fan](http://uk.rs-online.com/web/p/axial-fans/0126199/) should be ideal. (ordered)

**Comment by Dowz77** [comment]
Do we know where this fan is? If so I'll fit it this week.

Also looking at how much contamination there was on the HV psu is there a fresh air inlet or are the two fans pulling air from the electrical cabinet which is then drawing smokey air from the cutting area?

**Comment by magman2112** [comment]
I found a suitable replacement fan in the Laser Spares cupboard, so I fitted this today. Whilst fitting this, I noticed that the mains cables for the fans went through an un-insulated hole in the hole in the metal chassis, which is unsafe. I drilled a larger hole and fitted a grommet that @amcewen had, then re-fitted the mains connections for the fans.

Both fans are now working correctly.
