### ISSUE TITLE
Create a wishlist for the new space

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#534]
Probably worth going by room, but it's worth collecting an idea of what the community wants from the space, especially as the move is upcoming.

eg.

## Workshop

 * Solder station,
 * Laser cutters,
 * 3D printer area,
 * box storage,
 * Clear workdesk for laying out, small run production, photography, timelapse, but with no storage under/around it.

**Comment by ajlennon** [comment]
A couple of my thoughts fwiw:

- comfy chair sitting down area
- nespresso machine
- pool table
- bar billiards table
- creche facility
- bio-engineering workstation with DNA analysis and modification tooling
- quantum computing workstation with facilities to entangle particles
- overnighting hammocks
- belgian beer bar
- very fast broadband
- cake garden

**Comment by paulgeering** [comment]
* More wishes

**Comment by DoESsean** [comment]
If we have the space, it might be quite cool for there to be, for want of a
better phrase, theme banks of desks. So, if you looked at the main room
now, where Adrian sits, for example, could be the equivalent of the Aztec
Zone, with John's cluster being the Industrial Zone and mine being the
Ocean Zone (I liked when they brought in the Ocean Zone).

I mean, obviously not exactly that, but that.

**Comment by DoESsean** [comment]
I'd also like high desks either attached to or right next to the laser
cutters - breakfast bar height. That way, people are able to get on with
work or whatever without having to leave the cutters unattended, which
seems to have become a slight issue.

**Comment by ajlennon** [comment]
Was chatting with @jackie1050 tonight...

Is there somewhere else that support for people with disabilities is discussed, or might we consider putting a note on the virtual wall somewhere for what DoES would wish to provide to community members with disabilities, both from a minimal legal set of requirements, and then also from the perspective of the wish to be an open and welcoming community.

**Comment by johnmckerrell** [comment]
That the space should be accessible has always been a requirement for the move. If there are specific things you have in mind though it would be good to list them, probably start here and we can break it out if needed. 

--

**Comment by ajlennon** [comment]
I'm thinking it would be useful to know what people have found challenging about the existing space in the Gostins Building.

In particular I suppose questions coming to mind at present are:

- can we confirm that the proposed space is all on the ground floor?
- within that space are there any different levels that people in wheelchairs would find challenging?
- are there any steps entering the building? If so do we need to speak to the landlord about ramps?
- what is the situation with the toilet facilities? is there a toilet suitable for disabled use?
- will we bear in mind requirements for access when arranging layout of desks
- similarly requirements for access when laying out workspace.

**Comment by johnmckerrell** [comment]
The one aspect I know has caused difficulty that we completely missed originally with Gostins was that for a person in a wheelchair on their own the entrance doors to the building were too much to manage. We have raised this with the new landlord and are expecting that doors will be mechanised so that this won’t be an issue.

The space is actually on the 1st floor but there will be a lift available. The 1st floor space is much nicer than the previous ground floor space we looked at and would always have been our preference but only became realistic once the landlord decided that there would be a lift going in.

Within our space we don’t expect there to be any level changes.

There is 2 small steps on the way in currently but we are expecting a ramp to be put in.

There will be a disabled toilet on the ground floor but it’s likely that a disabled toilet will be put in within our own space too.

And yes we will be bearing it in mind when laying out the space although that process is only just beginning so feedback always welcome on specific issues that might come up.

**Comment by ajlennon** [comment]
Great. In particular I am aware that the fire alarm situation in Gostins caused difficulties. (Not helped by the damnable smokers out the front setting the alarm off every five minutes).

In this situation my understanding is that lifts couldn't be used so people with limited mobility had to resort to trying to get down the stairs themselves.

Perhaps something we need to consider an answer to if the new space is on the 1st floor.

**Comment by johnmckerrell** [comment]
Ah, yes that would certainly be something we would need to consider. One or more evacuation chairs would probably be the answer.

**Comment by amcewen** [comment]
I think the time for adding things to a wishlist for "before we move" has now passed.  Any future wishes can be spawned as individual issues on their own.

I think the accessibility issues are covered elsewhere, and I've copied the couple of things that seemed they might get missed over into issue #674.
