### ISSUE TITLE
return or replace the kitchen passes

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#539]
## Specific

As part of the normal attrition rate, the number of kitchen passes has dwindled to one, with no tag. We either need to cancel and replace the missing tags, or recover them from their current hiding places.

## Measurable

Have at least 2 tags, identified as kitchen passes, available in the main room

## Achievable

 - [x] laser cut tags from [somewhere-safe](https://github.com/DoESLiverpool/somewhere-safe/blob/master/Workshop/LaserCut/KitchenPass.svg) (should be different colours from each other)
 - [x] assign new RFID tags,
 - [ ] cancel any missing tags

**Comment by johnmckerrell** [comment]
I see three kitchen passes in the config and ISTR only 2 are in situ so we need to work out which one should be cancelled (and shall we remove the spanish inquisition audio for the kitchen pass too!)

**Comment by huffeec** [comment]
One of the passes was used by one of the Christmas tree team to get access
early this morning to collect their tools. It should have been left in the
workshop. Probably by the recycling bins.



On 1 Dec 2017 13:15, "John McKerrell" <notifications@github.com> wrote:

I see three kitchen passes in the config and ISTR only 2 are in situ so we
need to work out which one should be cancelled (and shall we remove the
spanish inquisition audio for the kitchen pass too!)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/539#issuecomment-348491883>,
or mute the thread

**Comment by johnmckerrell** [comment]
I thought I'd seen two recently but there was only one fob and one acrylic keyring so I've attached a new fob to that, added the new fob to config and removed any other fobs listed as Kitchen Pass.

**Comment by amcewen** [comment]
There were two recently, but at the moment Mick has one of them so he could get in to sort the aircon
