### ISSUE TITLE
We need guidance for eve-w/e workshop access and lone working

### ISSUE THREAD

**Issue by JimSparrow** [DoESLiverpool/somebody-should#541]
Following from issue #246.

With the imminent advent of increased out of hours access to the workshop.  We need to think about a new set of Induction procedures, which both ensure people have an excellent knowledge of all the different tools they may need to use, and clearly codify which machinery they can and cannot use when they are on their own.

I think this would involve better identifing the induction for workshop use for out-of-hours members, and ensuring the that all out of hours members have an induction for the whole workshop as part of their access.

I'd really appreciate any help here, on the sorts of things that need to be included in the induction, any out of hours procedures we may need, and what is and isn't appropriate for out of hours access usage.

At the same time we might follow up on grievance proceduresfor people using the space inappropriately.  I've included links from the previous issue below.

Thanks, Steve

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stevesparrow** [comment]
To be more specific.  Would anyone like to give this a go?

**Comment by amcewen** [comment]
From organisers meeting, we're still looking for someone to lead driving this forward.  Not necessarily to make all the decisions on it, but to gather options, issues, etc.

**Comment by DoESsean** [comment]
We need to check with current insurers about the possibility of increased premiums due to extended hours.

Lone worker vulnerability is an issue - example given at the organisers' meeting was of a beeper for anyone working on their own, but another discussion is then around who is on the other end of that beeper.

One proposal was 24hr access when available - essentially, offer far extended access and find out when people are actually interested in being in. Costs are also a factor due to increased heating and lighting of all hours access.

**Comment by DoESsean** [comment]
Co-workers would expect 24 hr access, as it's available at other spaces. Workshop is another matter.

**Comment by DoESsean** [comment]
Look into Nottinghack's policies, and how they might transfer.

**Comment by PeterEinig** [comment]
Left a message today for Jackie1050, I think. Lone working could come under H&Srisk assessment. Hmmm something I have knowledge about. Asked to set up a meeting as my interest is Rasp. Pi and robots. Available at peter.einig@btinternet.com as well.

**Comment by amcewen** [comment]
I don't think this impacts how we lay out the new space or needs to be done before we're in, so removing the `Move` label

**Comment by johnmckerrell** [comment]
This was discussed in the community meeting yesterday:

> Logistics of 24 hour access - issues raised around this included emergency contacts, whether we would be comfortable with random people being able to be in the space unaccompanied, safety issues regarding tiredness, and so on. We are aiming to try and get this sorted as quickly as possible, and it will be discussed at the Directors' Meeting next week

https://github.com/DoESLiverpool/wiki/wiki/CommunityMeetingAgenda20180517

We did list a few specific concerns and questions to resolve:
 * No sleeping in the space, this is not your bedroom or house, etc.
 * How to secure the building, e.g. if you're going to be in very late it would be best to close the shutter,  after 9-10pm and to make sure people know how to do this.
 * What to do in case of emergencies (e.g. dial 999 first, how to let DoES know something happened)
 * Comments on bringing other people into the space, is this allowed?

We have it on the list to re-visit this at the Directors meeting on Monday and try to resolve these questions.

**Comment by johnmckerrell** [comment]
We should have a separate new induction form, with a question to confirm you’ve filled in the general induction form.

We should also have the information written up (wiki page?) to give to people. First draft is here: https://github.com/DoESLiverpool/wiki/wiki/OutOfHours

**Comment by DoESsean** [comment]
Regarding inductions.

I think we need to do some general housekeeping around permissions, inductions, etc. It would be worth us keeping a canonical list somewhere of who has access to what, and who has been trained on which pieces of equipment. It may well be worth doing some big sessions, over the space of a couple of weeks maybe, to get people up to speed with all the equipment we've NOT previously had inductions for. Although they aren't as obviously dangerous as the lasers or CNC, the heat press gets really hot, the soldering stuff is a fire risk, all that kind of stuff. 

For a lot of people it will be reinventing the wheel (and depending how people feel, it might be worth implementing a system of self certification on a lot of stuff) but I think it would be useful for us to have a better handle on exactly who can do what, and who needs more training. 

This would then tie into the out of hours stuff. Once we have the ground rules properly nailed down (and stuck on the wall), we can have out of hours inductions so that people know the drill if they're here on their own at night, and it would just be another permission ticked off.

Yes, it would be an administrative pain to begin with but, along with the other things that we need to do and never really get round to like safety instructions for all the equipment, once it's done it's done, and it would be a huge weight gone.

**Comment by johnmckerrell** [comment]
Looking at this I think we do have this covered now, we have an out of ours induction, including access requirements. Inductions on specific pieces of equipment too. I'll close it but if anyone thinks I've missed anything feel free to re-open!
