### ISSUE TITLE
Look at whether there are any "no strings" funding sources to assist with the move

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#547]
Without taking a position on whether DoES would wish to be involved with funding applications it might be helpful to document if there are any relevant funding sources available for DoES activities. 

If not then the whole question obviously becomes much easier to answer.

Initial thoughts are that minimal requirements would be:

- grant not loan
- related to DoES community charitable status
- no restriction on DoES self-volition 

Actions that funding would support might include contributions towards

- actual move costs 

Man in a van etc.

- costs of outfitting the new space 

Furniture and fittings, tooling for the workshop

- seeding technology innovation 

Providing a space for people to be technology innovators in the North West

- mentoring and apprenticeships 

Providing a platform for DoES affiliated businesses, or those making use of DoES services, to engage with young people (and perhaps older people) wishing to embark upon a career in the technology industries. 

May involve training, project work, internships, apprenticeships.

**Comment by ajlennon** [comment]
@DoESsean 

I found this will looks like it might be the type of thing

"iAMDigital is a £1m fund from Nominet Trust and Creative England, investing in organisations working to increase digital inclusion and digital skills in England"

http://www.nominettrust.org.uk/

Although if we wanted to get an application into iAMDigital we'd have to do it by **Monday** !!!

**Comment by ajlennon** [comment]
Hmm - #IAmDigital seems to be an interest free loan, not a grant, so perhaps less interesting...

**Comment by SayBeano** [comment]
I don't know if this is any use: [Lottery cash](https://www.biglotteryfund.org.uk/global-content/programmes/england/awards-for-all-england)

> You can apply if your organisation is a:
>  - voluntary or community organisation
>  - not-for-profit company or Community Interest Company
>
> National Lottery Awards for All has three funding priorities and you must be able to tell us in your application how your project or activity will:
>
> - bring people together and build strong relationships in and across communities
> - improve the places and spaces that matter to communities
> - enable more people to fulfil their potential by working to address issues at the earliest possible stage.

> We can fund:
> - equipment
> - one-off events
> - small capital projects
> - staff costs
> - training costs
> - transport
> - utilities/running costs
> - volunteer expenses.
>
>  We can’t fund:
> - alcohol
> - contingency costs, loans, endowments or interest
> - electricity generation and feed in tariff payments.
> - paying someone else to write your application
> - political or religious activities
> - profit making/fundraising activities
> - recoverable VAT
> - statutory activities

**Comment by aubergine10** [comment]
https://www.beehivegiving.org/ - funding finder tool

http://www.internetsociety.org/what-we-do/grants-awards/beyond-net-funding-programme - you'd have to be member of internet society

https://www.spacehive.com/

https://www.biglotteryfund.org.uk/uk-wide/funding - this can be used for all sorts of things, talk to Liverpool Transition Network who can put you in touch with groups that have used it

https://www.biglotteryfund.org.uk/powertochange - bigger version of above

https://www.lotterygoodcauses.org.uk/funding-finder

BTW, in terms of funding/grants/whatever, the aim is generally to accelerate something. Depending on funding supplier, that would either be more permadesks (accelerate capacity to bring in more money) or workshop space/equipment (accelerate better features available to community).

**Comment by stevesparrow** [comment]
Thanks all,

A note for anyone else, this came out of a conversation at the Organisers meeting (for which there are no notes yet), around one-off funding to support the move.  We've also discussed previously crowd-sourcing (inc spacehive) for this area.

Alex - I agree, interest free loan not quite so good right now.  It's also worth checking eligibility at the start, as though we're non-profit, we're not a charity and we could *technically* take out funds if we choose.  Just an FYI.

Awards for All could be interesting.  I think it's the only lottery fund we could be eligible for without a much bigger programme with staff etc, focusing in a particular direction.  I know it reasonably well (I did 8 of them last summer), and I *think* it would be a stretch to match their target areas, but we should look properly.  They will (all) have monitoring requirements and outcomes, and so that will be the interesting conversation ;).  We should def. look.

The others are new to me.  May I suggest that the starting point (for any application really, and to know whether we would meet the funding criteria) would be to identify:

- What we would want to fund
- What it would cost
- What the outputs would be (what would happen as a result)
- What the outcomes would be (What would be the positive change for individuals as a result)
- Who the people are that things would change for
- A starting sense of how we would measure that.

It might be there are smaller pots that don't require this, but all but a handful would want at least an idea of these.  Happy to talk with anyone wanting to get stuck in, if useful.

Cheers
Steve

**Comment by ajlennon** [comment]
@stevesparrow 

My bad. I don't want to divert the thread but I recall somebody mentioning something about options for legal structure for DoES. Are there any notes anywhere about pros and cons of CIC status versus charitable status and so forth?

**Comment by stevesparrow** [comment]
Somewhere.  I was doing this and got rather stuck (and a knowledge/discovery level).  The primary question is can we be a charity and still be DoES in all we are.  I need to go back to LCVS for help.  If you wanted to come with me - always welcome.  The other question was limited by guarantee rather than share, which is where we run into issues.  Not sure there is much on github, but I can update it shortly.

**Comment by ajlennon** [comment]
I'll go anywhere if they have decent coffee. Let's make a date?

**Comment by stevesparrow** [comment]
Just a quick note to say that if you do want to have a look at applying for some one off funding  to support us as we move, that could be great.

It would be good if you could have a chat with someone about what we'd be applying for, and needing to deliver, before spending a lot of time on this, just to make sure we'll stay in the same place, are aiming for the same thing, .  I'm happy for that to be me.

**Comment by stevesparrow** [comment]
@ajlennon I've emailed Liverpool CVs to ask for a new appointment, or additional support, and copied you in.  Thanks.

**Comment by johnmckerrell** [comment]
Making a note of interest free loan type stuff wouldn't be the worst idea. Interest free certainly better than not interest free! And if anything is "only" offering match funding then it may still be an option, could run alongside crowdfunding perhaps (or other funding if we were successful with that).

**Comment by stevesparrow** [comment]
Interest free certainly better than not interest free!

Yes, that's definitely true. :)

On 28 Jul 2017 8:17 p.m., "John McKerrell" <notifications@github.com> wrote:

Making a note of interest free loan type stuff wouldn't be the worst idea.
Interest free certainly better than not interest free! And if anything is
"only" offering match funding then it may still be an option, could run
alongside crowdfunding perhaps (or other funding if we were successful with
that).

> On 28 Jul 2017, at 17:58, Steve <notifications@github.com> wrote:
>
> @ajlennon <https://github.com/ajlennon> I've emailed Liverpool CVs to ask
for a new appointment, or additional support, and copied you in. Thanks.

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/
DoESLiverpool/somebody-should/issues/547#issuecomment-318707582>, or mute
the thread <https://github.com/notifications/unsubscribe-
auth/AABqa0qO3khTEApt1j--1f_naIteb9CTks5sShNRgaJpZM4OmZvI>.

>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/547#issuecomment-318740040>,
or mute the thread

**Comment by huffeec** [comment]
On the lottery side I think Awards for all is the only option for DoES at the moment. They look for track record delivering funded programmes for their other strands. They, and most funders now are willing to fund constituted cic's as well as registered charities. So there's less incentive from a funding perspective to take on the additional regulatory burden of a formally registered charity. 

There are often small pots available from places like the community foundation too. The tricky bit would be finding one that was prepared to cover move costs. Funders look for community benefits and generally numbers of beneficiaries. There's a lot of does activity that could potentially be fundable but organisation moves, like a lot of core costs, are difficult to fund.

**Comment by stevesparrow** [comment]
Thanks Chris, that's good to hear about that CIC thing, and good advice all round.  We had talked about refurb costs, and I agree it would be hard, and would I think need tying to increased activity of some kind?  Do you think that might stand a chance?
S

**Comment by zarino** [comment]
http://awesomeliverpool.co.uk! It's only £500 but DoES moving to a new place is probably awesome enough to qualify you!

**Comment by johnmckerrell** [comment]
Any updates on this? I've been getting "Funding Central" emails for a few weeks but most things need to work in a specific locality or with disadvantaged demographics which we don't tend to do, certainly not simply by existing.

**Comment by DoESsean** [comment]
I don't think there's been much movement on it for some time.

I'm torn as to whether to leave this open or close it - if there are no-strings funding options available, then it makes sense to keep this live for the future. However, given that Christmas is fast approaching and we'll be moving within a few weeks after that, the idea of us being able to get an application in and accepted before that is pretty unlikely.

**Comment by SayBeano** [comment]
I've just remembered [I saw this](https://pineapplefund.org/) and tought of DoES, after I realised MakeFest isn't officially a thing that can benefit as it's not "set-up" to be identified like that, but DoES is...anyway - I read charity but it actually says "non-profit".

**Comment by SayBeano** [comment]
FYI - they've made smaller transactions than the millions you see to charities that've been advertised on the page...presuming therefore that it's not just big orgs that win...

**Comment by johnmckerrell** [comment]
Worth a try, I'll apply.

**Comment by johnmckerrell** [comment]
"What is the maximum account you can accept, and reasonably use?"

Well there's a question!

**Comment by johnmckerrell** [comment]
https://www.fundingcentral.org.uk/SchemeList.aspx?RF=NEWS&WCI=htmResults&WCU=CBC=View,DSCODE=OTSSCMLIVE,SCHEMEID=248-S41517,UDATA=SCHEMEVIEWBACK=HOME

That one almost felt applicable "Be able to demonstrate experience of working in and/or with disadvantaged communities." surely the whole of Liverpool counts these days? I guess they'd actually want more specific examples which we probably couldn't provide, and this is supposed to be for "projects" rather than general running costs, so it would require someone being willing to actually run a  project.

**Comment by amcewen** [comment]
I think this has been superseded by #704 ;-)

On a more serious note, we don't seem to have gotten anywhere with the funding things we've investigated, so I'm going to close it.

**Comment by ajlennon** [comment]
Which reminded me - can somebody with a way with words apply to Awesome Liverpool to ask them to donate their monthly £500 to our crowdfunder

http://awesomeliverpool.co.uk/#apply

**Comment by johnmckerrell** [comment]
Closing this again, I did actually ask @zarino about the chances of getting £500 towards a laser tube but we've missed November, December's not an award and even January wouldn't fit.
