### ISSUE TITLE
Update Calendar for New Laser Cutter Inductions

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#587]
@jackie1050 has put together some volunteers to deliver laser inductions.

The calendar needs updating to reflect this, and allow people to book. Jackie is happy to do this if someone tells her how, but in the meantime I imagine it's easier for @johnmckerrell or @amcewen to do.

**Comment by ajlennon** [comment]
Can you add me as a volunteer. Perhaps I could be a “floater” as I’m not always sure when I’m in but am happy to induct if about...

**Comment by jackie1050** [comment]
I suppose we'll need some sort of option for inductees to give preferred times? (Darren said he might be available on an add hoc basis too).

**Comment by DefProc** [comment]
The way inductions are currently set up, is that you add a calendar entry to the small and large laser cutter calendars on the times that you want to make available. This all works because youcanbook.me uses the google calendars as the true availability state of each laser cutter, one per piece of equipment. 

The only requirement for being able to add or change induction slots is that you need to have `Make changes to events` access to the small and large laser cutter calendars.

Induction slots are 1½ hours long to allow 1 hour induction plus time for questions, and putting a slot on both calendars allows up to two people to book inductions at the same time. If someone books the laser at the same time, the induction slot will become unavailable; and similarly, once an induction is booked, it prevents an overlapping laser booking. 

Currently there is no way to determine which laser the inductions will be booked on, and this system doesn't allow a laser booking if there are two inductions at the same time, even though these might still leave a laser free.

For the Thursday morning sessions, I set up recurring slots from 10am–1pm (two possible slots per laser, for a maximum of 4 inductees). To let youcanbook.me see these slots as inductions — and not bookings — add `YCBM-OVERRIDE-UNITS` as the first line in the **Description** of the entry, then these slots are immediately available for inductions. 

While I used the title "Laser Induction Slot" for these entries, it might be worth prefixing that with the name of the person responsible for running the induction, to prevent confusion.

It is also possible to make the laser unavailable for booking by adding a calendar entry over the normal opening time for DoES; eg. for marking a laser as down for maintenance or repairs, or for bank holidays when DoES is closed. 

NB. 
 * for all day calendar entries, ensure that the entry is set as `Busy` as these default to `Free` in Google Calendar, 
 * It's useful to set these events a `Public` so the title appears on the laser calendars on the website, otherwise these entries are only show as `Busy`

**Comment by johnmckerrell** [comment]
My short version was going to be “copy and paste one of the old ones to the time slot you want to use” ;-)

Good point on putting the inductor’s name in though.

While having extra availability through “adhoc” sounds good having the designated slots is ideal as when we get calls or emails it’s super easy to direct people to a calendar and/or youcanbook.me <http://youcanbook.me/> page.

John

**Comment by jackie1050** [comment]
I now have access to calendars (thanks @defproc). I've added Saturday morning slots, but these don't show up when booking, as booking calendar doesn't show Saturdays. Suggest we discuss at next organisers meeting.
DMd @huffeec for a reminder on his availability for inductions. If anyone else would like to do inductions and can specify dates/times, please get in touch.

**Comment by johnmckerrell** [comment]
I thought that making Saturday available would be simple enough to fix, and it seemed like it would be but the change I've made isn't showing up. Maybe someone else can see what I've done wrong.

**Comment by DefProc** [comment]
It's because the slots are marked as `busy` in the google calendar. I've changed them to `free` and the slots are bookable now.

**Comment by johnmckerrell** [comment]
Closing this as I think @jackie1050 has sorted it out, please reopen if not!
