### ISSUE TITLE
Somebody should buy a sublimation mug heat press

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#593]
Sublimation mugs went down really well at this year’s Make:Shift:Do open day.

For the open day, we borrowed a mug heat press from Helen at Little Sandbox. Maybe we should have one of our own?

It turns out a suitable heat press is only £60, and that includes the attachment you’d need to print onto standard 11oz mugs.

https://www.ebay.co.uk/itm/301985660746

![s-l400](https://user-images.githubusercontent.com/739624/32135898-4cb297ca-bbfe-11e7-83fd-75cb591dc67c.jpg)

**Comment by johnmckerrell** [comment]
I’m not 100% sure we should. Seems like quite a limited scope of what you can do with them. Not such a general prototyping tool as the other tools in the workshop. That said maybe our community /can/ come up with uses beyond decorating mugs. 

--

**Comment by DoESsean** [comment]
The mugs were VERY popular.

I think it's worth finding out if anywhere else in Liverpool has one for
public use, and also checking with some of our workshop users as to whether
or not they would be interested in having access to this. Some of the etsy
sellers might like to add them to their stores, for example. The mugs cost
us less than a pound each, so having them available to buy for two or three
(similar to the laser materials) would be financially worthwhile.

We know that the sublimation printer has proved extremely popular so far,
and there's no reason to suggest that having another string to that bow,
particularly if, as you say, we can think of other ways to use it.

I think that, if it were a couple of hundred quid, then it might be worth
pausing to think about. However, for a relatively low price, having another
piece of hardware is a good idea. Aside from anything else, we could use it
as a value add for permanent desks/monthly membership - like you get a mug
instead of a membership badge or something.

**Comment by ajlennon** [comment]
What about putting in place a funding model for these kinds of purchases?

e.g. £60 capital outlay, buy mugs at £1, sell at £3-4 including printout, money to pay off initial outlay ? 

Then track how successful it all was

**Comment by jackie1050** [comment]
We did discuss asking for pledges to fund this, I would certainly put some money towards it. 

I've spoken to a couple of people at DoES who are interested in mugs as promotional material for their businesses or other outside interests, and I think there are several Maker night people who would like to produce some as Christmas presents.

They are also seem good as something to take away from a workshop e.g. data visualisation, and I can imagine doing that again (I realise we didn't insist on people using their pulse data on Saturday).

**Comment by johnmckerrell** [comment]
Happy to be persuaded otherwise, it just felt like something that if you really wanted you'd just pay online for but it's probably still a lot cheaper this way, especially if you only want one or two and DoES can order the blank mugs in bulk.

Glad to know Sean's going to be making mugs for everyone ;-)

**Comment by DoESsean** [comment]
As long as someone makes a design we can easily change some details on, I
genuinely would have no issue with that!

**Comment by DoESsean** [comment]
I've ordered this today using @zarino 's link. It's estimated to be with us on Thursday.

**Comment by jackie1050** [comment]
We'll need mugs too ...

**Comment by johnmckerrell** [comment]
I believe this is on Sean's desk now.

**Comment by ajlennon** [comment]
On my way.

**Comment by DoESsean** [comment]
The mug press is sitting in the workshop waiting to be commissioned. 

We need to work out where is best to get blank mugs from - I've asked @jackie1050 via email, but if anyone has any ideas, please let me know. I think we stuck our nose into Little Sandbox's order for the M:S:D event.

We now need to think about pricing and how that will work. Where can mugs be stored, is it a good idea to have them just hanging out in the workshop, etc.

**Comment by ajlennon** [comment]
Fantastic! You can put them in one of my boxes where I have the tops if that's any use.

These are the MDP Supplies ones -

Looks like about a pound ish each plus VAT + shipping presumably?

http://www.mdpsupplies.co.uk/dye_sublimation_mugs.asp

**Comment by huffeec** [comment]
I'll ask Ash from Nerdy where she gets hers from. I think she found a cheaper supplier.
