### ISSUE TITLE
Restock the sublimation printer spare ink supplies

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#595]
Ste and I just replaced the Cyan and Magenta ink in the sublimation printer, which means that we don't have any spares in those colours.

There has been talk of getting some refillable cartridges instead, as that's cheaper.  Should we get that rather than just replace those specific cartridges?

**Comment by ajlennon** [comment]
I've damaged printers in the past trying to use refillable cartridges and would be a little concerned this might happen again...

**Comment by DoESsean** [comment]
There's no doubt that the official ink cartridges are pricey (although that
should be covered by people paying for usage, I guess). I did have a chat
with a couple of people about trying some off brand replacements to see if
they would work, but no decision was made. I think they were in the region
of £10-£20 cheaper, which is a fair chunk, especially given how popular the
printer has proven to be, but are still expensive, so I didn't want to just
buy some and then find out that they're no good after all.

Does anyone have experience of those kind of cartridges for a sublimation
printer? I see no reason that it should be any different to a regular
printer (and hands up who actually buys official inks for those), but it
somehow feels like we should err on the side of caution here.

**Comment by ajlennon** [comment]
>  (and hands up who actually buys official inks for those)

I do. I've destroyed two printers so far with refillable cartridges.

I'm willing to accept that's finger trouble on my part though if others are more confident with their OWN inky fingers...

**Comment by DoESsean** [comment]
I've never used refillable inks, so I don't know how much of a pain those
are. We would need someone to take on the mantle of ownership for that,
which could be an issue if they have limited time in the workshop, and
could result in downtime for the printer which hasn't been an issue so far.

What I have suggested is that I order a compatible, but off brand, yellow
cartridge as, since cyan and magenta have just been replaced, that is
likely to be the one that runs out next. We have a legit yellow there
anyway, so if it doesn't work as we would expect, we can swap it straight
out for the proprietary one and there will be minimal loss of usability. If
it doesn't work, then we know it's best to stick to the normal ones in
future, and we'll have to put up with the cost. If it does work, then I can
go ahead and order full sets as back up for when the inks in the printer
run dry.

Does that seem like a reasonable idea?

(I'm also going to email this to Darran, as it was his suggestion about
refillable inks in the first place, but he's not currently on github.)

**Comment by ajlennon** [comment]
Ah my mistake. Apologies. Unbranded != Refillable :)

I'm in your hands. Happy to replace the inks when needed but as you can see I've not been in much at the moment.

**Comment by DoESsean** [comment]
Hmm...

Does anyone have any experience with recycled cartridges?

Whilst trying to find a place to recycle our used cartridges, I came across [this website](https://www.makingitgreen.co.uk/7207/Ricoh-Aficio-SG3110dn/) which might be a reasonable compromise.

**Comment by DoESsean** [comment]
@ajlennon, can you tell me a little about the printer cartridges? Am I able to recycle them as normal cartridges or are they special?

I'm coming up a whole lot of blank whenever I search for specific sublimation ink recycling.

**Comment by ajlennon** [comment]
You've reached the limits of my knowledge I'm afraid @DoESsean (and quite possibly surpassed it). I was going by what MDP Suppliers recommended. The original cartridges were just part of the pack I bought which included printer/inks/papers.

**Comment by DoESsean** [comment]
No problem, thanks. I might well just email MDP.

**Comment by ajlennon** [comment]
I suppose the other question we might ask is that given about 40%  or something of an existing ink cartridge seems to sit in the tubes as it were, could starting to use an unbranded/refillable cartridge mix up with what's already in there and cause a problem. You'd hope not but these printer manufacturers can be sneaky buggers.

**Comment by amcewen** [comment]
Is there anything still to be done on this issue?

**Comment by DoESsean** [comment]
Don't think so, I think it had just been left open for the discussion on unofficial inks, but seeing as we have a supplier that seems to be working well, I think it's worth closing this down.
