### ISSUE TITLE
General solution to cardboard boxes and lasercut ply scrap

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#628]
It doesn't seem good enough just to be folding and stuffing this into the trash bins.  

If we had a successful resident business mailing out product, then the cardboard would be reused for the same purpose it arrived -- packaging and post.  

But without an active consumer of this waste, we ought to have a designated area to store the most intact and useful-looking boxes, where there is a sharp stanley knife and a cutting board to help cut off the bits of plastic and break the unwanted boxes down into small chunks that are either used for sound-proofing or sent for recycling.  (We should check if chopping stuff up and keeping it separate makes it better for the recyclers, or if they mix everything in and then resort by hand at the plant, so don't like small pieces.)

Similarly, the waste laser ply would be much more manageable if sawn down into small enough pieces (what size?) and stored in a designated bin.  What's the ideal answer?  Is it safe to burn in a logburning fire given its glue content, or is the only official answer that it has to go to landfill?  

One supplier merely has the icon which says "this item can be recycled"   https://hobarts.com/3mm-laserplystandard-russian-birch-plywood-bb-

Kitronik has a datasheet for their ply that says it's biodegradable and uses carbamide-fermaldehyde glue.  
https://www.kitronik.co.uk/pdf/3mm_birch_laser_plywood_material_safety_datasheet.pdf

We could ask any advice on what to do at the question section
https://www.kitronik.co.uk/3201-3mm-laser-plywood-600mm-x-400mm-sheet.html

**Comment by johnmckerrell** [comment]
I *wish* people stuffed it into trash bins rather than piling it up on top of recycling boxes. Well, not the trash bins part anyway. I welcome any help in removing clutter from the space. We've long had a "packaging" shelf for putting packaging that is reusable onto but we do tend to get a lot of deliveries so are most likely to have more than we need. I don't believe that the recycling gets mixed so I've always assumed they're happy taking small pieces but it certainly wouldn't hurt to check.

None of the cardboard should be going into landfill anyway as we do currently pay for recycling.

I believe our current recyclers have indicated they would be willing to take plywood and possibly even the perspex but I'd need to confirm that. The Liverpool tip takes both (I'm assuming for some sort of recycling) but DoES as a business doesn't get to dispose of stuff there.

Could be worth splitting this issue though (if we don't have similar ones already) as reusing cardboard and recycling wood are going to require quite different solutions.

**Comment by johnmckerrell** [comment]
@goatchurchprime it feels to me like this could be closed now as we have cardboard and wood recycling these days. What do you say?
