### ISSUE TITLE
Gerald ghosting when engraving

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#646]
Amy reported that Gerald was having problems when engraving yesterday.  For example...

![img_9951](https://user-images.githubusercontent.com/108468/34873101-b1befb22-f78b-11e7-9f57-9a6879a6157f.jpg)

**Comment by jackie1050** [comment]
I noticed a similar issue when cutting a circle of about 60 mm diameter. I thought it hadn't cut through and did the cut again. There was a difference between the 2 lines (less than 1mm?), so that slivers were cut from the edge.

From: Adrian McEwen
Sent: Friday, 12 January, 11:29
Subject: [DoESLiverpool/somebody-should] Gerald ghosting when engraving (#646)
To: DoESLiverpool/somebody-should
Cc: Subscribed


Amy reported that Gerald was having problems when engraving yesterday. For example...

**Comment by amcewen** [comment]
It looks like it was a problem caused by the mole grips that were clamped onto the chain drag.  Here are some test cuts with combinations of clamp, no clamp, one direction, bi-directional engraving...

![](https://c1.staticflickr.com/5/4707/38771409965_b7d72a6f37_b.jpg)

There's definite ghosting with bi-directional engraving, and it's worse when there's a clamp on it.

So, I've removed the mole grips, which now means that if you use uni-directional engraving it's fine.  The mole grips were fitted after the new chain drag (part of #596) because it was fouling against the lid of the laser-cutter.  It seems to have loosened up somewhat since then, and seems to be missing the lid now.  I've run it back and forth quite a bit more this afternoon to try to loosen it even further, and I think it's okay.  We'll see if anyone has any problems with it, and reassess if they do.
