### ISSUE TITLE
Sophia stopped lasering

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#648]
The beam gave out midway through a cut and won't come back even after turning off and on again.

**Comment by amcewen** [comment]
I think I know why it's not lasering any more...

![](https://c1.staticflickr.com/5/4696/24799395127_e969afdd16_b.jpg)

There's no obvious explanation as to why it's failed, but there's no cooling water in the tube now...

Marking as broken.  We'll need to get a new tube on order, and tell anyone booked in on it.

**Comment by amcewen** [comment]
I've notified the bookings for the next two weeks.

**Comment by JimNixon** [comment]
I can come by and help get Sophia fixed up when the replacement tubing
comes in if you need a hand.

**Comment by DefProc** [comment]
Assuming the laser tube still works, there should be enough slack water pipe to cut the a short length off, without needing new pipe.

**Comment by DefProc** [comment]
Both laser cutter cooling systems were filled with tap water. 

There is some automotive coolant in the cupboard, but that would only be useful for anti-algae (as it is not chlorine based), but doesn't provide any benefit for heat capacity at normal working temperatures.

I have not used de-ionised water, because the main components are not metal, and it seemed unlikely that there were multiple metal surfaces in the water flow. 

In use, the coolant has not gone black (as for algae) or brown (as for metal corrosion), so tap water is likely fine again.

**Comment by johnmckerrell** [comment]
Is the flow sensor still used?

**Comment by DefProc** [comment]
The flow sensor is still in the pipe, and in the circuit as far as I know. It might suggest that the flow sensor is stuck open, as I would have expected it to cut the laser if the water flow stopped.

It would be worth taking it out and checking operation while the water is drained.

**Comment by jackie1050** [comment]
@johncain39 and I have changed the pipework and water as recommended above. The pump is working is working and water is flowing with no visible leaks.. 
Darren cleaned the lenses.
We attempted to cut and engrave a file, but the laser is still not working.
We've looked for obvious loose connections but it might be good for someone to check the electrical side of the tube. Otherwise it looks like its time to order a new one.

**Comment by DoESsean** [comment]
I've contacted Smoke and Mirrors today about a [new tube](https://smokeandmirrors.store/products/yongli-1000-c-40w-co2-60w-peak) - I've just asked whether the one they stock is right for our laser, and am waiting for a reply.

**Comment by amcewen** [comment]
As a backup, Simon (who I worked with on the [Christmas tree](https://mcqn.com/ibal191/)) recommended [these folk in China](http://www.laserwd.com/product_c50-50w-co2-laser-tube_9129.html) (that link is for a 50W rather than 40W tube, so again we'd need to check if that's the right one for Sophia).  He bought a tube off them for his cutter and said it arrived in a couple of days.

**Comment by johnmckerrell** [comment]
New tube arrived today, I've placed onto the countertop by Sophia but haven't opened or inspected it at all.

**Comment by johnmckerrell** [comment]
@johncain39 fitted it this evening. Seemed to be mostly working although we did find it stopped cutting just after we fitted the exhaust but then after jiggling connectors it started again. The exhaust is definitely in need of replacement though! Will evaluate in the morning before updating the calendars.

**Comment by johnmckerrell** [comment]
Done some test cuts and happy enough that it's ready to go.
