### ISSUE TITLE
Install the required electrical circuits, sockets, etc.

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#664]
This issue is mostly to track progress of the fit out of the electrics in the new space, rather than do the work, given it will all be being installed by an electrician.

Notes should be made here during progress so we can see how things are going (and potentially coordinate networking from #598), and also so we don't forget anything before we move in.

 * [x] Agree/instruct electrician
 * [x] Finalise ring mains and position of sockets
 * [x] Install sockets
 * [x] Install lights
 * [x] Install heating (air con)
 * [x] Install fire alarm
 * [x] Install accessible toilet alarm
 * [x] Wiring for kitchen water heater

**Comment by amcewen** [comment]
Do we need forced ventilation, heating, disabled alarm, etc. in the toilets?

**Comment by amcewen** [comment]
Sockets will be recessed into walls that we're building.  Ones on the brick walls will be in black trunking and then sitting proud.

**Comment by johnmckerrell** [comment]
Disabled alarm is our responsibility (but thinking about it has not been requested from electrician at this point).

We are close to engaging an electrician but he needs to know more about the desired placement of sockets.

This is a layout that we did showing (in a mostly abstract sense) where we would want different ring-mains. The socket locations are mostly just to give numbers per-room rather than actual locations.
![img_5477](https://user-images.githubusercontent.com/27243/36815899-1b8da16c-1cd4-11e8-98c2-199eca4ccb66.jpeg)

This is actually an earlier layout but does show lighting and has generally better indications of locations for sockets. It misses off that we should have sockets on both sides of the new meeting room  wall and doesn't give locations for sockets in the workshops. Most probably we just want them on the new stud walls as that'll save on conduit.
 ![scan 16 jan 2018 at 06 47](https://user-images.githubusercontent.com/27243/36815990-728b0f90-1cd4-11e8-8874-ed7e44cc8524.jpg)

This diagram shows panel heaters but Jason hasn't confirmed 100% how he wants to provide heating (we're hoping for fewer panel heaters as they're more expensive to run, but will likely have them in the workshops and meeting room)

If I don't have time to suggest better locations then whomever is doing it should use these as inspiration!

**Comment by johnmckerrell** [comment]
Forgot to mention that we do want to have a floor box where the second diagram says "3D printing" and I would strongly prefer to have a floor box in the middle of the meeting room floor too (I've mentioned this to the electrician so I'm hopeful this is already included in his quote).

**Comment by johnmckerrell** [comment]
See #598 and note that we might want high up power points for wireless access points.

**Comment by johnmckerrell** [comment]
Electrician needs to know tomorrow where the sockets are going. He's also asked how high the sockets would go, I said "knee high" which translated to 0.5m. I'm now thinking higher or lower are probably better. It'll depend on the wall really.

**Comment by johnmckerrell** [comment]
I've done this updated version, not a lot has changed but I've added the ones by the meeting room and placed the sockets in the workshop. Also mentioned the floor boxes. I'm hoping to go in tomorrow and chat to the electrician. Still not entirely sure on heights, having sockets at desk height could be useful, but then if we don't put a desk there does it just look weird?

![updated-tapestry-does-electrics](https://user-images.githubusercontent.com/27243/36869735-b0f03ba0-1d94-11e8-930a-5537bc319987.png)

**Comment by Robotorium** [comment]
Maybe. Could just put small floating shelves up and provide easy-to-access
places to charge things or whatnot? Is that a thing?

Op 1 mrt. 2018 9:09 p.m. schreef "John McKerrell" <notifications@github.com

**Comment by Dowz77** [comment]
Hi, Had a brief chat with Adrian this morning who recommended joining Github to keep upto date with the move. I'm very much a casual user of Does, laser cutter hire and the odd maker night but if I can help, I will.

Can I suggest using cable tray across the ceiling, very acceptable in commercial buildings, and most importantly easy to add a cable later and have cable segregation. Do any drops to multiple sockets/LAN in 50mm galv trunking with sockets mounted from them or a more expensive but more versatile option use dado trunking. I wired an office running a perimeter of dado trunking and have been back several times to move sockets, add LAN and door switches, all very easy to do with minimal disruption and complete cable segregation.

If your having a metal working shop I'd add a 16a commando socket on a radial circuit to support a welder.

Please use galv conduit, looks great against brick work!

CU I fitted a few years ago with metal clad sockets, top right EM light switch is how i'd tee off sockets in offices
![imag0148](https://user-images.githubusercontent.com/36996732/36912062-741dc6d0-1e3d-11e8-803d-d1452a8206f8.jpg)

Trunking with conduit drops and cage lights 
![imag1070](https://user-images.githubusercontent.com/36996732/36912157-c87e33ae-1e3d-11e8-9f36-c16a7a086f2a.jpg)

**Comment by APtec-elec** [comment]
Hi I have used does Liverpool with dowz77 on a couple of occasions, and attempted to encourage my young daughter to get involved making stuff. Anyway having a scan through your ideas I couldn’t see anything about emergency lighting and emergency exit illuminated signs? Something worth while considering. Also galvanised trunking solution is excellent for modifications in the future as the rooms are used or changed.

**Comment by amcewen** [comment]
I think we've got a combination of cables being run inside the walls and black conduit where things are going onto the brick walls, which is cheaper than galvanised but still looks decent.

@Dowz77 that work looks very nice!  I'm not sure the metal workshop will have enough space for welding, BICBW.  That feels (to not-really-done-any-metalwork-since-I-was-at-school me) like a level up from where we'll be (CNC mill, pillar drill are the current candidate bits of kit to go in there, and it'd be nice to get a small lathe in the future), but happy to be corrected...

@Pfw74 emergency lighting, etc. is a good question.  I'm assuming (because he's also sorting the alarm system) that the landlord will be providing that, but I'll check.

One last note, after a meeting on site today, the plan shows that there aren't any panel heaters in the North side rooms (the main area will have combined air-con/heater), but we're going to run wiring into them in case we need to add them once we're in.

**Comment by johnmckerrell** [comment]
Electric quote that Adrian should have in email mentions emergency lighting etc. Also accessible toilet alarm. 

--

**Comment by johnmckerrell** [comment]
FYI we've had a complaint about the noise of the fit-out from the ground floor tenants. They're being very nice about it but if you're working in the building please try to limit the noise you make between 10-3 Monday-Thursday and Saturday 9:30 - 4:30. Thanks!

**Comment by johnmckerrell** [comment]
Need to confirm how the rings have been arranged, will ask Mick tomorrow.

**Comment by johnmckerrell** [comment]
Unfortunately the rings have been arranged per-area so we don't get quite the isolation we hoped for. If we particularly want to put the 3D printers on their own ring that's probably the easiest thing to get in now but it wouldn't happen for a week.

Electrician is now on holiday until Tuesday 3rd April.

Most of the work is done, lights and sockets are all live. There's live wires in the soundproof room that haven't been connected to anything yet (for sockets), actually I noticed yesterday that some of the power sockets in the meeting room aren't connected up, I assume that's because he was waiting to know what was happening with the soundproof room's electrics. The water heater in the toilet isn't connected yet and hand dryers are yet to be installed. I'm not sure about the disability alarm but I don't recall seeing it so I suspect it's not there either.

**Comment by amcewen** [comment]
The rings in the electrics are broadly as follows:
 * East side of North wing (basically meeting room and soundproof room)
 * Centre of North side
 * West side of North wing (wood and metal workshops)
 * Kitchen
 * Meeting nook
 * Room 29 (South wing co-working)
 * Events room

**Comment by johnmckerrell** [comment]
Water heater in the kitchen is active, also a new floor box has gone in under the 3x2 workshop desks. Wirin

**Comment by johnmckerrell** [comment]
Aircon went into the main space but it's still a WIP for the events room and Room 29. Still no alarm in the look either although I keep being told he has one and will do it sometime.

**Comment by amcewen** [comment]
The aircon in the main room still ices up and has been dripping from the slats too (not just from the exposed copper pipes.  Plus the water outlet is dripping water onto the fire escape, making it more likely to rust).

The aircon engineers (not who fitted the ones in the main room) should be in this week to fit the aircon in the events space and Room 29, so we should ask them about the main room too.

**Comment by amcewen** [comment]
Mick will be in this week to fit the electrics for the new aircon units (for Room 29 and the events space).  He's aiming to get all the drilling done before 9:30am, so hopefully there'll be minimal disruption during the day.

**Comment by amcewen** [comment]
The electrics are in for the aircon on the South side, and the aircon engineers will be back sometime to finish commissioning that.  If any electrics need doing to fix the aircon in the North side (not sure what the plan is with that, but could include installing a whole new system...) then we can add that as we know about it.

That only leaves the alarm in the accessible toilet.  I mentioned that to Mick just now when he we updating me on the aircon wiring, and he's not forgotten it - didn't get time to get to it today, but is due back to work upstairs in the next week or two and will pop down to sort it then.

**Comment by amcewen** [comment]
When he popped in to warn us about tomorrow morning's electricity outage, Mick (unprompted) said he hasn't forgotten about the alarm in the accessible toilet and he should get to it next week.

**Comment by johnmckerrell** [comment]
It would be good to hassle Mick to complete the labelling on the fuse board when he's next in.

**Comment by johnmckerrell** [comment]
The accessible toilet alarm was installed yesterday.
