### ISSUE TITLE
Install baby-change facilities in the accessible toilet

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#665]
We should have baby change facilities.  There should be room in the accessible toilet.

(Including the DoES Move label, as it would be good to get done during the general move tasks.  However, it could happen after we're in, if need be).

**Comment by amcewen** [comment]
Check with the landlord about how things are being laid out in the toilet just to check that won't impede it.

**Comment by DoESsean** [comment]
From a brief search, it looks like a wall mounted, fold down changing table will cost between £100-£150.

**Comment by magman2112** [comment]
If there is the space for it, just spotted this at Ikea for £25, £30 with a mat.
http://www.ikea.com/gb/en/products/childrens-ikea-products/baby/changing-tables-nursing/sniglar-changing-table-beech-white-art-20045205/

**Comment by Robotorium** [comment]
That takes up permanent space though. The reason they fold down is because
some mobility devices are larger than others, and some disabled people need
more space than others. Putting a permanent table down means that space is
never available; a fold-down table leaves it open when needed.

Op 5 mrt. 2018 4:25 p.m. schreef "Mike Gorman" <notifications@github.com>:

**Comment by Robotorium** [comment]
I'm on my phone but looking at the map of the toilet, is it me or is there a space at the back? Or am I reading the map wrong? That could conceivably be a space for a permanent table, I'm just very wary of permanent tables because of the number of "accessible" toilets that have been rendered inaccessible by permanent furniture or, in the case of Deansgate train station, a whole entire motorbike.

**Comment by magman2112** [comment]
I had thought of that, hence my query if the space was available. 

I was tempted to see if I could make a suitable folding table, as the plans I have looked at are not too hard, but I suspect timescales would likely be the key issue here. There are loads of reasonable folding tables on Amazon that look like they could be copied as well.

Also, as a single man, I would definately need guidance from parents as to what is really needed/wanted on these tables. :-)

**Comment by magman2112** [comment]
Just thought of something else - a solid wall would be preferable for a folding table, to get a safer fixing to the wall - or lots of good fixing points.

The weight of a baby and possibly a parent leaning on the edge of the table could put quite a bit of load on fixings for a folding table, a solid wall would obviously give us a more secure fixing point.

**Comment by Robotorium** [comment]
It is generally considered poor form if the kid crashes to the floor,
sure... Hard to pass off as a design element :)

Necessary: table, nappy bin, changing mat (a lot of the plastic folding
tables don't have one; a table made of porous material would need one).
Nice to provide: baby wipes.
I have two kids (now long out of nappies) but never saw a place that
provided more, and only saw maybe two that provided wipes.

Op 5 mrt. 2018 17:00 schreef "Mike Gorman" <notifications@github.com>:

**Comment by johnmckerrell** [comment]
Found these options:

https://www.janitorialdirect.co.uk/baby-change-unit-vertical-co8252-v-1398.html
https://www.janitorialdirect.co.uk/baby-changing-unit-horizontal-co8250be-248.html

**Comment by DoESsean** [comment]
Since we're looking at getting the child friendly days up and running very soon, we need to look into this as a matter of urgency. Does anyone have any additional thoughts?

**Comment by jackie1050** [comment]
This appears to have been done
