### ISSUE TITLE
Submit DoES LIverpool to the Hannah Directory

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#682]
The Hannah Directory is an awesome annual directory of interesting grassroots arts/creative/interesting organisations across the North.  You might have spotted the nice little A6(?)-sized books knocking around in DoES over the past few years, last year's was bright pink.

We've been included in the past, @cheapjack submitted us a couple of years back, but missed out on last year's because I was useless at getting back to Andy who runs it.

Submissions are open for this year's now, and we shouldn't miss out this year.

Deadline for page content:
Midnight Sunday 25 March

Launch week:
Monday 4 - Sunday 10 June

Hopefully @cheapjack can dig out the content from our last submission, as a starting point (at least) for a submission this year.

**Comment by cheapjack** [comment]
Heres what we sent in last time obviously we'll have to change dates building location etc and work out how we'd like to contribute to their launch week 4th-10th June 2018: just distributing copies at any activity or just activity in the office we are doing that week in the tapestry would work. Also worth distributing any crowdfunding we are doing through their social networks if it's still happening then as that's a really good northern community that are likely to support that 

https://github.com/DoESLiverpool/somewhere-safe/tree/master/HannahDirectoryCopy

**Comment by cheapjack** [comment]
Just noticed the directory submissions are open and heavily subscribed so Andy's running it as  first come first serve: so Ive knocked up similar entry to last time to fit 80 word limit and could post it up to their google form. Had to ruthlessly edit from [What Is DoES Liverpool](https://doesliverpool.com/about/) Maybe @amcewen or anyone could comment. Our name and email are seperate from the limit

"We’re a co-working space in the heart of Liverpool. Desks renatble monthly or daily, alongside a workshop equipped with electronics and fabrication equipment and events run by the community.

We want to be the natural home for startups and businesses in Liverpool and beyond, a friendly environment where you do your best work. We foster collaboration and want to support the growth of the region in a meaningful way – by doing rather than talking.

Most of all: get involved!"

**Comment by cheapjack** [comment]
Also is this our address now?

DoES Liverpool
Liverpool’s Fabric District, 
68-76 Kempston Street
Liverpool
L3 8HL

**Comment by johnmckerrell** [comment]
DoES Liverpool
The Tapestry
68-76 Kempston Street
Liverpool
L3 8HL

**Comment by cheapjack** [comment]
Oh and their book launch is in the week 4th - 10th June 2018, a week with a maker night and a maker day (at least in the calendar at the moment) so that could be a place to distribute our allocation of books, (part of the pre-requisite of being included is helping distribute the books) and maybe also at our stand at Liverpool MakeFest on the 30th June.

**Comment by amcewen** [comment]
Thanks for all that @cheapjack.  Doing something at maker night and maker day for the launch sounds good, as does taking it to MakeFest.

I've stolen a bit of @DoESsean's copy for the #crowdfunder and re-jigged your copy too - how does this sound?

> DoES Liverpool is a community of makers, designers, coders, engineers, and many others. A co-working and makerspace in the heart of Liverpool. Desks rentable monthly or daily, alongside a workshop equipped with electronics and fabrication equipment and community-run events.
>
> Providing a home for startups and businesses in Liverpool, a friendly environment where you do your best work. We foster collaboration and want to support the growth of the region in a meaningful way – by doing rather than talking.

If no-one complains before 11pm, I'll get that submitted (and hope that we're in time to make it into the directory!)

**Comment by amcewen** [comment]
Submitted.  Fingers crossed we made it in before it was full!

**Comment by cheapjack** [comment]
🤞

**Comment by amcewen** [comment]
I heard back last night that we've made it into the directory.  Woohoo!

**Comment by cheapjack** [comment]
👍 yay! Domestic Science did also!
