### ISSUE TITLE
Setup snag board in The Tapestry

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#688]
Find the biggest whiteboard we've taken over to the Tapestry, plus some whiteboard markers, put them in a easily seen location, and write Snag list on the top in whiteboard marker.
Assigning this to myself as I was asked to do it yesterday, but if anyone needs one first then feel free to set one up.

[Added by @amcewen]: Add a column for "Issue #" so people can tie items on the snag list back here.  For extra credit, fill in the first line as "Setup snag board in The Tapestry" with 688 in the "Issue #" column, and then ~strike a line through it~ and come close this issue.

**Comment by johnmckerrell** [comment]
We'd want them online too though wouldn't we? I've found it difficult being away from the space to know what I'd be able to help with on my day off on Thursday.

(Leak in the laser cutter workshop would be one snag on the list)

**Comment by jackie1050** [comment]
A problem for a lot of us - A snag board is good, because it should help make sure stuff gets written down before it's forgotten about, butin my view we should have a new snag label in GitHub and record things there as soon as we're able to.

On 12 Mar 2018 16:12, John McKerrell <notifications@github.com> wrote:

We'd want them online too though wouldn't we? I've found it difficult being away from the space to know what I'd be able to help with on my day off on Thursday.

(Leak in the laser cutter workshop would be one snag on the list)

**Comment by amcewen** [comment]
Agreed on the online being best (he says, being able to participate despite being in London because this is online :-D), *however* over the weekend during the move there were lots of observations and comments being made, and not very much of it being captured.  

So I think we need to make it as easy as possible to make a note of something while you're working on something else.  We can add a column to tie things back here - I've updated the original issue description to add that.

I think it'll probably be easier to buy some new whiteboard markers for it rather than try to work out where some might be packed.  Whoever does it should get a receipt and then see @DoESsean (or me, or another organiser) to get reimbursed.

**Comment by johnmckerrell** [comment]
Yeah, sorry didn't mean to dismiss the idea. Definitely worth having. I should be able to take some pens up late tomorrow afternoon unless someone does it earlier. I still forgot to check the "who's about" board to work out what I'll be doing on Thursday!

**Comment by johnmckerrell** [comment]
Sean bought some pens, I have them to take up at about 2pm today.

**Comment by johnmckerrell** [comment]
This is now active
