### ISSUE TITLE
Investigate whether doorbots can be run from PoE

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#699]
@magman2112 thinks they can

**Comment by magman2112** [comment]
I am actually not sure if they can, as it depends on how much power the door release solenoid and the display requires, which I suspect is the main power used by the Doorbot. 

I suspect all of the components would need to be measured to determine their power requirements, perhaps on the bench power supply. Also, the power available from a PoE switch (is there one of these in DoES already?) will be a factor.

**Comment by ajlennon** [comment]
Something like this might be a starting point?

https://www.raspberrypi.org/products/poe-hat/

**Comment by amcewen** [comment]
They can't at present, although the newly announced Raspberry Pi B+ does have PoE as an option...

I'm not sure what the power draw will be for the relay in the new system, as there'll be maglocks rather than door release solenoids.  However, they'll likely be powered separately because they can be triggered in other ways too - "push to exit" button, fire alarm going off, etc.

Most of them won't have screens attached (I think), so maybe the ones that do will be near enough for the screen to be powered separately?  (Although it then doesn't matter too much if the Pi is powered over Ethernet or not).

What's the use case for this?  Is it just to save on power sockets needed for them?

**Comment by magman2112** [comment]
At present, there is no mains power or LAN connections next to any of the doors, but it is likely easier, quicker and cheaper to run a LAN cable than mains power to these locations. Also, as we will need a PoE switch to run the Wi-fi devices, we will likely have additional ports that could be used to power the doorbots.

It’s obviously not cast in stone yet, as the electrician is still on site and power will likely be needed for the magnetic locks, but it may be worth exploring the options whilst all the relevant people and resources are still on site.

**Comment by goatchurchprime** [comment]
This problem is a non-issue as the magloc control boxes have a 12V power supply for us, which we are stepping down to 5V.
