### ISSUE TITLE
DoES move priorities

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#715]
Trying to codify what needs to be agreed and done in order of priority. Please edit, revise. correct, shout out as needed:

Please don’t have discussions here. Let’s keep it clean. Link back to other issues and reorder priorities as necessary. Let’s keep the immediate blockers in our sights right now as things we have to answer/discuss/agree to be able to move forward 

I will start

Urgent stuff

- we need to fix the floor in the main area. This will involve as a minimum taking up some of the floorboards.
- plumbing to the kitchen

**Comment by johnmckerrell** [comment]
I've had another look at the "Project" functionality in GitHub and tried to improve the prioritisation that was there, tricky as there's a lot of balls in the air at the moment but might be a reasonable way to manage this. You can see the overview here:

https://github.com/DoESLiverpool/somebody-should/projects/1?fullscreen=true

I hadn't noticed but even though I'd added the new flooring issues to the project they weren't showing up on the board as they were in "triage".

**Comment by johnmckerrell** [comment]
But I would add plumbing to the list of blockers, I've added a blocked column on that list (which is not the same thing but is hopefully helpful)

**Comment by amcewen** [comment]
Yeah, I'm not sure _another_ issue is the best way to keep track of what needs doing.  That's what the priority labels are for.  Maybe we need to run a triage to tidy things up, but there are lots of important things to do, and we should be focusing on the top priority move label first, then once we're through that we can hit the next priority level...

If there are things we can live with when we first move in, then remove the `DoES Move` label and replace it with the `Settling In` one.  If there are things that would be nice ideas but aren't going to work any more, we should be close them.

Small focused issues that *can get closed easily* are our friends now.

I was going to suggest... 
> We should be living [in this view with all the issues with both `DoES Move: The Tapestry` and `1 - Must DoES` labels](https://github.com/DoESLiverpool/somebody-should/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22DoES+Move%3A+The+Tapestry%22+label%3A%221+-+Must+DoES%22+) and driving to where it's empty.

But @johnmckerrell has suggested the project thing, so we should use that.  Is the "Done" column in that useful?  I think it's better if the stuff that's done just disappears.  Is the "Blocked" column for things we're waiting on someone else for?

I'm going to close this, as there are better ways for us to prioritise things.

**Comment by ajlennon** [comment]
^ a _simple_ way

**Comment by ajlennon** [comment]
I'm thinking an A3 page of paper on the door at the Tapestry and some coloured pens would probably work better...

**Comment by amcewen** [comment]
For some things, yes.  There isn't a simple answer, I'm afraid.  This is why we have project managers, much as everyone likes to disparage it as a job, it's an important role.  (And I know I'm largely preaching to the choir, I'm just over-explaining for anyone playing along at home :-)

At the moment, that's mostly split between @johnmckerrell and me, with support most immediately from @zarino and @jackie1050.  For aesthetics issues, conferring with @zarino is best, as he's got the overall picture of how things will look.  For expensive things, @johnmckerrell or I are probably best.

Writing things down is the best way to move things forward.

Communication between everyone is the big problem.  The DoES culture still favours group discussions face-to-face where no-one writes any of it down afterwards, and so it doesn't get disseminated any wider than those in the discussion.  Then other groups have similar but different discussions and there's a mass of Chinese whispers and confusion.

There isn't one top priority thing that people need to get on with - there are many of them and we need to run as many in parallel as we can.

Flooring is one of the top priorities, but adding more people to it yesterday wouldn't have moved it on any more than you, @jackie1050 and @magman2112 did, and would've meant no painting happened.

The flooring also wouldn't benefit from being written down in the Tapestry, because it's a big decision and cuts across cost, aesthetics, how we actually do it, etc.  Given that it's hard to get us all in the same place at the same time then doing it online seems the best way *at the moment*.  As things progress, particularly if we're just making good the existing flooring in some rooms, then it'll no doubt switch to where a board like the painting one physically in the space will make sense.

There are still open questions from John about lots of the flooring, particularly the bits that aren't terrible, so I'll try to get (someone to get) that documented today.  

I'll also try to find some time to relabel the `DoES Move: The Tapestry` issues with more gradations of priority (i.e. move some of the `1 - Must DoES` to `2 - Should DoES`).

Most of all, write things down.  You're handing the task over to someone else (although that "someone else" *might* happen to be you), so think about what they'd need to know.

We're getting there.  I know the issue list looks daunting and noisy, because there's lots to do.  It'll also get worse before it gets better (although that's only in the number of issues, not the amount of work - I expect we'll get lots more small issues before the count in [this view tends to zero](https://github.com/DoESLiverpool/somebody-should/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22DoES+Move%3A+The+Tapestry%22+label%3A%221+-+Must+DoES%22))
