### ISSUE TITLE
Agree policy on accessibility of new space

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#727]
I was talking with @Robotorium about the move and I know for me I'm just going to move stuff from the Gostins building and put it wherever I am told and my back says is easiest.

But I also know we're all committed to accessibility. And I know I don't really understand what that means.

So I'm opening this issue in the hopes we can have a bit of a chat about how we might organise the stuff we move in and take some expert advice on what a good accessible environment would look like

@cheapjack have you got thoughts?

**Comment by amcewen** [comment]
It's good to be working out what we need to do, @ajlennon, but this doesn't feel very measurable to me.  How do we know if this task has been completed?

Is it just that we should leave an X.Ym wide corridor between desks, etc. so a wheelchair can get through?

**Comment by ajlennon** [comment]
No idea - but it's a crucial set of questions that needs to be answered as a high priority if we are committed to accessibility...

**Comment by ajlennon** [comment]
What about "Agree policy on accessibilility of new space"

To be agreed at next directors' meeting.

This ticket to contain input from interested parties

**Comment by johnmckerrell** [comment]
I'm glad to see that the title of this issue has changed. I didn't really get what it was trying to achieve originally. 

We've tried to keep accessibility in mind throughout the process of finding a new venue. In fact it's our efforts that have pushed Jason to provide lifts in the Tapestry building and step-free access. We have also made sure that we could have a more accessible toilet facility on our floor rather than relying on the one on the ground floor (for the record ours is unfortunately not the full size required to be officially "accessible" but is larger and has accessible equipment). 

We have tried to consider accessibility throughout the process of laying out the rooms. I'm not saying we will achieve this 100% - one area I know we may fall down on initially is having automated doors on our floor - but we are trying and we're aware we need to consider it when laying out the furniture in the rooms too. I don't really know what the policy would look like, "we will aim to make as many DoES services available to as many people as possible" sounds great but also a bit vague. Any input is welcomed.

**Comment by ajlennon** [comment]
I'd particularly like to see input into this on how events should be organised to ensure they are accessible.

e.g. seating layout etc. etc.

**Comment by Robotorium** [comment]
It's hard to tell without having been (and I will come round as soon as I
can, I need to have my leg X-rayed again first), but I like when I can roll
myself onto the end of any given row. Seats not so far back that it's
difficult to get in and to the front (for those who want to sit in the
front) is probably more important (I'm assuming the "stage" is on the end
opposite the door, again it'll be easier once I've had a look at the actual
space).

I really appreciate the commitment to accessibility, not just from
individuals but also from DoES as a whole. I'd say it's a huge part of why
I keep coming when I can, but it's a huge part of why I *can* come in the
first place. It's really stressful going somewhere new when you don't know
what people and the space will be like, and I've never had that with does
(partly because @huffeec did know those things, obviously). I'm looking
into places online where I can indicate accessibility levels, so other
disabled people can see it and know they can turn up and be accommodated as
much as the space allows.

Op di 3 apr. 2018 08:20 schreef Alex Lennon <notifications@github.com>:

**Comment by ajlennon** [comment]
So would it help if we had a floor plan of the space @Robotorium for people to see in advance of coming?

**Comment by Robotorium** [comment]
It would probably help to have a fairly expansive page on accessibility
that's easily available, if that's an option? Floorplan probably less
important, but level access/lift/any other features would be great.

Op di 3 apr. 2018 10:09 schreef Alex Lennon <notifications@github.com>:

**Comment by amcewen** [comment]
That would be excellent @Robotorium.  The wiki would be the best place to build something like that, and then everyone can contribute to it.  If you or @ajlennon want to kick one off, head to https://github.com/DoESLiverpool/wiki/wiki and hit `New Page`

**Comment by ajlennon** [comment]
Fancy working together on that page @Robotorium ?

**Comment by Robotorium** [comment]
Sounds brilliant, yes please!

2018-04-03 13:09 GMT+01:00 Alex Lennon <notifications@github.com>:

**Comment by ajlennon** [comment]
@johnmckerrell @amcewen can we invite @Robotorium to the DoES #Slack space so the two of us can discuss this and involve others without creating a massively complicated GitHub issue

**Comment by johnmckerrell** [comment]
Slack signup is here: http://slack.doesliverpool.com

**Comment by Robotorium** [comment]
We've started discussing and also started the page at
https://github.com/DoESLiverpool/wiki/wiki/Accessibility

2018-04-03 13:37 GMT+01:00 John McKerrell <notifications@github.com>:

**Comment by ajlennon** [comment]
And there's a new slack channel "accessiblilitywiki" where all the cool kids are at....

**Comment by ajlennon** [comment]
@magman2112 I'm talking wiht @Robotorium about the scale of a photo I put on Slack (remember when we were talking about the networking layout originally). Can you remind me what the units are? We're trying to lay out paths for accessibility in different modes of room use. I'd ask you to join us if I didn't know how busy you are (but join us ;) )

**Comment by magman2112** [comment]
Just picked up this message, so likely a bit late for your discussions. The grid was 1 metre squared on the plans that were used for the network layout.

**Comment by Robotorium** [comment]
Brilliant, thanks Mike!

Op di 3 apr. 2018 23:48 schreef Mike Gorman <notifications@github.com>:
