### ISSUE TITLE
makernight.co.uk should be updated or just redirect to somewhere on doesliverpool.com

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#74]
The Maker Night website predates DoES Liverpool, and doesn't ever get updated.  We should either (a) create a page on doesliverpool.com and set up some redirects so anyone visiting makernight.co.uk ends up there, or (b) set up a script to automatically set the dates of the next meetings from the doesliverpool.com calendar.

**Comment by DoESsean** [comment]
I assume @johnmckerrell can do this, as he has credentials for the Maker Night site (according to recent emails with JR at least). Is it worth waiting to do the redirect till we have something better on the site though?

**Comment by huffeec** [comment]
Is the plan still to retire http://makernight.co.uk/ ?

I've been speaking with someone via maker night who'd be happy to volunteer to update the site currently at this domain. It'd be good to update the info there and have space to show off the things that are getting made..

**Comment by johnmckerrell** [comment]
I suggest that we get makernight.co.uk redirected to the wiki page at least, we should transfer ownership to DoES too. I'll ping @OddEssay an email asking him to do this (unless he sees this first).

**Comment by huffeec** [comment]
There are/were plans to develop something for this domain. The idea was to
have biographies of regular makers, to give new members an idea who we are
and what it is we're interested in at the moment.

Also it'd be handy to have an archive of things made at maker nights. A bit
more specific than weeknotes to keep track of what's happening in the
workshop at maker events. Again it'd help show new people what we get up to.

Keeping a separate site updated could be an issue though , so it might be
that it's better done on the wiki too? Definitely it makes sense to point
makernight.co.uk there for now.

On 27 Jan 2017 09:53, "John McKerrell" <notifications@github.com> wrote:

I suggest that we get makernight.co.uk redirected to the wiki page at
least, we should transfer ownership to DoES too. I'll ping @OddEssay
<https://github.com/OddEssay> an email asking him to do this (unless he
sees this first).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/somebody-should/issues/74#issuecomment-275628110>,
or mute the thread

**Comment by johnmckerrell** [comment]
Yeah, @amcewen mentioned there was plans afoot. As we don't currently have control over the domain the first thing to do is to get control! I've initiated that and when we have it I'll point it at the wiki page, then once other plans are developed it can be updated.

**Comment by huffeec** [comment]
Thanks John. I'll have a chat with @helicalbytes 
Thinking about it we can probably achieve the above with a makers sub page on the wiki and an instagram account..

**Comment by stevesparrow** [comment]
What happened here?

_Sent from my Asus P027 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by huffeec** [comment]
There is an [Instagram account](https://www.instagram.com/doesliverpool/)  
Nothing has happened with the domain, I think the consensus is to retire it and have the makernight information across the website and wiki as part of #19

**Comment by DoESsean** [comment]
Was this completed? Can it be closed now?

**Comment by johnmckerrell** [comment]
So, the domain is now under our control and redirecting to DoES Liverpool. Having followed a link recently and found it dead I would kinda like to do something to avoid link rot. I've had a few ideas around putting the website live as an archive, or forwarding to the internet archive, but I think the best idea might be to copy the blog posts, and anything else that looks interesting, over to the DoES Liverpool site and set up makernight.co.uk to redirect across. This is likely to be a bit of effort but would be nice to aim for at least.

**Comment by DoESsean** [comment]
Anything done with this in the last year?

**Comment by johnmckerrell** [comment]
It would be nice not to have link rot but I don't see it happening soon, adding the hero tag and closing...
