### ISSUE TITLE
Check the alignment of Gerald

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#762]
@KarlDunkerley was having real issues getting a good cut today, we cleaned the lens to no avail, may be an alignment issue as it was worse at the far end of the bed.

https://forum.hackspace.org.uk/t/chinese-laser/470/4

**Comment by KarlDunkerley** [comment]
To explain a little further. I was trying to cut perspex 3mm. The small test piece I did was fine though needed two passes.

However, doing a larger piece in the centre of the bed failed. Anything further than 200mm to the right of the origin became rapidly fainter until the furthest point (600mm) was not even scratching the surface.

I checked the distancing focussing and that was fine. Tried again with similar results. I had started in the middle of the bed but also tried starting on the left. Same results. The issue seems to be the distance to the right of the origin point. I also tried putting a piece of ply underneath the right hand side to be more level but it had no effect.

The cut quality did not vary front to back. It was only from left to right.

Even when the lenses as cleaned (but still badly pitted) it made no difference.

For anything over a few inches wide I would suggest caution using Gerald.

**Comment by cheapjack** [comment]
It's worth noting that we didn't align the first lens in the tube casing so it could well be out of alignment on the rightmost side of the bed. Sorry my bad for not checking it at the extremity of the beam range.

Also as noted the lens we cannabalised from Sophia was far from perfect.

Ordering lens in #749 will help but we should order for Sophia also

We really could do with regular lens cleaning maybe every maker night? Any material from cutting that adheres to lens (when doing high volume cutting esp.) seems to get 'baked on' if it's not cleaned regularly. Will prelong lens life so logging in issue #473 a good start and something the Laser Maintenance Crew could coordinate #757 maybe?

**Comment by KarlDunkerley** [comment]
Adrian, Sean, Julian etc, I've come across a chap called Richard Butler based in prestatyn who is a laser engineer. Had a brief chat with him. I was wondering if we could meet with him to discuss getting Sophia and Gerald back to their peak and then him train us up in routine maintenance so that we can handle most of it ourselves. He's up for it and also has tubes and he can re-gas them. He's free monday morning to come in and discuss things. Would it be okay to go ahead and who could be there? I've told him no promises at this stage. Ps he can also supply controller boards for the lasers to bypass the existing ones which might be useful for Harry the Humungous.

What are your thoughts?

**Comment by KarlDunkerley** [comment]
Richard's website is https://www.rtbtech.co.uk/ and he's also on Facebook.

**Comment by DoESsean** [comment]
This seems like a fantastic idea to me, but I'll defer to people who know
more about the lasers and would be the people taking on the maintenance
(also, I know that Adrian definitely isn't around next Monday).

Is it every Monday morning he's free, or just next week? If the former, I
think it would be worth seeing if we can book a slot a few weeks in advance
and publicising it so as many people who want to be involved with the
upkeep of the machines can be there. Also, I assume there will be a charge
for this, so it would be useful to know what that will be.

I've said for a while that it would be useful to have a list of all the
perishable components that are on the lasers and try as far as possible to
always have spares on hand to keep downtime to a minimum, and it seems like
this would be a good time to create that inventory, so that could be rolled
into this.

Thanks for doing this Karl, it's really useful. When other, more involved,
people have had their say, and if they think it's a good idea too, we can
go ahead and set something up.

**Comment by KarlDunkerley** [comment]
Hi, at this stage I just think we need an exploratory chat. I'm too new to know how DoesLiverpool works, who decides such matters so I was hoping he could just come in and a way forward be agreed.
I'm then up for helping keep key kit in tip top condition. I'll be in this evening so am hoping a few of us can get together for a chat.
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Thursday, 19 April 2018, 10:09:50 BST, Seán Gleeson <notifications@github.com> wrote:  
 
 This seems like a fantastic idea to me, but I'll defer to people who know
more about the lasers and would be the people taking on the maintenance
(also, I know that Adrian definitely isn't around next Monday).

Is it every Monday morning he's free, or just next week? If the former, I
think it would be worth seeing if we can book a slot a few weeks in advance
and publicising it so as many people who want to be involved with the
upkeep of the machines can be there. Also, I assume there will be a charge
for this, so it would be useful to know what that will be.

I've said for a while that it would be useful to have a list of all the
perishable components that are on the lasers and try as far as possible to
always have spares on hand to keep downtime to a minimum, and it seems like
this would be a good time to create that inventory, so that could be rolled
into this.

Thanks for doing this Karl, it's really useful. When other, more involved,
people have had their say, and if they think it's a good idea too, we can
go ahead and set something up.

**Comment by KarlDunkerley** [comment]
Is Gerald still out of order?

**Comment by johnmckerrell** [comment]
It is still having issues I’m afraid. It was partially realigned last week but is still having some power issues. 

--

**Comment by amcewen** [comment]
I did some more testing on this today, without much success.

In the back left corner it was cutting through 3mm ply with a speed of 5 and power 70, but further away from the corner it wasn't even getting through the wood on a speed of 2.

That was with the air assist nozzle removed, because with it on the power is much reduced, so the alignment is sufficiently out that it must be hitting the nozzle.

I did also swap in one of the other old lenses from the padded envelope in the laser spares cupboard, as it seemed a bit better than Sophia's old one (the "new" one is still the shorter focal length, so the revised focusing method still applies).

I'm marking him as `Broken` too, because the power isn't enough to do any useful cutting at present :-(

**Comment by amcewen** [comment]
Is anyone else around tomorrow or Monday?  I'm going to have a look into this one of those days - don't really mind which, if anyone wants to join me...

**Comment by KarlDunkerley** [comment]
Maybe Monday. Is Sophia working yet?

Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com

--------------------------------------------
On Sat, 5/5/18, Adrian McEwen <notifications@github.com> wrote:

 Subject: Re: [DoESLiverpool/somebody-should] Check the alignment of Gerald (#762)
 To: "DoESLiverpool/somebody-should" <somebody-should@noreply.github.com>
 Cc: "KarlDunkerley" <karldunkerley@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Saturday, 5 May, 2018, 12:59
 
 Is anyone else around
 tomorrow or Monday?  I'm going to have a look into this
 one of those days - don't really mind which, if anyone
 wants to join me...
 
 —
 You are
 receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by amcewen** [comment]
Can do Monday then.  10:30am onwards if anyone wants to join.  Sophia is still out of action, awaiting the new tube which should [arrive on Tuesday](https://github.com/DoESLiverpool/somebody-should/issues/676#issuecomment-385688107)

**Comment by KarlDunkerley** [comment]
I'll be in around noon.
Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Saturday, 5 May 2018, 17:26:24 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 
Can do Monday then. 10:30am onwards if anyone wants to join. Sophia is still out of action, awaiting the new tube which should arrive on Tuesday

**Comment by amcewen** [comment]
So, @magman2112, @KarlDunkerley, @dazz-ling and I aligned the mirrors, and did some testing.  Then aligned the mirrors again, as they'd already gone out of alignment because the sprung screws on the back of the mirrors were loose.

It seems to be cutting consistently now across the bed, although is down on power.  we were struggling to get through 3mm ply with a speed of 5.  I'm going to close this now, as the alignment is okay, and we can see how things are with power once the new lens is in tomorrow (which is tracked in #749)
