### ISSUE TITLE
Order more sublimation printer cartridges

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#780]
Ste has replaced the cyan, magenta and yellow cartridges in the sublimation printer today, so presumably we'll need to order some new spares.

**Comment by DoESsean** [comment]
I've reordered these today.

I'm still concerned that we're not properly logging the amount that the printer is being used. We really do need to recover our costs, given how pricey the paper and inks are for this, and I don't know how to be sure that we are.

There's a semi reasonable chance that monies have just been going in different jars rather than solely the one for the sublimation printer, but I can't be certain.

**Comment by amcewen** [comment]
The yellow ink is out, and magenta is getting low, so I've ordered new ones of those from https://www.mdpsupplies.co.uk/sawgrass-inks-ricoh.asp

Should be here tomorrow, then we can close this issue

**Comment by DoESsean** [comment]
These have been delivered (in an inordinate amount of packaging).
