### ISSUE TITLE
Find out why the bandsaw isn't working

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#819]
Keep it simple to start with, like trying the fuse, etc..

**Comment by amcewen** [comment]
It is now not working because it doesn't have a plug on it, and has a "BROKEN" sticker across the on button.  @Sean-anotherone can detail properly what's broken and needs replacing, and I've [updated the "days since last explosion" counter](https://github.com/DoESLiverpool/doesscreens/commit/19d776d4a01e7205fbee5d4b781c1e61e1767c65)

**Comment by amcewen** [comment]
I've ordered a [capacitor](https://www.ebay.co.uk/itm/192580042555) and a [24V single-output transformer](http://www.ebay.co.uk/itm/173187511836), so that will hopefully give us the parts we need for a fix.

**Comment by Sean-anotherone** [comment]
Assuming said parts have arrived I will have a go at this on Thursday

**Comment by amcewen** [comment]
The capacitor has arrived.  I've left it on the bandsaw ready for fitting.

**Comment by Sean-anotherone** [comment]
Pleased to report that the bandsaw is now fully operational :)

**Comment by Shay-Allen** [comment]
Hi Sean-anotherone, I`m having the same trouble with my startrite 301, it wont start at all now, had been sluggish for a good while. Could you give me the details of the transformer and cap ( and supplier) that you used to repair yours. thanks Shay.
