### ISSUE TITLE
Sink elbow joint came loose

### ISSUE THREAD

**Issue by willcrobinson** [DoESLiverpool/somebody-should#834]
The elbow joint in the grey pipe between the dishwasher and the sink unit came loose and caused a bit of a flood in the kitchen.

@Helen-8 and I have fixed the issue for now with the aid of some gaffer tape but we'll want to keep an eye on it.

Also, please reset the flood counter!

**Comment by willcrobinson** [comment]
Flood counter updated

**Comment by amcewen** [comment]
Sadly it's come loose again today.

**Comment by DoESsean** [comment]
More gaffer!

**Comment by Helen-8** [comment]
I think the pipe behind the units are dodgy all the way along as there are puddles around the dishwasher and underneath the workshop sink as well.

Seems to be intermittent leakage, especially when a lot of water is put down either sink so the flow increases a lot suddenly.

So potentially needs a whole new section of pipe all the way along.

**Comment by Helen-8** [comment]
Turns out it was just the elbow joint, added to the fact that the pipe had sunk down so the water was draining the wrong way down the pipe and putting a lot of pressure on that corner.

@magman2112 has put a piece of wood underneath that elbow joint to prop it up so water doesn't drain the wrong way anymore, which should fix the issue for now.
