### ISSUE TITLE
Fix the leak in the left hand side sink

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#854]
There's some kind of leak in the LHS sink, relating to the drainage hole at the bottom, which leads to the shelf beneath being covered in water and the magic pool of water appearing on the kitchenette floor

**Comment by johnmckerrell** [comment]
Is this definitely a leak in the sink pipes? Turns out the drain pipe has been leaking so could it be that? See #924

**Comment by DoESsean** [comment]
Has anyone looked at this? Is it sorted?

**Comment by amcewen** [comment]
Not sure if it's the same leak (because it's outside the cupboard, so floods the floor rather than the shelf...), but right now the right-angle joint in this photo isn't attached to the straight section running down to the pipe at the back of the sinks.
 
![DSC_0322](https://user-images.githubusercontent.com/108468/71354558-3c84ed80-2574-11ea-8b53-ff17c59c8909.JPG)

So at present the left-hand sink is out of action as any waste water just leaks out onto the floor.

**Comment by jackie1050** [comment]
When I got in this morning someone had put a lot of cardboard on the floor but this was soaked through and there was also a lot of water which I mopped up.
There was a bowl in the sink, but this had filled up with water from the leaking tap and overflowed.

**Comment by jackie1050** [comment]
I've spoken to @magman2112. He has a long term plan for the waste pipes to go to the back, which he will document. In the meantime we will buy an elbow joint tomorrow as a temporary measure.

**Comment by magman2112** [comment]
The 90 degree bend on the joint going through the side of the cabinet had come apart, so a new compression fitting 90 degree bend was sourced from B&Q and this has cleared the initial issue for this sink.
