### ISSUE TITLE
Accept Bitcoin payments via Lightning Network for snacks

### ISSUE THREAD

**Issue by paulfurley** [DoESLiverpool/somebody-should#857]
The [Lightning Network](http://lightning.network/) is an interesting protocol on top of Bitcoin which tries to solve 2 of Bitcoin's major problems:

1. slow transactions (~1 hour to verify)
2. massive transaction fees (anywhere from $0.10 -> $10)

If we're willing to accept Bitcoin payments *in principle* then I think it would be really interesting to try out accepting them for snacks using the Lightning network. Snacks are a small amount of money which is exactly the use case lightning is designed for (it wouldn't make sense to do a regular Bitcoin transaction because of the fees)

@idrysdale and I have set up a Lightning Node to figure out how it all works. We could use [our node](https://supernode.li) to take lightning Bitcoin payments, batch them up and send them to a DoES bitcoin wallet periodically, or something like that. If it's a raging success DoES might want to run its own lightning node.

I know there are quite a few Bitcoin enthusiasts in the community, and very little to actually spend bitcoin on. It would be cool if DoES could trailblaze some new finance tech.

I'll volunteer to do the gruntwork to make it happen... @DoESLiverpool/directors can we give it a go?

**Comment by ajlennon** [comment]
I spy with my little eye... Somebody with a new snackcoin mining rig...

**Comment by johnmckerrell** [comment]
Yes, happy to give this a go.

**Comment by paulfurley** [comment]
:+1:

**Comment by MatthewCroughan** [comment]
You're on a roll, you haven't stopped doing stuff with lightning since I mentioned it haha. I'll try laser cutting a vending machine with an integrated display that displays a qr code and instructions on how to get set up with lightning, maybe even opens a reverse channel to them, just for DoES. Using supernode.li with a budget of £10.

**Comment by MatthewCroughan** [comment]
@ajlennon Alternatively, you could back Snackcoin with your own storage of £. For every Snackcoin, there is £1 in a vault somewhere, or at least that's the claim, and thus Snackcoin is worth £1.

**Comment by idrysdale** [comment]
This looks like a good place to start for the vending machine https://github.com/ElementsProject/nanopos

**Comment by MatthewCroughan** [comment]
@ajlennon That would be excellent indeed, I'll take it, I owe you some snackcoin. Now all I need is a coin detector, which are magic black boxes that I have no idea how to make, I'm probably going to just buy one tomorrow, unless you know how to make one that would be rather reliable, since I'd want the option of paying with both cash and or Bitcoin.
