### ISSUE TITLE
Gerald has issues with fast movement in the Y-Axis (Front to back)

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#859]
A few people have been having issues with Gerald when trying to user higher speeds with inaccuracy in the Y-Axis. This has been worked around for a while by just using slower speeds, but there is obviously an issue with some play in the laser head which is more apparent with faster movements. 

We need to investigate how to eliminate the play in the laser head on the Y-axis, as this is likely to be the main cause of this issue

**Comment by MatthewCroughan** [comment]
![img_20180822_194558](https://user-images.githubusercontent.com/26458780/44547001-9b80eb00-a711-11e8-8a30-78300db57340.jpg)
These are available from various retailers online

**Comment by magman2112** [comment]
I checked this bearing out on Gerald on Wednesday night and it is well worn. I made the mistake of opening the bearing at first (but managed to put it back together), but this did show some significant wear in the ball races, which will severely affect its operation. 

I would suggest that replacing this bearing will go some way to improving this poor aspect of Gerald's performance, though it may not be a 100% fix as we don't know whether wear on the rail itself contributes to this issue.

Determining and sourcing the precise replacement for this bearing is a bit more difficult, as there are a large number of options for these parts and we want the replacement to be virtually an exact replacement for the existing unit, just better.

**Comment by MatthewCroughan** [comment]
@magman2112 http://www.pmi-amt.com/en/products/amt_msb.htm 

![image](https://user-images.githubusercontent.com/26458780/44584355-9fa81980-a7a0-11e8-8eee-4b9ce72517c3.png)

This spec guide will be incredibly useful to determine the differences between available MSB units. We might be able to get something quite a lot better than what we have by understanding what the pro's and cons are of these different form factors. 

We can order these from this retailer https://www.yoycart.com/Product/561358459150/ who sells quite a lot of variants, and some of the closest to exactly our part.

I think it may be the case that the industry has moved on since this exact part was produced, meaning the only option we have is an upgraded option, though it's not clear if these parts such as the MS15B-E are what we want. I can't seem to find exactly the "MSB15" without any extension such as -E or -TS around, nor on the spec, so it may be that we haven't read what we have, there may be some other indication on the unit as to what variation it is.

**Comment by magman2112** [comment]
Having obtained 2 new bearings from Adafruit :- 

https://www.adafruit.com/product/1860

It was then found that these are not compatible with the existing rail in Gerald (they don't fit :-()

With a bit more analysis, it is obvious that the rail itself is worn, so is likely to be contribute to this issue anyway, so it is worth looking at a replacement for the rail at the same time. The rail needs to be 1300mm long with a spacing of 60mm for the mounting bolts.

Discussing this with @MatthewCroughan we found that it is possible to get a new rail and bearing set from an eBay supplier - though the item is for 2 complete sets of rails and bearings.

https://www.ebay.co.uk/itm/15mm-linear-slide-guide-shaft-SBR15-1500mm-2-rail-4HSR15CA-bearing-block-CNC-set/232585268762?hash=item3627298e1a:g:8UcAAOSwNWxaJP-~:rk:2:pf:0

This supplier is based in Germany, but carriage is a quite reasonable £10.

One possible alternative is to just buy the rail from a UK based supplier and just use the bearings from Adafruit.

https://www.mooreinternational.co.uk/Products/Size_15_Linear_Rails/HLRHGR15RH1300

These are cut to the right size, but we would have to confirm that these are compatible with the bearings we have. This is also a more established company, so may be available in the future as a parts supplier id needed.

**Comment by DoESsean** [comment]
At the risk of sounding incredibly dumb (no change there then), and given
that my brain essentially shut off midway through this as I have no idea
what any of it is, could you possibly make it super simple for me as to
what, if anything, I should be ordering? Thanks!

**Comment by DoESsean** [comment]
@magman2112 has commented on a couple of the other issues related to Gerald that I've brought back up, so hopefully he'll know what to do with this too :)

Do we still need to be looking at buying things for Gerald, or will this be looked into along with everything else when he's taken out of service for a while for an overhaul?

**Comment by magman2112** [comment]
I have now ordered a new rail and bearings from eBay, as the vendor has reduced the price to £68, so I thought I would grab them. They should hopefully be delivered to me in a week or so.

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.co.uk%2Fulk%2Fitm%2F123686041994

**Comment by magman2112** [comment]
This was fixed when the x-axis rail and bearing were replaced as part of issue #1467.
