### ISSUE TITLE
Sort out Reward Mugs

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#862]
We've been slack with getting the Crowdfunder rewards out, and some of that may be down to the information required being dispersed rather than in one place, so here we go.

* [x] Design mug
* [x] Agree on design for mugs
* [x] Print mugs
* [x] Mail them to rewardees (who have told us their addresses)

We require 18 mugs to be printed.

**Comment by amcewen** [comment]
I think we should go with the "3 step plan" idea for the design, so... DoES Liverpool logo on one side, and then the other side would read:

The DoES Liverpool three-step plan for success:

1. Do epic ______________
2. Tell people about it
3. Go to step 1

With some space above the step one line so that there's room for people to write in their own thing that they want to do epic versions of.

Do we know what the dimensions of the mug are?  I can put something together if so...

**Comment by ajlennon** [comment]
Can I help make some mugs please? I'd like to have a go. (i.e. the sublimating bit not the clever design bit)

**Comment by zarino** [comment]
I can do a design, if you tell me what size it should be, and what you want on it.

**Comment by jackie1050** [comment]
Thanks Zarino

I've left the existing mug on your desk (it was made elsewhere and I think the reason it's faded is that they didn't use OEM ink). I've left one of the new mugs too, in case it's a different size.

So something similar, but with a long underline instead of sh**, so people can choose what epic thing they're going to do. All design decisions left to you.

I think it might make a good t shirt too.

**Comment by ajlennon** [comment]
If you have time @zarino and can knock up a design I can try to make these tomorrow

**Comment by zarino** [comment]
Circumference of the mug is about 260mm, but excluding the handle and some space around it (~40mm), we get a 220mm × 90mm printable area.

I’ve uploaded [two PDFs to somewhere-safe](https://github.com/DoESLiverpool/somewhere-safe/tree/master/designs/mugs) – one with crop marks, one without. They’re both obviously the same size. The position of the logo and text have been worked out so that they should be exactly opposite each other when wrapped around the mug.

Preview:

![prevew](https://user-images.githubusercontent.com/739624/43644125-87c9c95c-9725-11e8-84ef-6cfa94a9501f.png)

In a slight change from the original mug, I’ve capitalised the "E" in "Epic", to hint at the Do…E of DoES. Lemme know if you think it just looks a bit weird.

**Comment by jackie1050** [comment]
That looks fine - thanks Zarino.

I'd be very careful with crop marks though! I thought I'd cut just on the inside of some on a transfer I'd made, but I still ended up with extra lines on the mug.
________________________________

**Comment by zarino** [comment]
@jackie1050 the crop marks are a few millimetres _away_ from the outside edge of the artwork. All @ajlennon needs to do is cut between the marks:

![screen shot 2018-08-03 at 15 23 30](https://user-images.githubusercontent.com/739624/43648035-3365f96a-9731-11e8-84e8-c808b63eaf91.png)

**Comment by ajlennon** [comment]
Any time anybody says "all @ajlennon has to do..." I know it's going to go horribly wrong!

Thanks! I shall try my best :)

**Comment by ajlennon** [comment]
Mugs printed. Just need mailing out now.

**Comment by ajlennon** [comment]
I just hope the one who gets the upside down one doesn’t immediately flip it on eBay for 50k. That’ll be worth something in the future, mark my words ;)

**Comment by ajlennon** [comment]
I modified the design to make it easier to print the mugs. I've uploaded this to somewhere-safe [here](https://github.com/DoESLiverpool/somewhere-safe/blob/21c083ca3c1bb3858cd33e8a5520da6d3b2a5cd5/designs/mugs/alex%20-%202x%20mug%20220x90mm%20with%20crop%20marks.svg)

**Comment by DoESsean** [comment]
Thanks for all your work on this guys, now I just wait for everyone to send
me their address...

**Comment by johnmckerrell** [comment]
Marking this as done as we've told people and distributed all the ones we can so far.
