### ISSUE TITLE
Advertise mailbox service

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#865]
I wonder if there's something we can do to advertise the mailbox humorously. Like showing a parcel with a label to:

> Super Big Megacorp Ltd
> Quiet Cottage
> 3 Rural Lane

or an invoice from

> Experienced UX Company
> c/o Student Union
> City University

I wouldn't want to belittle people starting out small, just show that they might be able to create a better impression. Any thoughts?

**Comment by amcewen** [comment]
I dunno, it feels like it'd be much easier to stray into the belittling people than getting the humorous pitch right.  Especially when we then suggest people use

Excellent Firm Ltd
c/o DoES Liverpool
The Tapestry...

as their address.

What if we just told the truth?  That we don't see why you have to pay £40/month for a service to receive half-a-dozen letters each year.  We're trying to make it easier for people to start and run businesses and so part of that is lowering the barrier to having a business address.  And as we *also* think that there's value in getting out of the house and being around like-minded people, but realise that in the early days, when every penny counts more than usual, you might not understand that, we give you six free days of hot-desking so that barrier is reduced too.

**Comment by johnmckerrell** [comment]
Fair enough, hadn't realised £40/month was standard! Seems like www.mbe.co.uk have sewn up the SEO given that they have half the first page on Google but I'm sure @willcrobinson can sort them out!

**Comment by johnmckerrell** [comment]
I was thinking about this and really we should be able to take out "The Tapestry" from our postal address. Having the building number should be enough, granted it wouldn't hurt to confirm this but the numbers should locate us well enough without having the building name on (although I wonder if the building numbers are anywhere on the building, simple enough to cut some acrylic or vinyl numbers though!)

**Comment by willcrobinson** [comment]
I've just had a quick look at the content on that page. What about something like this instead?

> Looking for a secure postal address for your business? Need a Liverpool city centre mailing address that looks professional? We're now offering a virtual office address as one of our services!
> 
> DoES Liverpool's mailbox service costs just £99 per year which represents a huge saving compared to other PO Box and virtual address services.
> 
> This service allows you to use DoES Liverpool's office address as your address to receive letters by post. Your communications will be stored in pigeon holes ready for you to retrieve.
> 
> As a special bonus, and to encourage you to visit more often, this option includes 6 hot desk days.
> 
> If you're interested in purchasing this, get in touch at hello@doesliverpool.com letting us know the business name that we should expect post for and we will invoice you straight away for one year of mailbox rental.
> 
> If you have taken this option, you will want to use the following as your postal address, for example if your company name is "Your Company Name Goes Here":
> 
> Your Company Name Goes Here
> c/o DoES Liverpool
> The Tapestry
> 68 - 76 Kempston Street
> Liverpool
> L3 8HL

**Comment by johnmckerrell** [comment]
Sounds good. Worth mentioning that you can use it as a registered business address too. 

--

**Comment by willcrobinson** [comment]
Good point. I've made those changes now and added in the part about registered business addresses.

**Comment by DoESsean** [comment]
With this now being in place on the website, can this issue be closed?

**Comment by johnmckerrell** [comment]
Closing this.
