### ISSUE TITLE
Networking and serial communication on Gerald and Sophia's workstations dysfunctional. Unable to cut.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#873]
This has been the case since last night, I came in late around 8pm and realised that the networking in that room isn't functional, have tried replacing all the cables, so clearly isn't a problem with those. 
Also of note is that the serial communication between the workstations and the cutters is also not functioning, has somebody been re-configuring the software/drivers? 

Gerald's workstation complains about the driver/software: "laser cut and engrave system 5.0 not found"
Sophia's workstation does not respond or give an error, but will not download any data to the cutter.

**Comment by amcewen** [comment]
The networking doesn't seem to be connected, I haven't looked into that at all.  I also haven't checked Sophia.

Gerald is working okay, although there was one point this morning where it wasn't sending the file across to the cutter - it didn't report any error, but the file didn't show up in the dialog box and the cutter didn't think it had anything in it (if you hit `start` it'd just beep to show it had finished straight away).  Closing the lasercutter software and reopening it seemed to fix things...

**Comment by magman2112** [comment]
There was a lose connector on the patch panel in the wiring closet which has now been fixed. 

The tag on the RJ45 connector was squashed flat on one end of the patch lead, which allowed the connector to pull out out of the socket just enough to disconnect it but look like it was still patched. I have bent the tag out a little more so that this connection is now more secure.
