### ISSUE TITLE
Get Fab Manager running again to try out

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#885]
Relates to #175, someone needs to get Fab Manager going again so that we can evaluate it.

**Comment by amcewen** [comment]
The basic install is now up and running at https://organisers.doesliverpool.com

@johnmckerrell the admin login is in the usual place, if you want to set yourself up an admin account.  

I guess the first priority would be working out if it can replace our laser-cutting (and meeting room) booking system?

We've got our own [fork of it]() but at present it's using the standard docker container.  So the other thing to look at would be getting it using our fork so that we can push out changes we make.  All the user data is in mounted volumes, so there shouldn't be any problem with any data that gets added in the meantime (modulo making sure we start from the right database schema when we do the switch).  I'll look at that.
