### ISSUE TITLE
Problems with some files when cutting vinyl from Inkscape

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#888]
I've tried a few times recently to cut some vinyl but not had much luck. Every time I try it's giving me the "Er2:Wrong No.s" message which apparently is normal when it finishes a cut but does appear to suggest it's not sending data to the cutter. 

I've tried testing the machine which works, I've tried testing the communication which also works (press a button in the print preferences and the vinyl rolls forward and backwards as the head moves as if to cut a square). I tried printing to a file and it didn't contain very much so it does seem like it's either a problem in my file, in Inkscape, or the printer driver. 

I've tried a couple of files: a pair of padlocks that are on the Desktop, a basic square and also some text. I couldn't find a "known good" file to use though. I've also checked that strokes are coloured and opacity is all 100%.

**Comment by johnmckerrell** [comment]
I tried today as Abdullah said it had been working fine for him, turned out he was using Corel Draw. I tried Inkscape and again it failed, tried Inkscape and it worked fine (although with 1.5m spooling!) I printed to a file again and it looked much different, `c:\foo.txt` and `c:\foo2.txt` fwiw.

**Comment by ajlennon** [comment]
Reopening...

Had a bit of a nightmare today trying to follow the instructions on the wiki.

- PC was running really slow. Took the RAM from 2GB to 4GB which helped
- Loading SVGs into Corel Draw x4 seems to cause it to crash
- Other printers connected seemed to confuse the printing

We eventually got to the point of printing an SVG from Inkscape to the printer with the Sublimation printer and label printer disconnected.

However we then got the message about invalid numbers noted above which indicates the printing has completed, but nothing had happened (other than the printer "woke up" so there was some kind of communication going on.

Tried the tricks of ungrouping the design and converting object to path but to no avail.

Very confused.

**Comment by ajlennon** [comment]
If anybody with more vinyl cutting skillz than me (which wouldn't be hard) can take a look the design is here

[\\freenas\does-samba\Other\CAROLINE\POWERFUL.svg
](\\freenas\does-samba\Other\CAROLINE\POWERFUL.svg)

**Comment by cheapjack** [comment]
It still seems impossible to cut anything with Inkscape and the vinyl cutter which is weird as managed to print on it before the PC and cutter was moved into it's current space (from where the knitting machines are now under the window)

I've followed all the instructions we have so far [in the wiki]() and tried disconnecting the sublimation and dymo printers, various restarts of cutter and PC unplugging and re-plugging cable into every possible usb. all to no avail. 

[This suggests](https://www.rolanddga.com/support/products/cutting/camm-1-cx-24-24-vinyl-cutter) we are actually not using the correct driver as it says Windows 7 is unsupported. The PC for Sublimation Printer/Roland Cutter seems to be running Windows 7 Ultimate so Im not sure what driver we went for in the end probably [camm1_win7_v150.zip](http://download.rolanddg.jp/en/cutting.html#win7dricamm1) and installed that got it running for a while. 
[This page has what relevant drivers there are it seems](http://download.rolanddg.jp/en/cutting.html#gx24)

Maybe @jackie1050 and I can try again this evening as think she and Jeremy managed to use it recently.

**Comment by amcewen** [comment]
I've been playing with Inkscape and the vinyl cutter a bit today (and did on Thursday too).  

* I was getting it spooling out lots of material first, until I rotated what I wanted to draw (I've got a pen in it rather than a blade) and then told it to rotate things 90 degrees when I printed it.
* I had trouble getting Inkscape to draw a circle and a square, although it was fine with the text I was drawing alongside it.  Tried turning all the objects to paths, but that made no difference (text paths drew okay, circle and box paths did not)
* Saving it as a DXF, I could then draw it fine from either Corel or Inkscape (had to close Inkscape and reopen the DXF).  Didn't get the double lines I'd had in Corel with a different file format.  However, that introduced a bunch of small lines and dots, so it's not the ideal cutting process.
* Saving the file as an `.emf` file and then reopening it in Inkscape seems to work quite well.  That's (I think) my current favourite approach

**Comment by amcewen** [comment]
Now that I've cut the signs for the doors (#719) using the `.emf` file method, I think that solves the issue.  I've updated the [instructions for the vinyl cutter on the wiki](https://github.com/DoESLiverpool/somebody-should/wiki/RolandVinylCutter) to reflect that, so going to call this issue done.
