### ISSUE TITLE
Gerald slipping on x axis

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#911]
@MatthewCroughan says that @magman2112 has a right angled screwdriver that can be used for tightening the belt - perhaps we should buy something similar for the laser maintenance team.

![img_20180914_202406](https://user-images.githubusercontent.com/12802256/45571044-e0092d80-b85c-11e8-8c18-ae311741ba42.jpg)

**Comment by dazz-ling** [comment]
I was doing quite a bit on it last night and it all worked fine,  even at quite high speeds. 
The only things I did notice was a software issue,  in that  it crashed or froze a couple of times and the bed alignments seemed out again

**Comment by magman2112** [comment]
I was expecting that we would need to tighten this belt in the near future, as it is only a week since it was replaced and some relaxing of the new belt is normal as it stretches slightly in use. A lesson learned perhaps is that we should do this after a few days, rather than the week I anticipated.

It does not need any special tools for adjustment, just a Phillips screwdriver that is not too long, especially if you open the access door on the left side of Gerald. You do have to careful to adjust the tension evenly though, to keep the belt even on the idler wheel, so as to prevent uneven wear on the edges of the drive belt.

Unfortunately, I have not been able to get into DoES for a few days with family issues, but I do plan to come in in either Monday, or Tuesday at the latest, and can check on this if no one else has a chance before I get in.

**Comment by Sean-anotherone** [comment]
If slippage is an ongoing issue some new pulleys might help. I use these guys for standard timing pulleys and endless belt :  http://www.beltingonline.com/timing-pulleys-bars-272/

If there are any issues with periodic error (presenting as a "slack side" on the pulleys) I can dress pulleys between centers to ensure they're perfectly concentric.

**Comment by magman2112** [comment]
I adjusted the belt tension 9n Monday, it had stretched quite a bit. I also showed @MatthewCroughan how I adjusted it, so there are other folks more likely to be in DoES who can make this adjustment if needed.

I will leave this issue open for a few days, so we can get feedback on the use of Gerald in case this has not resolved this issue. I will also check the tension again in a few days, as I expect the belt to stretch a bit more.

**Comment by Thingomy** [comment]
Not imediatly related to this job; but does it follow that belt stretch can
result in caleberation issues with the belt drives on all our machines? I
had been working under the false logic that as the belts have a "fixed"
pitch, they are quite precise and dimentionally stable. Presumably at most
stages during this streching process a circle cut on the machine comes out
as an elypse.

What kind of percetages are we dealing with here?

Thanks,
JR

**Comment by Sean-anotherone** [comment]
I have never heard of timing belt "stretch" (until the time they fail...) but have certainly encountered a bedding-in period, where the tops of all the belt teeth become bedded-in to the teeth on the pulleys.  After a while in operation they do need an adjustment but that is because they are sitting better, rather than due to stretch (even t2.5 belts are incredibly strong)

**Comment by jackie1050** [comment]
Ok - so when's the best time to try to cut circles (need to be accurate) for the the Knitic?


________________________________

**Comment by magman2112** [comment]
OK, I might be mistaken in the “Stretching” of the belt, but from my experience, after replacing the belt on Gerald, it does need to be re-tightened a few times to keep the correct tension in the belt - then it tends to settle down. 

Thinking about it, this may be a bit of slippage in the mounting points on the head, but I had assumed it was due to a slight give in the belt. We are talking of over 3m of belt that is installed for this axis, so a small amount of give can make a difference over this length.

To answer @jackie1050 question, I would give it a week or two of successful cuts before attempting a critical cut, like the for the Knitic. I will check the tension again tomorrow and likely every few days, to see if there are any significant adjustments are needed and also when the changes tend to settle down.

**Comment by Sean-anotherone** [comment]
Ahhh....   over a 3M length you might well see stretch, even sub 1% stretch would leave a belt that long with slack.

Strictly, a drive belt 3M long is better known as a rope.........

**Comment by magman2112** [comment]
Closing this issue now, as new belts and clamps have been fitted that appear to have addressed this issue.
