### ISSUE TITLE
Gerald needs his filters cleaning

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#952]
Gerald has been quite smelly recently and could do with a good vacuum.

**Comment by magman2112** [comment]
I gave the fan a clean just before Maker night on Thursday. The fan didn’t look too blocked, but should be improved anyway.

I did notice though that the tube from the blower to the outside was quite squashed, so repositioning this improved the airflow significantly. This tube is getting more and more fragile, in some sections there are more patches than original tube. There are still a few air leaks despite these patches, which is leaking some fumes into the Laser room.

I would suggest that we get a replacement for this tube sooner rather than later, as this will likely still be needed should we get a longer term installation of the extraction system.
