### ISSUE TITLE
Somebody should… clean up after they make Huel in the kitchen

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#996]
The kitchen worktops may be a Huel _preparation_ area, but they’re not a Huel _display_ area. A few times this month I’ve come in, in the morning, to find Huel scattered over and dried onto the worktops:

![img_7953](https://user-images.githubusercontent.com/739624/49339269-541acc80-f627-11e8-98aa-eb9c824a7081.jpg)

![img_7954](https://user-images.githubusercontent.com/739624/49339273-5b41da80-f627-11e8-86ef-e0de48950aa0.jpg)

So, whoever’s making the Huel, can you clean up after yourself once you’re finished? Wiping down the worktops would take literally a couple of seconds. If you lack the neccesary training on how to operate a kitchen wipe or damp paper towel, I would be willing to tutor you for free, just come find me at my desk.

@goatchurchprime @MatthewCroughan You tend to be in the space late, maybe if you spot this Huel scatterer, you could point them towards this ticket? :+1:

**Comment by MatthewCroughan** [comment]
I can not, for the huel scatterer was me, I left the packet on the worktop (bad bad bad) and didn't clean under it. As for the thick glob in the drain, this was definitely a mistake I won't make again. 

I failed at making the huel, it was far too thick, poured as much hot water as I could on it until it looked as if it was gone, but in the night it has made a limescale-like chemical mess that's shown in your image. Ideally the only mess would have been the dust left under the bag, but it has came out far worse because I didn't realise how silly it was to attempt to pour this down the drain.

In future, I'll package it up in a bag if the result is too thick, I was only trying the Huel anyway, unlikely to occur again as I didn't like it too much. My bad.

**Comment by zarino** [comment]
> Also, it's worth noting that it's not just me, so I'll make sure to suggest cleanliness to anybody else drinking huel. This was my first time trying it.

Yep, this has definitely been a problem for at least the last month or two.
